/* -*- Mode: C++; c-basic-offset: 2; indent-tabs-mode: nil; tab-width: 8 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

webidl Document;
webidl DocumentFragment;

[scriptable, uuid(21b1cfa4-00ce-4cc1-bfc1-92af1d00e580)]
interface txIEXSLTFunctions : nsISupports {
  DocumentFragment match(in AString str, in AString regex,
                         in AString flags, in Document doc);

  AString replace(in AString str, in AString regex, in AString flags,
                  in AString replace);

  boolean test(in AString str, in AString regex, in AString flags);
};
