   interface DOMImplementation {
 /* IID: { 0xa6cf9074, 0x15b3, 0x11d2, \
  { 0x93, 0x2e, 0x00, 0x80, 0x5f, 0x8a, 0xdd, 0x32 } } */

      boolean                   hasFeature(in DOMString feature, 
                                           in DOMString version);

      DocumentType              createDocumentType(in DOMString qualifiedName,
                                                   in DOMString publicId,
                                                   in DOMString systemId)
                                                   raises(DOMException);

      Document                  createDocument(in DOMString namespaceURI,
                                               in DOMString qualifiedName,
                                               in DocumentType doctype)
                                                   raises(DOMException);
   };

