#
# Copyright 2002 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#ident	"$Id: Makefile,v 1.2 2002/10/02 23:11:29 kirk.erickson%sun.com Exp $"
#

CORE_DEPTH = ../../../..
include ../Makefile.com

DATAFILES += pkgdepend

all:: $(FILES)
publish:: all pkg

include ../Makefile.targ
