/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*-
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

%{C++
#include "nsRect.h"
%}

interface imgIContainer;
interface imgIRequest;
[ptr] native nsIntRect(nsIntRect);

/**
 * imgIContainerObserver interface
 *
 * @author Stuart Parmenter <pavlov@netscape.com>
 * @version 0.1
 */
[scriptable, uuid(f01efdb3-4b20-4313-a636-a2aa01a4ef5d)]
interface imgIContainerObserver : nsISupports
{
  [noscript] void frameChanged(in imgIRequest aRequest,
                               in imgIContainer aContainer,
                               [const] in nsIntRect aDirtyRect);
};
