/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsIDOMEvent.idl"

[scriptable, builtinclass, uuid(90c55b1c-2da5-4a30-bf09-0c70369a8d89)]
interface nsIDOMBluetoothDeviceAddressEvent : nsIDOMEvent
{
  readonly attribute DOMString  deviceAddress;

  [noscript] void initBluetoothDeviceAddressEvent(in DOMString aType,
                                                  in boolean aCanBubble,
                                                  in boolean aCancelable,
                                                  in DOMString aDeviceAddress);
};

dictionary BluetoothDeviceAddressEventInit : EventInit
{
  DOMString  deviceAddress;
};
