/* -*- Mode: c++; c-basic-offset: 2; indent-tabs-mode: nil; tab-width: 40 -*- */
/* vim: set ts=2 et sw=2 tw=80: */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsIDOMEventTarget.idl"

interface nsIDOMDOMRequest;
interface nsIDOMBluetoothAdapter;

[scriptable, builtinclass, uuid(303a262a-1dd1-486d-a108-d8c582e86765)]
interface nsIDOMBluetoothManager : nsIDOMEventTarget
{
  readonly attribute bool enabled;

  nsIDOMDOMRequest getDefaultAdapter();

  bool isConnected(in unsigned short aProfile);

  [implicit_jscontext] attribute jsval onenabled;
  [implicit_jscontext] attribute jsval ondisabled;
  [implicit_jscontext] attribute jsval onadapteradded;
};
