/* -*- Mode: c++; c-basic-offset: 2; indent-tabs-mode: nil; tab-width: 40 -*- */
/* vim: set ts=2 et sw=2 tw=40: */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsIDOMEventTarget.idl"

interface nsIDOMDOMRequest;
interface nsIDOMBluetoothAdapter;

[scriptable, builtinclass, uuid(9d4bcbad-8904-4985-b366-036d32959312)]
interface nsIDOMBluetoothManager : nsIDOMEventTarget
{
  readonly attribute bool enabled;
  readonly attribute nsIDOMBluetoothAdapter defaultAdapter;

  nsIDOMDOMRequest setEnabled(in boolean enabled);
};
