/* -*- Mode: c++; c-basic-offset: 2; indent-tabs-mode: nil; tab-width: 40 -*- */
/* vim: set ts=2 et sw=2 tw=80: */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsIDOMEvent.idl"

interface nsIDOMBluetoothDevice;

[scriptable, builtinclass, uuid(e53dd06e-acd7-444a-914a-5fb60df0ad5b)]
interface nsIDOMBluetoothDeviceEvent : nsIDOMEvent
{
  readonly attribute nsIDOMBluetoothDevice device;

  [noscript] void initBluetoothDeviceEvent(in DOMString aType,
                                           in boolean aCanBubble,
                                           in boolean aCancelable,
                                           in nsIDOMBluetoothDevice aDevice);
};

dictionary BluetoothDeviceEventInit : EventInit
{
  nsIDOMBluetoothDevice  device;
};
