/* -*- Mode: c++; c-basic-offset: 2; indent-tabs-mode: nil; tab-width: 40 -*- */
/* vim: set ts=2 et sw=2 tw=80: */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsIDOMEventTarget.idl"

interface nsIDOMDOMRequest;
interface nsIDOMBluetoothAdapter;

[scriptable, builtinclass, uuid(b9e0a4a2-fa84-402d-8830-d0f3625f120a)]
interface nsIDOMBluetoothManager : nsIDOMEventTarget
{
  readonly attribute bool enabled;

  nsIDOMDOMRequest getDefaultAdapter();

  [implicit_jscontext] attribute jsval onenabled;
  [implicit_jscontext] attribute jsval ondisabled;
};
