/* -*- Mode: C++; tab-width: 8; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* vim: set ts=2 et sw=2 tw=80: */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

interface mozIDOMWindow;
webidl DOMRequest;

[scriptable, builtinclass, uuid(9a57e5de-ce93-45fa-8145-755722834f7c)]
interface nsIDOMRequestService : nsISupports
{
  DOMRequest createRequest(in mozIDOMWindow window);

  void fireSuccess(in DOMRequest request, in jsval result);
  void fireError(in DOMRequest request, in DOMString error);
  void fireSuccessAsync(in DOMRequest request, in jsval result);
  void fireErrorAsync(in DOMRequest request, in DOMString error);
};
