#!nmake
#
# The contents of this file are subject to the Netscape Public
# License Version 1.1 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy of
# the License at http://www.mozilla.org/NPL/
#
# Software distributed under the License is distributed on an "AS
# IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
# implied. See the License for the specific language governing
# rights and limitations under the License.
#
# The Original Code is mozilla.org code.
#
# The Initial Developer of the Original Code is Netscape
# Communications Corporation.  Portions created by Netscape are
# Copyright (C) 1998 Netscape Communications Corporation. All
# Rights Reserved.
#
# Contributor(s): 

DEPTH=..\..
REQUIRES	= xpcom \
		  string \
		  necko \
		  $(NULL)
include <$(DEPTH)/config/config.mak>



DIRS = dynamic windows services 

MAKE_OBJ_TYPE	= EXE
PROG1 = .\$(OBJDIR)\TestFactory.exe
PROG3 = .\$(OBJDIR)\TestArray.exe
PROG4 = .\$(OBJDIR)\TestID.exe
PROG5 = .\$(OBJDIR)\TestServMgr.exe
#PROG6 = .\$(OBJDIR)\TimerTest.exe
PROG7 = .\$(OBJDIR)\TestAtoms.exe
PROG8 = .\$(OBJDIR)\nsIFileTest.exe
PROG9 = .\$(OBJDIR)\TestCRT.exe
PROG10 = .\$(OBJDIR)\FilesTest.exe
PROG11 = .\$(OBJDIR)\PropertiesTest.exe
PROG12 = .\$(OBJDIR)\TestAutoLock.exe
PROG13 = .\$(OBJDIR)\TestThreads.exe
PROG14 = .\$(OBJDIR)\TestObserverService.exe
PROG16 = .\$(OBJDIR)\TestPipes.exe
PROG17 = .\$(OBJDIR)\TestShutdown.exe
PROG18 = .\$(OBJDIR)\TestStackCrawl.exe
PROG19 = .\$(OBJDIR)\TestVoidBTree.exe
PROG20 = .\$(OBJDIR)\nsIFileEnumerator.exe
PROG21 = .\$(OBJDIR)\TestCOMPtrEq.exe
PROG22 = .\$(OBJDIR)\TestCallTemplates.exe
PROG23 = .\$(OBJDIR)\TestPermanentAtoms.exe

RESFILE = timer.res

PROGRAMS = $(PROG1) \
           $(PROG3) \
           $(PROG4) \
           $(PROG5) \
           $(PROG6) \
           $(PROG7) \
           $(PROG8) \
           $(PROG9) \
           $(PROG10) \
           $(PROG11) \
           $(PROG12) \
           $(PROG13) \
           $(PROG14) \
           $(PROG16) \
           $(PROG17) \
           $(PROG18) \
           $(PROG19) \
           $(PROG20) \
           $(PROG21) \
           $(PROG22) \
           $(PROG23) \
           $(NULL)

LCFLAGS=-DUSE_NSREG -GX


LINCS=                     \
        -Iservices         \
        -I..\ds            \
        $(NULL)

LLIBS=                         \
        $(DIST)\lib\xpcom.lib  \
        $(LIBNSPR)

include <$(DEPTH)\config\rules.mak>

install:: $(PROGRAMS)
	-for %p in ($(PROGRAMS)) do $(MAKE_INSTALL) %p $(DIST)\bin

clobber::
	-for %p in ($(PROGRAMS)) do $(RM) %p $(DIST)\bin\%p

$(PROG1): $(OBJDIR) TestFactory.cpp
$(PROG3): $(OBJDIR) TestArray.cpp
$(PROG4): $(OBJDIR) TestID.cpp
$(PROG5): $(OBJDIR) TestServMgr.cpp
#$(PROG6): $(OBJDIR) TimerTest.cpp $(RESFILE)
$(PROG7): $(OBJDIR) TestAtoms.cpp
$(PROG8): $(OBJDIR) nsIFileTest.cpp
$(PROG9): $(OBJDIR) TestCRT.cpp
$(PROG10): $(OBJDIR) FilesTest.cpp
$(PROG11): $(OBJDIR) PropertiesTest.cpp
$(PROG12): $(OBJDIR) TestAutoLock.cpp
$(PROG13): $(OBJDIR) TestThreads.cpp
$(PROG14): $(OBJDIR) TestObserverService.cpp
$(PROG16): $(OBJDIR) TestPipes.cpp
$(PROG17): $(OBJDIR) TestShutdown.cpp
$(PROG18): $(OBJDIR) TestStackCrawl.cpp
$(PROG19): $(OBJDIR) TestVoidBTree.cpp
$(PROG20): $(OBJDIR) nsIFileEnumerator.cpp
$(PROG21): $(OBJDIR) TestCOMPtrEq.cpp
$(PROG22): $(OBJDIR) TestCallTemplates.cpp
$(PROG23): $(OBJDIR) TestPermanentAtoms.cpp


