#!nmake
#
# The contents of this file are subject to the Netscape Public License
# Version 1.0 (the "NPL"); you may not use this file except in
# compliance with the NPL.  You may obtain a copy of the NPL at
# http://www.mozilla.org/NPL/
#
# Software distributed under the NPL is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the NPL
# for the specific language governing rights and limitations under the
# NPL.
#
# The Initial Developer of this code under the NPL is Netscape
# Communications Corporation.  Portions created by Netscape are
# Copyright (C) 1998 Netscape Communications Corporation.  All Rights
# Reserved.

DEPTH=..\..
include <$(DEPTH)/config/config.mak>

IGNORE_MANIFEST=1

DIRS = dynamic windows services 

MAKE_OBJ_TYPE	= EXE
PROG1 = .\$(OBJDIR)\TestFactory.exe
PROG2 = .\$(OBJDIR)\RegFactory.exe
PROG3 = .\$(OBJDIR)\TestArray.exe
PROG4 = .\$(OBJDIR)\TestID.exe
PROG5 = .\$(OBJDIR)\TestServMgr.exe
#PROG6 = .\$(OBJDIR)\TimerTest.exe
PROG7 = .\$(OBJDIR)\TestAtoms.exe
PROG8 = .\$(OBJDIR)\CvtURL.exe
PROG9 = .\$(OBJDIR)\TestCRT.exe
PROG10 = .\$(OBJDIR)\FilesTest.exe
PROG11 = .\$(OBJDIR)\PropertiesTest.exe
PROG12 = .\$(OBJDIR)\TestAutoLock.exe
PROG13 = .\$(OBJDIR)\TestThreads.exe
PROG14 = .\$(OBJDIR)\TestObserverService.exe
PROG16 = .\$(OBJDIR)\TestPipes.exe
PROG17 = .\$(OBJDIR)\TestShutdown.exe
PROG18 = .\$(OBJDIR)\TestStackCrawl.exe

RESFILE = timer.res

PROGRAMS = $(PROG1) $(PROG2) $(PROG3) $(PROG4) $(PROG5) \
        $(PROG6) $(PROG7) \
!ifdef MODULAR_NETLIB
        $(PROG8) \
	$(PROG9) \
	$(PROG10) \
!endif
	$(PROG11) \
        $(PROG12) \
        $(PROG13) \
        $(PROG14) \
        $(PROG16) \
        $(PROG17) \
        $(PROG18) \
	$(NULL)

LCFLAGS=-DUSE_NSREG -GX -DNECKO

REQUIRES=libreg

LINCS=                     \
        -Iservices         \
!ifdef NECKO
        -I$(PUBLIC)\necko  \
!else
!ifdef MODULAR_NETLIB
        -I$(PUBLIC)\netlib \
!endif
!endif
        -I$(PUBLIC)\xpcom

LLIBS=                         \
        $(DIST)\lib\xpcom.lib  \
!ifdef NECKO
        $(DIST)\lib\neckoutil_s.lib \
!else
!ifdef MODULAR_NETLIB
        $(DIST)\lib\netlib.lib \
!endif
!endif
        $(LIBNSPR)

!if "$(MOZ_BITS)"=="32" && defined(MOZ_DEBUG) && defined(GLOWCODE)
LLIBS=$(LLIBS) $(GLOWDIR)\glowcode.lib
!endif

include <$(DEPTH)\config\rules.mak>

install:: $(PROGRAMS)
	-for %p in ($(PROGRAMS)) do $(MAKE_INSTALL) %p $(DIST)\bin

clobber::
	-for %p in ($(PROGRAMS)) do $(RM) %p $(DIST)\bin\%p

$(PROG1): $(OBJDIR) TestFactory.cpp
$(PROG2): $(OBJDIR) RegFactory.cpp
$(PROG3): $(OBJDIR) TestArray.cpp
$(PROG4): $(OBJDIR) TestID.cpp
$(PROG5): $(OBJDIR) TestServMgr.cpp

#$(PROG6): $(OBJDIR) TimerTest.cpp $(RESFILE)

$(PROG7): $(OBJDIR) TestAtoms.cpp

$(PROG8): $(OBJDIR) FilesTest.cpp

!ifdef MODULAR_NETLIB
$(PROG9): $(OBJDIR) CvtURL.cpp

$(PROG10): $(OBJDIR) TestCRT.cpp

$(PROG11): $(OBJDIR) PropertiesTest.cpp
!endif

$(PROG12): $(OBJDIR) TestAutoLock.cpp

$(PROG13): $(OBJDIR) TestThreads.cpp

$(PROG14): $(OBJDIR) TestObserverService.cpp

$(PROG16): $(OBJDIR) TestPipes.cpp

$(PROG17): $(OBJDIR) TestShutdown.cpp

$(PROG18): $(OBJDIR) TestStackCrawl.cpp
