function f(x) {
    Math.round == Math.round();
}
function g(f, y) {
    for (var k = 0; k < 9999; ++k) {
        f()
    }
}
g(f, [
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    /x/,
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    createIsHTMLDDA(),
    new Boolean(false),
    new Boolean(false),
    new Boolean(false),
    new Boolean(false),
    new Boolean(false),
    new Boolean(false),
    new Boolean(false),
    new Boolean(false),
    new Boolean(false),
    new Boolean(false),
    new Boolean(false),
    new Boolean(false),
    new Boolean(false),
    new Boolean(false),
    new Boolean(false),
    new Boolean(false),
    new Boolean(false),
    new Boolean(false),
    new Boolean(false),
    new Boolean(false),
    new Boolean(false),
    new Boolean(false),
    new Boolean(false),
    new Boolean(false),
]);
for (var k = 0; k < 99999; ++k) {
    f()
}
