#filter emptyLines

# This file is in the UTF-8 encoding

#define BRAND_COMPANY_NAME Mozilla
#define BRAND_PRODUCT_NAME Mozilla Firefox

#define UNINST_RUNNING Mozilla Firefox is detected to be currently running.  Please quit Mozilla Firefox before continuing.  Click OK to exit Mozilla Firefox automatically and proceed with uninstallation.
#define UNINST_SHUTDOWN Shutting down Mozilla Firefox.  Please wait...
#define UNINST_FONT MS Sans Serif
#define UNINST_FONTSIZE 8
#define UNINST_CHARSET 0
# Here is a partial list CHAR_SETS
#  ANSI_CHARSET = 0
#  DEFAULT_CHARSET = 1
#  SYMBOL_CHARSET = 2
#  SHIFTJIS_CHARSET = 128
#  GB2312_CHARSET = 134
#  HANGEUL_CHARSET = 129
#  CHINESEBIG5_CHARSET = 136
#  OEM_CHARSET 255

#define UNINST_TITLE Mozilla Firefox Uninstaller
#define UNINST_MESSAGE0 Are you sure you want to completely remove %s and all of its components?
#define BTN_UNINST &Uninstall
#define BTN_CANCEL &Cancel
#define BTN_MESSAGE1 Uninstall has detected that the following shared file is no longer used by any programs.  If any programs still require the shared file and it is removed, those programs may no longer function.  Are you sure you want to remove this shared file?
#define BTN_MESSAGE2 Leaving this file will not harm your system.  If you are not sure, it is recommended that the shared file be not removed from the system.
#define BTN_FILENAME File name:
#define BTN_NO &No
#define BTN_NOTOALL N&o to all
#define BTN_YES &Yes
#define BTN_YESTOALL Y&es to all
#define BTN_OK OK

#define ERROR_DLL_LOAD Could not load %s
#define ERROR_STRING_LOAD Could not load string resource ID %d
#define ERROR_STRING_NULL Null pointer encountered.
#define ERROR_GLOBALALLOC Memory allocation error.
#define ERROR_FAILED %s failed.
#define ERROR_DIALOG_CREATE Could not create %s dialog.
#define DLGQUITTITLE Question
#define DLGQUITMSG Are you sure you want to cancel?
#define ERROR_GET_SYSTEM_DIRECTORY_FAILED GetSystemDirectory() failed.
#define ERROR_GET_WINDOWS_DIRECTORY_FAILED GetWindowsDirectory() failed.
#define ERROR_CREATE_TEMP_DIR Uninstall was not able to create the TEMP directory: %s
#define ERROR_SETUP_REQUIREMENT Windows95 or greater Operating System is required!  Exiting Uninstall...
#define MB_WARNING_STR Warning
#define ERROR_UNINSTALL_LOG_FOLDER Uninstall log folder not found:%s
#define MB_MESSAGE_STR Message
#define DLG_REMOVE_FILE_TITLE Remove File?
#define ERROR_GETVERSION GetVersionEx() failed!
#define MB_ATTENTION_STR Attention
#define MSG_FORCE_QUIT_PROCESS Uninstall has detected that %s (%s) is still running.  Click OK to quit %s and proceed with uninstallation. Alternatively, use the Windows Task Manager to quit %s, and then click OK to continue with uninstallation.
#define MSG_FORCE_QUIT_PROCESS_FAILED Uninstall will now exit.  Uninstall could not continue because %s (%s) is still running. Try manually quitting %s using Windows Task Manager, and then run Uninstall again.
#define MSG_DELETE_INSTALLATION_PATH Not all files were uninstalled from the installation directory:\n\n  %s\n\nDo you want to completely delete this directory?
#define MSG_INSTALLATION_PATH_WITHIN_WINDIR Uninstall has detected that the installation path of Mozilla Firefox is installed to a folder within your Windows folder.  Uninstall will not attempt to delete this installation due to the potential removal of critical system files.

#unfilter emptyLines
