/* -*- Mode: IDL; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsIURL.idl"

/**
 * JAR URLs have the following syntax
 *
 * jar:<jar-file-uri>!/<jar-entry>
 *
 * EXAMPLE: jar:http://www.big.com/blue.jar!/ocean.html
 *
 * The nsIURL methods operate on the <jar-entry> part of the spec.
 */
[scriptable, uuid(1ee60719-c056-43b3-8f54-6a6e7ba0ca6c)]
interface nsIJARURI : nsIURL {

    /**
     * Returns the root URI (the one for the actual JAR file) for this JAR
     * (e.g., http://www.big.com/blue.jar).
     */
    readonly attribute nsIURI JARFile;

    /**
     * Returns the entry specified for this JAR URI (e.g., "ocean.html").  This
     * value may contain %-escaped byte sequences.
     */
    attribute AUTF8String JAREntry;

    /**
     * Create a clone of the JAR URI with a new root URI (the URI for the
     * actual JAR file).
     */
    nsIJARURI cloneWithJARFile(in nsIURI jarFile);
};
