/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

FRAME_ID(BRFrame, Br)
FRAME_ID(DetailsFrame, Details)
FRAME_ID(nsAutoRepeatBoxFrame, Box)
FRAME_ID(nsBCTableCellFrame, BCTableCell)
FRAME_ID(nsBackdropFrame, Backdrop)
FRAME_ID(nsBlockFrame, Block)
FRAME_ID(nsBox, None)
FRAME_ID(nsBoxFrame, Box)
FRAME_ID(nsBulletFrame, Bullet)
FRAME_ID(nsButtonBoxFrame, Box)
FRAME_ID(nsCanvasFrame, Canvas)
FRAME_ID(nsColorControlFrame, ColorControl)
FRAME_ID(nsColumnSetFrame, ColumnSet)
FRAME_ID(nsComboboxControlFrame, ComboboxControl)
FRAME_ID(nsComboboxDisplayFrame, ComboboxDisplay)
FRAME_ID(nsContinuingTextFrame, Text)
FRAME_ID(nsDateTimeControlFrame, DateTimeControl)
FRAME_ID(nsDeckFrame, Deck)
FRAME_ID(nsDocElementBoxFrame, Box)
FRAME_ID(nsFieldSetFrame, FieldSet)
FRAME_ID(nsFileControlFrame, Block)
FRAME_ID(nsFirstLetterFrame, Letter)
FRAME_ID(nsFirstLineFrame, Line)
FRAME_ID(nsFlexContainerFrame, FlexContainer)
FRAME_ID(nsFrame, None)
FRAME_ID(nsGfxButtonControlFrame, GfxButtonControl)
FRAME_ID(nsGfxCheckboxControlFrame, FormControl)
FRAME_ID(nsGfxRadioControlFrame, FormControl)
FRAME_ID(nsGridContainerFrame, GridContainer)
FRAME_ID(nsGridRowGroupFrame, Box)
FRAME_ID(nsGridRowLeafFrame, Box)
FRAME_ID(nsGroupBoxFrame, Box)
FRAME_ID(nsHTMLButtonControlFrame, HTMLButtonControl)
FRAME_ID(nsHTMLCanvasFrame, HTMLCanvas)
FRAME_ID(nsHTMLFramesetBlankFrame, None)
FRAME_ID(nsHTMLFramesetBorderFrame, None)
FRAME_ID(nsHTMLFramesetFrame, FrameSet)
FRAME_ID(nsHTMLScrollFrame, Scroll)
FRAME_ID(nsImageBoxFrame, ImageBox)
FRAME_ID(nsImageControlFrame, ImageControl)
FRAME_ID(nsImageFrame, Image)
FRAME_ID(nsInlineFrame, Inline)
FRAME_ID(nsLeafBoxFrame, LeafBox)
FRAME_ID(nsLegendFrame, Legend)
FRAME_ID(nsListBoxBodyFrame, Box)
FRAME_ID(nsListControlFrame, ListControl)
FRAME_ID(nsListItemFrame, Box)
FRAME_ID(nsMathMLFrame, None)
FRAME_ID(nsMathMLmactionFrame, None)
FRAME_ID(nsMathMLmathBlockFrame, Block)
FRAME_ID(nsMathMLmathInlineFrame, Inline)
FRAME_ID(nsMathMLmencloseFrame, None)
FRAME_ID(nsMathMLmfencedFrame, None)
FRAME_ID(nsMathMLmfracFrame, None)
FRAME_ID(nsMathMLmmultiscriptsFrame, None)
FRAME_ID(nsMathMLmoFrame, None)
FRAME_ID(nsMathMLmoverFrame, None) // XXX unused?
FRAME_ID(nsMathMLmpaddedFrame, None)
FRAME_ID(nsMathMLmrootFrame, None)
FRAME_ID(nsMathMLmrowFrame, None)
FRAME_ID(nsMathMLmspaceFrame, None)
FRAME_ID(nsMathMLmsqrtFrame, None)
FRAME_ID(nsMathMLmstyleFrame, None)  // XXX unused?
FRAME_ID(nsMathMLmtableFrame, Table)
FRAME_ID(nsMathMLmtableWrapperFrame, TableWrapper)
FRAME_ID(nsMathMLmtdFrame, TableCell)
FRAME_ID(nsMathMLmtdInnerFrame, Block)
FRAME_ID(nsMathMLmtrFrame, TableRow)
FRAME_ID(nsMathMLmunderFrame, None)  // XXX unused?
FRAME_ID(nsMathMLmunderoverFrame, None)
FRAME_ID(nsMathMLsemanticsFrame, None)
FRAME_ID(nsMathMLTokenFrame, None)
FRAME_ID(nsMenuBarFrame, Box)
FRAME_ID(nsMenuFrame, Menu)
FRAME_ID(nsMenuPopupFrame, MenuPopup)
FRAME_ID(nsMeterFrame, Meter)
FRAME_ID(nsNumberControlFrame, NumberControl)
FRAME_ID(nsPluginFrame, Object)
FRAME_ID(nsPageBreakFrame, PageBreak)
FRAME_ID(nsPageContentFrame, PageContent)
FRAME_ID(nsPageFrame, Page)
FRAME_ID(nsPlaceholderFrame, Placeholder)
FRAME_ID(nsPopupSetFrame, PopupSet)
FRAME_ID(nsProgressFrame, Progress)
FRAME_ID(nsProgressMeterFrame, Box)
FRAME_ID(nsRangeFrame, Range)
FRAME_ID(nsResizerFrame, Box)
FRAME_ID(nsRootBoxFrame, Root)
FRAME_ID(nsRubyBaseContainerFrame, RubyBaseContainer)
FRAME_ID(nsRubyBaseFrame, RubyBase)
FRAME_ID(nsRubyFrame, Ruby)
FRAME_ID(nsRubyTextContainerFrame, RubyTextContainer)
FRAME_ID(nsRubyTextFrame, RubyText)
FRAME_ID(nsScrollbarButtonFrame, Box)
FRAME_ID(nsScrollbarFrame, Scrollbar)
FRAME_ID(nsSelectsAreaFrame, Block)
FRAME_ID(nsSimplePageSequenceFrame, Sequence)
FRAME_ID(nsSliderFrame, Slider)
FRAME_ID(nsSplitterFrame, Box)
FRAME_ID(nsStackFrame, Box)
FRAME_ID(nsSubDocumentFrame, SubDocument)
FRAME_ID(nsSVGAFrame, SVGA)
FRAME_ID(nsSVGClipPathFrame, SVGClipPath)
FRAME_ID(nsSVGContainerFrame, None)
FRAME_ID(SVGFEContainerFrame, SVGFEContainer)
FRAME_ID(SVGFEImageFrame, SVGFEImage)
FRAME_ID(SVGFELeafFrame, SVGFELeaf)
FRAME_ID(SVGFEUnstyledLeafFrame, SVGFEUnstyledLeaf)
FRAME_ID(nsSVGFilterFrame, SVGFilter)
FRAME_ID(nsSVGForeignObjectFrame, SVGForeignObject)
FRAME_ID(nsSVGGenericContainerFrame, SVGGenericContainer)
FRAME_ID(nsSVGGFrame, SVGG)
FRAME_ID(nsSVGImageFrame, SVGImage)
FRAME_ID(nsSVGInnerSVGFrame, SVGInnerSVG)
FRAME_ID(nsSVGLinearGradientFrame, SVGLinearGradient)
FRAME_ID(nsSVGMarkerFrame, SVGMarker)
FRAME_ID(nsSVGMarkerAnonChildFrame, SVGMarkerAnonChild)
FRAME_ID(nsSVGMaskFrame, SVGMask)
FRAME_ID(nsSVGOuterSVGFrame, SVGOuterSVG)
FRAME_ID(nsSVGOuterSVGAnonChildFrame, SVGOuterSVGAnonChild)
FRAME_ID(SVGGeometryFrame, SVGGeometry)
FRAME_ID(nsSVGPatternFrame, SVGPattern)
FRAME_ID(nsSVGRadialGradientFrame, SVGRadialGradient)
FRAME_ID(nsSVGStopFrame, SVGStop)
FRAME_ID(nsSVGSwitchFrame, SVGSwitch)
FRAME_ID(SVGTextFrame, SVGText)
FRAME_ID(nsSVGUseFrame, SVGUse)
FRAME_ID(SVGViewFrame, SVGView)
FRAME_ID(nsTableCellFrame, TableCell)
FRAME_ID(nsTableColFrame, TableCol)
FRAME_ID(nsTableColGroupFrame, TableColGroup)
FRAME_ID(nsTableFrame, Table)
FRAME_ID(nsTableWrapperFrame, TableWrapper)
FRAME_ID(nsTableRowFrame, TableRow)
FRAME_ID(nsTableRowGroupFrame, TableRowGroup)
FRAME_ID(nsTextBoxFrame, LeafBox)
FRAME_ID(nsTextControlFrame, TextInput)
FRAME_ID(nsTextFrame, Text)
FRAME_ID(nsTitleBarFrame, Box)
FRAME_ID(nsTreeBodyFrame, LeafBox)
FRAME_ID(nsTreeColFrame, Box)
FRAME_ID(nsVideoFrame, HTMLVideo)
FRAME_ID(nsXULLabelFrame, XULLabel)
FRAME_ID(nsXULScrollFrame, Scroll)
FRAME_ID(ViewportFrame, Viewport)

// Non-concrete classes (for FrameIID use)
ABSTRACT_FRAME_ID(nsContainerFrame)
ABSTRACT_FRAME_ID(nsFormControlFrame)
ABSTRACT_FRAME_ID(nsIFrame)
ABSTRACT_FRAME_ID(nsLeafFrame)
ABSTRACT_FRAME_ID(nsMathMLContainerFrame)
ABSTRACT_FRAME_ID(nsRubyContentFrame)
ABSTRACT_FRAME_ID(nsSplittableFrame)
ABSTRACT_FRAME_ID(nsSVGDisplayContainerFrame)
ABSTRACT_FRAME_ID(nsSVGGradientFrame)
ABSTRACT_FRAME_ID(nsSVGPaintServerFrame)

// Interfaces (for FrameIID use)
ABSTRACT_FRAME_ID(nsIAnonymousContentCreator)
ABSTRACT_FRAME_ID(nsIComboboxControlFrame)
ABSTRACT_FRAME_ID(nsIFormControlFrame)
ABSTRACT_FRAME_ID(nsIFrameFrame)
ABSTRACT_FRAME_ID(nsIListControlFrame)
ABSTRACT_FRAME_ID(nsIMathMLFrame)
ABSTRACT_FRAME_ID(nsIMenuFrame)
ABSTRACT_FRAME_ID(nsIObjectFrame)
ABSTRACT_FRAME_ID(nsIPageSequenceFrame)
ABSTRACT_FRAME_ID(nsIPercentBSizeObserver)
ABSTRACT_FRAME_ID(nsIRootBox)
ABSTRACT_FRAME_ID(nsIScrollableFrame)
ABSTRACT_FRAME_ID(nsIScrollbarMediator)
ABSTRACT_FRAME_ID(nsISelectControlFrame)
ABSTRACT_FRAME_ID(nsISVGSVGFrame)
ABSTRACT_FRAME_ID(nsIStatefulFrame)
ABSTRACT_FRAME_ID(nsITableCellLayout)
ABSTRACT_FRAME_ID(nsITableLayout)
ABSTRACT_FRAME_ID(nsITextControlFrame)
ABSTRACT_FRAME_ID(nsITreeBoxObject)
ABSTRACT_FRAME_ID(nsSVGDisplayableFrame)
