#!nmake
#
# The contents of this file are subject to the Mozilla Public
# License Version 1.1 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy of
# the License at http://www.mozilla.org/MPL/
#
# Software distributed under the License is distributed on an "AS
# IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
# implied. See the License for the specific language governing
# rights and limitations under the License.
#
# The Original Code is mozilla.org code.
#
# The Initial Developer of the Original Code is Sun Microsystems,
# Inc. Portions created by Sun are
# Copyright (C) 1999 Sun Microsystems, Inc. All
# Rights Reserved.
#
# Contributor(s): 
# Client QA Team, St. Petersburg, Russia
#

DEPTH		= ..\..\..\..\..\..\..
topsrcdir	= ..\..\..\..\..\..\..
srcdir		= .
VPATH		= .

MAKE_OBJ_TYPE=DLL
MODULE=J2XRETClientTestComponent
COMPONENT=1

XPIDLSRCS	= \
	.\iJ2XRETClientTestComponent.idl \
	$(NULL)

JAVA_SRC	= \
	J2XRETClientTestComponent.java  

JAVAI_SRC	= \
	iJ2XRETClientTestComponent.java 

include <$(DEPTH)\config\rules.mak>

J2XRETClientTestComponent.jar.comp: manifest  J2XRETClientTestComponent.class
	$(JDKHOME)\bin\jar cvfm J2XRETClientTestComponent.jar.comp  manifest *.class

J2XRETClientTestComponent.class:
	$(JDKHOME)\bin\javac  -classpath $(DEPTH)/dist/classes $(JAVA_SRC)

javai:
	echo $(JDKHOME)\bin\javac -classpath $(CLASSPATH);$(DEPTH)\dist\classes -d $(DEPTH)\dist\classes $(JAVAI_SRC)
	$(JDKHOME)\bin\javac -classpath $(CLASSPATH);$(DEPTH)\dist\classes -d $(DEPTH)\dist\classes $(JAVAI_SRC)

install-component: javai J2XRETClientTestComponent.jar.comp J2XRETClientTestComponent.jar.info $(DLL)
	copy J2XRETClientTestComponent.jar* $(DIST)\bin\components
	
clobber::
	-del /f *.class *.jar.comp
	-del /f $(DIST)\bin\components\J2XRETClientTestComponent.jar.*
	-del /f $(DIST)\..\classes\org\mozilla\xpcom\iJ2XRETServerTestComponent.*
	-del /f $(DIST)\..\classes\org\mozilla\xpcom\iJ2XRETClientTestComponent.*
clobber_all:: clobber
install:: install-component
