#//------------------------------------------------------------------------
#//
#// Makefile to build the MODULES\APPLET tree
#//
#//------------------------------------------------------------------------

#//------------------------------------------------------------------------
#//
#// Specify the depth of the current directory relative to the
#// root of NS
#//
#//------------------------------------------------------------------------
DEPTH=..\..

#//------------------------------------------------------------------------
#//
#// Specify any "command" targets. (ie. DIRS, INSTALL_FILES, ...)
#// (these must come before the common makefiles are included)
#// 
#// DIRS          - There are subdirectories to process
#//
#//------------------------------------------------------------------------
!if !defined(NGLAYOUT_PLUGINS)
DIRS= public src
!else
DIRS= public
!endif
#//------------------------------------------------------------------------
#//
#// Include the common makefile rules
#//
#//------------------------------------------------------------------------
include <$(DEPTH)\config\rules.mak>
