#define VERSION_MAJOR  1
#define VERSION_MINOR  6
#define VERSION_PATCH  1
#define VERSION_EXTRA  ""
#define VERSION_PACKED ((VERSION_MAJOR<<16)|(VERSION_MINOR<<8)|(VERSION_PATCH))
#define VERSION_STRING_NOSP "v1.6.1"
#define VERSION_STRING      " v1.6.1"
