#!gmake
#
# The contents of this file are subject to the Netscape Public License
# Version 1.0 (the "NPL"); you may not use this file except in
# compliance with the NPL.  You may obtain a copy of the NPL at
# http://www.mozilla.org/NPL/
#
# Software distributed under the NPL is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the NPL
# for the specific language governing rights and limitations under the
# NPL.
#
# The Initial Developer of this code under the NPL is Netscape
# Communications Corporation.  Portions created by Netscape are
# Copyright (C) 1998 Netscape Communications Corporation.  All Rights
# Reserved.

# 

DEPTH		= ../../../..

MODULE		= Xfe
LIBRARY_NAME	= XfeWidgets

#
# This guy is just a demo widget that has all the bells and whistles.
# It can be conveniently used as a template.
#
#		TempTwo.c
#

CSRCS		= \
		  Arrow.c \
		  BmButton.c \
		  BmCascade.c \
		  Button.c \
		  BypassShell.c \
		  CallProcs.c \
		  Cascade.c \
		  ChildrenUtil.c \
		  Chrome.c \
		  ComboBox.c \
		  Converters.c \
		  Cursor.c \
		  DashBoard.c \
		  Debug.c \
		  DialogUtil.c \
		  Draw.c \
		  FancyBox.c \
		  Find.c \
		  FontChooser.c \
		  FrameShell.c \
		  GcUtil.c \
		  Geometry.c \
		  Label.c \
		  ListUtil.c \
		  Logo.c \
		  Manager.c \
		  MenuUtil.c \
		  Oriented.c \
		  Pane.c \
		  PixmapUtil.c \
		  Primitive.c \
		  Private.c \
		  ProgressBar.c \
		  RepType.c \
		  Resources.c \
		  ShellUtil.c \
		  StringUtil.c \
		  Tab.c \
		  TaskBar.c \
		  ToolBar.c \
		  ToolBox.c \
		  ToolItem.c \
		  ToolScroll.c \
		  Translations.c \
		  Util.c \
		  WmUtil.c \
		  $(NULL)

include $(DEPTH)/config/rules.mk

INCLUDES	+= -I..
