# This file is in the UTF-8 encoding. It is *not*
# a Java .properties file and does *not* use \escapes

Welcome_Title=$ProductName$ Setup
Welcome_MessageWelcome=Welcome to %s
Welcome_Message0=You are about to install %s.
Welcome_Message1=It is strongly recommended that you exit all Windows programs before running this Setup program.
Welcome_Message2=Click Cancel to quit Setup and then close any programs you have running.  Click Next to continue the Setup program.
Welcome_Message3=Click Next to continue installing %s.

License_Title=Software License Agreement
License_SubTitle=Terms and conditions for using this software.
License_Message0=Please read the following license agreement. Use the scroll bar to view the rest of this agreement.
License_Accept=I &Accept the terms of the License Agreement
License_Decline=I do NO&T Accept the terms of the License Agreement

Type_Title=Setup Type
Type_SubTitle=Choose setup options.
Type_Message0=Choose the type of Setup you prefer, then click Next.

Standard_Short=&Standard
Standard_Long=Thunderbird will be installed with the most common options.

Custom_Short=&Custom
Custom_Long=You may choose individual options to be installed. Recommended for experienced users.

Select_Title=Select Components
Select_SubTitle=Additional components that enhance $ProductName$.
Select_Message0=Choose additional components you want to install, then click Next.

Path_Title=Install Folder
Path_SubTitle=Where $ProductName$ will be installed.
Path_Message0=$ProductName$ will be installed into the following folder:

Integration_Title=Set Up Shortcuts
Integration_SubTitle=Creates Program Icons
Integration_Message0=Create icons for $ProductShortName$:

Integration_Desktop=On my Desktop
Integration_StartMenu=In my Start Menu Programs folder
Integration_QuickLaunch=In my Quick Launch bar

SelectFolder_Title=$ProductName$ Setup - Select Program Folder
SelectFolder_Message0=Setup will add program icons to the Program Folder listed below.  You may type a new folder name, or select one from the Existing Folders list.  Click Next to continue.

Advanced_Title=$ProductName$ Setup - Advanced Settings
Advanced_Message0=If your Internet connection requires a proxy server, enter your server name and port information.  If your Internet connection doesn't require a proxy server, leave the fields blank.

Install_Title=Summary
Install_SubTitle=Ready to start installing $ProductName$.
Install_MessageInstall=Setup will now install the following components:
Install_MessageDownload=Setup will now download and install the following components:
Install_Message0=Click Next to continue.

Downloading_Title=Downloading
Downloading_SubTitle=Downloading required components...
Downloading_Blurb=Setup is downloading the files required to install $ProductName$.
Downloading_FileName=Currently Downloading:
Downloading_Time=Time Remaining:

Installing_Title=Installing
Installing_SubTitle=Installing $ProductName$...
Installing_Blurb=Setup is installing application files. 
Installing_Status=Preparing File:
Installing_Component=Currently Installing:

Success_Title=Install Complete
Success_Header=Install Complete
Success_Message0=%s was successfully installed.
Success_Message1=Click Finish to complete Setup. 
Success_Launch=Launch %s now.

Check_Message=Download of $ProductName$ was successful. $ProductNameInternal$ must be closed to proceed with installation. Click OK to exit $ProductNameInternal$ automatically and to begin installation.
Check_FullMessage=$ProductNameInternal$ must be closed to proceed with installation. Click OK to exit $ProductNameInternal$ automatically and to begin installation.
Check_Wait=Shutting down $ProductNameInternal$.  Please wait...

Component_XPCOM=Cross-Platform COM
Component_Mail=$ProductName$
Component_Offline=Offline Support
Component_Offline_Long=Adds Offline support to $ProductName$ Mail.
Component_RSS=RSS Support
Component_RSS_Long=Adds RSS support to $ProductName$.
Component_QFA=Quality Feedback Agent
Component_QFA_Long=for reporting $ProductName$ crash information
