#! gmake
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

CORE_DEPTH	= ../../..

include $(CORE_DEPTH)/coreconf/config.mk

objdir_name:
	@echo $(OBJDIR_NAME)

os_arch:
	@echo $(OS_ARCH)

dll_prefix:
	@echo $(DLL_PREFIX)

dll_suffix:
	@echo $(DLL_SUFFIX)
