${license_mak}

DEPTH 		= ${depth_1_win}
topsrcdir	= @top_srcdir@
srcdir		= @srcdir@
VPATH		= @srcdir@

include <$(DEPTH)\config\config.mak>

MODULE			= ${component_module_name}
LIBRARY_NAME	= ${component_library_name}
IS_COMPONENT	= 1
REQUIRES		= ${component_required_libs}

CPPSRCS			= ${filename:implementation.cpp}

include <$(DEPTH)\config\rules.mak>
