/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsIDOMNode.idl"

[scriptable, uuid(cf5ad6cf-6f49-4ca7-9b50-590d7bb27a13)]
interface nsIDOMCaretPosition : nsISupports {
  readonly attribute nsIDOMNode offsetNode;
  readonly attribute unsigned long offset;
};
