%filter substitution

%define panel_dark_color #41464C
%define panel_dark_background url(chrome://browser/skin/images/panel-dark.png)
%define panel_light_color #F1F1F1
%define panel_light_background url(chrome://browser/skin/images/panel-light.png)

%define field_sizing 30px
%define field_foreground_color #000000
%define field_disabled_foreground_color #999999
%define field_mid_foreground_color #bababa
%define field_background_color #FFFFFF

%define border_color #BFC6CE
%define selected_color #FF8000

%define urlbar_border_color #BFC6CC
%define urlbar_edit_height 36px

%define toolbar_vertical_spacing 5px
%define toolbar_horizontal_spacing 20px
%define toolbar_height 68px
%define tabs_height 178px
%define tray_slide_height 247px

%define progress_height 3px
%define progress_start_color #0095dd
%define progress_end_color #97cbff

%define appbar_color #FF8000
%define appbar_top_border #BFC6CE

%define label_height 30px

%define thumbnail_width 232px
%define thumbnail_height 148px

%define tile_border_color #dbdcde
%define tile_width 200px

%define tab_inner_width 180px
%define tab_spacing 45px;
%define tab_compression 40px;

%define scroller_thickness 4px
%define scroller_minimum 8px

%define metro_spacing_xxsmall 2px
%define metro_spacing_xsmall 3px
%define metro_spacing_small 5px
%define metro_spacing_snormal 10px
%define metro_spacing_normal 15px
%define metro_spacing_xnormal 20px
%define metro_spacing_xxnormal 25px
%define metro_spacing_xxxnormal 30px
%define metro_spacing_large 40px
%define metro_spacing_xlarge 45px
%define metro_spacing_xxxlarge 65px

%define metro_border_thin 1px
%define metro_border_thick 2px
%define metro_border_xthick 4px

%define metro_font_snormal 14px
%define metro_font_normal 15px
%define metro_font_large 25px
%define metro_font_xlarge 45px

%define font_xlarge 32px
%define font_xnormal 17px
%define font_normal 16px
%define font_snormal 15px
%define font_small 12px
%define font_xsmall 11px
%define font_tiny 9px
%define font_xtiny 8px
%define font_xxtiny 7px

%define touch_row 47px
%define touch_button_xlarge 48px
%define touch_button_large 43px
%define touch_button_small 37px
%define touch_action_minwidth 133px
%define touch_normal 43px
%define touch_small 36px

%define margin_context_popup 21px
%define margin_large 16px
%define margin_xxxnormal 11px
%define margin_xnormal 7px
%define margin_normal 5px
%define margin_snormal 4px
%define margin_small 3px
%define margin_tiny 1px
%define margin_xtiny 1px

%define padding_xlarge 21px
%define padding_large 16px
%define padding_xxxnormal 11px
%define padding_xxnormal 8px
%define padding_xnormal 7px
%define padding_normal 5px
%define padding_snormal 4px
%define padding_small 3px
%define padding_xsmall 1px
%define padding_tiny 1px

%define border_width_xxlarge 4px
%define border_width_xlarge 3px
%define border_width_large 2px
%define border_width_small 1px
%define border_width_tiny 1px

%define border_radius_normal 5px
%define border_radius_small 4px
%define border_radius_xsmall 2px
%define border_radius_tiny 1px

%define shadow_width_xlarge 7px
%define shadow_width_large 4px
%define shadow_width_small 1px

% easing function and duration for animations match winJS showPanel method
%define metro_animation_duration 550ms
%define metro_animation_easing cubic-bezier(0.1, 0.9, 0.2, 1)
