#!/usr/bin/perl -w
#############################################################################
#
# The contents of this file are subject to the Mozilla Public License
# Version 1.0 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.mozilla.org/MPL/
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is PerLDAP. The Initial Developer of the Original
# Code is Netscape Communications Corp. and Clayton Donley. Portions
# created by Netscape are Copyright (C) Netscape Communications
# Corp., portions created by Clayton Donley are Copyright (C) Clayton
# Donley. All Rights Reserved.
#
# Contributor(s):
#
# DESCRIPTION
#    Perl Script to Install PerLDAP Binaries without a Makefile.
#    For use with the binary distribution of PerLDAP.
#
#############################################################################

use File::Path;
use File::Copy;
use Config;

print "\n##############################################\n";
print "#       Installing Netscape PerLDAP v1.0     #\n";
print "##############################################\n\n";

$ARCH_LIB = $Config{'sitearchexp'} . "/auto/Mozilla/LDAP/API";
$PERL_LIB = $Config{'sitelibexp'};

print "Creating Directory '$ARCH_LIB'...\n";
File::Path::mkpath "$ARCH_LIB";
print "Creating Directory '$PERL_LIB/Mozilla/LDAP'...\n";
File::Path::mkpath "$PERL_LIB/Mozilla/LDAP";

print "Copying Architecture Dependent Files...\n";

foreach $file (glob "blib/arch/auto/Mozilla/LDAP/API/*")
{
   copy($file,"$ARCH_LIB");
}

print "Copying Module Components...\n";

foreach $file (glob "blib/lib/Mozilla/LDAP/*")
{
   copy($file,"$PERL_LIB/Mozilla/LDAP");
}

print "Finished!\n\n";
exit 0;
