/*
 * ************* DO NOT EDIT THIS FILE ***********
 *
 * This file was automatically generated from dom.idl.
 */


package org.mozilla.dom;

import org.mozilla.xpcom.*;
import org.w3c.dom.DOMException;


/**
 * Interface Element
 *
 * IID: 0x0a7d6f40-9ad5-11d4-a983-00105ae3801e
 */

public interface Element extends Node
{
    public static final String IID =
        "0a7d6f40-9ad5-11d4-a983-00105ae3801e";


    /* readonly attribute DOMString tagName; */
    public String getTagName();

    /* DOMString getAttribute (in DOMString name); */
    public String getAttribute(String name);

    /* void setAttribute (in DOMString name, in DOMString value)  raises (DOMException); */
    public void setAttribute(String name, String value) throws DOMException;

    /* void removeAttribute (in DOMString name)  raises (DOMException); */
    public void removeAttribute(String name) throws DOMException;

    /* Attr getAttributeNode (in DOMString name); */
    public Attr getAttributeNode(String name);

    /* Attr setAttributeNode (in Attr newAttr)  raises (DOMException); */
    public Attr setAttributeNode(Attr newAttr) throws DOMException;

    /* Attr removeAttributeNode (in Attr oldAttr)  raises (DOMException); */
    public Attr removeAttributeNode(Attr oldAttr) throws DOMException;

    /* NodeList getElementsByTagName (in DOMString name); */
    public NodeList getElementsByTagName(String name);

    /* DOMString getAttributeNS (in DOMString namespaceURI, in DOMString localName); */
    public String getAttributeNS(String namespaceURI, String localName);

    /* void setAttributeNS (in DOMString namespaceURI, in DOMString qualifiedName, in DOMString value)  raises (DOMException); */
    public void setAttributeNS(String namespaceURI, String qualifiedName, String value) throws DOMException;

    /* void removeAttributeNS (in DOMString namespaceURI, in DOMString localName)  raises (DOMException); */
    public void removeAttributeNS(String namespaceURI, String localName) throws DOMException;

    /* Attr getAttributeNodeNS (in DOMString namespaceURI, in DOMString localName); */
    public Attr getAttributeNodeNS(String namespaceURI, String localName);

    /* Attr setAttributeNodeNS (in Attr newAttr)  raises (DOMException); */
    public Attr setAttributeNodeNS(Attr newAttr) throws DOMException;

    /* NodeList getElementsByTagNameNS (in DOMString namespaceURI, in DOMString localName); */
    public NodeList getElementsByTagNameNS(String namespaceURI, String localName);

    /* boolean hasAttribute (in DOMString name); */
    public boolean hasAttribute(String name);

    /* boolean hasAttributeNS (in DOMString namespaceURI, in DOMString localName); */
    public boolean hasAttributeNS(String namespaceURI, String localName);

}

/*
 * end
 */
