/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/*
 * The contents of this file are subject to the Netscape Public License
 * Version 1.0 (the "NPL"); you may not use this file except in
 * compliance with the NPL.  You may obtain a copy of the NPL at
 * http://www.mozilla.org/NPL/
 *
 * Software distributed under the NPL is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the NPL
 * for the specific language governing rights and limitations under the
 * NPL.
 *
 * The Initial Developer of this code under the NPL is Netscape
 * Communications Corporation.  Portions created by Netscape are
 * Copyright (C) 1999 Netscape Communications Corporation.  All Rights
 * Reserved.
 */
/* handles operations dealing with enabling and disabling privileges */
#include "nsISupports.idl"
#include "nsIPrincipal.idl"
#include "nsITarget.idl"
#include "nsIPrincipalArray.idl"

interface nsIScriptContext;

[uuid(43019898-4782-11d3-ba17-0060b0f199a2)]
interface nsIPrivilegeManager : nsISupports
{
	void IsPrivilegeEnabled(in nsIScriptContext cx, in nsITarget target, in long callerDepth, out boolean result);

	void EnablePrivilege(in nsIScriptContext cx, in nsITarget target, in nsIPrincipal prin, in long callerDeph, out boolean result);

	void RevertPrivilege(in nsIScriptContext cx, in nsITarget target, in long callerDepth, out boolean result);

	void DisablePrivilege(in nsIScriptContext cx, in nsITarget target, in long callerDepth, out boolean result);

	void CheckPrivilegeGranted(in nsIScriptContext cx, in nsITarget target, in long callerDepth, in voidStar data, out boolean result);

	void GetPrincipalPrivilege(in nsITarget target, in nsIPrincipal prin, in voidStar data, out nsIPrivilege priv);

	void RemovePrincipalsPrivilege(in string prinName, in string targetName, out boolean result);

	void AskPermission(in nsIPrincipal useThisPrin, in nsITarget target, in voidStar data, out boolean result);

	void SetPermission(in nsIPrincipal useThisPrin, in nsITarget target, in nsIPrivilege newPrivilege);

};
%{C++
#define NS_PRIVILEGEMANAGER_CID \
{ 0x422e8544, 0x4b91, 0x11d3, \
{ 0xba, 0x18, 0x00, 0x60, 0xb0, 0xf1, 0x99, 0xa2 }}
#define NS_PRIVILEGEMANAGER_PROGID "component://netscape/privilegemanager"
#define NS_PRIVILEGEMANAGER_CLASSNAME "privilegemanager"
%}