# 
# This is a special file.
# It's syntax is as follows:
# Lines starting with a # are comments as are lines with # in them.
# Lines starting with a & are includes to another task list
# All other lines are fully qualified classnames that extend from Task
# Lines will be trimmed.
#
# This file lists the Tasks to be preformed at abnormal shutdown
# Keep this file short!
# 
grendel.addressbook.HSQLDBShutdownTask
grendel.addressbook.DerbyShutdownTask