      interface Element : Node {
        wstring             getTagName();
        NodeIterator        getAttributes();
        wstring             getAttribute(in name name);
        void                setAttribute(in string name, 
                                         in string value);
        void                removeAttribute(in wstring name);
        Attribute           getAttributeNode(in name name);
        void                setAttributeNode(in Attribute newAttr);
        void                removeAttributeNode(in Attribute oldAttr);
        void                getElementsByTagName(in wstring tagname);
        void                normalize();
      };

