#!nmake
#
# The contents of this file are subject to the Mozilla Public
# License Version 1.1 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy of
# the License at http://www.mozilla.org/MPL/
#
# Software distributed under the License is distributed on an "AS
# IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
# implied. See the License for the specific language governing
# rights and imitations under the License.
#
# The Original Code is mozilla.org code.
#
# The Initial Developer of the Original Code is International
# Business Machines Corporation. Portions created by IBM
# Corporation are Copyright (C) 2000 International Business
# Machines Corporation. All Rights Reserved.
#
# Contributor(s): IBM Corporation.
#                 Heikki Toivonen <heikki@netscape.com>
#

DEPTH = ..\..\..

REQUIRES	= xpcom \
		  string \
		  xmlextras \
		  necko \
		  dom \
		  content \
		  layout \
		  widget \
		  $(NULL)

include <$(DEPTH)/config/config.mak>

MAKE_OBJ_TYPE = EXE
PROG1 = .\$(OBJDIR)\TestXMLExtras.exe

PROGRAMS = $(PROG1) \
           $(NULL)

LCFLAGS  = -DUSE_NSREG -GX

LLIBS =                       \
        $(DIST)\lib\xpcom.lib \
        $(LIBNSPR)

include <$(DEPTH)\config\rules.mak>

install:: $(PROGRAMS)
	-for %p in ($(PROGRAMS)) do $(MAKE_INSTALL) %p $(DIST)\bin

clobber::
	-for %p in ($(PROGRAMS)) do $(RM) %p $(DIST)\bin\%p

$(PROG1): $(OBJDIR) TestXMLExtras.cpp
