/* This file is included as the content of an array 
 * 
 * the first column is the mozilla pref name, the second column is the 
 * the related gconf pref name.
 *
 *************************************************************************/

    {"network.proxy.http", "/system/http_proxy/host"},
    {"network.proxy.http_port", "/system/http_proxy/port"},
    {"network.proxy.ftp", "/system/ftp_proxy/host"},
    {"network.proxy.ftp_port", "/system/ftp_proxy/port"},
    {"config.use_system_prefs.accessibility", "/desktop/gnome/interface/accessibility"},
