/* This file is included as the content of an array 
 * 
 * the first column is the mozilla pref name, the second column is the 
 * the related gconf pref name.
 *
 *************************************************************************/

    {"network.proxy.http", "/system/http_proxy/host"},
    {"network.proxy.http_port", "/system/http_proxy/port"},
    {"network.proxy.ftp", "/system/proxy/ftp_host"},
    {"network.proxy.ftp_port", "/system/proxy/ftp_port"},
    {"network.proxy.ssl", "/system/proxy/secure_host"},
    {"network.proxy.ssl_port", "/system/proxy/secure_port"},
    {"network.proxy.socks", "/system/proxy/socks_host"},
    {"network.proxy.socks_port", "/system/proxy/socks_port"},
    {"network.proxy.no_proxies_on", "/system/http_proxy/ignore_hosts"},
    {"network.proxy.autoconfig_url", "/system/proxy/autoconfig_url"},
    {"network.proxy.type", "/system/proxy/mode"}, 
    {"config.use_system_prefs.accessibility", "/desktop/gnome/interface/accessibility"},
