#!/bin/sh
# S80calendar_fix_permissions_bug_230617
# 
# This script will correct the permission bits for the Mozilla
# Calendar (see bug 230617 - "Jan 9 Build will not create new
# Calendar, Event, or Task for *first time* installation") for details.

# Prechecks
if [ -z "${MOZ_PIS_USER_DIR}" ] ; then
    echo "${0}: Internal error: MOZ_PIS_USER_DIR not set."
    exit 1
fi
if [ ${MOZ_PIS_API} -lt 2 ] ; then
    echo "${0}: Internal error: MOZ_PIS_API is ${MOZ_PIS_API}, should be >= 2."
    exit 1
fi

# We run in a seperate process so we are allows to use single-letter
# shell vars (see mozilla/xpfe/bootstrap/init.d/README)
for i in "${HOME}/${MOZ_PIS_USER_DIR}"/*/*.slt/Calendar ; do
    if [ -d "${i}" ] ; then
        if [ ! -r "${i}" -o ! -w "${i}" -o ! -x "${i}" ] ; then
            echo "${0}: Fixing permissions for ${i} ..."
            chmod u+rwx "${i}"
        fi
    fi
done
# EOF.
