#//------------------------------------------------------------------------
#//
#// Makefile to install MODULES/APPLET/INCLUDE header files into the distribution
#// directory.
#//
#//------------------------------------------------------------------------
include <manifest.mn>
include <$(DEPTH)/config/rules.mak>

