#!/bin/csh -f
# 
# The contents of this file are subject to the Mozilla Public
# License Version 1.1 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy of
# the License at http://www.mozilla.org/MPL/
# 
# Software distributed under the License is distributed on an "AS
# IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
# implied. See the License for the specific language governing
# rights and limitations under the License.
# 
# The Original Code is browser-buster.
# 
# The Initial Developer of the Original Code is Netscape Comm.
# Inc.  Portions created by Netscape are
# Copyright (C) Netscape.  All
# Rights Reserved.
# 
# Contributor(s):
#  Chris Hofmann <chofmann@netscape.com>
# 

# usage - runtest 30 28 [directory]

while (1)

  rotate_pages $1 $2 $3

end
