/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
 *
 * The contents of this file are subject to the Netscape Public
 * License Version 1.1 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of
 * the License at http://www.mozilla.org/NPL/
 *
 * Software distributed under the License is distributed on an "AS
 * IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
 * implied. See the License for the specific language governing
 * rights and limitations under the License.
 *
 * The Original Code is mozilla.org code.
 *
 * The Initial Developer of the Original Code is Netscape
 * Communications Corporation.  Portions created by Netscape are
 * Copyright (C) 1999 Netscape Communications Corporation. All
 * Rights Reserved.
 *
 * Contributor(s): Radha Kulkarni (radha@netscape.com)
 *                 Jason Eager    (jce2@po.cwru.edu)
 */
 
#include "nsISupports.idl"
#include "nsIFactory.idl"


%{C++
#define NS_URLBARHISTORY_CID \
{0x74254499, 0x171a, 0x11d4, {0x98, 0x70, 0x0, 0xc0, 0x4f, 0xa0, 0x2f, 0x40}}


#define NS_URLBARHISTORY_CONTRACTID "@mozilla.org/browser/urlbarhistory;1"
#define NS_URLBARAUTOCOMPLETE_CONTRACTID "@mozilla.org/autocompleteSession;1?type=urlbar"
#define UBHISTORY_MAX_ENTRIES = 15;
%}

[scriptable, uuid(74254499-171a-11d4-9870-00c04fa02f40)]
interface nsIUrlbarHistory: nsISupports
{
  /**
   * Get the size of the History list
   */
   readonly attribute long count;

  /**
   * print the History contents
   */
   void printHistory();

  /**
   * clear the History contents
   */
   void clearHistory();
    

};
