#!nmake
#
# The contents of this file are subject to the Netscape Public
# License Version 1.1 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy of
# the License at http://www.mozilla.org/NPL/
#
# Software distributed under the License is distributed on an "AS
# IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
# implied. See the License for the specific language governing
# rights and limitations under the License.
#
# The Original Code is mozilla.org code.
#
# The Initial Developer of the Original Code is Netscape
# Communications Corporation.  Portions created by Netscape are
# Copyright (C) 1998 Netscape Communications Corporation. All
# Rights Reserved.
#
# Contributor(s): 

DEPTH=..\..\..

MAKE_OBJ_TYPE   = EXE
PROGRAM = .\$(OBJDIR)\test_main.exe

OBJS =  \
	.\$(OBJDIR)\test_main.obj		\
	.\$(OBJDIR)\nsString2.obj		\
	.\$(OBJDIR)\nsStr.obj		\
	.\$(OBJDIR)\nsString.obj		\
	.\$(OBJDIR)\nsCRT.obj		\
	.\$(OBJDIR)\nsAllocator.obj		\
	.\$(OBJDIR)\nsDeque.obj		\
	$(NULL)

CPPSRCS =				\
	test_main.cpp			\
	$(DEPTH)\xpcom\nsString2.cpp \
	$(DEPTH)\xpcom\ds\nsStr.cpp \
	$(DEPTH)\xpcom\ds\nsString.cpp \
	$(DEPTH)\xpcom\ds\nsCRT.cpp \
	$(DEPTH)\xpcom\ds\nsAllocator.cpp \
	$(DEPTH)\xpcom\ds\nsDeque.cpp \
	$(NULL)

LCFLAGS = \
        -DNEW_STRING_APIS -DSTANDALONE_STRING_TESTS -DNDEBUG -GX\
        $(DEFINES) \
        $(NULL)

LINCS=-I$(PUBLIC)\xpcom	\
	-I$(MOZ_TOOLS)\include	\
	$(NULL)

include <$(DEPTH)\config\rules.mak>

export:: $(PROGRAM)
	$(MAKE_INSTALL) $(PROGRAM) $(DIST)\bin

clobber::
	rm -f $(DIST)\bin\test_main.exe

$(PROGRAM):: $(OBJS) $(MYLIBS)
