#!nmake
#
# The contents of this file are subject to the Netscape Public License
# Version 1.0 (the "NPL"); you may not use this file except in
# compliance with the NPL.  You may obtain a copy of the NPL at
# http://www.mozilla.org/NPL/
#
# Software distributed under the NPL is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the NPL
# for the specific language governing rights and limitations under the
# NPL.
#
# The Initial Developer of this code under the NPL is Netscape
# Communications Corporation.  Portions created by Netscape are
# Copyright (C) 1998 Netscape Communications Corporation.  All Rights
# Reserved.

DEPTH=..\..
IGNORE_MANIFEST=1

DIRS = btest

MAKE_OBJ_TYPE	= EXE
PROG1 = .\$(OBJDIR)\TestRect.exe
PROG2 = .\$(OBJDIR)\TestColorNames.exe
PROG3 = .\$(OBJDIR)\DumpColors.exe
PROGRAMS = $(PROG1) $(PROG2) $(PROG3)

LINCS=-I$(XPDIST)\public\raptor -I$(XPDIST)\public\xpcom -I..\src

LLIBS=				\
 $(DIST)\lib\raptorbase.lib	\
 $(DIST)\lib\raptorgfxwin.lib	\
 $(DIST)\lib\xpcom32.lib	\
 $(LIBNSPR)			\
 $(DIST)\lib\plc3.lib

include <$(DEPTH)\config\rules.mak>

install:: $(PROGRAMS)
	$(MAKE_INSTALL) $(PROG1) $(DIST)\bin
	$(MAKE_INSTALL) $(PROG2) $(DIST)\bin
	$(MAKE_INSTALL) $(PROG3) $(DIST)\bin

clobber::
	rm -f $(DIST)\bin\TestRect.exe
	rm -f $(DIST)\bin\TestColorNames.exe
	rm -f $(DIST)\bin\DumpColors.exe

# Move this into config/obj.inc when it's allowed
.cpp{.\$(OBJDIR)\}.exe:
    $(CC) @<<$(CFGFILE)
        $(CFLAGS)
        $(LCFLAGS)
        $(LINCS)
        $(LINCS_1)
        $(INCS)
        $(LLIBS)
        $(OS_LIBS)
        -Fd.\$(OBJDIR)\
        -Fe.\$(OBJDIR)\
        -Fo.\$(OBJDIR)\
        $(CURDIR)$(*B).cpp
<<

$(PROG1): $(OBJDIR) TestRect.cpp

$(PROG2): $(OBJDIR) TestColorNames.cpp

$(PROG3): $(OBJDIR) DumpColors.cpp
