/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"
#include "nsIPaymentActionResponse.idl"

[scriptable, uuid(ea008d0c-9e9f-411f-a6c5-a62106ba7ab9)]
interface nsIPaymentUIService : nsISupports
{
  nsIPaymentActionResponse canMakePayment(in AString requestId);
  nsIPaymentActionResponse showPayment(in AString requestId);
  nsIPaymentActionResponse abortPayment(in AString requestId);
  nsIPaymentActionResponse completePayment(in AString requestId);
  nsIPaymentActionResponse updatePayment(in AString requestId);
};
