#!nmake
#
# The contents of this file are subject to the Netscape Public
# License Version 1.1 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy of
# the License at http://www.mozilla.org/NPL/
#
# Software distributed under the License is distributed on an "AS
# IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
# implied. See the License for the specific language governing
# rights and limitations under the License.
#
# The Original Code is mozilla.org code.
#
# The Initial Developer of the Original Code is Netscape
# Communications Corporation.  Portions created by Netscape are
# Copyright (C) 1998 Netscape Communications Corporation. All
# Rights Reserved.
#
# Contributor(s): 

DEPTH=..\..\..
include <$(DEPTH)/config/config.mak>

MAKE_OBJ_TYPE	= EXE
PROG2 = .\$(OBJDIR)\TestCSSPropertyLookup.exe
PROGRAMS = $(PROG2)

DEFINES = -D_IMPL_NS_HTML

LCFLAGS = \
        $(LCFLAGS) \
        $(DEFINES) \
        $(NULL)

LINCS=				\
  -I$(PUBLIC)\xpcom		\
  -I$(PUBLIC)\raptor		\
  -I$(PUBLIC)\dom		\
  -I$(PUBLIC)\js		\
  -I..\base\src			\
  -I..\style\src		\
  -I..\..\css\layout\src	\
  -I..\..\base\src \
  -I..\document\src

LLIBS=				\
 $(DIST)\lib\layouthtmlbase_s.lib	\
 $(DIST)\lib\layouthtmldoc_s.lib	\
 $(DIST)\lib\layouthtmlforms_s.lib	\
 $(DIST)\lib\layouthtmlstyle_s.lib	\
 $(DIST)\lib\layouthtmltable_s.lib	\
 $(DIST)\lib\gkparser.lib	\
 $(DIST)\lib\layoutbase_s.lib	\
 $(DIST)\lib\gkgfxwin.lib	\
 $(DIST)\lib\layoutxulbase_s.lib \
 $(DIST)\lib\contentshared_s.lib \
!ifdef MOZ_MATHML
 $(DIST)\lib\layoutmathmlbase_s.lib \
 $(DIST)\lib\layoutmathmlcontent_s.lib	\
!endif
!ifdef MOZ_SVG
 $(DIST)\lib\layoutsvgbase_s.lib      \
 $(DIST)\lib\layoutsvgcontent_s.lib   \
!endif
 $(DIST)\lib\img32$(VERSION_NUMBER).lib	\
 $(DIST)\lib\util.lib		\
 $(DIST)\lib\xpcom.lib	\
 $(DIST)\lib\jsdom.lib		        \
 $(DIST)\lib\timer_s.lib \
 $(LIBNSPR)			\
 $(DIST)\lib\js32$(VERSION_NUMBER).lib	

include <$(DEPTH)\config\rules.mak>

install:: $(PROGRAMS)
	$(MAKE_INSTALL) $(PROG2) $(DIST)\bin

clobber::
	rm -f $(DIST)\bin\TestCSSPropertyLookup.exe

$(PROG2): $(OBJDIR) TestCSSPropertyLookup.cpp
