// This file was autogenerated by the `uniffi-bindgen-gecko-js` crate.
// Trust me, you don't want to mess with it!

{% import "macros.jsm" as js %}

"use strict";

var EXPORTED_SYMBOLS = [];

{% include "Helpers.jsm" %}

{% include "Types.jsm" %}

{% include "TopLevelFunctions.jsm" %}
