/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

/*
 * Used by the console service to notify listeners of new console messages.
 */

#include "nsISupports.idl"

interface nsIConsoleMessage;

[scriptable, function, uuid(35c400a4-5792-438c-b915-65e30d58d557)]
interface nsIConsoleListener : nsISupports
{
    void observe(in nsIConsoleMessage aMessage);
};
