/* -*- Mode: IDL; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
 *
 * The contents of this file are subject to the Netscape Public License
 * Version 1.0 (the "NPL"); you may not use this file except in
 * compliance with the NPL.  You may obtain a copy of the NPL at
 * http://www.mozilla.org/NPL/
 *
 * Software distributed under the NPL is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the NPL
 * for the specific language governing rights and limitations under the
 * NPL.
 *
 * The Initial Developer of this code under the NPL is Netscape
 * Communications Corporation.  Portions created by Netscape are
 * Copyright (C) 1998 Netscape Communications Corporation.  All Rights
 * Reserved.
 */

/* DOM stubs so that we can pass DOM objects across XPConnect */

%{C++
/* C++ should ignore this file because there are real DOM interfaces
   elsewhere, so if 0 it out
*/
#if 0
%}

#include "nsISupports.idl"

/* put your DOM stub interfaces here */
/* if you have XUL element stubs, put them in
 * mozilla/rdf/public/xulstubs.idl
 */

[scriptable, uuid(a6cf907c-15b3-11d2-932e-00805f8add32)]
interface nsIDOMNode : nsISupports {};

[scriptable, uuid(a6cf9078-15b3-11d2-932e-00805f8add32)]
interface nsIDOMElement : nsIDOMNode {};

[scriptable, uuid(a6cf9075-15b3-11d2-932e-00805f8add32)]
interface nsIDOMDocument : nsIDOMNode {};

[scriptable, uuid(a6cf907d-15b3-11d2-932e-00805f8add32)]
interface nsIDOMNodeList : nsISupports {};

[scriptable, uuid(a6cf906e-15b3-11d2-932e-00805f8add32)]
interface nsIDOMNavigator : nsISupports {};

[scriptable, uuid(77947960-b4af-11d2-bd93-00805f8ae3f4)]
interface nsIDOMScreen : nsISupports {};

[scriptable, uuid(896d1d20-b4c4-11d2-bd93-00805f8ae3f4)]
interface nsIDOMHistory : nsISupports {};

[scriptable, uuid(9eb2c150-1d56-11d3-8221-0060083a0bcf)]
interface nsIDOMBarProp : nsISupports {};

[scriptable, uuid(a6cf906f-15b3-11d2-932e-00805f8add32)]
interface nsIDOMWindowCollection : nsISupports {};

[scriptable, uuid(a6cf906b-15b3-11d2-932e-00805f8add32)]
interface nsIDOMWindow : nsISupports {
    readonly attribute  nsIDOMWindow window;
    readonly attribute  nsIDOMWindow self;
    readonly attribute  nsIDOMDocument document;
    readonly attribute  nsIDOMNavigator navigator;
    readonly attribute  nsIDOMScreen screen;
    readonly attribute  nsIDOMHistory history;
    readonly attribute  nsIDOMWindow parent;
    readonly attribute  nsIDOMWindow top;
    readonly attribute  nsIDOMBarProp menubar;
    readonly attribute  nsIDOMBarProp toolbar;
    readonly attribute  nsIDOMBarProp locationbar;
    readonly attribute  nsIDOMBarProp personalbar;
    readonly attribute  nsIDOMBarProp statusbar;
    readonly attribute  nsIDOMBarProp scrollbars;
    readonly attribute  nsIDOMBarProp directories;
    readonly attribute  boolean closed;
    readonly attribute  nsIDOMWindowCollection frames;
             attribute  nsIDOMWindow opener;
             attribute  wstring status;
             attribute  wstring defaultStatus;
             attribute  wstring name;
             attribute  long innerWidth;
             attribute  long innerHeight;
             attribute  long outerWidth;
             attribute  long outerHeight;
             attribute  long screenX;
             attribute  long screenY;
             attribute  long pageXOffset;
             attribute  long pageYOffset;

    boolean Equals(in nsIDOMWindow aWindow);
};


%{C++
#endif
%}
