# 
# The contents of this file are subject to the Mozilla Public
# License Version 1.1 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy of
# the License at http://www.mozilla.org/MPL/
#
# Software distributed under the License is distributed on an "AS
# IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
# implied. See the License for the specific language governing
# rights and limitations under the License.
#
# The Original Code is mozilla.org code.
#
# The Initial Developer of the Original Code is Sun Microsystems,
# Inc. Portions created by Sun are
# Copyright (C) 1999 Sun Microsystems, Inc. All
# Rights Reserved.
#
# Contributor(s): 
TOP_DIR = ../../..

OBJ_DIR = ../obj

CPP = 	GetStringChars_1.cpp \
	GetStringChars_2.cpp \
	GetStringChars_3.cpp \
	GetStringChars_4.cpp \
	GetStringLength_1.cpp \
	GetStringLength_2.cpp \
	GetStringLength_3.cpp \
	GetStringUTFChars_1.cpp \
	GetStringUTFChars_2.cpp \
	GetStringUTFChars_3.cpp \
	GetStringUTFChars_4.cpp \
	GetStringUTFLength_1.cpp \
	GetStringUTFLength_2.cpp \
	GetStringUTFLength_3.cpp \
	NewStringUTF_1.cpp \
	NewStringUTF_2.cpp \
	NewStringUTF_3.cpp \
	NewString_1.cpp \
	NewString_2.cpp \
	NewString_3.cpp \
	ReleaseStringChars_1.cpp \
	ReleaseStringChars_2.cpp \
	ReleaseStringUTFChars_1.cpp \
	ReleaseStringUTFChars_2.cpp 


OBJS = 	$(OBJ_DIR)/GetStringChars_1.obj \
	$(OBJ_DIR)/GetStringChars_2.obj \
	$(OBJ_DIR)/GetStringChars_3.obj \
	$(OBJ_DIR)/GetStringChars_4.obj \
	$(OBJ_DIR)/GetStringLength_1.obj \
	$(OBJ_DIR)/GetStringLength_2.obj \
	$(OBJ_DIR)/GetStringLength_3.obj \
	$(OBJ_DIR)/GetStringUTFChars_1.obj \
	$(OBJ_DIR)/GetStringUTFChars_2.obj \
	$(OBJ_DIR)/GetStringUTFChars_3.obj \
	$(OBJ_DIR)/GetStringUTFChars_4.obj \
	$(OBJ_DIR)/GetStringUTFLength_1.obj \
	$(OBJ_DIR)/GetStringUTFLength_2.obj \
	$(OBJ_DIR)/GetStringUTFLength_3.obj \
	$(OBJ_DIR)/NewStringUTF_1.obj \
	$(OBJ_DIR)/NewStringUTF_2.obj \
	$(OBJ_DIR)/NewStringUTF_3.obj \
	$(OBJ_DIR)/NewString_1.obj \
	$(OBJ_DIR)/NewString_2.obj \
	$(OBJ_DIR)/NewString_3.obj \
	$(OBJ_DIR)/ReleaseStringChars_1.obj \
	$(OBJ_DIR)/ReleaseStringChars_2.obj \
	$(OBJ_DIR)/ReleaseStringUTFChars_1.obj \
	$(OBJ_DIR)/ReleaseStringUTFChars_2.obj 


INCLUDES = -I../include

include ../../../build/rules.mak

all: compile
