#!nmake
#
# The contents of this file are subject to the Netscape Public
# License Version 1.1 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy of
# the License at http://www.mozilla.org/NPL/
#
# Software distributed under the License is distributed on an "AS
# IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
# implied. See the License for the specific language governing
# rights and limitations under the License.
#
# The Original Code is mozilla.org code.
#
# The Initial Developer of the Original Code is Netscape
# Communications Corporation.  Portions created by Netscape are
# Copyright (C) 1998 Netscape Communications Corporation. All
# Rights Reserved.
#
# Contributor(s): 

DEPTH=..\..\..
include <$(DEPTH)/config/config.mak>



DEFINES=-DWIN32_LEAN_AND_MEAN
MODULE=bal_test 

CPPSRCS=                                \
 bal_test.cpp                        \
 $(NULL)

CPP_OBJS=                               \
 .\$(OBJDIR)\bal_test.obj            \
 $(NULL)

MAKE_OBJ_TYPE = EXE
PROGRAM = .\$(OBJDIR)\bal_test.exe

LCFLAGS = \
        $(LCFLAGS) \
        $(DEFINES) \
        $(NULL)

LLIBS = \
	$(DIST)\lib\webclient.lib \
	$(NULL)

include <$(DEPTH)\config\rules.mak>

INCS = \
	-I..\src_moz \
	-I..\bal \
	-I..\bal\win32 \
	$(NULL)

install:: $(PROGRAM)
	$(MAKE_INSTALL) $(PROGRAM) $(DIST)\bin

clobber::
	rm -f $(DIST)\bin\mozilla.exe
