#!nmake
#
# The contents of this file are subject to the Netscape Public
# License Version 1.1 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy of
# the License at http://www.mozilla.org/NPL/
#
# Software distributed under the License is distributed on an "AS
# IS" basis, WITHOUT WARRANTY OF ANY KIND, either express oqr
# implied. See the License for the specific language governing
# rights and limitations under the License.
#
# The Original Code is Mozilla Communicator client code, released
# March 31, 1998.
#
# The Initial Developer of the Original Code is Netscape
# Communications Corporation.  Portions created by Netscape are
# Copyright (C) 1998 Netscape Communications Corporation. All
# Rights Reserved.
#
# Contributor(s): 
#   John Bandhauer <jband@netscape.com>
#
# Alternatively, the contents of this file may be used under the
# terms of the GNU Public License (the "GPL"), in which case the
# provisions of the GPL are applicable instead of those above.
# If you wish to allow use of your version of this file only
# under the terms of the GPL and not to allow others to use your
# version of this file under the NPL, indicate your decision by
# deleting the provisions above and replace them with the notice
# and other provisions required by the GPL.  If you do not delete
# the provisions above, a recipient may use your version of this
# file under either the NPL or the GPL.

DEPTH=..\..\..\..\..

MAKE_OBJ_TYPE	= DLL
DLLNAME		= xpctest
DLL		=.\$(OBJDIR)\$(DLLNAME).dll

MODULE=xpconnect_tests
REQUIRES	= xpcom \
		  string \
		  xpconnect \
		  js \
		  timer \
		  $(NULL)

DEFINES=-DWIN32_LEAN_AND_MEAN

OBJS=					\
	.\$(OBJDIR)\xpctest_array.obj	\
	.\$(OBJDIR)\xpctest_echo.obj	\
	.\$(OBJDIR)\xpctest_child.obj	\
	.\$(OBJDIR)\xpctest_noisy.obj	\
	.\$(OBJDIR)\xpctest_overloaded.obj \
	.\$(OBJDIR)\xpctest_string.obj	\
	.\$(OBJDIR)\xpctest_module.obj	\
	.\$(OBJDIR)\xpctest_attributes.obj \
	.\$(OBJDIR)\xpctest_in.obj	\
	.\$(OBJDIR)\xpctest_const.obj	\
	.\$(OBJDIR)\xpctest_out.obj     \
	.\$(OBJDIR)\xpctest_inout.obj   \
	.\$(OBJDIR)\xpctest_calljs.obj  \
	.\$(OBJDIR)\xpctest_multiple.obj\
	.\$(OBJDIR)\xpctest_domstring.obj \
	.\$(OBJDIR)\xpctest_variant.obj \
	$(NULL)

LINCS=-I$(PUBLIC)\xpconnect -I$(PUBLIC)\xpcom -I$(PUBLIC)\js \
      -I$(PUBLIC)\raptor -I$(PUBLIC)\xpconnect

LCFLAGS = \
        $(LCFLAGS) \
        $(DEFINES) \
        $(NULL)

LLIBS=	$(LIBNSPR)	\
		$(DIST)\lib\js$(MOZ_BITS)$(VERSION_NUMBER).lib	\
		$(DIST)\lib\xpcom.lib	\
		$(NULL)

!ifndef XPCOM_STANDALONE
LLIBS=	$(LLIBS)	\
		$(DIST)\lib\timer_s.lib	\
		$(NULL)
!endif

include <$(DEPTH)\config\rules.mak>

install:: $(DLL)
	$(MAKE_INSTALL) .\$(OBJDIR)\$(DLLNAME).dll $(DIST)\bin\components
#	$(MAKE_INSTALL) .\$(OBJDIR)\$(DLLNAME).lib $(DIST)\lib

clobber::
#	rm -f $(DIST)\lib\$(DLLNAME).lib
	rm -f $(DIST)\bin\$(DLLNAME).dll
