#filter emptyLines

#define MOZ_LANGPACK_EID {fc121405-5aef-4291-86c6-8b43b04194b7}
#define MOZ_LANGPACK_CREATOR mozilla.org

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
# #define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Joe Solon</em:contributor> <em:contributor>Suzy Solon</em:contributor>

#unfilter emptyLines
