#!gmake
#
# The contents of this file are subject to the Mozilla Public License
# Version 1.0 (the "License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.mozilla.org/MPL/
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.  See
# the License for the specific language governing rights and limitations
# under the License.
# 
# The Original Code is the Grendel mail/news client.
# 
# The Initial Developer of the Original Code is Netscape Communications
# Corporation.  Portions created by Netscape are Copyright (C) 1997
# Netscape Communications Corporation.  All Rights Reserved.

SRCS=						\
	ActionFactory.java			\
	BiffIcon.java				\
	BiffThread.java				\
	DialogAuthenticator.java		\
	EditHostDialog.java			\
	FolderCombo.java			\
	FolderFrame.java			\
	FolderListTransferable.java		\
	FolderPanel.java			\
	FolderPanelListener.java		\
	GeneralDialog.java			\
	GeneralFrame.java			\
	GeneralPanel.java			\
	MasterPanel.java			\
	MasterPanelListener.java		\
	MessageCellRenderer.java		\
	MessageDisplayManager.java		\
	MessageFrame.java			\
	MessageHeader.java			\
	MessageListTransferable.java		\
	MessageModel.java			\
	MessagePanel.java			\
	MessagePanelListener.java		\
	MultiMessageDisplayManager.java		\
	NewFolderDialog.java			\
	PrefsDialog.java			\
	ProgressFactory.java			\
	ProgressFrame.java			\
	SimpleAuthenticator.java		\
	SimpleMessageHeader.java		\
	StoreFactory.java			\
	ToolBarLayout.java			\
	UIAction.java				\
	UIFactory.java				\
	UnifiedMessageDisplayManager.java	\
	Util.java				\
	$(NULL)

include ../rules.mk
