	  interface TextRange {
/* IID: {0xb471ab41, 0x2a79, 0x11d3, \
	{ 0x9e, 0xa4, 0x0, 0x60, 0x8, 0x9f, 0xe5, 0x9b } } */
		const int TEXTRANGE_RAWINPUT				= 1;
		const int TEXTRANGE_SELECTEDRAWTEXT			= 2;
		const int TEXTRANGE_CONVERTEDTEXT			= 3;
		const int TEXTRANGE_SELECTEDCONVERTEDTEXT	= 4;

		attribute unsigned short rangeStart;
		attribute unsigned short rangeEnd;
		attribute unsigned short rangeType;
	};
	  interface TextRangeList {
/* IID: { 0x1ee9d531, 0x2a79, 0x11d3, \
	{ 0x9e, 0xa4, 0x0, 0x60, 0x8, 0x9f, 0xe5, 0x9b} } */
		readonly attribute unsigned short length;
		TextRange	Item(in unsigned short index);

	};		
