#include "nsISupports.idl"

interface nsIDOMWindow;

[scriptable, uuid(54fd2dd3-c01b-4f71-888f-462f37a54f57)]
interface nsIWorkerDebuggerListener : nsISupports
{
  void onClose();
};

[scriptable, builtinclass, uuid(b0ea6da8-8bd9-446a-94e2-2ee979903205)]
interface nsIWorkerDebugger : nsISupports
{
  const unsigned long TYPE_DEDICATED = 0;
  const unsigned long TYPE_SHARED = 1;
  const unsigned long TYPE_SERVICE = 2;

  readonly attribute bool isClosed;

  readonly attribute bool isChrome;

  readonly attribute nsIWorkerDebugger parent;

  readonly attribute unsigned long type;

  readonly attribute DOMString url;

  readonly attribute nsIDOMWindow window;

  [implicit_jscontext]
  void initialize(in DOMString url);

  void addListener(in nsIWorkerDebuggerListener listener);

  void removeListener(in nsIWorkerDebuggerListener listener);
};
