#include "nsISupports.idl"

interface nsIDOMWindow;
interface nsIPrincipal;

[scriptable, uuid(9cf3b48e-361d-486a-8917-55cf8d00bb41)]
interface nsIWorkerDebuggerListener : nsISupports
{
  void onClose();

  void onError(in DOMString filename, in unsigned long lineno,
               in DOMString message);

  void onMessage(in DOMString message);
};

[scriptable, builtinclass, uuid(2fe71e0d-3a39-40a3-b809-8418b72328b4)]
interface nsIWorkerDebugger : nsISupports
{
  const unsigned long TYPE_DEDICATED = 0;
  const unsigned long TYPE_SHARED = 1;
  const unsigned long TYPE_SERVICE = 2;

  readonly attribute bool isClosed;

  readonly attribute bool isChrome;

  readonly attribute bool isInitialized;

  readonly attribute nsIWorkerDebugger parent;

  readonly attribute unsigned long type;

  readonly attribute DOMString url;

  readonly attribute nsIDOMWindow window;

  readonly attribute nsIPrincipal principal;

  readonly attribute unsigned long serviceWorkerID;

  [implicit_jscontext]
  void initialize(in DOMString url);

  [implicit_jscontext, binaryname(PostMessageMoz)]
  void postMessage(in DOMString message);

  void addListener(in nsIWorkerDebuggerListener listener);

  void removeListener(in nsIWorkerDebuggerListener listener);
};
