#!gmake
#
# The contents of this file are subject to the Netscape Public License
# Version 1.0 (the "NPL"); you may not use this file except in
# compliance with the NPL.  You may obtain a copy of the NPL at
# http://www.mozilla.org/NPL/
#
# Software distributed under the NPL is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the NPL
# for the specific language governing rights and limitations under the
# NPL.
#
# The Initial Developer of this code under the NPL is Netscape
# Communications Corporation.  Portions created by Netscape are
# Copyright (C) 1998 Netscape Communications Corporation.  All Rights
# Reserved.
#//------------------------------------------------------------------------
#//
#// Makefile to build 
#//
#//------------------------------------------------------------------------

#//------------------------------------------------------------------------
#//
#// Specify the depth of the current directory relative to the
#// root of NS
#//
#//------------------------------------------------------------------------
DEPTH= ..\..\..

#//------------------------------------------------------------------------
#//
#// Define any Public Make Variables here: (ie. PDFFILE, MAPFILE, ...)
#//
#//------------------------------------------------------------------------

USE_STATIC_LIBS=1

!ifndef MAKE_OBJ_TYPE
MAKE_OBJ_TYPE=DLL
!endif

#//------------------------------------------------------------------------
#// 
#// Define the files necessary to build the target (ie. OBJS)
#//
#//------------------------------------------------------------------------

OBJS=                                       \
    .\$(OBJDIR)\reg.obj                     \
    .\$(OBJDIR)\VerReg.obj                  \
    .\$(OBJDIR)\vr_stubs.obj                \
    $(NULL)

#//------------------------------------------------------------------------
#//
#// Define any Public Targets here (ie. PROGRAM, LIBRARY, DLL, ...)
#// (these must be defined before the common makefiles are included)
#//
#//------------------------------------------------------------------------


LIBNAME=nsreg
DLL=$(OBJDIR)\$(LIBNAME).dll
LIBRARY=$(OBJDIR)\$(LIBNAME)_s.lib

#//------------------------------------------------------------------------
#//
#// Define any local options for the make tools 
#//     (ie. LCFLAGS, LLFLAGS, LLIBS, LINCS)
#//
#//------------------------------------------------------------------------

LCFLAGS = $(LCFLAGS) -DSTANDALONE_REGISTRY

LINCS= $(LINCS) -I$(PUBLIC)/libreg   \
       $(NULL)

#//------------------------------------------------------------------------
#//
#// Include the common makefile rules
#//
#//------------------------------------------------------------------------
include <$(DEPTH)/config/rules.mak>

docopy:
    $(MAKE_INSTALL) ..\src\*.h .
    $(MAKE_INSTALL) ..\src\*.c .


export:: docopy $(DLL) $(LIBRARY)
    
    $(MAKE_INSTALL) $(DLL)                    $(DIST)\bin
    $(MAKE_INSTALL) $(LIBRARY)                $(DIST)\lib
    $(MAKE_INSTALL) $(OBJDIR)\$(LIBNAME).lib  $(DIST)\lib
     

clobber_all::
    
    $(RM) $(DIST)\bin\$(LIBNAME).dll
    $(RM) $(DIST)\lib\$(LIBNAME).lib
    $(RM) $(DIST)\lib\$(LIBNAME)_s.lib
    $(RM) *.[hc]

clobber::
    $(RM) *.[hc]