/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsITaskbarProgress.idl"

interface mozIDOMWindowProxy;

/**
 * Allow the TaskbarProgress instance to set a new target window.
 */

[scriptable, uuid(39f6fc5a-2386-4bc6-941c-d7479253bc3f)]
interface nsIGtkTaskbarProgress : nsITaskbarProgress
{
  /**
   * Sets the window that is considered primary for purposes of
   * setting the XApp progress property.
   */

  void setPrimaryWindow(in mozIDOMWindowProxy aWindow);
};
