/* -*- Mode: idl; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is Oracle Corporation code.
 *
 * The Initial Developer of the Original Code is
 *  Oracle Corporation
 * Portions created by the Initial Developer are Copyright (C) 2004
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *   Mike Shaver <shaver@off.net>
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */

#include "nsISupports.idl"

interface calIItemBase;
interface calIDateTime;

interface calIIcalProperty;

[scriptable,uuid(4d7e456b-cfd0-4ebf-8794-c57789dafdc3)]
interface calIIcalComponent : nsISupports
{
    calIIcalComponent getFirstSubcomponent(in PRUint32 componentType);
    calIIcalComponent getNextSubcomponent(in PRUint32 componentType);

    const PRUint32 ANY_COMPONENT = 1;
    const PRUint32 XROOT_COMPONENT = 2;
    const PRUint32 VEVENT_COMPONENT = 4;
    const PRUint32 VTODO_COMPONENT = 5;
    const PRUint32 VJOURNAL_COMPONENT = 6;
    const PRUint32 VCALENDAR_COMPONENT = 7;
    const PRUint32 VFREEBUSY_COMPONENT = 8;
    readonly attribute PRUint32 isA;

    attribute AUTF8String uid;
    attribute AUTF8String prodid;
    attribute AUTF8String version;

    const PRUint32 METHOD_PUBLISH = 10012;
    const PRUint32 METHOD_REQUEST = 10013;
    const PRUint32 METHOD_REPLY = 10014;
    const PRUint32 METHOD_ADD = 10015;
    const PRUint32 METHOD_CANCEL = 10016;
    const PRUint32 METHOD_REFRESH = 10017;
    const PRUint32 METHOD_COUNTER = 10018;
    const PRUint32 METHOD_DECLINECOUNTER = 10019;
    const PRUint32 METHOD_CREATE = 10020;
    const PRUint32 METHOD_READ = 10021;
    const PRUint32 METHOD_RESPONSE = 10022;
    const PRUint32 METHOD_MOVE = 10023;
    const PRUint32 METHOD_MODIFY = 10024;
    const PRUint32 METHOD_GENERATEUID = 10025;
    const PRUint32 METHOD_DELETE = 10026;
    const PRUint32 METHOD_NONE = 10027;
    attribute PRUint32 method;

    const PRUint32 STATUS_TENTATIVE = 10029;
    const PRUint32 STATUS_CONFIRMED = 10030;
    const PRUint32 STATUS_COMPLETED = 10031;
    const PRUint32 STATUS_NEEDSACTION = 10032;
    const PRUint32 STATUS_CANCELLED = 10033;
    const PRUint32 STATUS_INPROCESS = 10034;
    const PRUint32 STATUS_DRAFT = 10035;
    const PRUint32 STATUS_FINAL = 10036;
    const PRUint32 STATUS_NONE = 10037;
    attribute PRUint32 status;

    const PRUint32 TRANSP_OPAQUE = 10039;
    const PRUint32 TRANSP_TRANSPARENT = 10040;
    attribute PRUint32 transp;

    attribute AUTF8String summary;
    attribute AUTF8String description;
    attribute AUTF8String location;
    attribute AUTF8String categories;
    attribute AUTF8String URL;

    attribute PRUint32 priority;

    const PRUint32 VISIBILITY_PUBLIC = 10007;
    const PRUint32 VISIBILITY_PRIVATE = 10008;
    const PRUint32 VISIBILITY_CONFIDENTIAL = 10009;
    const PRUint32 VISIBILITY_NONE = 10010;
    attribute PRUint32 icalClass;

    attribute calIDateTime startTime;
    attribute calIDateTime endTime;
    attribute calIDateTime dueTime;
    attribute calIDateTime stampTime;

    attribute calIDateTime createdTime;
    attribute calIDateTime completedTime;
    attribute calIDateTime lastModified;

    void getAttendees(out PRUint32 count,
                      [array,size_is(count),retval] out string attendees);
    void setAttendees(in PRUint32 count,
                      [array,size_is(count)] in string attendees);

    AUTF8String serializeToICS();

    void addSubcomponent(in calIIcalComponent comp);
    void removeSubcomponent(in calIIcalComponent comp);

    const PRUint32 ANY_PROPERTY = 0;
    const PRUint32 ACTION_PROPERTY = 1;
    const PRUint32 ATTACH_PROPERTY = 2;
    const PRUint32 ATTENDEE_PROPERTY = 3;
    calIIcalProperty getFirstProperty(in PRUint32 kind);
    calIIcalProperty getNextProperty(in PRUint32 kind);
    calIIcalProperty addProperty(in PRUint32 kind);
    void removeProperty(in calIIcalProperty prop);

    calIIcalProperty getFirstXProperty(in AUTF8String xpropname);
    calIIcalProperty getNextXProperty(in AUTF8String xpropname);
    calIIcalProperty addXProperty(in AUTF8String xpropname,
                                  in AUTF8String xpropval);
};

[scriptable,uuid(17349a10-5d80-47fa-9bea-f22957357675)]
interface calIIcalProperty : nsISupports
{
    attribute AUTF8String stringValue;
    readonly attribute PRUint32 isA;

    AUTF8String getXParameter(in AUTF8String xparamname);
    void setXParameter(in AUTF8String xparamname, in AUTF8String xparamval);
    void removeXParameter(in AUTF8String xparamname);

    const PRUint32 ALTREP_PARAMETER = 1;
    const PRUint32 CN_PARAMETER = 2;
    const PRUint32 CUTYPE_PARAMETER = 3;
    const PRUint32 DELEGATEDFROM_PARAMETER = 4;
    const PRUint32 DELEGATEDTO_PARAMETER = 5;
    const PRUint32 DIR_PARAMETER = 6;
    const PRUint32 ENCODING_PARAMETER = 7;
    const PRUint32 FBTYPE_PARAMETER = 8;
    const PRUint32 FMTTYPE_PARAMETER = 9;
    const PRUint32 LANGUAGE_PARAMETER = 10;
    const PRUint32 MEMBER_PARAMETER = 11;
    const PRUint32 PARTSTAT_PARAMETER = 12;
    const PRUint32 RANGE_PARAMETER = 13;
    const PRUint32 RELATED_PARAMETER = 14;
    const PRUint32 RELTYPE_PARAMETER = 15;
    const PRUint32 ROLE_PARAMETER = 16;
    const PRUint32 RSVP_PARAMETER = 17;
    const PRUint32 SENTBY_PARAMETER = 18;
    const PRUint32 TZID_PARAMETER = 19;
    const PRUint32 VALUE_PARAMETER = 20;
    /* const PRUint32 X_PARAMETER = 21; */
    const PRUint32 XLICCOMPARETYPE_PARAMETER = 22;
    const PRUint32 XLICERRORTYPE_PARAMETER = 23;

    AUTF8String getParameter(in PRUint32 kind);
    void setParameter(in PRUint32 kind, in AUTF8String value);
    void removeParameter(in PRUint32 kind);
};

[scriptable,uuid(c788a1dc-0929-4029-9a14-e1bc654eafad)]
interface calIICSService : nsISupports
{
    calIIcalComponent parseICS(in AUTF8String serialized);
    calIIcalComponent createIcalComponent(in PRUint32 kind);
};
