/* -*- Mode: idl; tab-width: 20; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is Simdesk Technologies code.
 *
 * The Initial Developer of the Original Code is Simdesk Technologies Inc.
 * Portions created by the Initial Developer are Copyright (C) 2007
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *   Clint Talbert <ctalbert.moz@gmail.com>
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */

#include "nsISupports.idl"

interface calIItipItem;
interface calIAttendee;
interface calIDateTime;

/**
 * calIItipTransport is a generic transport interface that is implemented
 * by transports (eg: email, XMPP, etc.) wishing to send calIItipItems
 */
[scriptable, uuid(d9e439da-1014-42f9-be40-aa7e878b8a7d)]
interface calIItipTransport : nsISupports
{
    /**
     * Default identity for me within this transport. For example, this is
     * your default email address in Thunderbird.
     */
    readonly attribute AUTF8String defaultIdentity;

    /**
     * Sending identity. This can be set to change the "sender" identity from
     * defaultIdentity above.
     */
    attribute AUTF8String senderAddress;

    /**
     * Type of the transport: email, xmpp, etc.
     */
    readonly attribute AUTF8String type;

    /**
     * Pass the transport an itipItem and have it figure out what to do with
     * it based on the itipItem's methods.
     */
    void simpleSendResponse(in calIItipItem item);

    /**
     * Sends a calIItipItem to the recipients using the specified title and
     * alternative representation. If a calIItipItem is attached, then an ICS
     * representation of those objects are generated and attached to the email.
     * If the calIItipItem is null, then the item(s) is sent without any
     * text/calendar mime part.
     * @param count             size of recipient array
     * @param recipientArray    array of recipients
     * @param title             title of the exchange
     * @param altrep            an alternative representation (usually text)
                                in case the recipient cannot handle the
                                text/calendar mime-type
     * @param calIItipItem      set of calIItems encapsulated as calIItipItems
     */
    void sendItems(in PRUint32 count,
                   [array, size_is(count)] in calIAttendee recipientArray,
                   in AUTF8String title,
                   in AUTF8String altrep,
                   in calIItipItem item);

    /**
     * Checks the configured transport for any incoming messages with
     * text/calendar mime parts (invitations) that are more recent than the
     * specified date.  It returns a calIItipItem object containing the found
     * items
     * @param  searchStart   Defines on what date to start the search.
     * @return calIItipItem  The items it finds in a calIItipItem object.
     */
    calIItipItem checkForInvitations(in calIDateTime searchStart);
};
