#!gmake
#
# The contents of this file are subject to the Netscape Public License
# Version 1.0 (the "NPL"); you may not use this file except in
# compliance with the NPL.  You may obtain a copy of the NPL at
# http://www.mozilla.org/NPL/
#
# Software distributed under the NPL is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the NPL
# for the specific language governing rights and limitations under the
# NPL.
#
# The Initial Developer of this code under the NPL is Netscape
# Communications Corporation.  Portions created by Netscape are
# Copyright (C) 1998 Netscape Communications Corporation.  All Rights
# Reserved.


DEPTH	= ..\..\..
MODULE=rdfcat

MAKE_OBJ_TYPE=EXE

EXENAME=rdfcat
PDBFILE=rdfcat
MAPFILE=rdfcat.map

PROGRAM=        .\$(OBJDIR)\$(EXENAME).exe

OBJS=           .\$(OBJDIR)\rdfcat.obj

LINCS=          -I$(PUBLIC)\rdf         \
                -I$(PUBLIC)\dom         \
                -I$(LIBNSPR)            \
                -I$(PUBLIC)\xpcom       \
                -I$(PUBLIC)\netlib      \
                -I$(PUBLIC)\raptor      \
                $(NULL)

LLIBS=				\
 $(DIST)\lib\rdf.lib            \
 $(DIST)\lib\xpcom32.lib	\
 $(DIST)\lib\raptorbase.lib     \
 $(DIST)\lib\netlib.lib         \
 $(DIST)\lib\plc3.lib       \
 $(LIBNSPR)  

include <$(DEPTH)\config\rules.mak>

install:: $(PROGRAM)
	$(MAKE_INSTALL) $(PROGRAM) $(DIST)\bin


