
    interface CSSStyleDeclaration {
 /* IID: { 0xa6cf90be, 0x15b3, 0x11d2, \
  { 0x93, 0x2e, 0x00, 0x80, 0x5f, 0x8a, 0xdd, 0x32 } } */

      wstring getPropertyValue(in wstring propertyName);
      wstring getPropertyPriority(in wstring propertyName);
      void setProperty(in wstring propertyName, in wstring value, in wstring priority);
      readonly attribute unsigned long length;
      wstring item(in unsigned long index); /* Returns property name */

      attribute wstring azimuth;
      attribute wstring background;
      attribute wstring backgroundAttachment;
      attribute wstring backgroundColor;
      attribute wstring backgroundImage; 
      attribute wstring backgroundPosition; 
      attribute wstring backgroundRepeat; 
      attribute wstring border; 
      attribute wstring borderCollapse; 
      attribute wstring borderColor; 
      attribute wstring borderSpacing; 
      attribute wstring borderStyle; 
      attribute wstring borderTop; 
      attribute wstring borderRight; 
      attribute wstring borderBottom; 
      attribute wstring borderLeft; 
      attribute wstring borderTopColor;
      attribute wstring borderRightColor;
      attribute wstring borderBottomColor;
      attribute wstring borderLeftColor; 
      attribute wstring borderTopStyle;
      attribute wstring borderRightStyle;
      attribute wstring borderBottomStyle;
      attribute wstring borderLeftStyle; 
      attribute wstring borderTopWidth;
      attribute wstring borderRightWidth;
      attribute wstring borderBottomWidth;
      attribute wstring borderLeftWidth; 
      attribute wstring borderWidth; 
      attribute wstring bottom; 
      attribute wstring captionSide; 
      attribute wstring clear; 
      attribute wstring clip; 
      attribute wstring color; 
      attribute wstring content; 
      attribute wstring counterIncrement; 
      attribute wstring counterReset; 
      attribute wstring cue; 
      attribute wstring cueAfter; 
      attribute wstring cueBefore; 
      attribute wstring cursor; 
      attribute wstring direction; 
      attribute wstring display; 
      attribute wstring elevation; 
      attribute wstring emptyCells; 
      attribute wstring styleFloat; 
      attribute wstring font; 
      attribute wstring fontFamily; 
      attribute wstring fontSize; 
      attribute wstring fontSizeAdjust; 
      attribute wstring fontStretch; 
      attribute wstring fontStyle; 
      attribute wstring fontVariant; 
      attribute wstring fontWeight; 
      attribute wstring height; 
      attribute wstring left; 
      attribute wstring letterSpacing; 
      attribute wstring lineHeight; 
      attribute wstring listStyle; 
      attribute wstring listStyleImage; 
      attribute wstring listStylePosition; 
      attribute wstring listStyleType; 
      attribute wstring margin; 
      attribute wstring marginTop;
      attribute wstring marginRight;
      attribute wstring marginBottom;
      attribute wstring marginLeft; 
      attribute wstring markerOffset; 
      attribute wstring marks; 
      attribute wstring maxHeight; 
      attribute wstring maxWidth; 
      attribute wstring minHeight; 
      attribute wstring minWidth; 
      attribute wstring orphans; 
      attribute wstring outline; 
      attribute wstring outlineColor; 
      attribute wstring outlineStyle; 
      attribute wstring outlineWidth; 
      attribute wstring overflow; 
      attribute wstring padding; 
      attribute wstring paddingTop;
      attribute wstring paddingRight;
      attribute wstring paddingBottom;
      attribute wstring paddingLeft; 
      attribute wstring page; 
      attribute wstring pageBreakAfter; 
      attribute wstring pageBreakBefore; 
      attribute wstring pageBreakInside; 
      attribute wstring pause; 
      attribute wstring pauseAfter; 
      attribute wstring pauseBefore; 
      attribute wstring pitch; 
      attribute wstring pitchRange; 
      attribute wstring playDuring; 
      attribute wstring position; 
      attribute wstring quotes; 
      attribute wstring richness; 
      attribute wstring right; 
      attribute wstring size; 
      attribute wstring speak; 
      attribute wstring speakHeader; 
      attribute wstring speakNumeral; 
      attribute wstring speakPunctuation; 
      attribute wstring speechRate; 
      attribute wstring stress; 
      attribute wstring tableLayout; 
      attribute wstring textAlign; 
      attribute wstring textDecoration; 
      attribute wstring textIndent; 
      attribute wstring textShadow; 
      attribute wstring textTransform; 
      attribute wstring top; 
      attribute wstring unicodeBidi; 
      attribute wstring verticalAlign; 
      attribute wstring visibility; 
      attribute wstring voiceFamily; 
      attribute wstring volume; 
      attribute wstring whiteSpace; 
      attribute wstring widows; 
      attribute wstring width; 
      attribute wstring wordSpacing; 
      attribute wstring zIndex;       
    };




