pref("general.useragent.extra.minimo", "Minimo/0.007");

pref("browser.startup.homepage",            "http://www.google.com");

pref("browser.active_color",                "#EE0000");
pref("browser.anchor_color",                "#0000EE");
pref("browser.blink_allowed",               true);
pref("browser.block.target_new_window",     false);
pref("browser.cache.check_doc_frequency",   3);
pref("browser.cache.memory.capacity",       256);
pref("browser.cache.memory.enable",         true);
pref("browser.display.background_color",    "#FFFFFF");
pref("browser.display.focus_background_color", "#117722");
pref("browser.display.focus_ring_on_anything", false);
pref("browser.display.focus_ring_width",     1);
pref("browser.display.focus_text_color",     "#ffffff");
pref("browser.display.force_inline_alttext", false);
pref("browser.display.foreground_color",    "#000000");
pref("browser.display.normal_lineheight_calc_control", 2);
pref("browser.display.show_image_placeholders", true);
pref("browser.display.use_document_colors", true);
pref("browser.display.use_document_fonts",  1); 
pref("browser.display.use_focus_colors",    false);
pref("browser.display.use_system_colors",   false);
pref("browser.enable_automatic_image_resizing", false);
pref("browser.fixup.alternate.enabled", true);
pref("browser.fixup.alternate.prefix", "www.");
pref("browser.fixup.alternate.suffix", ".com");
pref("browser.fixup.hide_user_pass", true);
pref("browser.forms.submit.backwards_compatible", true);
pref("browser.frames.enabled", true);

pref("browser.sessionhistory.max_entries", 4);

pref("browser.throbber.url","chrome://navigator-region/locale/region.properties");
pref("browser.underline_anchors",           true);
pref("browser.visited_color",               "#551A8B");
pref("clipboard.autocopy", false);

pref("dom.allow_scripts_to_close_windows",          false);
pref("dom.disable_image_src_set",           false);
pref("dom.disable_open_during_load",              false);
pref("dom.disable_window_flip",             false);
pref("dom.disable_window_move_resize",      false);
pref("dom.disable_window_open_feature.close",       false);
pref("dom.disable_window_open_feature.directories", false);
pref("dom.disable_window_open_feature.location",    false);
pref("dom.disable_window_open_feature.menubar",     false);
pref("dom.disable_window_open_feature.minimizable", false);
pref("dom.disable_window_open_feature.personalbar", false);
pref("dom.disable_window_open_feature.resizable",   false);
pref("dom.disable_window_open_feature.scrollbars",  false);
pref("dom.disable_window_open_feature.status",      false);
pref("dom.disable_window_open_feature.titlebar",    false);
pref("dom.disable_window_open_feature.toolbar",     false);
pref("dom.disable_window_status_change",    false);

pref("image.animation_mode",                "normal");
pref("images.dither", "auto");
pref("intl.accept_charsets",                "iso-8859-1,*,utf-8");
pref("intl.accept_languages",               "chrome://navigator/locale/navigator.properties");
pref("intl.accept_languages",               "chrome://navigator/locale/navigator.properties");
pref("intl.charset.default",                "chrome://navigator-platform/locale/navigator.properties");
pref("intl.charset.detector",               "chrome://navigator/locale/navigator.properties");
pref("intl.collationOption",                "chrome://navigator-platform/locale/navigator.properties");
pref("intl.content.langcode",               "chrome://communicator-region/locale/region.properties");
pref("intl.fallbackCharsetList.ISO-8859-1", "windows-1252");
pref("intl.locale.matchOS",                 false);
pref("intl.menuitems.alwaysappendaccesskeys","chrome://navigator/locale/navigator.properties");
pref("intl.menuitems.insertseparatorbeforeaccesskeys","chrome://navigator/locale/navigator.properties");
pref("javascript.enabled",                  true);
pref("javascript.options.showInConsole",    true);
pref("javascript.options.strict",           false);
pref("keyword.enabled", true);
pref("layout.frames.force_resizability", false);
pref("layout.word_select.eat_space_to_next_word", false);
pref("layout.word_select.stop_at_punctuation", true);
pref("network.cookie.cookieBehavior",       0);
pref("network.cookie.disableCookieForMailNews", true);
pref("network.cookie.lifetime.behavior",    0);
pref("network.cookie.lifetime.days",        90);
pref("network.cookie.lifetime.enabled",     false);
pref("network.cookie.warnAboutCookies",     false);
pref("network.enableIDN", false);
pref("network.http.accept-encoding" ,"gzip,deflate");
pref("network.http.accept.default", "text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,image/jpeg,image/gif;q=0.2,*/*;q=0.1");
pref("network.http.default-socket-type", "");
pref("network.http.keep-alive", false);
pref("network.http.keep-alive.timeout", 300);
pref("network.http.max-connections", 2);
pref("network.http.max-connections-per-server", 2);
pref("network.http.max-persistent-connections-per-proxy", 2);
pref("network.http.max-persistent-connections-per-server", 2);
pref("network.http.pipelining"      , false);
pref("network.http.pipelining.firstrequest", false);
pref("network.http.pipelining.maxrequests" , 4);
pref("network.http.proxy.keep-alive", true);
pref("network.http.proxy.pipelining", false);
pref("network.http.proxy.version", "1.1");
pref("network.http.redirection-limit", 20);
pref("network.http.request.max-start-delay", 10);
pref("network.http.sendRefererHeader",      2); 
pref("network.http.sendSecureXSiteReferrer", true);
pref("network.http.use-cache", false);
pref("network.http.version", "1.1");
pref("network.image.imageBehavior",         0);
pref("network.image.warnAboutImages",       false);
pref("network.online",                      true);
pref("network.prefetch-next", false);
pref("network.protocol-handler.expose-all", true);
pref("network.protocol-handler.external-default", true);
pref("network.protocol-handler.external.data", false);
pref("network.protocol-handler.external.disk", false);
pref("network.protocol-handler.external.hcp", false);
pref("network.protocol-handler.external.help", false);
pref("network.protocol-handler.external.javascript", false);
pref("network.protocol-handler.external.ms-help", false);
pref("network.protocol-handler.external.vbscript", false);
pref("network.protocol-handler.external.vnd.ms.radio", false);
pref("network.protocol-handler.warn-external-default", true);
pref("network.proxy.autoconfig_url",        "");
pref("network.proxy.ftp",                   "");
pref("network.proxy.ftp_port",              0);
pref("network.proxy.gopher",                "");
pref("network.proxy.gopher_port",           0);
pref("network.proxy.http",                  "");
pref("network.proxy.http_port",             0);
pref("network.proxy.no_proxies_on",         "localhost, 127.0.0.1");
pref("network.proxy.socks",                 "");
pref("network.proxy.socks_port",            0);
pref("network.proxy.socks_version",         5);
pref("network.proxy.ssl",                   "");
pref("network.proxy.ssl_port",              0);
pref("network.proxy.type",                  0);
pref("network.standard-url.escape-utf8", true);
pref("nglayout.debug.enable_xbl_forms", false);
pref("nglayout.events.dispatchLeftClickOnly", true);
pref("prefs.converted-to-utf8",false);
pref("security.checkloaduri", true);
pref("security.enable_java",                false);
pref("security.xpconnect.plugin.unrestricted", true);
pref("signed.applets.codebase_principal_support", false);
pref("slider.snapMultiplier", 0);
pref("ui.key.accelKey", 17);
pref("ui.key.generalAccessKey", 18);
pref("ui.key.menuAccessKey", 18);
pref("ui.key.menuAccessKeyFocuses", false);
pref("ui.key.saveLink.shift", true); 
pref("viewmanager.do_doublebuffering", true);

pref("security.warn_entering_secure", false);
pref("security.warn_entering_weak", false);
pref("security.warn_leaving_secure", false);
pref("security.warn_submit_insecure", false);

pref("network.autodial-helper.enabled", true);

pref("config.wince.useOKBtn", true);

