#include "nsISupports.idl"
#include "nsIEventFilter.idl"

/**
 * The nsIWinEventFilter defines what a message filter looks like on the Windows 
 * Platform.    
 */						  

[scriptable, uuid(2EFB5006-4508-11d3-AEDA-00A024FFC08C)]
interface nsIWinEventFilter : nsIEventFilter
{
	[noscript] attribute voidStar hwnd;
	attribute unsigned long MsgFilterMin;
	attribute unsigned long MsgFilterMax;
	attribute unsigned long RemoveFlags;
};
