/* -*- Mode: IDL; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
 *
 * The contents of this file are subject to the Netscape Public
 * License Version 1.1 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of
 * the License at http://www.mozilla.org/NPL/
 *
 * Software distributed under the License is distributed on an "AS
 * IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
 * implied. See the License for the specific language governing
 * rights and limitations under the License.
 *
 * The Original Code is mozilla.org code.
 *
 * The Initial Developer of the Original Code is Netscape
 * Communications Corporation.  Portions created by Netscape are
 * Copyright (C) 1998 Netscape Communications Corporation. All
 * Rights Reserved.
 *
 * Contributor(s): 
 */

#include "nsISupports.idl"
#include "MailNewsTypes2.idl"

%{ C++
#include "nsINNTPNewsgroupPost.h"
#include "nsIMsgMailNewsUrl.h"

#define NEWS_PORT 119
#define SECURE_NEWS_PORT 563
%}

interface nsIMsgDBHdr;
interface nsINNTPNewsgroupPost;

typedef long nsNewsAction;

[scriptable, uuid(BDD12930-A682-11d2-804C-006008128C4E)]
interface nsINntpUrl : nsISupports {
  attribute nsINNTPNewsgroupPost messageToPost;
  readonly attribute nsIMsgDBHdr messageHeader;
  attribute nsNewsAction newsAction;
  attribute boolean getOldMessages;

  const nsNewsAction ActionGetNewNews = 0;
  const nsNewsAction ActionFetchArticle = 1;
  const nsNewsAction ActionSaveMessageToDisk = 2;
  const nsNewsAction ActionCancelArticle = 3;
  const nsNewsAction ActionPostArticle = 4;
  const nsNewsAction ActionSearch = 5;
  const nsNewsAction ActionUpdateCounts = 6;
  const nsNewsAction ActionListGroups = 7;
  const nsNewsAction ActionFetchPart = 8;
};
