#!nmake
#
# The contents of this file are subject to the Netscape Public
# License Version 1.1 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy of
# the License at http://www.mozilla.org/NPL/
#
# Software distributed under the License is distributed on an "AS
# IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
# implied. See the License for the specific language governing
# rights and limitations under the License.
#
# The Original Code is mozilla.org code.
#
# The Initial Developer of the Original Code is Netscape
# Communications Corporation.  Portions created by Netscape are
# Copyright (C) 1998-2000 Netscape Communications Corporation. All
# Rights Reserved.
#
# Contributor(s): 


#//------------------------------------------------------------------------
#//
#// Makefile to build 
#//
#//------------------------------------------------------------------------


#//------------------------------------------------------------------------
#//
#// Specify the depth of the current directory relative to the
#// root of MOZILLA
#//
#//------------------------------------------------------------------------
DEPTH= ..\..

#//------------------------------------------------------------------------
#//
#// Define any Public Make Variables here: (ie. PDFFILE, MAPFILE, ...)
#//
#//------------------------------------------------------------------------

MODULE=caps
LIBRARY_NAME=caps
MODULE_NAME=nsSecurityManagerModule
REQUIRES	= xpcom \
		  string \
		  pref \
		  js \
		  dom \
		  xpconnect \
		  necko \
		  jar \
		  widget \
		  plugin \
		  intl \
		  docshell \
		  windowwatcher \
		  $(NULL)

#//------------------------------------------------------------------------
#// 
#// Define the files necessary to build the target (ie. OBJS)
#//
#//------------------------------------------------------------------------

C_OBJS=                                     \
     $(NULL)

CPP_OBJS=                                    \
    .\$(OBJDIR)\nsBasePrincipal.obj          \
    .\$(OBJDIR)\nsCertificatePrincipal.obj   \
    .\$(OBJDIR)\nsCodebasePrincipal.obj      \
    .\$(OBJDIR)\nsAggregatePrincipal.obj     \
    .\$(OBJDIR)\nsJSPrincipals.obj           \
    .\$(OBJDIR)\nsScriptSecurityManager.obj  \
    .\$(OBJDIR)\nsSecurityManagerFactory.obj \
    .\$(OBJDIR)\nsSystemPrincipal.obj        \
     $(NULL)

#//------------------------------------------------------------------------
#//
#// Define any Public Targets here (ie. PROGRAM, LIBRARY, DLL, ...)
#// (these must be defined before the common makefiles are included)
#//
#//------------------------------------------------------------------------

#//------------------------------------------------------------------------
#//
#// Define any local options for the make tools 
#//     (ie. LCFLAGS, LLFLAGS, LLIBS, LINCS)
#//
#//------------------------------------------------------------------------

LLIBS = \
	$(LIBNSPR)                    \
	$(DIST)\lib\xpcom.lib         \
	$(DIST)\lib\js3250.lib	      \
	$(DIST)\lib\zlib.lib          \
	$(NULL)


#//------------------------------------------------------------------------
#//
#// Include the common makefile rules
#//
#//------------------------------------------------------------------------
include <$(DEPTH)/config/rules.mak>

