/* -*- Mode: IDL; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-*/
/* ----- BEGIN LICENSE BLOCK -----
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public
 * License Version 1.1 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of
 * the License at http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS
 * IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
 * implied. See the License for the specific language governing
 * rights and limitations under the License.
 *
 * The Original Code is .
 *
 * The Initial Developer of the Original Code is  Communications Corporation..
 * Portions created by  Communications Corporation. are
 * Copyright (C) 1998  Communications Corporation.. All
 * Rights Reserved.
 *
 * Contributor(s):
 *  Scott MacGregor <mscott@netscape.com>
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either of the GNU General Public License Version 2 or later (the "GPL"),
 * or the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the LGPL or the GPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ----- END LICENSE BLOCK ----- */

#include "nsIURI.idl"

//
//  moz-icon URLs have the following syntax
// 
//  moz-icon:<file-uri>?size=16&contentType=text/html
// OR
// moz-icon://dummyfile.html
// moz-icon://dummyfile.html?size=32
// 
//  The content type field is optional. The size field is optional. You only need to specify a file url inside the icon
// if the file you want the icon for actually exists. Otherwise you can omit the file:// and just place a dummy file name with the extension
// or content type you want: moz-icon://dummy.html. 
// 

[scriptable, uuid(733A7A16-2D36-11d5-9907-001083010E9B)]
interface nsIMozIconURI : nsIURI 
{
  // Returns the file URL contained within this -moz-icon url.
  attribute nsIURI IconFile; // maybe null if there isn't a real file we are trying to fetch

  attribute unsigned long imageSize; // measured by # of pixels in a row. defaults to 16.
  attribute string contentType;      // may be an empty string
  readonly attribute string fileExtension;    
};
