/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

interface nsIArray;

[scriptable, uuid(bfdef4aa-dcd1-4d31-b5d9-188fe8d98623)]
interface nsIEdgeReadingListExtractor : nsISupports
{
  /**
   * Import data from the database indicated by the databasePath
   * May fail if the path is invalid, unreadable, the database is corrupt,
   * or the data in the database is not in the format we expect.
   *
   * @param  databasePath the absolute path to the database we'd like to import
   * @return an enumerator of nsIPropertyBag2 items that each have a URL, title, and
   *         creation dates.
   */
  nsIArray extract(in DOMString databasePath);
};
