interface RDFCore : BaseAppCore
{

/* IID: { 0xdf365f00, 0xcc53, 0x11d2, \
  { 0x8f, 0xdf, 0x0, 0x08, 0xc7, 0x0a, 0xdc, 0x7b } } */

        void RDFCore();

        void            doSort(in Node node, in DOMString sortResource, in DOMString sortDirection);
        void            addBookmark(in DOMString url, in DOMString optionalTitle);
        DOMString       findBookmarkShortcut(in DOMString userInput);
  };
