/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*-
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

/**
 * Defines cross platform (Gecko) roles.
 */
[scriptable, builtinclass, uuid(05a9f33f-dcfd-4e7b-b825-138ba784c1f5)]
interface nsIAccessibleRole : nsISupports
{
  /**
   * Used when accessible hans't strong defined role.
   */
  const unsigned long ROLE_NOTHING = 0;

  /**
   * Represents a title or caption bar for a window. It is used by MSAA only,
   * supported automatically by MS Windows.
   */
  const unsigned long ROLE_TITLEBAR = 1;

  /**
   * Represents the menu bar (positioned beneath the title bar of a window)
   * from which menus are selected by the user. The role is used by
   * xul:menubar or role="menubar".
   */
  const unsigned long ROLE_MENUBAR = 2;

  /**
   * Represents a vertical or horizontal scroll bar, which is part of the client
   * area or used in a control.
   */
  const unsigned long ROLE_SCROLLBAR = 3;

  /**
   * Represents a special mouse pointer, which allows a user to manipulate user
   * interface elements such as windows. For example, a user clicks and drags
   * a sizing grip in the lower-right corner of a window to resize it.
   */
  const unsigned long ROLE_GRIP = 4;

  /**
   * Represents a system sound, which is associated with various system events.
   */
  const unsigned long ROLE_SOUND = 5;

  /**
   * Represents the system mouse pointer.
   */
  const unsigned long ROLE_CURSOR = 6;

  /**
   * Represents the system caret. The role is supported for caret.
   */
  const unsigned long ROLE_CARET = 7;

  /**
   * Represents an alert or a condition that a user should be notified about.
   * Assistive Technologies typically respond to the role by reading the entire
   * onscreen contents of containers advertising this role. Should be used for
   * warning dialogs, etc. The role is used by xul:browsermessage,
   * role="alert".
   */
  const unsigned long ROLE_ALERT = 8;

  /**
   * Represents the window frame, which contains child objects such as
   * a title bar, client, and other objects contained in a window. The role
   * is supported automatically by MS Windows.
   */
  const unsigned long ROLE_WINDOW = 9;

  /**
   * A sub-document (<frame> or <iframe>)
   */
  const unsigned long ROLE_INTERNAL_FRAME = 10;

  /**
   * Represents a menu, which presents a list of options from which the user can
   * make a selection to perform an action. It is used for role="menu".
   */
  const unsigned long ROLE_MENUPOPUP = 11;

  /**
   * Represents a menu item, which is an entry in a menu that a user can choose
   * to carry out a command, select an option. It is used for xul:menuitem,
   * role="menuitem".
   */
  const unsigned long ROLE_MENUITEM = 12;

  /**
   * Represents a ToolTip that provides helpful hints.
   */
  const unsigned long ROLE_TOOLTIP = 13;

  /**
   * Represents a main window for an application. It is used for
   * role="application". Also refer to ROLE_APP_ROOT
   */
  const unsigned long ROLE_APPLICATION = 14;

  /**
   * Represents a document window. A document window is always contained within
   * an application window. For role="document", see NON_NATIVE_DOCUMENT.
   */
  const unsigned long ROLE_DOCUMENT = 15;

  /**
   * Represents a pane within a frame or document window. Users can navigate
   * between panes and within the contents of the current pane, but cannot
   * navigate between items in different panes. Thus, panes represent a level
   * of grouping lower than frame windows or documents, but above individual
   * controls. It is used for the first child of a <frame> or <iframe>.
   */
  const unsigned long ROLE_PANE = 16;

  /**
   * Represents a graphical image used to represent data.
   */
  const unsigned long ROLE_CHART = 17;

  /**
   * Represents a dialog box or message box. It is used for xul:dialog, 
   * role="dialog".
   */
  const unsigned long ROLE_DIALOG = 18;

  /**
   * Represents a window border.
   */
  const unsigned long ROLE_BORDER = 19;

  /**
   * Logically groups other objects. There is not always a parent-child
   * relationship between the grouping object and the objects it contains. It
   * is used for html:textfield, xul:groupbox, role="group".
   */
  const unsigned long ROLE_GROUPING = 20;

  /**
   * Used to visually divide a space into two regions, such as a separator menu
   * item or a bar that divides split panes within a window. It is used for
   * xul:separator, html:hr, role="separator".
   */
  const unsigned long ROLE_SEPARATOR = 21;

  /**
   * Represents a toolbar, which is a grouping of controls (push buttons or
   * toggle buttons) that provides easy access to frequently used features. It
   * is used for xul:toolbar, role="toolbar".
   */
  const unsigned long ROLE_TOOLBAR = 22;

  /**
   * Represents a status bar, which is an area at the bottom of a window that
   * displays information about the current operation, state of the application,
   * or selected object. The status bar has multiple fields, which display
   * different kinds of information. It is used for xul:statusbar.
   */
  const unsigned long ROLE_STATUSBAR = 23;

  /**
   * Represents a table that contains rows and columns of cells, and optionally,
   * row headers and column headers. It is used for html:table,
   * role="grid". Also refer to the following roles: ROLE_COLUMNHEADER,
   * ROLE_ROWHEADER, ROLE_COLUMN, ROLE_ROW, ROLE_CELL.
   */
  const unsigned long ROLE_TABLE = 24;

  /**
   * Represents a column header, providing a visual label for a column in
   * a table. It is used for XUL tree column headers, html:th,
   * role="colheader". Also refer to ROLE_TABLE.
   */
  const unsigned long ROLE_COLUMNHEADER = 25;

  /**
   * Represents a row header, which provides a visual label for a table row.
   * It is used for role="rowheader". Also, see ROLE_TABLE.
   */
  const unsigned long ROLE_ROWHEADER = 26;

  /**
   * Represents a column of cells within a table. Also, see ROLE_TABLE.
   */
  const unsigned long ROLE_COLUMN = 27;

  /**
   * Represents a row of cells within a table. Also, see ROLE_TABLE.
   */
  const unsigned long ROLE_ROW = 28;

  /**
   * Represents a cell within a table. It is used for html:td,
   * xul:tree cell and xul:listcell. Also, see ROLE_TABLE.
   */
  const unsigned long ROLE_CELL = 29;

  /**
   * Represents a link to something else. This object might look like text or
   * a graphic, but it acts like a button. It is used for
   * xul:label@class="text-link", html:a, html:area.
   */
  const unsigned long ROLE_LINK = 30;

  /**
   * Displays a Help topic in the form of a ToolTip or Help balloon.
   */
  const unsigned long ROLE_HELPBALLOON = 31;

  /**
   * Represents a cartoon-like graphic object, such as Microsoft Office
   * Assistant, which is displayed to provide help to users of an application.
   */
  const unsigned long ROLE_CHARACTER = 32;

  /**
   * Represents a list box, allowing the user to select one or more items. It
   * is used for xul:listbox, html:select@size, role="list". See also
   * ROLE_LIST_ITEM.
   */
  const unsigned long ROLE_LIST = 33;

  /**
   * Represents an item in a list. See also ROLE_LIST.
   */
  const unsigned long ROLE_LISTITEM = 34;

  /**
   * Represents an outline or tree structure, such as a tree view control,
   * that displays a hierarchical list and allows the user to expand and
   * collapse branches. Is is used for role="tree".
   */
  const unsigned long ROLE_OUTLINE = 35;

  /**
   * Represents an item in an outline or tree structure. It is used for
   * role="treeitem".
   */
  const unsigned long ROLE_OUTLINEITEM = 36;

  /**
   * Represents a page tab, it is a child of a page tab list. It is used for
   * xul:tab, role="treeitem". Also refer to ROLE_PAGETABLIST.
   */
  const unsigned long ROLE_PAGETAB = 37;

  /**
   * Represents a property sheet. It is used for xul:tabpanel,
   * role="tabpanel".
   */
  const unsigned long ROLE_PROPERTYPAGE = 38;

  /**
   * Represents an indicator, such as a pointer graphic, that points to the
   * current item.
   */
  const unsigned long ROLE_INDICATOR = 39;

  /**
   * Represents a picture. Is is used for xul:image, html:img.
   */
  const unsigned long ROLE_GRAPHIC = 40;

  /**
   * Represents read-only text, such as labels for other controls or
   * instructions in a dialog box. Static text cannot be modified or selected.
   * Is is used for xul:label, xul:description, html:label, role="label".
   */
  const unsigned long ROLE_STATICTEXT = 41;

  /**
   * Represents selectable text that allows edits or is designated read-only.
   */
  const unsigned long ROLE_TEXT_LEAF = 42;

  /**
   * Represents a push button control. It is used for xul:button, html:button,
   * role="button".
   */
  const unsigned long ROLE_PUSHBUTTON = 43;

  /**
   * Represents a check box control. It is used for xul:checkbox,
   * html:input@type="checkbox", role="checkbox".
   */
  const unsigned long ROLE_CHECKBUTTON = 44;

  /**
   * Represents an option button, also called a radio button. It is one of a
   * group of mutually exclusive options. All objects sharing a single parent
   * that have this attribute are assumed to be part of single mutually
   * exclusive group. It is used for xul:radio, html:input@type="radio",
   * role="radio".
   */
  const unsigned long ROLE_RADIOBUTTON = 45;

  /**
   * Represents a combo box; a popup button with an associated list box that
   * provides a set of predefined choices. It is used for html:select with a
   * size of 1 and xul:menulist. See also ROLE_EDITCOMBOBOX.
   */
  const unsigned long ROLE_COMBOBOX = 46;

  /**
   * Represents the calendar control.
   */
  const unsigned long ROLE_DROPLIST = 47;

  /**
   * Represents a progress bar, dynamically showing the user the percent
   * complete of an operation in progress. It is used for xul:progressmeter,
   * role="progressbar".
   */
  const unsigned long ROLE_PROGRESSBAR = 48;

  /**
   * Represents a dial or knob whose purpose is to allow a user to set a value.
   */
  const unsigned long ROLE_DIAL = 49;

  /**
   * Represents a hot-key field that allows the user to enter a combination or
   * sequence of keystrokes.
   */
  const unsigned long ROLE_HOTKEYFIELD = 50;

  /**
   * Represents a slider, which allows the user to adjust a setting in given
   * increments between minimum and maximum values. It is used by xul:scale,
   * role="slider".
   */
  const unsigned long ROLE_SLIDER = 51;

  /**
   * Represents a spin box, which is a control that allows the user to increment
   * or decrement the value displayed in a separate "buddy" control associated
   * with the spin box. It is used for input[type=number] spin buttons.
   */
  const unsigned long ROLE_SPINBUTTON = 52;

  /**
   * Represents a graphical image used to diagram data. It is used for svg:svg.
   */
  const unsigned long ROLE_DIAGRAM = 53;

  /**
   * Represents an animation control, which contains content that changes over
   * time, such as a control that displays a series of bitmap frames.
   */
  const unsigned long ROLE_ANIMATION = 54;

  /**
   * Represents a mathematical equation. It is used by MATHML, where there is a
   * rich DOM subtree for an equation. Use ROLE_FLAT_EQUATION for <img role="math" alt="[TeX]"/>
   */
  const unsigned long ROLE_EQUATION = 55;

  /**
   * Represents a button that drops down a list of items.
   */
  const unsigned long ROLE_BUTTONDROPDOWN = 56;

  /**
   * Represents a button that drops down a menu.
   */
  const unsigned long ROLE_BUTTONMENU = 57;

  /**
   * Represents a button that drops down a grid. It is used for xul:colorpicker.
   */
  const unsigned long ROLE_BUTTONDROPDOWNGRID = 58;

  /**
   * Represents blank space between other objects.
   */
  const unsigned long ROLE_WHITESPACE = 59;

  /**
   * Represents a container of page tab controls. Is it used for xul:tabs,
   * DHTML: role="tabs". Also refer to ROLE_PAGETAB.
   */
  const unsigned long ROLE_PAGETABLIST = 60;

  /**
   * Represents a control that displays time.
   */
  const unsigned long ROLE_CLOCK = 61;

  /**
   * Represents a button on a toolbar that has a drop-down list icon directly
   * adjacent to the button.
   */
  const unsigned long ROLE_SPLITBUTTON = 62;

  /**
   * Represents an edit control designed for an Internet Protocol (IP) address.
   * The edit control is divided into sections for the different parts of the
   * IP address.
   */
  const unsigned long ROLE_IPADDRESS = 63;

  /**
   * Represents a label control that has an accelerator.
   */
  const unsigned long ROLE_ACCEL_LABEL = 64;

  /**
   * Represents an arrow in one of the four cardinal directions.
   */
  const unsigned long ROLE_ARROW  = 65;

  /**
   * Represents a control that can be drawn into and is used to trap events.
   * It is used for html:canvas.
   */
  const unsigned long ROLE_CANVAS = 66;

  /**
   * Represents a menu item with a check box.
   */
  const unsigned long ROLE_CHECK_MENU_ITEM = 67;

  /**
   * Represents a specialized dialog that lets the user choose a color.
   */
  const unsigned long ROLE_COLOR_CHOOSER  = 68;

  /**
   * Represents control whose purpose is to allow a user to edit a date.
   */
  const unsigned long ROLE_DATE_EDITOR = 69;

  /**
   * An iconified internal frame in an ROLE_DESKTOP_PANE. Also refer to
   * ROLE_INTERNAL_FRAME.
   */
  const unsigned long ROLE_DESKTOP_ICON = 70;

  /**
   * A desktop pane. A pane that supports internal frames and iconified
   * versions of those internal frames.
   */
  const unsigned long ROLE_DESKTOP_FRAME = 71;

  /**
   * A directory pane. A pane that allows the user to navigate through
   * and select the contents of a directory. May be used by a file chooser.
   * Also refer to ROLE_FILE_CHOOSER.
   */
  const unsigned long ROLE_DIRECTORY_PANE = 72;

  /**
   * A file chooser. A specialized dialog that displays the files in the
   * directory and lets the user select a file, browse a different directory,
   * or specify a filename. May use the directory pane to show the contents of
   * a directory. Also refer to ROLE_DIRECTORY_PANE.
   */
  const unsigned long ROLE_FILE_CHOOSER = 73;

  /**
   * A font chooser. A font chooser is a component that lets the user pick
   * various attributes for fonts.
   */
  const unsigned long ROLE_FONT_CHOOSER = 74;

  /**
   * Frame role. A top level window with a title bar, border, menu bar, etc.
   * It is often used as the primary window for an application.
   */
  const unsigned long ROLE_CHROME_WINDOW = 75;

  /**
   *  A glass pane. A pane that is guaranteed to be painted on top of all
   * panes beneath it. Also refer to ROLE_ROOT_PANE.
   */
  const unsigned long ROLE_GLASS_PANE = 76;

  /**
   * A document container for HTML, whose children represent the document
   * content.
   */
  const unsigned long ROLE_HTML_CONTAINER = 77;

  /**
   * A small fixed size picture, typically used to decorate components.
   */
  const unsigned long ROLE_ICON = 78;

  /**
   * Presents an icon or short string in an interface.
   */
  const unsigned long ROLE_LABEL = 79;

  /**
   * A layered pane. A specialized pane that allows its children to be drawn
   * in layers, providing a form of stacking order. This is usually the pane
   * that holds the menu bar as  well as the pane that contains most of the
   * visual components in a window. Also refer to ROLE_GLASS_PANE and
   * ROLE_ROOT_PANE.
   */
  const unsigned long ROLE_LAYERED_PANE = 80;

  /**
   * A specialized pane whose primary use is inside a dialog.
   */
  const unsigned long ROLE_OPTION_PANE = 81;

  /**
   * A text object uses for passwords, or other places where the text content
   * is not shown visibly to the user.
   */
  const unsigned long ROLE_PASSWORD_TEXT = 82;

  /**
   * A temporary window that is usually used to offer the user a list of
   * choices, and then hides when the user selects one of those choices.
   */
  const unsigned long ROLE_POPUP_MENU = 83;

  /**
   * A radio button that is a menu item.
   */
  const unsigned long ROLE_RADIO_MENU_ITEM = 84;

  /**
   * A root pane. A specialized pane that has a glass pane and a layered pane
   * as its children. Also refer to ROLE_GLASS_PANE and ROLE_LAYERED_PANE.
   */
  const unsigned long ROLE_ROOT_PANE = 85;

  /**
   * A scroll pane. An object that allows a user to incrementally view a large
   * amount of information.  Its children can include scroll bars and a
   * viewport. Also refer to ROLE_VIEW_PORT.
   */
  const unsigned long ROLE_SCROLL_PANE = 86;

  /**
   * A split pane. A specialized panel that presents two other panels at the
   * same time. Between the two panels is a divider the user can manipulate to
   * make one panel larger and the other panel smaller.
   */
  const unsigned long ROLE_SPLIT_PANE = 87;

  /**
   * The header for a column of a table.
   * XXX: it looks this role is dupe of ROLE_COLUMNHEADER.
   */
  const unsigned long ROLE_TABLE_COLUMN_HEADER = 88;

  /**
   * The header for a row of a table.
   * XXX: it looks this role is dupe of ROLE_ROWHEADER
   */
  const unsigned long ROLE_TABLE_ROW_HEADER = 89;

  /**
   * A menu item used to tear off and reattach its menu.
   */
  const unsigned long ROLE_TEAR_OFF_MENU_ITEM = 90;

  /**
   * Represents an accessible terminal.
   */
  const unsigned long ROLE_TERMINAL = 91;

  /**
   * Collection of objects that constitute a logical text entity.
   */
  const unsigned long ROLE_TEXT_CONTAINER = 92;

  /**
   * A toggle button. A specialized push button that can be checked or
   * unchecked, but does not provide a separate indicator for the current state.
   */
  const unsigned long ROLE_TOGGLE_BUTTON = 93;

  /**
   * Representas a control that is capable of expanding and collapsing rows as
   * well as showing multiple columns of data.
   * XXX: it looks like this role is dupe of ROLE_OUTLINE.
   */
  const unsigned long ROLE_TREE_TABLE = 94;

  /**
   * A viewport. An object usually used in a scroll pane. It represents the
   * portion of the entire data that the user can see. As the user manipulates
   * the scroll bars, the contents of the viewport can change. Also refer to
   * ROLE_SCROLL_PANE.
   */
  const unsigned long ROLE_VIEWPORT = 95;

  /**
   * Header of a document page. Also refer to ROLE_FOOTER.
   */
  const unsigned long ROLE_HEADER = 96;

  /**
   * Footer of a document page. Also refer to ROLE_HEADER.
   */
  const unsigned long ROLE_FOOTER = 97;

  /**
   * A paragraph of text.
   */
  const unsigned long ROLE_PARAGRAPH = 98;

  /**
   * A ruler such as those used in word processors.
   */
  const unsigned long ROLE_RULER = 99;

  /**
   * A text entry having dialog or list containing items for insertion into
   * an entry widget, for instance a list of words for completion of a
   * text entry. It is used for xul:textbox@autocomplete
   */
  const unsigned long ROLE_AUTOCOMPLETE = 100;

  /**
   *  An editable text object in a toolbar.
   */
  const unsigned long ROLE_EDITBAR = 101;

  /**
   * An control whose textual content may be entered or modified by the user.
   */
  const unsigned long ROLE_ENTRY = 102;

  /**
   * A caption describing another object.
   */
  const unsigned long ROLE_CAPTION = 103;

  /**
   * An element containing content that assistive technology users may want to
   * browse in a reading mode, rather than a focus/interactive/application mode.
   * This role is used for role="document". For the container which holds the
   * content of a web page, see ROLE_DOCUMENT.
   */
  const unsigned long ROLE_NON_NATIVE_DOCUMENT = 104;

  /**
   * Heading.
   */
  const unsigned long ROLE_HEADING = 105;

  /**
   * An object representing a page of document content.  It is used in documents
   * which are accessed by the user on a page by page basis.
   */
  const unsigned long ROLE_PAGE = 106;

  /**
   * A container of document content.  An example of the use of this role is to
   * represent an html:div.
   */
  const unsigned long ROLE_SECTION = 107;

  /**
   * An object which is redundant with another object in the accessible
   * hierarchy. ATs typically ignore objects with this role.
   */
  const unsigned long ROLE_REDUNDANT_OBJECT = 108;

  /**
   * A container of form controls. An example of the use of this role is to
   * represent an html:form.
   */
  const unsigned long ROLE_FORM = 109;

  /**
   * An object which is used to allow input of characters not found on a
   * keyboard, such as the input of Chinese characters on a Western keyboard.
   */
  const unsigned long ROLE_IME = 110;

  /**
   * XXX: document this.
   */
  const unsigned long ROLE_APP_ROOT = 111;

  /**
   * Represents a menu item, which is an entry in a menu that a user can choose
   * to display another menu.
   */
  const unsigned long ROLE_PARENT_MENUITEM = 112;

  /**
   * A calendar that allows the user to select a date.
   */
  const unsigned long ROLE_CALENDAR = 113;

  /**
   * A list of items that is shown by combobox.
   */
  const unsigned long ROLE_COMBOBOX_LIST = 114;

  /**
   * A item of list that is shown by combobox;
   */
  const unsigned long ROLE_COMBOBOX_OPTION = 115;

  /**
   * An image map -- has child links representing the areas
   */
  const unsigned long ROLE_IMAGE_MAP = 116;
  
  /**
   * An option in a listbox
   */
  const unsigned long ROLE_OPTION = 117;
  
  /**
   * A rich option in a listbox, it can have other widgets as children
   */
  const unsigned long ROLE_RICH_OPTION = 118;
  
  /**
   * A list of options
   */
  const unsigned long ROLE_LISTBOX = 119;

  /**
   * Represents a mathematical equation in the accessible name
   */
  const unsigned long ROLE_FLAT_EQUATION = 120;
  
  /**
   * Represents a cell within a grid. It is used for role="gridcell". Unlike
   * ROLE_CELL, it allows the calculation of the accessible name from subtree.
   * Also, see ROLE_TABLE.
   */
  const unsigned long ROLE_GRID_CELL = 121;

  /**
   * Represents an embedded object. It is used for html:object or html:embed.
   */
  const unsigned long ROLE_EMBEDDED_OBJECT = 122;

  /**
   * A note. Originally intended to be hidden until activated, but now also used
   * for things like html 'aside'.
   */
  const unsigned long ROLE_NOTE = 123;

  /**
   * A figure. Used for things like HTML5 figure element.
   */
  const unsigned long ROLE_FIGURE = 124;

  /**
   * Represents a rich item with a check box.
   */
  const unsigned long ROLE_CHECK_RICH_OPTION = 125;

  /**
   * An HTML definition list <dl>
   */
  const unsigned long ROLE_DEFINITION_LIST = 126;

  /**
   * An HTML definition term <dt>
   */
  const unsigned long ROLE_TERM = 127;

  /**
   * An HTML definition <dd>
   */
  const unsigned long ROLE_DEFINITION = 128;

  /**
   * A keyboard or keypad key.
   */
  const unsigned long ROLE_KEY = 129;

  /**
   * A switch control widget.
   */
  const unsigned long ROLE_SWITCH = 130;

  /**
   * A block of MathML code (math).
   */
  const unsigned long ROLE_MATHML_MATH = 131;

  /**
   * A MathML identifier (mi in MathML).
   */
  const unsigned long ROLE_MATHML_IDENTIFIER = 132;

  /**
   * A MathML number (mn in MathML).
   */
  const unsigned long ROLE_MATHML_NUMBER = 133;

  /**
   * A MathML operator (mo in MathML).
   */
  const unsigned long ROLE_MATHML_OPERATOR = 134;

  /**
   * A MathML text (mtext in MathML).
   */
  const unsigned long ROLE_MATHML_TEXT = 135;

  /**
   * A MathML string literal (ms in MathML).
   */
  const unsigned long ROLE_MATHML_STRING_LITERAL = 136;

  /**
   * A MathML glyph (mglyph in MathML).
   */
  const unsigned long ROLE_MATHML_GLYPH = 137;

  /**
   * A MathML row (mrow in MathML).
   */
  const unsigned long ROLE_MATHML_ROW = 138;

  /**
   * A MathML fraction (mfrac in MathML).
   */
  const unsigned long ROLE_MATHML_FRACTION = 139;

  /**
   * A MathML square root (msqrt in MathML).
   */
  const unsigned long ROLE_MATHML_SQUARE_ROOT = 140;

  /**
   * A MathML root (mroot in MathML).
   */
  const unsigned long ROLE_MATHML_ROOT = 141;

  /**
   * A MathML fenced element (mfenced in MathML).
   */
  const unsigned long ROLE_MATHML_FENCED = 142;

  /**
   * A MathML enclosed element (menclose in MathML).
   */
  const unsigned long ROLE_MATHML_ENCLOSED = 143;

  /**
   * A MathML styling element (mstyle in MathML).
   */
  const unsigned long ROLE_MATHML_STYLE = 144;

  /**
   * A MathML subscript (msub in MathML).
   */
  const unsigned long ROLE_MATHML_SUB = 145;

  /**
   * A MathML superscript (msup in MathML).
   */
  const unsigned long ROLE_MATHML_SUP = 146;

  /**
   * A MathML subscript and superscript (msubsup in MathML).
   */
  const unsigned long ROLE_MATHML_SUB_SUP = 147;

  /**
   * A MathML underscript (munder in MathML).
   */
  const unsigned long ROLE_MATHML_UNDER = 148;

  /**
   * A MathML overscript (mover in MathML).
   */
  const unsigned long ROLE_MATHML_OVER = 149;

  /**
   * A MathML underscript and overscript (munderover in MathML).
   */
  const unsigned long ROLE_MATHML_UNDER_OVER = 150;

  /**
   * A MathML multiple subscript and superscript element (mmultiscripts in
   * MathML).
   */
  const unsigned long ROLE_MATHML_MULTISCRIPTS = 151;

  /**
   * A MathML table (mtable in MathML).
   */
  const unsigned long ROLE_MATHML_TABLE = 152;

  /**
   * A MathML labelled table row (mlabeledtr in MathML).
   */
  const unsigned long ROLE_MATHML_LABELED_ROW = 153;

  /**
   * A MathML table row (mtr in MathML).
   */
  const unsigned long ROLE_MATHML_TABLE_ROW = 154;

  /**
   * A MathML table entry or cell (mtd in MathML).
   */
  const unsigned long ROLE_MATHML_CELL = 155;

  /**
   * A MathML interactive element (maction in MathML).
   */
  const unsigned long ROLE_MATHML_ACTION = 156;

  /**
   * A MathML error message (merror in MathML).
   */
  const unsigned long ROLE_MATHML_ERROR = 157;

  /**
   * A MathML stacked (rows of numbers) element (mstack in MathML).
   */
  const unsigned long ROLE_MATHML_STACK = 158;

  /**
   * A MathML long division element (mlongdiv in MathML).
   */
  const unsigned long ROLE_MATHML_LONG_DIVISION = 159;

  /**
   * A MathML stack group (msgroup in MathML).
   */
  const unsigned long ROLE_MATHML_STACK_GROUP = 160;

  /**
   * A MathML stack row (msrow in MathML).
   */
  const unsigned long ROLE_MATHML_STACK_ROW = 161;

  /**
   * MathML carries, borrows, or crossouts for a row (mscarries in MathML).
   */
  const unsigned long ROLE_MATHML_STACK_CARRIES = 162;

  /**
   * A MathML carry, borrow, or crossout for a column (mscarry in MathML).
   */
  const unsigned long ROLE_MATHML_STACK_CARRY = 163;

  /**
   * A MathML line in a stack (msline in MathML).
   */
  const unsigned long ROLE_MATHML_STACK_LINE = 164;

  /**
   * A group containing radio buttons
   */
  const unsigned long ROLE_RADIO_GROUP = 165;

  /**
   * A text container exposing brief amount of information. See related
   * TEXT_CONTAINER role.
   */
  const unsigned long ROLE_TEXT = 166;

  /**
   * A text container exposing brief amount of information. See related
   * DETAILS role.
   */
  const unsigned long ROLE_DETAILS = 167;

  /**
   * A text container exposing brief amount of information. See related
   * SUMMARY role.
   */
  const unsigned long ROLE_SUMMARY = 168;

  /**
   * An ARIA landmark. See related NAVIGATION role.
   */
  const unsigned long ROLE_LANDMARK = 169;

  /**
   * A specific type of ARIA landmark. The ability to distinguish navigation
   * landmarks from other types of landmarks is needed because macOS has a
   * specific AXSubrole and AXRoleDescription for navigation landmarks.
   */
  const unsigned long ROLE_NAVIGATION = 170;

  /**
   * An object that contains the text of a footnote.
   */
  const unsigned long ROLE_FOOTNOTE = 171;

  /**
   * A complete or self-contained composition in a document, page, application,
   * or site and that is, in principle, independently distributable or reusable,
   * e.g. in syndication.
   */
  const unsigned long ROLE_ARTICLE = 172;

  /**
   * A perceivable section containing content that is relevant to a specific,
   * author-specified purpose and sufficiently important that users will likely
   * want to be able to navigate to the section easily and to have it listed in
   * a summary of the page.
   */
  const unsigned long ROLE_REGION = 173;

  /**
   * Represents a control with a text input and a popup with a set of predefined
   * choices. It is used for ARIA's combobox role. See also ROLE_COMBOBOX.
   */
  const unsigned long ROLE_EDITCOMBOBOX = 174;

  /**
   * A section of content that is quoted from another source.
   */
  const unsigned long ROLE_BLOCKQUOTE = 175;
};
