 interface HTMLTableRowElement : HTMLElement {
 /* IID: { 0xa6cf90b6, 0x15b3, 0x11d2, \
  { 0x93, 0x2e, 0x00, 0x80, 0x5f, 0x8a, 0xdd, 0x32 } } */

            attribute  long                 rowIndex;
            attribute  long                 sectionRowIndex;
            attribute  HTMLCollection       cells;
            attribute  DOMString            align;
            attribute  DOMString            bgColor;
            attribute  DOMString            ch;
            attribute  DOMString            chOff;
            attribute  DOMString            vAlign;
   HTMLElement               insertCell(in long index);
   void                      deleteCell(in long index);
 };
