 interface HTMLAnchorElement : HTMLElement {
 /* IID: { 0xa6cf90aa, 0x15b3, 0x11d2, \
  { 0x93, 0x2e, 0x00, 0x80, 0x5f, 0x8a, 0xdd, 0x32 } } */

            attribute  DOMString            accessKey;
            attribute  DOMString            charset;
            attribute  DOMString            coords;
            attribute  DOMString            href;
            attribute  DOMString            hreflang;
            attribute  DOMString            name;
            attribute  DOMString            rel;
            attribute  DOMString            rev;
            attribute  DOMString            shape;
            attribute  long                 tabIndex;
            attribute  DOMString            target;
            attribute  DOMString            type;
   void                      blur();
   void                      focus();
 };

  interface NSHTMLAnchorElement {
 /* IID: { 0xa6cf911c, 0x15b3, 0x11d2,  \
  { 0x93, 0x2e, 0x00, 0x80, 0x5f, 0x8a, 0xdd, 0x32 } } */

   readonly attribute DOMString   protocol;
   readonly attribute DOMString   host;
   readonly attribute DOMString   hostname;  
   readonly attribute DOMString   pathname;
   readonly attribute DOMString   search;
   readonly attribute DOMString   port;
   readonly attribute DOMString   hash;
   readonly attribute DOMString   text;
  };
