   interface HTMLTableElement : HTMLElement {
     attribute HTMLTableCaptionElement caption;
     attribute HTMLTableSectionElement tHead;
     attribute HTMLTableSectionElement tFoot;
     attribute HTMLCollection  rows;
     attribute HTMLCollection  tBodies;
     attribute wstring         align;
     attribute wstring         bgColor;
     attribute wstring         border;
     attribute wstring         cellPadding;
     attribute wstring         cellSpacing;
     attribute wstring         frame;
     attribute wstring         rules;
     attribute wstring         summary;
     attribute wstring         width;
     HTMLElement               createTHead();
     void                      deleteTHead();
     HTMLElement               createTFoot();
     void                      deleteTFoot();
     HTMLElement               createCaption();
     void                      deleteCaption();
     HTMLElement               insertRow(in long index);
     void                      deleteRow(in long index);
   };
