   interface HTMLTableRowElement : HTMLElement {
     attribute long            rowIndex;
     attribute long            sectionRowIndex;
     attribute HTMLCollection  cells;
     attribute wstring         align;
     attribute wstring         bgColor;
     attribute wstring         ch;
     attribute wstring         chOff;
     attribute wstring         vAlign;
     HTMLElement               insertCell(in long index);
     void                      deleteCell(in long index);
   };
