   interface HTMLElement : Element {
     attribute wstring         id;
     attribute wstring         title;
     attribute wstring         lang;
     attribute wstring         dir;
     attribute wstring         className;
     readonly attribute CSSStyleDeclaration style;
   };
