   interface HTMLOptionElement : HTMLElement {
     attribute HTMLFormElement form;
     attribute boolean         defaultSelected;
     attribute wstring         text;
     attribute long            index;
     attribute boolean         disabled;
     attribute wstring         label;
     attribute boolean         selected;
     attribute wstring         value;
   };
