/* -*- Mode: IDL; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*-
 *
 * The contents of this file are subject to the Netscape Public
 * License Version 1.1 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of
 * the License at http://www.mozilla.org/NPL/
 *
 * Software distributed under the License is distributed on an "AS
 * IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
 * implied. See the License for the specific language governing
 * rights and limitations under the License.
 *
 * The Original Code is Mozilla Communicator client code.
 *
 * The Initial Developer of the Original Code is Netscape Communications
 * Corporation.  Portions created by Netscape are
 * Copyright (C) 1998 Netscape Communications Corporation. All
 * Rights Reserved.
 *
 * Contributor(s):
 * Alec Flett <alecf@netscape.com>
 * Brian Nesse <bnesse@netscape.com>
 */

#include "nsISupports.idl"
#include "nsIObserver.idl"

[scriptable, uuid(24ef9578-1dd2-11b2-b439-fcc3d2b4fa20)]
interface nsIPrefBranchInternal : nsISupports
{
  /*
   * Listeners
   */

  /*
   * The observers have their |Observe| methods called with
   * ([the observer], "nsPref:changed", [pref name]).
   */
  void addObserver(in string aDomain, in nsIObserver aObserver);
  void removeObserver(in string aDomain, in nsIObserver aObserver);

};

