
#Dependencies

$(OBJS) $(OBJS_PIC): Makefile

# DO NOT REMOVE
mod_gzip_content.o: mod_gzip_content.c $(INCDIR)/httpd.h \
 $(INCDIR)/conf.h $(OSDIR)/os.h $(INCDIR)/alloc.h \
 $(INCDIR)/buff.h $(INCDIR)/ap.h $(INCDIR)/util_uri.h \
 $(INCDIR)/http_config.h $(INCDIR)/http_core.h \
 $(INCDIR)/http_log.h $(INCDIR)/http_main.h \
 $(INCDIR)/http_protocol.h $(INCDIR)/util_script.h

