interface InstallVersion
{
/* IID: { 0x18c2f986, 0xb09f, 0x11d2, \
  {0xbc, 0xde, 0x00, 0x80, 0x5f, 0x0e, 0x13, 0x53}} */
	 
	const int SU_EQUAL				=  0;
    const int SU_BLD_DIFF			=  1;
	const int SU_BLD_DIFF_MINUS		= -1;
    const int SU_REL_DIFF			=  2;
	const int SU_REL_DIFF_MINUS		= -2;
    const int SU_MINOR_DIFF			=  3;
	const int SU_MINOR_DIFF_MINUS   = -3;
    const int SU_MAJOR_DIFF			=  4;
	const int SU_MAJOR_DIFF_MINUS   = -4;
	
	attribute int major;
	attribute int minor;
	attribute int release;
	attribute int build;

	void InstallVersion();

	void init(in wstring versionString);	
/*
	void init(in int major, in int minor, in int release, in int build);	
*/
	wstring toString();

/*	int compareTo(in wstring version);
	int compareTo(in int major, in int minor, in int release, in int build);
*/
	int compareTo(in InstallVersion versionObject);

};