<!-- Commands included by the browser overlay
     browser/base/content/browser-sets.inc -->
    <command id="safebrowsing-show-warning"
    oncommand="SB_executeCommandLocally('safebrowsing-show-warning')" />
    <command id="safebrowsing-accept-warning"
    oncommand="SB_executeCommandLocally('safebrowsing-accept-warning')" />  
    <command id="safebrowsing-decline-warning"
    oncommand="SB_executeCommandLocally('safebrowsing-decline-warning')" />
    <command id="safebrowsing-palm-showmore"
    oncommand="SB_executeCommandLocally('safebrowsing-palm-showmore')" />
    <command id="safebrowsing-palm-phishingorg"
    oncommand="SB_executeCommandLocally('safebrowsing-palm-phishingorg')" />
    <command id="safebrowsing-palm-phishingfaq"
    oncommand="SB_executeCommandLocally('safebrowsing-palm-phishingfaq')" />
    <command id="safebrowsing-palm-fraudpage"
    oncommand="SB_executeCommandLocally('safebrowsing-palm-fraudpage')" />
    <command id="safebrowsing-palm-falsepositive"
    oncommand="SB_executeCommandLocally('safebrowsing-palm-falsepositive')" />
    <command id="safebrowsing-submit-blacklist"
    oncommand="SB_executeCommandLocally('safebrowsing-submit-blacklist')" />
    <command id="safebrowsing-submit-generic-phishing"
             oncommand="SB_executeCommandLocally('safebrowsing-submit-generic-phishing')"/>
    <command id="safebrowsing-preferences"
    oncommand="SB_executeCommandLocally('safebrowsing-preferences')" />
    <command id="safebrowsing-test-link"
    oncommand="SB_executeCommandLocally('safebrowsing-test-link')" />
