# 
# The contents of this file are subject to the Mozilla Public
# License Version 1.1 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy of
# the License at http://www.mozilla.org/MPL/
#
# Software distributed under the License is distributed on an "AS
# IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
# implied. See the License for the specific language governing
# rights and limitations under the License.
#
# The Original Code is mozilla.org code.
#
# The Initial Developer of the Original Code is Sun Microsystems,
# Inc. Portions created by Sun are
# Copyright (C) 1999 Sun Microsystems, Inc. All
# Rights Reserved.
#
# Contributor(s): 
TOP_DIR = ../../..
OBJ_DIR = ../obj
CPP = \
	DeleteGlobalRef_1.cpp \
	DeleteGlobalRef_2.cpp \
	DeleteLocalRef_1.cpp \
	DeleteLocalRef_2.cpp \
	NewGlobalRef_1.cpp \
	NewGlobalRef_2.cpp

OBJS = \
	$(OBJ_DIR)/DeleteGlobalRef_1.o \
	$(OBJ_DIR)/DeleteGlobalRef_2.o \
	$(OBJ_DIR)/DeleteLocalRef_1.o \
	$(OBJ_DIR)/DeleteLocalRef_2.o \
	$(OBJ_DIR)/NewGlobalRef_1.o \
	$(OBJ_DIR)/NewGlobalRef_2.o

INCLUDES = -I../include 
include ../../../build/rules.mk 
all: compile
