/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

/**
 * nsIEditorObserver is the interface used by applications wishing to be
 * notified when the editor has completed a user action.
 * Note that when you want to use this from C++, please check if EditorBase
 * can treat your class directly since using this interface may make editor
 * slower.
 */
[scriptable, uuid(f3ee57a6-890c-4ce0-a584-8a84bba0292e)]
interface nsIEditorObserver : nsISupports
{
  /**
   * Called after the editor completes a user action.
   */
  void EditAction();
};
