#
# This is a list of local files which get copied to the mozilla:dist directory
#

netscape_javascript_JSObject.h
netscape_plugin_Plugin.h
netscape_security_Principal.h
netscape_security_Privilege.h
netscape_security_Target.h
netscape_security_Zig.h
n_applet_MozillaAppletContext.h
n_a_EmbeddedObjectNatives.h
n_javascript_JSException.h
n_plugin_composer_Composer.h
n_p_composer_PluginManager.h
n_security_PrivilegeManager.h
n_security_PrivilegeTable.h
