# 
# The contents of this file are subject to the Mozilla Public
# License Version 1.1 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy of
# the License at http://www.mozilla.org/MPL/
#
# Software distributed under the License is distributed on an "AS
# IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
# implied. See the License for the specific language governing
# rights and limitations under the License.
#
# The Original Code is mozilla.org code.
#
# The Initial Developer of the Original Code is Sun Microsystems,
# Inc. Portions created by Sun are
# Copyright (C) 1999 Sun Microsystems, Inc. All
# Rights Reserved.
#
# Contributor(s): 
TOP_DIR = ../..

OBJ_DIR = obj

CPP = 	CreateThread.cpp \
	EnterMonitor.cpp \
	ExitMonitor.cpp \
	get_tm.cpp \
	GetCurrentThread.cpp \
	Notify.cpp \
	NotifyAll.cpp \
	Sleep.cpp \
	Wait.cpp \
	PostEvent.cpp

OBJS = 	$(OBJ_DIR)/CreateThread.obj \
	$(OBJ_DIR)/EnterMonitor.obj \
	$(OBJ_DIR)/ExitMonitor.obj \
	$(OBJ_DIR)/get_tm.obj \
	$(OBJ_DIR)/GetCurrentThread.obj \
	$(OBJ_DIR)/Notify.obj \
	$(OBJ_DIR)/NotifyAll.obj \
	$(OBJ_DIR)/Sleep.obj \
	$(OBJ_DIR)/Wait.obj \
	$(OBJ_DIR)/PostEvent.obj


DLL = ojiapitmtests

include ../../build/rules.mak

all: compile link



