/*
 * Copyright (c) 2008 Mozilla Foundation
 *
 * Permission is hereby granted, free of charge, to any person obtaining a 
 * copy of this software and associated documentation files (the "Software"), 
 * to deal in the Software without restriction, including without limitation 
 * the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 * and/or sell copies of the Software, and to permit persons to whom the 
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in 
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL 
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
 * DEALINGS IN THE SOFTWARE.
 */

/*
 * THIS IS A GENERATED FILE. PLEASE DO NOT EDIT.
 * Please edit AttributeName.java instead and regenerate.
 */

#ifndef nsHtml5AttributeName_h__
#define nsHtml5AttributeName_h__

#include "prtypes.h"
#include "nsIAtom.h"
#include "nsString.h"
#include "nsINameSpaceManager.h"
#include "nsIContent.h"
#include "nsIDocument.h"
#include "jArray.h"
#include "nsHtml5DocumentMode.h"
#include "nsHtml5ArrayCopy.h"
#include "nsHtml5NamedCharacters.h"
#include "nsHtml5Parser.h"
#include "nsHtml5StringLiterals.h"
#include "nsHtml5Atoms.h"

class nsHtml5Parser;

class nsHtml5Tokenizer;
class nsHtml5TreeBuilder;
class nsHtml5ElementName;
class nsHtml5HtmlAttributes;
class nsHtml5StackNode;
class nsHtml5UTF16Buffer;
class nsHtml5Portability;

class nsHtml5AttributeName
{
  private:
    static PRInt32* ALL_NO_NS;
    static PRInt32* XMLNS_NS;
    static PRInt32* XML_NS;
    static PRInt32* XLINK_NS;
    static nsIAtom** ALL_NO_PREFIX;
    static nsIAtom** XMLNS_PREFIX;
    static nsIAtom** XLINK_PREFIX;
    static nsIAtom** XML_PREFIX;
    static nsIAtom** SVG_DIFFERENT(nsIAtom* name, nsIAtom* camel);
    static nsIAtom** MATH_DIFFERENT(nsIAtom* name, nsIAtom* camel);
    static nsIAtom** COLONIFIED_LOCAL(nsIAtom* name, nsIAtom* suffix);
    static nsIAtom** SAME_LOCAL(nsIAtom* name);
  public:
    static nsHtml5AttributeName* nameByBuffer(PRUnichar* buf, PRInt32 offset, PRInt32 length);
  private:
    static PRInt32 bufToHash(PRUnichar* buf, PRInt32 len);
    PRInt32* uri;
    nsIAtom** local;
    nsIAtom** prefix;
    nsHtml5AttributeName(PRInt32* uri, nsIAtom** local, nsIAtom** prefix);
    static nsHtml5AttributeName* create(nsIAtom* name);
  public:
    void release();
  private:
    void destructor();
  public:
    PRInt32 getUri(PRInt32 mode);
    nsIAtom* getLocal(PRInt32 mode);
    nsIAtom* getPrefix(PRInt32 mode);
    PRBool equalsAnother(nsHtml5AttributeName* another);
    static nsHtml5AttributeName* D;
    static nsHtml5AttributeName* K;
    static nsHtml5AttributeName* R;
    static nsHtml5AttributeName* X;
    static nsHtml5AttributeName* Y;
    static nsHtml5AttributeName* Z;
    static nsHtml5AttributeName* BY;
    static nsHtml5AttributeName* CX;
    static nsHtml5AttributeName* CY;
    static nsHtml5AttributeName* DX;
    static nsHtml5AttributeName* DY;
    static nsHtml5AttributeName* G2;
    static nsHtml5AttributeName* G1;
    static nsHtml5AttributeName* FX;
    static nsHtml5AttributeName* FY;
    static nsHtml5AttributeName* K4;
    static nsHtml5AttributeName* K2;
    static nsHtml5AttributeName* K3;
    static nsHtml5AttributeName* K1;
    static nsHtml5AttributeName* ID;
    static nsHtml5AttributeName* IN;
    static nsHtml5AttributeName* U2;
    static nsHtml5AttributeName* U1;
    static nsHtml5AttributeName* RT;
    static nsHtml5AttributeName* RX;
    static nsHtml5AttributeName* RY;
    static nsHtml5AttributeName* TO;
    static nsHtml5AttributeName* Y2;
    static nsHtml5AttributeName* Y1;
    static nsHtml5AttributeName* X1;
    static nsHtml5AttributeName* X2;
    static nsHtml5AttributeName* ALT;
    static nsHtml5AttributeName* DIR;
    static nsHtml5AttributeName* DUR;
    static nsHtml5AttributeName* END;
    static nsHtml5AttributeName* FOR;
    static nsHtml5AttributeName* IN2;
    static nsHtml5AttributeName* MAX;
    static nsHtml5AttributeName* MIN;
    static nsHtml5AttributeName* LOW;
    static nsHtml5AttributeName* REL;
    static nsHtml5AttributeName* REV;
    static nsHtml5AttributeName* SRC;
    static nsHtml5AttributeName* AXIS;
    static nsHtml5AttributeName* ABBR;
    static nsHtml5AttributeName* BBOX;
    static nsHtml5AttributeName* CITE;
    static nsHtml5AttributeName* CODE;
    static nsHtml5AttributeName* BIAS;
    static nsHtml5AttributeName* COLS;
    static nsHtml5AttributeName* CLIP;
    static nsHtml5AttributeName* CHAR;
    static nsHtml5AttributeName* BASE;
    static nsHtml5AttributeName* EDGE;
    static nsHtml5AttributeName* DATA;
    static nsHtml5AttributeName* FILL;
    static nsHtml5AttributeName* FROM;
    static nsHtml5AttributeName* FORM;
    static nsHtml5AttributeName* FACE;
    static nsHtml5AttributeName* HIGH;
    static nsHtml5AttributeName* HREF;
    static nsHtml5AttributeName* OPEN;
    static nsHtml5AttributeName* ICON;
    static nsHtml5AttributeName* NAME;
    static nsHtml5AttributeName* MODE;
    static nsHtml5AttributeName* MASK;
    static nsHtml5AttributeName* LINK;
    static nsHtml5AttributeName* LANG;
    static nsHtml5AttributeName* LIST;
    static nsHtml5AttributeName* TYPE;
    static nsHtml5AttributeName* WHEN;
    static nsHtml5AttributeName* WRAP;
    static nsHtml5AttributeName* TEXT;
    static nsHtml5AttributeName* PATH;
    static nsHtml5AttributeName* PING;
    static nsHtml5AttributeName* REFX;
    static nsHtml5AttributeName* REFY;
    static nsHtml5AttributeName* SIZE;
    static nsHtml5AttributeName* SEED;
    static nsHtml5AttributeName* ROWS;
    static nsHtml5AttributeName* SPAN;
    static nsHtml5AttributeName* STEP;
    static nsHtml5AttributeName* ROLE;
    static nsHtml5AttributeName* XREF;
    static nsHtml5AttributeName* ASYNC;
    static nsHtml5AttributeName* ALINK;
    static nsHtml5AttributeName* ALIGN;
    static nsHtml5AttributeName* CLOSE;
    static nsHtml5AttributeName* COLOR;
    static nsHtml5AttributeName* CLASS;
    static nsHtml5AttributeName* CLEAR;
    static nsHtml5AttributeName* BEGIN;
    static nsHtml5AttributeName* DEPTH;
    static nsHtml5AttributeName* DEFER;
    static nsHtml5AttributeName* FENCE;
    static nsHtml5AttributeName* FRAME;
    static nsHtml5AttributeName* ISMAP;
    static nsHtml5AttributeName* ONEND;
    static nsHtml5AttributeName* INDEX;
    static nsHtml5AttributeName* ORDER;
    static nsHtml5AttributeName* OTHER;
    static nsHtml5AttributeName* ONCUT;
    static nsHtml5AttributeName* NARGS;
    static nsHtml5AttributeName* MEDIA;
    static nsHtml5AttributeName* LABEL;
    static nsHtml5AttributeName* LOCAL;
    static nsHtml5AttributeName* WIDTH;
    static nsHtml5AttributeName* TITLE;
    static nsHtml5AttributeName* VLINK;
    static nsHtml5AttributeName* VALUE;
    static nsHtml5AttributeName* SLOPE;
    static nsHtml5AttributeName* SHAPE;
    static nsHtml5AttributeName* SCOPE;
    static nsHtml5AttributeName* SCALE;
    static nsHtml5AttributeName* SPEED;
    static nsHtml5AttributeName* STYLE;
    static nsHtml5AttributeName* RULES;
    static nsHtml5AttributeName* STEMH;
    static nsHtml5AttributeName* STEMV;
    static nsHtml5AttributeName* START;
    static nsHtml5AttributeName* XMLNS;
    static nsHtml5AttributeName* ACCEPT;
    static nsHtml5AttributeName* ACCENT;
    static nsHtml5AttributeName* ASCENT;
    static nsHtml5AttributeName* ACTIVE;
    static nsHtml5AttributeName* ALTIMG;
    static nsHtml5AttributeName* ACTION;
    static nsHtml5AttributeName* BORDER;
    static nsHtml5AttributeName* CURSOR;
    static nsHtml5AttributeName* COORDS;
    static nsHtml5AttributeName* FILTER;
    static nsHtml5AttributeName* FORMAT;
    static nsHtml5AttributeName* HIDDEN;
    static nsHtml5AttributeName* HSPACE;
    static nsHtml5AttributeName* HEIGHT;
    static nsHtml5AttributeName* ONMOVE;
    static nsHtml5AttributeName* ONLOAD;
    static nsHtml5AttributeName* ONDRAG;
    static nsHtml5AttributeName* ORIGIN;
    static nsHtml5AttributeName* ONZOOM;
    static nsHtml5AttributeName* ONHELP;
    static nsHtml5AttributeName* ONSTOP;
    static nsHtml5AttributeName* ONDROP;
    static nsHtml5AttributeName* ONBLUR;
    static nsHtml5AttributeName* OBJECT;
    static nsHtml5AttributeName* OFFSET;
    static nsHtml5AttributeName* ORIENT;
    static nsHtml5AttributeName* ONCOPY;
    static nsHtml5AttributeName* NOWRAP;
    static nsHtml5AttributeName* NOHREF;
    static nsHtml5AttributeName* MACROS;
    static nsHtml5AttributeName* METHOD;
    static nsHtml5AttributeName* LOWSRC;
    static nsHtml5AttributeName* LSPACE;
    static nsHtml5AttributeName* LQUOTE;
    static nsHtml5AttributeName* USEMAP;
    static nsHtml5AttributeName* WIDTHS;
    static nsHtml5AttributeName* TARGET;
    static nsHtml5AttributeName* VALUES;
    static nsHtml5AttributeName* VALIGN;
    static nsHtml5AttributeName* VSPACE;
    static nsHtml5AttributeName* POSTER;
    static nsHtml5AttributeName* POINTS;
    static nsHtml5AttributeName* PROMPT;
    static nsHtml5AttributeName* SCOPED;
    static nsHtml5AttributeName* STRING;
    static nsHtml5AttributeName* SCHEME;
    static nsHtml5AttributeName* STROKE;
    static nsHtml5AttributeName* RADIUS;
    static nsHtml5AttributeName* RESULT;
    static nsHtml5AttributeName* REPEAT;
    static nsHtml5AttributeName* RSPACE;
    static nsHtml5AttributeName* ROTATE;
    static nsHtml5AttributeName* RQUOTE;
    static nsHtml5AttributeName* ALTTEXT;
    static nsHtml5AttributeName* ARCHIVE;
    static nsHtml5AttributeName* AZIMUTH;
    static nsHtml5AttributeName* CLOSURE;
    static nsHtml5AttributeName* CHECKED;
    static nsHtml5AttributeName* CLASSID;
    static nsHtml5AttributeName* CHAROFF;
    static nsHtml5AttributeName* BGCOLOR;
    static nsHtml5AttributeName* COLSPAN;
    static nsHtml5AttributeName* CHARSET;
    static nsHtml5AttributeName* COMPACT;
    static nsHtml5AttributeName* CONTENT;
    static nsHtml5AttributeName* ENCTYPE;
    static nsHtml5AttributeName* DATASRC;
    static nsHtml5AttributeName* DATAFLD;
    static nsHtml5AttributeName* DECLARE;
    static nsHtml5AttributeName* DISPLAY;
    static nsHtml5AttributeName* DIVISOR;
    static nsHtml5AttributeName* DEFAULT;
    static nsHtml5AttributeName* DESCENT;
    static nsHtml5AttributeName* KERNING;
    static nsHtml5AttributeName* HANGING;
    static nsHtml5AttributeName* HEADERS;
    static nsHtml5AttributeName* ONPASTE;
    static nsHtml5AttributeName* ONCLICK;
    static nsHtml5AttributeName* OPTIMUM;
    static nsHtml5AttributeName* ONBEGIN;
    static nsHtml5AttributeName* ONKEYUP;
    static nsHtml5AttributeName* ONFOCUS;
    static nsHtml5AttributeName* ONERROR;
    static nsHtml5AttributeName* ONINPUT;
    static nsHtml5AttributeName* ONABORT;
    static nsHtml5AttributeName* ONSTART;
    static nsHtml5AttributeName* ONRESET;
    static nsHtml5AttributeName* OPACITY;
    static nsHtml5AttributeName* NOSHADE;
    static nsHtml5AttributeName* MINSIZE;
    static nsHtml5AttributeName* MAXSIZE;
    static nsHtml5AttributeName* LOOPEND;
    static nsHtml5AttributeName* LARGEOP;
    static nsHtml5AttributeName* UNICODE;
    static nsHtml5AttributeName* TARGETX;
    static nsHtml5AttributeName* TARGETY;
    static nsHtml5AttributeName* VIEWBOX;
    static nsHtml5AttributeName* VERSION;
    static nsHtml5AttributeName* PATTERN;
    static nsHtml5AttributeName* PROFILE;
    static nsHtml5AttributeName* SPACING;
    static nsHtml5AttributeName* RESTART;
    static nsHtml5AttributeName* ROWSPAN;
    static nsHtml5AttributeName* SANDBOX;
    static nsHtml5AttributeName* SUMMARY;
    static nsHtml5AttributeName* STANDBY;
    static nsHtml5AttributeName* REPLACE;
    static nsHtml5AttributeName* AUTOPLAY;
    static nsHtml5AttributeName* ADDITIVE;
    static nsHtml5AttributeName* CALCMODE;
    static nsHtml5AttributeName* CODETYPE;
    static nsHtml5AttributeName* CODEBASE;
    static nsHtml5AttributeName* CONTROLS;
    static nsHtml5AttributeName* BEVELLED;
    static nsHtml5AttributeName* BASELINE;
    static nsHtml5AttributeName* EXPONENT;
    static nsHtml5AttributeName* EDGEMODE;
    static nsHtml5AttributeName* ENCODING;
    static nsHtml5AttributeName* GLYPHREF;
    static nsHtml5AttributeName* DATETIME;
    static nsHtml5AttributeName* DISABLED;
    static nsHtml5AttributeName* FONTSIZE;
    static nsHtml5AttributeName* KEYTIMES;
    static nsHtml5AttributeName* PANOSE_1;
    static nsHtml5AttributeName* HREFLANG;
    static nsHtml5AttributeName* ONRESIZE;
    static nsHtml5AttributeName* ONCHANGE;
    static nsHtml5AttributeName* ONBOUNCE;
    static nsHtml5AttributeName* ONUNLOAD;
    static nsHtml5AttributeName* ONFINISH;
    static nsHtml5AttributeName* ONSCROLL;
    static nsHtml5AttributeName* OPERATOR;
    static nsHtml5AttributeName* OVERFLOW;
    static nsHtml5AttributeName* ONSUBMIT;
    static nsHtml5AttributeName* ONREPEAT;
    static nsHtml5AttributeName* ONSELECT;
    static nsHtml5AttributeName* NOTATION;
    static nsHtml5AttributeName* NORESIZE;
    static nsHtml5AttributeName* MANIFEST;
    static nsHtml5AttributeName* MATHSIZE;
    static nsHtml5AttributeName* MULTIPLE;
    static nsHtml5AttributeName* LONGDESC;
    static nsHtml5AttributeName* LANGUAGE;
    static nsHtml5AttributeName* TEMPLATE;
    static nsHtml5AttributeName* TABINDEX;
    static nsHtml5AttributeName* READONLY;
    static nsHtml5AttributeName* SELECTED;
    static nsHtml5AttributeName* ROWLINES;
    static nsHtml5AttributeName* SEAMLESS;
    static nsHtml5AttributeName* ROWALIGN;
    static nsHtml5AttributeName* STRETCHY;
    static nsHtml5AttributeName* REQUIRED;
    static nsHtml5AttributeName* XML_BASE;
    static nsHtml5AttributeName* XML_LANG;
    static nsHtml5AttributeName* X_HEIGHT;
    static nsHtml5AttributeName* ARIA_OWNS;
    static nsHtml5AttributeName* AUTOFOCUS;
    static nsHtml5AttributeName* ARIA_SORT;
    static nsHtml5AttributeName* ACCESSKEY;
    static nsHtml5AttributeName* ARIA_BUSY;
    static nsHtml5AttributeName* ARIA_GRAB;
    static nsHtml5AttributeName* AMPLITUDE;
    static nsHtml5AttributeName* ARIA_LIVE;
    static nsHtml5AttributeName* CLIP_RULE;
    static nsHtml5AttributeName* CLIP_PATH;
    static nsHtml5AttributeName* EQUALROWS;
    static nsHtml5AttributeName* ELEVATION;
    static nsHtml5AttributeName* DIRECTION;
    static nsHtml5AttributeName* DRAGGABLE;
    static nsHtml5AttributeName* FILTERRES;
    static nsHtml5AttributeName* FILL_RULE;
    static nsHtml5AttributeName* FONTSTYLE;
    static nsHtml5AttributeName* FONT_SIZE;
    static nsHtml5AttributeName* KEYPOINTS;
    static nsHtml5AttributeName* HIDEFOCUS;
    static nsHtml5AttributeName* ONMESSAGE;
    static nsHtml5AttributeName* INTERCEPT;
    static nsHtml5AttributeName* ONDRAGEND;
    static nsHtml5AttributeName* ONMOVEEND;
    static nsHtml5AttributeName* ONINVALID;
    static nsHtml5AttributeName* ONKEYDOWN;
    static nsHtml5AttributeName* ONFOCUSIN;
    static nsHtml5AttributeName* ONMOUSEUP;
    static nsHtml5AttributeName* INPUTMODE;
    static nsHtml5AttributeName* ONROWEXIT;
    static nsHtml5AttributeName* MATHCOLOR;
    static nsHtml5AttributeName* MASKUNITS;
    static nsHtml5AttributeName* MAXLENGTH;
    static nsHtml5AttributeName* LINEBREAK;
    static nsHtml5AttributeName* LOOPSTART;
    static nsHtml5AttributeName* TRANSFORM;
    static nsHtml5AttributeName* V_HANGING;
    static nsHtml5AttributeName* VALUETYPE;
    static nsHtml5AttributeName* POINTSATZ;
    static nsHtml5AttributeName* POINTSATX;
    static nsHtml5AttributeName* POINTSATY;
    static nsHtml5AttributeName* PLAYCOUNT;
    static nsHtml5AttributeName* SYMMETRIC;
    static nsHtml5AttributeName* SCROLLING;
    static nsHtml5AttributeName* REPEATDUR;
    static nsHtml5AttributeName* SELECTION;
    static nsHtml5AttributeName* SEPARATOR;
    static nsHtml5AttributeName* XML_SPACE;
    static nsHtml5AttributeName* AUTOSUBMIT;
    static nsHtml5AttributeName* ALPHABETIC;
    static nsHtml5AttributeName* ACTIONTYPE;
    static nsHtml5AttributeName* ACCUMULATE;
    static nsHtml5AttributeName* ARIA_LEVEL;
    static nsHtml5AttributeName* COLUMNSPAN;
    static nsHtml5AttributeName* CAP_HEIGHT;
    static nsHtml5AttributeName* BACKGROUND;
    static nsHtml5AttributeName* GLYPH_NAME;
    static nsHtml5AttributeName* GROUPALIGN;
    static nsHtml5AttributeName* FONTFAMILY;
    static nsHtml5AttributeName* FONTWEIGHT;
    static nsHtml5AttributeName* FONT_STYLE;
    static nsHtml5AttributeName* KEYSPLINES;
    static nsHtml5AttributeName* HTTP_EQUIV;
    static nsHtml5AttributeName* ONACTIVATE;
    static nsHtml5AttributeName* OCCURRENCE;
    static nsHtml5AttributeName* IRRELEVANT;
    static nsHtml5AttributeName* ONDBLCLICK;
    static nsHtml5AttributeName* ONDRAGDROP;
    static nsHtml5AttributeName* ONKEYPRESS;
    static nsHtml5AttributeName* ONROWENTER;
    static nsHtml5AttributeName* ONDRAGOVER;
    static nsHtml5AttributeName* ONFOCUSOUT;
    static nsHtml5AttributeName* ONMOUSEOUT;
    static nsHtml5AttributeName* NUMOCTAVES;
    static nsHtml5AttributeName* MARKER_MID;
    static nsHtml5AttributeName* MARKER_END;
    static nsHtml5AttributeName* TEXTLENGTH;
    static nsHtml5AttributeName* VISIBILITY;
    static nsHtml5AttributeName* VIEWTARGET;
    static nsHtml5AttributeName* VERT_ADV_Y;
    static nsHtml5AttributeName* PATHLENGTH;
    static nsHtml5AttributeName* REPEAT_MAX;
    static nsHtml5AttributeName* RADIOGROUP;
    static nsHtml5AttributeName* STOP_COLOR;
    static nsHtml5AttributeName* SEPARATORS;
    static nsHtml5AttributeName* REPEAT_MIN;
    static nsHtml5AttributeName* ROWSPACING;
    static nsHtml5AttributeName* ZOOMANDPAN;
    static nsHtml5AttributeName* XLINK_TYPE;
    static nsHtml5AttributeName* XLINK_ROLE;
    static nsHtml5AttributeName* XLINK_HREF;
    static nsHtml5AttributeName* XLINK_SHOW;
    static nsHtml5AttributeName* ACCENTUNDER;
    static nsHtml5AttributeName* ARIA_SECRET;
    static nsHtml5AttributeName* ARIA_ATOMIC;
    static nsHtml5AttributeName* ARIA_HIDDEN;
    static nsHtml5AttributeName* ARIA_FLOWTO;
    static nsHtml5AttributeName* ARABIC_FORM;
    static nsHtml5AttributeName* CELLPADDING;
    static nsHtml5AttributeName* CELLSPACING;
    static nsHtml5AttributeName* COLUMNWIDTH;
    static nsHtml5AttributeName* COLUMNALIGN;
    static nsHtml5AttributeName* COLUMNLINES;
    static nsHtml5AttributeName* CONTEXTMENU;
    static nsHtml5AttributeName* BASEPROFILE;
    static nsHtml5AttributeName* FONT_FAMILY;
    static nsHtml5AttributeName* FRAMEBORDER;
    static nsHtml5AttributeName* FILTERUNITS;
    static nsHtml5AttributeName* FLOOD_COLOR;
    static nsHtml5AttributeName* FONT_WEIGHT;
    static nsHtml5AttributeName* HORIZ_ADV_X;
    static nsHtml5AttributeName* ONDRAGLEAVE;
    static nsHtml5AttributeName* ONMOUSEMOVE;
    static nsHtml5AttributeName* ORIENTATION;
    static nsHtml5AttributeName* ONMOUSEDOWN;
    static nsHtml5AttributeName* ONMOUSEOVER;
    static nsHtml5AttributeName* ONDRAGENTER;
    static nsHtml5AttributeName* IDEOGRAPHIC;
    static nsHtml5AttributeName* ONBEFORECUT;
    static nsHtml5AttributeName* ONFORMINPUT;
    static nsHtml5AttributeName* ONDRAGSTART;
    static nsHtml5AttributeName* ONMOVESTART;
    static nsHtml5AttributeName* MARKERUNITS;
    static nsHtml5AttributeName* MATHVARIANT;
    static nsHtml5AttributeName* MARGINWIDTH;
    static nsHtml5AttributeName* MARKERWIDTH;
    static nsHtml5AttributeName* TEXT_ANCHOR;
    static nsHtml5AttributeName* TABLEVALUES;
    static nsHtml5AttributeName* SCRIPTLEVEL;
    static nsHtml5AttributeName* REPEATCOUNT;
    static nsHtml5AttributeName* STITCHTILES;
    static nsHtml5AttributeName* STARTOFFSET;
    static nsHtml5AttributeName* SCROLLDELAY;
    static nsHtml5AttributeName* XMLNS_XLINK;
    static nsHtml5AttributeName* XLINK_TITLE;
    static nsHtml5AttributeName* ARIA_INVALID;
    static nsHtml5AttributeName* ARIA_PRESSED;
    static nsHtml5AttributeName* ARIA_CHECKED;
    static nsHtml5AttributeName* AUTOCOMPLETE;
    static nsHtml5AttributeName* ARIA_SETSIZE;
    static nsHtml5AttributeName* ARIA_CHANNEL;
    static nsHtml5AttributeName* EQUALCOLUMNS;
    static nsHtml5AttributeName* DISPLAYSTYLE;
    static nsHtml5AttributeName* DATAFORMATAS;
    static nsHtml5AttributeName* FILL_OPACITY;
    static nsHtml5AttributeName* FONT_VARIANT;
    static nsHtml5AttributeName* FONT_STRETCH;
    static nsHtml5AttributeName* FRAMESPACING;
    static nsHtml5AttributeName* KERNELMATRIX;
    static nsHtml5AttributeName* ONDEACTIVATE;
    static nsHtml5AttributeName* ONROWSDELETE;
    static nsHtml5AttributeName* ONMOUSELEAVE;
    static nsHtml5AttributeName* ONFORMCHANGE;
    static nsHtml5AttributeName* ONCELLCHANGE;
    static nsHtml5AttributeName* ONMOUSEWHEEL;
    static nsHtml5AttributeName* ONMOUSEENTER;
    static nsHtml5AttributeName* ONAFTERPRINT;
    static nsHtml5AttributeName* ONBEFORECOPY;
    static nsHtml5AttributeName* MARGINHEIGHT;
    static nsHtml5AttributeName* MARKERHEIGHT;
    static nsHtml5AttributeName* MARKER_START;
    static nsHtml5AttributeName* MATHEMATICAL;
    static nsHtml5AttributeName* LENGTHADJUST;
    static nsHtml5AttributeName* UNSELECTABLE;
    static nsHtml5AttributeName* UNICODE_BIDI;
    static nsHtml5AttributeName* UNITS_PER_EM;
    static nsHtml5AttributeName* WORD_SPACING;
    static nsHtml5AttributeName* WRITING_MODE;
    static nsHtml5AttributeName* V_ALPHABETIC;
    static nsHtml5AttributeName* PATTERNUNITS;
    static nsHtml5AttributeName* SPREADMETHOD;
    static nsHtml5AttributeName* SURFACESCALE;
    static nsHtml5AttributeName* STROKE_WIDTH;
    static nsHtml5AttributeName* REPEAT_START;
    static nsHtml5AttributeName* STDDEVIATION;
    static nsHtml5AttributeName* STOP_OPACITY;
    static nsHtml5AttributeName* ARIA_CONTROLS;
    static nsHtml5AttributeName* ARIA_HASPOPUP;
    static nsHtml5AttributeName* ACCENT_HEIGHT;
    static nsHtml5AttributeName* ARIA_VALUENOW;
    static nsHtml5AttributeName* ARIA_RELEVANT;
    static nsHtml5AttributeName* ARIA_POSINSET;
    static nsHtml5AttributeName* ARIA_VALUEMAX;
    static nsHtml5AttributeName* ARIA_READONLY;
    static nsHtml5AttributeName* ARIA_SELECTED;
    static nsHtml5AttributeName* ARIA_REQUIRED;
    static nsHtml5AttributeName* ARIA_EXPANDED;
    static nsHtml5AttributeName* ARIA_DISABLED;
    static nsHtml5AttributeName* ATTRIBUTETYPE;
    static nsHtml5AttributeName* ATTRIBUTENAME;
    static nsHtml5AttributeName* ARIA_DATATYPE;
    static nsHtml5AttributeName* ARIA_VALUEMIN;
    static nsHtml5AttributeName* BASEFREQUENCY;
    static nsHtml5AttributeName* COLUMNSPACING;
    static nsHtml5AttributeName* COLOR_PROFILE;
    static nsHtml5AttributeName* CLIPPATHUNITS;
    static nsHtml5AttributeName* DEFINITIONURL;
    static nsHtml5AttributeName* GRADIENTUNITS;
    static nsHtml5AttributeName* FLOOD_OPACITY;
    static nsHtml5AttributeName* ONAFTERUPDATE;
    static nsHtml5AttributeName* ONERRORUPDATE;
    static nsHtml5AttributeName* ONBEFOREPASTE;
    static nsHtml5AttributeName* ONLOSECAPTURE;
    static nsHtml5AttributeName* ONCONTEXTMENU;
    static nsHtml5AttributeName* ONSELECTSTART;
    static nsHtml5AttributeName* ONBEFOREPRINT;
    static nsHtml5AttributeName* MOVABLELIMITS;
    static nsHtml5AttributeName* LINETHICKNESS;
    static nsHtml5AttributeName* UNICODE_RANGE;
    static nsHtml5AttributeName* THINMATHSPACE;
    static nsHtml5AttributeName* VERT_ORIGIN_X;
    static nsHtml5AttributeName* VERT_ORIGIN_Y;
    static nsHtml5AttributeName* V_IDEOGRAPHIC;
    static nsHtml5AttributeName* PRESERVEALPHA;
    static nsHtml5AttributeName* SCRIPTMINSIZE;
    static nsHtml5AttributeName* SPECIFICATION;
    static nsHtml5AttributeName* XLINK_ACTUATE;
    static nsHtml5AttributeName* XLINK_ARCROLE;
    static nsHtml5AttributeName* ACCEPT_CHARSET;
    static nsHtml5AttributeName* ALIGNMENTSCOPE;
    static nsHtml5AttributeName* ARIA_MULTILINE;
    static nsHtml5AttributeName* BASELINE_SHIFT;
    static nsHtml5AttributeName* HORIZ_ORIGIN_X;
    static nsHtml5AttributeName* HORIZ_ORIGIN_Y;
    static nsHtml5AttributeName* ONBEFOREUPDATE;
    static nsHtml5AttributeName* ONFILTERCHANGE;
    static nsHtml5AttributeName* ONROWSINSERTED;
    static nsHtml5AttributeName* ONBEFOREUNLOAD;
    static nsHtml5AttributeName* MATHBACKGROUND;
    static nsHtml5AttributeName* LETTER_SPACING;
    static nsHtml5AttributeName* LIGHTING_COLOR;
    static nsHtml5AttributeName* THICKMATHSPACE;
    static nsHtml5AttributeName* TEXT_RENDERING;
    static nsHtml5AttributeName* V_MATHEMATICAL;
    static nsHtml5AttributeName* POINTER_EVENTS;
    static nsHtml5AttributeName* PRIMITIVEUNITS;
    static nsHtml5AttributeName* SYSTEMLANGUAGE;
    static nsHtml5AttributeName* STROKE_LINECAP;
    static nsHtml5AttributeName* SUBSCRIPTSHIFT;
    static nsHtml5AttributeName* STROKE_OPACITY;
    static nsHtml5AttributeName* ARIA_DROPEFFECT;
    static nsHtml5AttributeName* ARIA_LABELLEDBY;
    static nsHtml5AttributeName* ARIA_TEMPLATEID;
    static nsHtml5AttributeName* COLOR_RENDERING;
    static nsHtml5AttributeName* CONTENTEDITABLE;
    static nsHtml5AttributeName* DIFFUSECONSTANT;
    static nsHtml5AttributeName* ONDATAAVAILABLE;
    static nsHtml5AttributeName* ONCONTROLSELECT;
    static nsHtml5AttributeName* IMAGE_RENDERING;
    static nsHtml5AttributeName* MEDIUMMATHSPACE;
    static nsHtml5AttributeName* TEXT_DECORATION;
    static nsHtml5AttributeName* SHAPE_RENDERING;
    static nsHtml5AttributeName* STROKE_LINEJOIN;
    static nsHtml5AttributeName* REPEAT_TEMPLATE;
    static nsHtml5AttributeName* ARIA_DESCRIBEDBY;
    static nsHtml5AttributeName* CONTENTSTYLETYPE;
    static nsHtml5AttributeName* FONT_SIZE_ADJUST;
    static nsHtml5AttributeName* KERNELUNITLENGTH;
    static nsHtml5AttributeName* ONBEFOREACTIVATE;
    static nsHtml5AttributeName* ONPROPERTYCHANGE;
    static nsHtml5AttributeName* ONDATASETCHANGED;
    static nsHtml5AttributeName* MASKCONTENTUNITS;
    static nsHtml5AttributeName* PATTERNTRANSFORM;
    static nsHtml5AttributeName* REQUIREDFEATURES;
    static nsHtml5AttributeName* RENDERING_INTENT;
    static nsHtml5AttributeName* SPECULAREXPONENT;
    static nsHtml5AttributeName* SPECULARCONSTANT;
    static nsHtml5AttributeName* SUPERSCRIPTSHIFT;
    static nsHtml5AttributeName* STROKE_DASHARRAY;
    static nsHtml5AttributeName* XCHANNELSELECTOR;
    static nsHtml5AttributeName* YCHANNELSELECTOR;
    static nsHtml5AttributeName* ARIA_AUTOCOMPLETE;
    static nsHtml5AttributeName* CONTENTSCRIPTTYPE;
    static nsHtml5AttributeName* ENABLE_BACKGROUND;
    static nsHtml5AttributeName* DOMINANT_BASELINE;
    static nsHtml5AttributeName* GRADIENTTRANSFORM;
    static nsHtml5AttributeName* ONBEFORDEACTIVATE;
    static nsHtml5AttributeName* ONDATASETCOMPLETE;
    static nsHtml5AttributeName* OVERLINE_POSITION;
    static nsHtml5AttributeName* ONBEFOREEDITFOCUS;
    static nsHtml5AttributeName* LIMITINGCONEANGLE;
    static nsHtml5AttributeName* VERYTHINMATHSPACE;
    static nsHtml5AttributeName* STROKE_DASHOFFSET;
    static nsHtml5AttributeName* STROKE_MITERLIMIT;
    static nsHtml5AttributeName* ALIGNMENT_BASELINE;
    static nsHtml5AttributeName* ONREADYSTATECHANGE;
    static nsHtml5AttributeName* OVERLINE_THICKNESS;
    static nsHtml5AttributeName* UNDERLINE_POSITION;
    static nsHtml5AttributeName* VERYTHICKMATHSPACE;
    static nsHtml5AttributeName* REQUIREDEXTENSIONS;
    static nsHtml5AttributeName* COLOR_INTERPOLATION;
    static nsHtml5AttributeName* UNDERLINE_THICKNESS;
    static nsHtml5AttributeName* PRESERVEASPECTRATIO;
    static nsHtml5AttributeName* PATTERNCONTENTUNITS;
    static nsHtml5AttributeName* ARIA_MULTISELECTABLE;
    static nsHtml5AttributeName* SCRIPTSIZEMULTIPLIER;
    static nsHtml5AttributeName* ARIA_ACTIVEDESCENDANT;
    static nsHtml5AttributeName* VERYVERYTHINMATHSPACE;
    static nsHtml5AttributeName* VERYVERYTHICKMATHSPACE;
    static nsHtml5AttributeName* STRIKETHROUGH_POSITION;
    static nsHtml5AttributeName* STRIKETHROUGH_THICKNESS;
    static nsHtml5AttributeName* EXTERNALRESOURCESREQUIRED;
    static nsHtml5AttributeName* GLYPH_ORIENTATION_VERTICAL;
    static nsHtml5AttributeName* COLOR_INTERPOLATION_FILTERS;
    static nsHtml5AttributeName* GLYPH_ORIENTATION_HORIZONTAL;
  private:
    static nsHtml5AttributeName** ATTRIBUTE_NAMES;
    #ifdef nsHtml5AttributeName_cpp__
    static PRInt32 ATTRIBUTE_HASHES_DATA[];
    #endif
    static jArray<PRInt32,PRInt32> ATTRIBUTE_HASHES;
  public:
    static void initializeStatics();
    static void releaseStatics();
};

#ifdef nsHtml5AttributeName_cpp__
PRInt32* nsHtml5AttributeName::ALL_NO_NS = nsnull;
PRInt32* nsHtml5AttributeName::XMLNS_NS = nsnull;
PRInt32* nsHtml5AttributeName::XML_NS = nsnull;
PRInt32* nsHtml5AttributeName::XLINK_NS = nsnull;
nsIAtom** nsHtml5AttributeName::ALL_NO_PREFIX = nsnull;
nsIAtom** nsHtml5AttributeName::XMLNS_PREFIX = nsnull;
nsIAtom** nsHtml5AttributeName::XLINK_PREFIX = nsnull;
nsIAtom** nsHtml5AttributeName::XML_PREFIX = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::D = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::K = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::R = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::X = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::Y = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::Z = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::BY = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::CX = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::CY = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::DX = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::DY = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::G2 = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::G1 = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::FX = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::FY = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::K4 = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::K2 = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::K3 = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::K1 = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ID = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::IN = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::U2 = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::U1 = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::RT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::RX = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::RY = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::TO = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::Y2 = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::Y1 = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::X1 = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::X2 = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ALT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::DIR = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::DUR = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::END = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::FOR = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::IN2 = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::MAX = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::MIN = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::LOW = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::REL = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::REV = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::SRC = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::AXIS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ABBR = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::BBOX = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::CITE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::CODE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::BIAS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::COLS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::CLIP = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::CHAR = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::BASE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::EDGE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::DATA = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::FILL = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::FROM = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::FORM = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::FACE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::HIGH = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::HREF = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::OPEN = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ICON = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::NAME = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::MODE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::MASK = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::LINK = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::LANG = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::LIST = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::TYPE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::WHEN = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::WRAP = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::TEXT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::PATH = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::PING = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::REFX = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::REFY = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::SIZE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::SEED = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ROWS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::SPAN = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::STEP = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ROLE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::XREF = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ASYNC = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ALINK = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ALIGN = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::CLOSE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::COLOR = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::CLASS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::CLEAR = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::BEGIN = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::DEPTH = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::DEFER = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::FENCE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::FRAME = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ISMAP = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONEND = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::INDEX = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ORDER = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::OTHER = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONCUT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::NARGS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::MEDIA = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::LABEL = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::LOCAL = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::WIDTH = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::TITLE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::VLINK = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::VALUE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::SLOPE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::SHAPE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::SCOPE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::SCALE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::SPEED = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::STYLE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::RULES = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::STEMH = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::STEMV = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::START = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::XMLNS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ACCEPT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ACCENT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ASCENT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ACTIVE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ALTIMG = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ACTION = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::BORDER = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::CURSOR = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::COORDS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::FILTER = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::FORMAT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::HIDDEN = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::HSPACE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::HEIGHT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONMOVE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONLOAD = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONDRAG = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ORIGIN = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONZOOM = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONHELP = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONSTOP = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONDROP = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONBLUR = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::OBJECT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::OFFSET = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ORIENT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONCOPY = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::NOWRAP = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::NOHREF = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::MACROS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::METHOD = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::LOWSRC = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::LSPACE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::LQUOTE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::USEMAP = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::WIDTHS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::TARGET = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::VALUES = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::VALIGN = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::VSPACE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::POSTER = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::POINTS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::PROMPT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::SCOPED = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::STRING = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::SCHEME = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::STROKE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::RADIUS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::RESULT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::REPEAT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::RSPACE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ROTATE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::RQUOTE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ALTTEXT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ARCHIVE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::AZIMUTH = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::CLOSURE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::CHECKED = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::CLASSID = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::CHAROFF = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::BGCOLOR = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::COLSPAN = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::CHARSET = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::COMPACT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::CONTENT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ENCTYPE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::DATASRC = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::DATAFLD = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::DECLARE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::DISPLAY = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::DIVISOR = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::DEFAULT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::DESCENT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::KERNING = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::HANGING = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::HEADERS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONPASTE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONCLICK = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::OPTIMUM = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONBEGIN = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONKEYUP = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONFOCUS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONERROR = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONINPUT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONABORT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONSTART = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONRESET = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::OPACITY = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::NOSHADE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::MINSIZE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::MAXSIZE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::LOOPEND = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::LARGEOP = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::UNICODE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::TARGETX = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::TARGETY = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::VIEWBOX = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::VERSION = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::PATTERN = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::PROFILE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::SPACING = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::RESTART = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ROWSPAN = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::SANDBOX = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::SUMMARY = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::STANDBY = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::REPLACE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::AUTOPLAY = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ADDITIVE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::CALCMODE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::CODETYPE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::CODEBASE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::CONTROLS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::BEVELLED = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::BASELINE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::EXPONENT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::EDGEMODE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ENCODING = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::GLYPHREF = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::DATETIME = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::DISABLED = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::FONTSIZE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::KEYTIMES = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::PANOSE_1 = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::HREFLANG = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONRESIZE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONCHANGE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONBOUNCE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONUNLOAD = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONFINISH = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONSCROLL = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::OPERATOR = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::OVERFLOW = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONSUBMIT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONREPEAT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONSELECT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::NOTATION = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::NORESIZE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::MANIFEST = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::MATHSIZE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::MULTIPLE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::LONGDESC = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::LANGUAGE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::TEMPLATE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::TABINDEX = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::READONLY = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::SELECTED = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ROWLINES = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::SEAMLESS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ROWALIGN = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::STRETCHY = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::REQUIRED = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::XML_BASE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::XML_LANG = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::X_HEIGHT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ARIA_OWNS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::AUTOFOCUS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ARIA_SORT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ACCESSKEY = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ARIA_BUSY = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ARIA_GRAB = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::AMPLITUDE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ARIA_LIVE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::CLIP_RULE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::CLIP_PATH = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::EQUALROWS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ELEVATION = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::DIRECTION = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::DRAGGABLE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::FILTERRES = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::FILL_RULE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::FONTSTYLE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::FONT_SIZE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::KEYPOINTS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::HIDEFOCUS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONMESSAGE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::INTERCEPT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONDRAGEND = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONMOVEEND = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONINVALID = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONKEYDOWN = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONFOCUSIN = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONMOUSEUP = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::INPUTMODE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONROWEXIT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::MATHCOLOR = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::MASKUNITS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::MAXLENGTH = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::LINEBREAK = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::LOOPSTART = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::TRANSFORM = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::V_HANGING = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::VALUETYPE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::POINTSATZ = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::POINTSATX = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::POINTSATY = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::PLAYCOUNT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::SYMMETRIC = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::SCROLLING = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::REPEATDUR = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::SELECTION = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::SEPARATOR = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::XML_SPACE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::AUTOSUBMIT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ALPHABETIC = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ACTIONTYPE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ACCUMULATE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ARIA_LEVEL = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::COLUMNSPAN = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::CAP_HEIGHT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::BACKGROUND = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::GLYPH_NAME = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::GROUPALIGN = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::FONTFAMILY = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::FONTWEIGHT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::FONT_STYLE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::KEYSPLINES = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::HTTP_EQUIV = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONACTIVATE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::OCCURRENCE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::IRRELEVANT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONDBLCLICK = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONDRAGDROP = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONKEYPRESS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONROWENTER = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONDRAGOVER = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONFOCUSOUT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONMOUSEOUT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::NUMOCTAVES = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::MARKER_MID = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::MARKER_END = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::TEXTLENGTH = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::VISIBILITY = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::VIEWTARGET = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::VERT_ADV_Y = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::PATHLENGTH = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::REPEAT_MAX = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::RADIOGROUP = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::STOP_COLOR = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::SEPARATORS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::REPEAT_MIN = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ROWSPACING = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ZOOMANDPAN = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::XLINK_TYPE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::XLINK_ROLE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::XLINK_HREF = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::XLINK_SHOW = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ACCENTUNDER = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ARIA_SECRET = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ARIA_ATOMIC = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ARIA_HIDDEN = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ARIA_FLOWTO = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ARABIC_FORM = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::CELLPADDING = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::CELLSPACING = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::COLUMNWIDTH = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::COLUMNALIGN = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::COLUMNLINES = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::CONTEXTMENU = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::BASEPROFILE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::FONT_FAMILY = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::FRAMEBORDER = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::FILTERUNITS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::FLOOD_COLOR = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::FONT_WEIGHT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::HORIZ_ADV_X = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONDRAGLEAVE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONMOUSEMOVE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ORIENTATION = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONMOUSEDOWN = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONMOUSEOVER = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONDRAGENTER = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::IDEOGRAPHIC = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONBEFORECUT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONFORMINPUT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONDRAGSTART = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONMOVESTART = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::MARKERUNITS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::MATHVARIANT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::MARGINWIDTH = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::MARKERWIDTH = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::TEXT_ANCHOR = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::TABLEVALUES = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::SCRIPTLEVEL = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::REPEATCOUNT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::STITCHTILES = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::STARTOFFSET = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::SCROLLDELAY = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::XMLNS_XLINK = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::XLINK_TITLE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ARIA_INVALID = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ARIA_PRESSED = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ARIA_CHECKED = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::AUTOCOMPLETE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ARIA_SETSIZE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ARIA_CHANNEL = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::EQUALCOLUMNS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::DISPLAYSTYLE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::DATAFORMATAS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::FILL_OPACITY = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::FONT_VARIANT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::FONT_STRETCH = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::FRAMESPACING = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::KERNELMATRIX = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONDEACTIVATE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONROWSDELETE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONMOUSELEAVE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONFORMCHANGE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONCELLCHANGE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONMOUSEWHEEL = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONMOUSEENTER = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONAFTERPRINT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONBEFORECOPY = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::MARGINHEIGHT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::MARKERHEIGHT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::MARKER_START = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::MATHEMATICAL = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::LENGTHADJUST = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::UNSELECTABLE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::UNICODE_BIDI = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::UNITS_PER_EM = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::WORD_SPACING = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::WRITING_MODE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::V_ALPHABETIC = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::PATTERNUNITS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::SPREADMETHOD = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::SURFACESCALE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::STROKE_WIDTH = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::REPEAT_START = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::STDDEVIATION = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::STOP_OPACITY = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ARIA_CONTROLS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ARIA_HASPOPUP = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ACCENT_HEIGHT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ARIA_VALUENOW = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ARIA_RELEVANT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ARIA_POSINSET = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ARIA_VALUEMAX = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ARIA_READONLY = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ARIA_SELECTED = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ARIA_REQUIRED = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ARIA_EXPANDED = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ARIA_DISABLED = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ATTRIBUTETYPE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ATTRIBUTENAME = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ARIA_DATATYPE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ARIA_VALUEMIN = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::BASEFREQUENCY = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::COLUMNSPACING = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::COLOR_PROFILE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::CLIPPATHUNITS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::DEFINITIONURL = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::GRADIENTUNITS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::FLOOD_OPACITY = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONAFTERUPDATE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONERRORUPDATE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONBEFOREPASTE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONLOSECAPTURE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONCONTEXTMENU = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONSELECTSTART = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONBEFOREPRINT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::MOVABLELIMITS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::LINETHICKNESS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::UNICODE_RANGE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::THINMATHSPACE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::VERT_ORIGIN_X = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::VERT_ORIGIN_Y = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::V_IDEOGRAPHIC = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::PRESERVEALPHA = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::SCRIPTMINSIZE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::SPECIFICATION = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::XLINK_ACTUATE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::XLINK_ARCROLE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ACCEPT_CHARSET = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ALIGNMENTSCOPE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ARIA_MULTILINE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::BASELINE_SHIFT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::HORIZ_ORIGIN_X = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::HORIZ_ORIGIN_Y = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONBEFOREUPDATE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONFILTERCHANGE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONROWSINSERTED = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONBEFOREUNLOAD = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::MATHBACKGROUND = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::LETTER_SPACING = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::LIGHTING_COLOR = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::THICKMATHSPACE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::TEXT_RENDERING = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::V_MATHEMATICAL = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::POINTER_EVENTS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::PRIMITIVEUNITS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::SYSTEMLANGUAGE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::STROKE_LINECAP = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::SUBSCRIPTSHIFT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::STROKE_OPACITY = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ARIA_DROPEFFECT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ARIA_LABELLEDBY = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ARIA_TEMPLATEID = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::COLOR_RENDERING = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::CONTENTEDITABLE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::DIFFUSECONSTANT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONDATAAVAILABLE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONCONTROLSELECT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::IMAGE_RENDERING = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::MEDIUMMATHSPACE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::TEXT_DECORATION = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::SHAPE_RENDERING = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::STROKE_LINEJOIN = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::REPEAT_TEMPLATE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ARIA_DESCRIBEDBY = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::CONTENTSTYLETYPE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::FONT_SIZE_ADJUST = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::KERNELUNITLENGTH = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONBEFOREACTIVATE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONPROPERTYCHANGE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONDATASETCHANGED = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::MASKCONTENTUNITS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::PATTERNTRANSFORM = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::REQUIREDFEATURES = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::RENDERING_INTENT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::SPECULAREXPONENT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::SPECULARCONSTANT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::SUPERSCRIPTSHIFT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::STROKE_DASHARRAY = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::XCHANNELSELECTOR = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::YCHANNELSELECTOR = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ARIA_AUTOCOMPLETE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::CONTENTSCRIPTTYPE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ENABLE_BACKGROUND = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::DOMINANT_BASELINE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::GRADIENTTRANSFORM = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONBEFORDEACTIVATE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONDATASETCOMPLETE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::OVERLINE_POSITION = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONBEFOREEDITFOCUS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::LIMITINGCONEANGLE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::VERYTHINMATHSPACE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::STROKE_DASHOFFSET = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::STROKE_MITERLIMIT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ALIGNMENT_BASELINE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ONREADYSTATECHANGE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::OVERLINE_THICKNESS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::UNDERLINE_POSITION = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::VERYTHICKMATHSPACE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::REQUIREDEXTENSIONS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::COLOR_INTERPOLATION = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::UNDERLINE_THICKNESS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::PRESERVEASPECTRATIO = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::PATTERNCONTENTUNITS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ARIA_MULTISELECTABLE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::SCRIPTSIZEMULTIPLIER = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::ARIA_ACTIVEDESCENDANT = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::VERYVERYTHINMATHSPACE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::VERYVERYTHICKMATHSPACE = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::STRIKETHROUGH_POSITION = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::STRIKETHROUGH_THICKNESS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::EXTERNALRESOURCESREQUIRED = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::GLYPH_ORIENTATION_VERTICAL = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::COLOR_INTERPOLATION_FILTERS = nsnull;
nsHtml5AttributeName* nsHtml5AttributeName::GLYPH_ORIENTATION_HORIZONTAL = nsnull;
nsHtml5AttributeName** nsHtml5AttributeName::ATTRIBUTE_NAMES = nsnull;
PRInt32 nsHtml5AttributeName::ATTRIBUTE_HASHES_DATA[] = { 1153, 1383, 1601, 1793, 1827, 1857, 68600, 69146, 69177, 70237, 70270, 71572, 71669, 72415, 72444, 74846, 74904, 74943, 75001, 75276, 75590, 84742, 84839, 85575, 85963, 85992, 87204, 88074, 88171, 89130, 89163, 3207892, 3283895, 3284791, 3338752, 3358197, 3369562, 3539124, 3562402, 3574260, 3670335, 3696933, 3721879, 135280021, 135346322, 136317019, 136475749, 136548517, 136652214, 136884919, 136902418, 136942992, 137292068, 139120259, 139785574, 142250603, 142314056, 142331176, 142519584, 144752417, 145106895, 146147200, 146765926, 148805544, 149655723, 149809441, 150018784, 150445028, 150923321, 152528754, 152536216, 152647366, 152962785, 155219321, 155654904, 157317483, 157350248, 157437941, 157447478, 157604838, 157685404, 157894402, 158315188, 166078431, 169409980, 169700259, 169856932, 170007032, 170409695, 170466488, 170513710, 170608367, 173028944, 173896963, 176090625, 176129212, 179390001, 179489057, 179627464, 179840468, 179849042, 180004216, 181779081, 183027151, 183645319, 183698797, 185922012, 185997252, 188312483, 188675799, 190977533, 190992569, 191006194, 191033518, 191038774, 191096249, 191166163, 191194426, 191522106, 191568039, 200104642, 202506661, 202537381, 202602917, 203070590, 203120766, 203389054, 203690071, 203971238, 203986524, 209040857, 209125756, 212055489, 212322418, 212746849, 213002877, 213055164, 213088023, 213259873, 213273386, 213435118, 213437318, 213438231, 213493071, 213532268, 213542834, 213584431, 213659891, 215285828, 215880731, 216112976, 216684637, 217369699, 217565298, 217576549, 218186795, 219743185, 220082234, 221623802, 221986406, 222283890, 223089542, 223138630, 223311265, 224547358, 224587256, 224589550, 224655650, 224785518, 224810917, 224813302, 225429618, 225432950, 225440869, 236107233, 236709921, 236838947, 237117095, 237143271, 237172455, 237209953, 237354143, 237372743, 237668065, 237703073, 237714273, 239743521, 240512803, 240522627, 240560417, 240656513, 241015715, 241062755, 241065383, 243523041, 245865199, 246261793, 246556195, 246774817, 246923491, 246928419, 246981667, 247014847, 247058369, 247112833, 247118177, 247119137, 247128739, 247316903, 249533729, 250235623, 250269543, 251083937, 251402351, 252339047, 253260911, 253293679, 254844367, 255547879, 256077281, 256345377, 258124199, 258354465, 258605063, 258744193, 258845603, 258856961, 258926689, 269869248, 270174334, 270709417, 270778994, 270781796, 271102503, 271478858, 271490090, 272870654, 273335275, 273369140, 273924313, 274108530, 274116736, 276818662, 277476156, 279156579, 279349675, 280108533, 280128712, 280132869, 280162403, 280280292, 280413430, 280506130, 280677397, 280678580, 280686710, 280689066, 282736758, 283110901, 283275116, 283823226, 283890012, 284479340, 284606461, 286700477, 286798916, 291557706, 291665349, 291804100, 292138018, 292166446, 292418738, 292451039, 300298041, 300374839, 300597935, 303073389, 303083839, 303266673, 303354997, 303430688, 303576261, 303724281, 303819694, 304242723, 304382625, 306247792, 307227811, 307468786, 307724489, 309671175, 310252031, 310358241, 310373094, 311015256, 313357609, 313683893, 313701861, 313706996, 313707317, 313710350, 314027746, 314038181, 314091299, 314205627, 314233813, 316741830, 316797986, 317486755, 317794164, 318721061, 320076137, 322657125, 322887778, 323506876, 323572412, 323605180, 323938869, 325060058, 325320188, 325398738, 325541490, 325671619, 333868843, 336806130, 337212108, 337282686, 337285434, 337585223, 338036037, 338298087, 338566051, 340943551, 341190970, 342995704, 343352124, 343912673, 344585053, 346977248, 347218098, 347262163, 347278576, 347438191, 347655959, 347684788, 347726430, 347727772, 347776035, 347776629, 349500753, 350880161, 350887073, 353384123, 355496998, 355906922, 355979793, 356545959, 358637867, 358905016, 359164318, 359247286, 359350571, 359579447, 365560330, 367399355, 367420285, 367510727, 368013212, 370234760, 370353345, 370710317, 371074566, 371122285, 371194213, 371448425, 371448430, 371545055, 371596922, 371758751, 371964792, 372151328, 376550136, 376710172, 376795771, 376826271, 376906556, 380514830, 380774774, 380775037, 381030322, 381136500, 381281631, 381282269, 381285504, 381330595, 381331422, 381335911, 381336484, 383907298, 383917408, 384595009, 384595013, 387799894, 387823201, 392581647, 392584937, 392742684, 392906485, 393003349, 400644707, 400973830, 404428547, 404432113, 404432865, 404469244, 404478897, 404694860, 406887479, 408294949, 408789955, 410022510, 410467324, 410586448, 410945965, 411845275, 414327152, 414327932, 414329781, 414346257, 414346439, 414639928, 414835998, 414894517, 414986533, 417465377, 417465381, 417492216, 418259232, 419310946, 420103495, 420242342, 420380455, 420658662, 420717432, 423183880, 424539259, 425929170, 425972964, 426050649, 426126450, 426142833, 426607922, 437289840, 437347469, 437412335, 437423943, 437455540, 437462252, 437597991, 437617485, 437986305, 437986507, 437986828, 437987072, 438015591, 438034813, 438038966, 438179623, 438347971, 438483573, 438547062, 438895551, 441592676, 442032555, 443548979, 447881379, 447881655, 447881895, 447887844, 448416189, 448445746, 448449012, 450942191, 452816744, 453668677, 454434495, 456610076, 456642844, 456738709, 457544600, 459451897, 459680944, 468058810, 468083581, 470964084, 471470955, 471567278, 472267822, 481177859, 481210627, 481435874, 481455115, 481485378, 481490218, 485105638, 486005878, 486383494, 487988916, 488103783, 490661867, 491574090, 491578272, 493041952, 493441205, 493582844, 493716979, 504577572, 504740359, 505091638, 505592418, 505656212, 509516275, 514998531, 515571132, 515594682, 518712698, 521362273, 526592419, 526807354, 527348842, 538294791, 539214049, 544689535, 545535009, 548544752, 548563346, 548595116, 551679010, 558034099, 560329411, 560356209, 560671018, 560671152, 560692590, 560845442, 569212097, 569474241, 572252718, 572768481, 575326764, 576174758, 576190819, 582099184, 582099438, 582372519, 582558889, 586552164, 591325418, 594231990, 594243961, 605711268, 615672071, 616086845, 621792370, 624879850, 627432831, 640040548, 654392808, 658675477, 659420283, 672891587, 694768102, 705890982, 725543146, 759097578, 761686526, 795383908, 843809551, 878105336, 908643300, 945213471 };
jArray<PRInt32,PRInt32> nsHtml5AttributeName::ATTRIBUTE_HASHES = J_ARRAY_STATIC(PRInt32, PRInt32, ATTRIBUTE_HASHES_DATA);
#endif

#define NS_HTML5ATTRIBUTE_NAME_HTML 0
#define NS_HTML5ATTRIBUTE_NAME_MATHML 1
#define NS_HTML5ATTRIBUTE_NAME_SVG 2


#endif

