/* -*- Mode: IDL; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "domstubs.idl"

interface nsIDOMSVGPathSeg;

[scriptable, uuid(1e4efb5c-7b0f-4338-a92e-6ca5402b303c)]
interface nsIDOMSVGPathSegList : nsISupports
{ 
  readonly attribute unsigned long numberOfItems;
  readonly attribute unsigned long length;  // synonym for numberOfItems

  void clear();
          // raises(nsIDOMDOMException);
  nsIDOMSVGPathSeg initialize(in nsIDOMSVGPathSeg newItem );
                    // raises(nsIDOMDOMException, nsIDOMSVGException);
  nsIDOMSVGPathSeg getItem(in unsigned long index);
                    // raises(nsIDOMDOMException);
  [getter,noscript,notxpcom,nostdcall] nsIDOMSVGPathSeg getItemAt(in unsigned long index);
  nsIDOMSVGPathSeg insertItemBefore(in nsIDOMSVGPathSeg newItem, in unsigned long index);
                    // raises(nsIDOMDOMException, nsIDOMSVGException);
  nsIDOMSVGPathSeg replaceItem(in nsIDOMSVGPathSeg newItem, in unsigned long index);
                    // raises(nsIDOMDOMException, nsIDOMSVGException);
  nsIDOMSVGPathSeg removeItem(in unsigned long index);
                    // raises(nsIDOMDOMException);
  nsIDOMSVGPathSeg appendItem(in nsIDOMSVGPathSeg newItem);
                    // raises(nsIDOMDOMException, nsIDOMSVGException);
};
