/* -*- Mode: IDL; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsIDOMSVGElement.idl"

[scriptable, uuid(26BF6187-A720-47AA-B453-DEFB98FF433C)]
interface nsIDOMSVGAnimationElement
  : nsIDOMSVGElement
/*
        The SVG DOM makes use of multiple interface inheritance.
        Since XPCOM only supports single interface inheritance,
        the best thing that we can do is to promise that whenever
        an object implements _this_ interface it will also
        implement the following interfaces. (We then have to QI to
        hop between them.)
        
    nsIDOMSVGTests,
    nsIDOMSVGExternalResourcesRequired,
    smil::nsIDOMElementTimeControl,
    events::nsIDOMEventTarget
*/
{ 
  readonly attribute nsIDOMSVGElement targetElement;
  float getStartTime();
      // raises ( DOMException )
  float getCurrentTime();
  float getSimpleDuration();
      // raises ( DOMException )
};
