/* -*- Mode: IDL; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "domstubs.idl"

interface nsIDOMSVGMatrix;

[scriptable, uuid(45f18f8f-1315-4447-a7d5-8aeca77bdcaf)]
interface nsIDOMSVGPoint : nsISupports
{
  attribute float x;
      // raises DOMException on setting
  attribute float y;
      // raises DOMException on setting

  nsIDOMSVGPoint matrixTransform(in nsIDOMSVGMatrix matrix);
};
