interface XULPopupElement : XULElement {
/* IID: { 0x8fefe4a1, 0xd334, 0x11d3, \
    {0xbf, 0x87, 0x0, 0x10, 0x5a, 0x1b, 0x6, 0x27} } */

  void openPopup(in Element element,
                 in long xPos, in long yPos, 
                 in DOMString popupType, in DOMString anchorAlignment,
                 in DOMString popupAlignment);

  void closePopup();
};

