From: Mozilla <info@netscape.com>
Date: Sat, 20 Apr 1996 00:07:11 -0700 (PDT)
MIME-Version: 1.0
Content-Type: text/html; charset=us-ascii
Subject: Welcome!
Message-ID: <30666242nsintro@netscape.com>

<HEAD>
<BASE HREF="http://home.netscape.com/">
<TITLE>Welcome to Netscape</TITLE>
</HEAD>
<BODY>

<HR SIZE=4 WIDTH="50%">
<CENTER>
<FONT SIZE="+1">Welcome to<BR></FONT>
<FONT SIZE="+2"><B>Netscape Mail</B><SUP><FONT SIZE="-1">TM</FONT></SUP></FONT>
</CENTER>
<HR SIZE=4 WIDTH="50%">

<P>
<FONT SIZE="+1">Netscape's integrated email presents messages with the
familiar formatting, images, and links of World Wide Web pages.
</FONT>

<P><BR>

  <DL>
      <IMG SRC="about:logo" ALT="N E T S C A P E"
           ALIGN=RIGHT HSPACE=10 VSPACE=20>
    <DT>
    <FONT SIZE="+2">Features in Brief</FONT>
    <UL>
      <LI>Use the toolbar to quickly browse and reply to messages.
      <LI>Use menu items for the complete range of mail features.
      <LI>Create all messages in <B>Message Composition</B> windows,
          which are created with the various <B>Reply</B> commands.
      <LI>From the Message Composition window, use the <B>Options</B>
          menu to choose <I>immediate</I> or <I>deferred</I> delivery.
      <LI>Drag and drop messages into folders to organize your mail.
      <LI>Click on column headings to sort messages.
      <LI>Drag column headings to reorder their presentation.
      <LI>Click-and-drag on the space between column headings to change
          the relative sizes of the columns.
      <LI>Click the Mail icon in the lower right of any Netscape window
          to check for new messages.
      <LI>Choose <B>Address Book</B> from the <B>Windows</B> menu to
          store and access your addresses.
      <LI>Choose <B>Mail and News</B> from the <B>Options</B> menu to 
          set your preferences.
    </UL>

  <P>
  <DT>
    <FONT SIZE="+2">Learn More about Netscape Mail</FONT>
    <DD>
    The <A HREF="/eng/mozilla/3.0/handbook/">Netscape Navigator Handbook</A>
    offers tutorial and reference information on 
    <A HREF="/eng/mozilla/3.0/handbook/docs/mnb.html#C0">mail features</A>. 
    Take advantage of the Handbook's 
    <A HREF="/eng/mozilla/3.0/handbook/docs/atoz.html#M">index</A>
    for quick access to the topics that interest you.

    <P>Unix users, especially those who use <B>procmail</B>, should 
    be sure to read 
    <A HREF="/eng/mozilla/2.0/relnotes/demo/movemail.html">this document</A>,
    which explains some important Unix-<WBR>system-<WBR>dependent issues about
    file locking, which are important to understand to avoid losing mail.

  <P>
  <DT>
    <FONT SIZE="+2">Supplemental Resources</FONT>
    <DD>
    [<A HREF="/eng/mozilla/3.0/faq.html">FAQs</A> 
    | <A HREF="/assist/support/index.html">Support Pages</A>
    | <A HREF="/assist/support/client/tn/index.html">Navigator Technical Notes</A> 
    | <A HREF="snews://secnews.netscape.com/netscape.navigator">Navigator User Group</A>]
  </DL>

<HR SIZE=4 WIDTH="80%">
<P>
</BODY>

