/* -*- Mode: IDL; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

[scriptable, uuid(11e0176a-4a2d-4a90-8dcc-1590eeb1769d)]
interface nsINotificationsList : nsISupports
{
    /**
     * Adds a notification to the registration dictionary.
     *
     * @param aName The name of the notification we might be sending.
     * @param aEnabled Indicates if the notification is enabled by default.
     */
    void addNotification(in AString aName, in boolean aEnabled);

    /**
     * Checks to see if a paticular notification has already been registered.
     *
     * @param aName The name of the notification we are checking against.
     */
    boolean isNotification(in AString aName);
};

