%filter substitution

%define loweredShadow 0 1px rgba(255, 255, 255, .4)
%define focusRingShadow 0 0 1px -moz-mac-focusring inset, 0 0 4px 1px -moz-mac-focusring, 0 0 1.5px 1px -moz-mac-focusring
%define yosemiteFocusRingShadow 0 0 0 0.5px -moz-mac-focusring inset, 0 0 0 2px -moz-mac-focusring

%define roundButtonBorder 1px solid rgba(0,0,0,.35)
%define roundButtonBackground linear-gradient(#f6f6f6, #e9e9e9)
%define roundButtonShadow 0 1px rgba(255,255,255,.5), inset 0 1px 1px rgba(255,255,255,.5)
%define roundButtonPressedBackground #dadada
%define roundButtonPressedShadow 0 1px rgba(255,255,255,.4), inset 0 1px 3px rgba(0,0,0,.2)

%define scopeBarBackground linear-gradient(#E8E8E8, #D0D0D0) repeat-x
%define scopeBarSeparatorBorder 1px solid #888
%define scopeBarTitleColor #6D6D6D

%define sidebarItemBorderTop 1px solid #bcc5d5
%define sidebarItemBorderBottom 1px solid #94a1b9
%define sidebarItemBackground linear-gradient(#c3ccdf 1px, #bdc7db 2px, #9dabc5)
%define sidebarItemFocusedBorderTop 1px solid #61a6dd
%define sidebarItemFocusedBorderBottom 1px solid #387cc0
%define sidebarItemFocusedBackground linear-gradient(#79bbe6 1px, #6eb2e3 2px, #3f8ad2)
%define sidebarItemGraphiteBorderTop 1px solid #a9b5c1
%define sidebarItemGraphiteBorderBottom 1px solid #8594a4
%define sidebarItemGraphiteBackground linear-gradient(#bfcad3 1px, #b6c2cc 2px, #94a1b1)
%define sidebarItemGraphiteFocusedBorderTop 1px solid #7c8c9d
%define sidebarItemGraphiteFocusedBorderBottom 1px solid #536c83
%define sidebarItemGraphiteFocusedBackground linear-gradient(#9eacbb 1px, #8fa1b1 2px, #587087)

%define sidebarItemBackgroundYosemite hsla(0,0%,0%,.1)
%define sidebarItemFocusedBackgroundYosemite #2d8cf9
%define sidebarItemGraphiteBackgroundYosemite hsla(0,0%,0%,.1)
%define sidebarItemGraphiteFocusedBackgroundYosemite #86858c

%define toolbarbuttonCornerRadius 3px
%define toolbarbuttonBackground linear-gradient(#FFF, #ADADAD) repeat-x
%define toolbarbuttonPressedInnerShadow inset rgba(0, 0, 0, 0.3) 0 -6px 10px, inset #000 0 1px 3px, inset rgba(0, 0, 0, 0.2) 0 1px 3px
%define toolbarbuttonInactiveBorderColor rgba(146, 146, 146, 0.84)
