%filter substitution

%define roundButtonBorderWidth 1px
%define roundButtonBorderStyle solid
%define roundButtonBorderColor rgba(0,0,0,.35)
%define roundButtonColor black
%define roundButtonBackgroundImage linear-gradient(#f6f6f6, #e9e9e9)
%define roundButtonShadow 0 1px rgba(255,255,255,.5), inset 0 1px 1px rgba(255,255,255,.5)
%define roundButtonPressedBackgroundImage linear-gradient(#dadada, #dadada)
%define roundButtonPressedShadow 0 1px rgba(255,255,255,.4), inset 0 1px 3px rgba(0,0,0,.2)
