%filter substitution

%define loweredShadow 0 1px rgba(255, 255, 255, .4)
%define focusRingShadow 0 0 1px -moz-mac-focusring inset, 0 0 4px 1px -moz-mac-focusring, 0 0 1.5px 1px -moz-mac-focusring

%define roundButtonBorder 1px solid rgba(0,0,0,.35)
%define roundButtonBackground linear-gradient(#f6f6f6, #e9e9e9)
%define roundButtonShadow 0 1px rgba(255,255,255,.5), inset 0 1px 1px rgba(255,255,255,.5)
%define roundButtonPressedBackground #dadada
%define roundButtonPressedShadow 0 1px rgba(255,255,255,.4), inset 0 1px 3px rgba(0,0,0,.2)

%define scopeBarBackground linear-gradient(#E8E8E8, #D0D0D0) repeat-x
%define scopeBarSeparatorBorder 1px solid #888
%define scopeBarTitleColor #6D6D6D

%define sidebarItemBorderTop 1px solid #94A1C0
%define sidebarItemBackground linear-gradient(#A0B0CF, #7386AB) repeat-x
%define sidebarItemFocusedBorderTop 1px solid #5382C5
%define sidebarItemFocusedBackground linear-gradient(#6494D4, #2559AC) repeat-x
%define sidebarItemGraphiteBorderTop 1px solid #97A4B1
%define sidebarItemGraphiteBackground linear-gradient(#AAB7C4, #8393A4) repeat-x
%define sidebarItemGraphiteFocusedBorderTop 1px solid #6B798D
%define sidebarItemGraphiteFocusedBackground linear-gradient(#8293A6, #425972) repeat-x
%define sidebarItemInactiveBorderTop 1px solid #979797
%define sidebarItemInactiveBackground linear-gradient(#B4B4B4, #8A8A8A) repeat-x

%define toolbarbuttonCornerRadius 3px
%define toolbarbuttonBackground linear-gradient(#FFF, #ADADAD) repeat-x
%define toolbarbuttonPressedInnerShadow inset rgba(0, 0, 0, 0.3) 0 -6px 10px, inset #000 0 1px 3px, inset rgba(0, 0, 0, 0.2) 0 1px 3px
%define toolbarbuttonInactiveBorderColor rgba(146, 146, 146, 0.84)
