/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "domstubs.idl"

[scriptable, function, uuid(42692976-57fd-4bb4-ab95-2b97ebdc5056)]
interface nsIDOMSystemMessageCallback : nsISupports
{
    void handleMessage(in jsval message);
};

[scriptable, uuid(d04d3c11-26aa-46eb-a981-353af101f9cf)]
interface nsIDOMNavigatorSystemMessages : nsISupports
{
    void mozSetMessageHandler(in DOMString type, in nsIDOMSystemMessageCallback callback);

    boolean mozHasPendingMessage(in DOMString type); 

    // the parameter is a promise object.
    void mozSetMessageHandlerPromise(in nsISupports promise);

    bool mozIsHandlingMessage();
};
