/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* ***** BEGIN LICENSE BLOCK *****
 * Version: NPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Netscape Public License
 * Version 1.1 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 * http://www.mozilla.org/NPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is mozilla.org code.
 *
 * The Initial Developer of the Original Code is 
 * Netscape Communications Corporation.
 * Portions created by the Initial Developer are Copyright (C) 1999
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or 
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the NPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the NPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */

#include "MailNewsTypes2.idl"
#include "nsIMsgFolder.idl"

interface nsIMsgHeaderParser;

%{C++
#include "nsIMsgHeaderParser.h"
%}
interface nsIMsgDatabase;
interface nsIMsgDBHdr;

[scriptable, uuid(5fe70a74-304e-11d3-9be1-00a0c900d445)]

interface nsMsgSearchScope {
    const nsMsgSearchScopeValue offlineMail = 0;
    const nsMsgSearchScopeValue onlineMail = 1;
    const nsMsgSearchScopeValue onlineMailFilter = 2;
    const nsMsgSearchScopeValue localNews = 3;
    const nsMsgSearchScopeValue news = 4;
    const nsMsgSearchScopeValue newsEx = 5;
    const nsMsgSearchScopeValue LDAP = 6;
    const nsMsgSearchScopeValue allSearchableGroups = 7;
};

typedef long nsMsgSearchAttribValue;

[scriptable, uuid(68c8710a-304e-11d3-97bf-00a0c900d445)]
interface nsMsgSearchAttrib {

    const nsMsgSearchAttribValue Subject = 0;	/* mail and news */
    const nsMsgSearchAttribValue Sender = 1;   
    const nsMsgSearchAttribValue Body = 2;	
    const nsMsgSearchAttribValue Date = 3;	

    const nsMsgSearchAttribValue Priority = 4;	    /* mail only */
    const nsMsgSearchAttribValue MsgStatus = 5;	
    const nsMsgSearchAttribValue To = 6;
    const nsMsgSearchAttribValue CC = 7;
    const nsMsgSearchAttribValue ToOrCC = 8;

    const nsMsgSearchAttribValue CommonName = 9;   /* LDAP only */
    const nsMsgSearchAttribValue RFC822Address = 10;	
    const nsMsgSearchAttribValue PhoneNumber = 11;
    const nsMsgSearchAttribValue Organization = 12;
    const nsMsgSearchAttribValue OrgUnit = 13;
    const nsMsgSearchAttribValue Locality = 14;
    const nsMsgSearchAttribValue StreetAddress = 15;
    const nsMsgSearchAttribValue Size = 16;
    const nsMsgSearchAttribValue AnyText = 17;      /* any header or body */
	const nsMsgSearchAttribValue Keywords = 18;

    const nsMsgSearchAttribValue DistinguishedName = 19; /* LDAP result elem only */
    const nsMsgSearchAttribValue ObjectClass = 20;       
    const nsMsgSearchAttribValue JpegFile = 21;

    const nsMsgSearchAttribValue Location = 22;          /* result list only */
    const nsMsgSearchAttribValue MessageKey = 23;        /* message result elems */

	const nsMsgSearchAttribValue AgeInDays = 24;    /* for purging old news articles */

	const nsMsgSearchAttribValue GivenName = 25;    /* for sorting LDAP results */
	const nsMsgSearchAttribValue Surname = 26; 

	const nsMsgSearchAttribValue FolderInfo = 27;	/* for "view thread context" from result */

	const nsMsgSearchAttribValue Custom1 = 28;		/* custom LDAP attributes */
	const nsMsgSearchAttribValue Custom2 = 29;
	const nsMsgSearchAttribValue Custom3 = 30;
	const nsMsgSearchAttribValue Custom4 = 31;
	const nsMsgSearchAttribValue Custom5 = 32;

	const nsMsgSearchAttribValue MessageId = 33; 
	/* the following are LDAP specific attributes */
	const nsMsgSearchAttribValue nsnMsgSearchAttribCarlicense = 34;
	const nsMsgSearchAttribValue BusinessCategory = 35;
	const nsMsgSearchAttribValue DepartmentNumber = 36;
	const nsMsgSearchAttribValue Description = 37;
	const nsMsgSearchAttribValue EmployeeType = 38;
	const nsMsgSearchAttribValue FaxNumber = 39;
	const nsMsgSearchAttribValue Manager = 40;
	const nsMsgSearchAttribValue PostalAddress = 41;
	const nsMsgSearchAttribValue PostalCode = 42;
	const nsMsgSearchAttribValue Secretary = 43;
	const nsMsgSearchAttribValue Title = 44;
	const nsMsgSearchAttribValue Nickname = 45;
	const nsMsgSearchAttribValue HomePhone = 46;
	const nsMsgSearchAttribValue Pager = 47;
	const nsMsgSearchAttribValue Cellular = 48;
    //49 is for showing customize... in ui headers start from 50 onwards up until 99.
	const nsMsgSearchAttribValue OtherHeader = 49;  /* for mail and news. MUST ALWAYS BE LAST attribute since we can have an arbitrary # of these... */

    const nsMsgSearchAttribValue kNumMsgSearchAttributes = 100;      /* must be last attribute */
};

/* NB: If you add elements to this enum, add only to the end, since 
 *     RULES.DAT stores enum values persistently
 */

typedef long nsMsgSearchOpValue;

[scriptable, uuid(82cc4518-304e-11d3-831d-00a0c900d445)]
interface nsMsgSearchOp {
    const nsMsgSearchOpValue Contains = 0; /* for text attributes      */
    const nsMsgSearchOpValue DoesntContain = 1;
    const nsMsgSearchOpValue Is = 2; /* is and isn't also apply to some non-text attrs */
    const nsMsgSearchOpValue Isnt = 3; 
    const nsMsgSearchOpValue IsEmpty = 4;

    const nsMsgSearchOpValue IsBefore = 5; /* for date attributes              */
    const nsMsgSearchOpValue IsAfter = 6;
    
    const nsMsgSearchOpValue IsHigherThan = 7; /* for priority. Is also applies  */
    const nsMsgSearchOpValue IsLowerThan = 8;

    const nsMsgSearchOpValue BeginsWith = 9;              
	const nsMsgSearchOpValue EndsWith = 10;

    const nsMsgSearchOpValue SoundsLike = 11; /* for LDAP phoenetic matching      */
	const nsMsgSearchOpValue LdapDwim = 12; /* Do What I Mean for simple search */

	const nsMsgSearchOpValue IsGreaterThan = 13;	
	const nsMsgSearchOpValue IsLessThan = 14;

	const nsMsgSearchOpValue NameCompletion = 15; /* Name Completion operator...as the name implies =) */
    const nsMsgSearchOpValue kNumMsgSearchOperators  = 16;     /* must be last operator */
};

typedef long nsMsgSearchWidgetValue;

/* FEs use this to help build the search dialog box */
[scriptable,uuid(903dd2e8-304e-11d3-92e6-00a0c900d445)]
interface nsMsgSearchWidget {
    const nsMsgSearchWidgetValue Text = 0;
    const nsMsgSearchWidgetValue Date = 1;
    const nsMsgSearchWidgetValue Menu = 2;
	const nsMsgSearchWidgetValue Int = 3;          /* added to account for age in days which requires an integer field */
    const nsMsgSearchWidgetValue None = 4;
};

typedef long nsMsgSearchTypeValue;


/* Used to specify type of search to be performed */
[scriptable,uuid(964b7f32-304e-11d3-ae13-00a0c900d445)]
interface nsMsgSearchType {
	const nsMsgSearchTypeValue None = 0;
	const nsMsgSearchTypeValue RootDSE = 1;
	const nsMsgSearchTypeValue Normal = 2;
	const nsMsgSearchTypeValue LdapVLV = 3;
	const nsMsgSearchTypeValue NameCompletion = 4;
};

typedef long nsMsgSearchBooleanOperator;
 
[scriptable, uuid(a37f3f4a-304e-11d3-8f94-00a0c900d445)]
interface nsMsgSearchBooleanOp {
    const nsMsgSearchBooleanOperator BooleanOR = 0;
    const nsMsgSearchBooleanOperator BooleanAND = 1;
};

/* Use this to specify the value of a search term */

[ptr] native nsMsgSearchValue(nsMsgSearchValue);

%{C++
typedef struct nsMsgSearchValue
{
    nsMsgSearchAttribValue attribute;
    union
    {
        nsMsgPriorityValue priority;
        PRTime date;
        PRUint32 msgStatus; /* see MSG_FLAG in msgcom.h */
        PRUint32 size;
        nsMsgKey key;
		PRUint32 age; /* in days */
		nsIMsgFolder *folder;
    } u;
    char *string;
} nsMsgSearchValue;
%}

[ptr] native nsMsgSearchTerm(nsMsgSearchTerm);

[ptr] native nsMsgDIRServer(nsMsgDIRServer);
%{C++
class nsMsgDIRServer;
%}


%{C++
#define IS_STRING_ATTRIBUTE(_a) \
(!(_a == nsMsgSearchAttrib::Priority || _a == nsMsgSearchAttrib::Date || \
   _a == nsMsgSearchAttrib::MsgStatus || _a == nsMsgSearchAttrib::MessageKey || \
   _a == nsMsgSearchAttrib::Size || _a == nsMsgSearchAttrib::AgeInDays || \
   _a == nsMsgSearchAttrib::FolderInfo || _a == nsMsgSearchAttrib::Location))
%}

[ptr] native nsSearchMenuItem(nsSearchMenuItem);

