/*
 * DO NOT EDIT.  THIS FILE IS GENERATED FROM nsIMsgSend.idl
 */

#ifndef __gen_nsIMsgSend_h__
#define __gen_nsIMsgSend_h__

THIS SHOULD NO LONGER BE USED BY ANYTHING IN MAILNEWS! THESE ARE GENERATED
FROM IDL! IF YOU ARE INCLUDING THIS FILE, THERE IS SOMETHING WRONG WITH THE
MAKEFILES FOR YOUR TREE

#endif /* __gen_nsIMsgSend_h__ */
