#! gmake
# The contents of this file are subject to the Netscape Public License
# Version 1.0 (the "NPL"); you may not use this file except in
# compliance with the NPL.  You may obtain a copy of the NPL at
# http://www.mozilla.org/NPL/
#
# Software distributed under the NPL is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the NPL
# for the specific language governing rights and limitations under the
# NPL.
#
# The Initial Developer of this code under the NPL is Netscape
# Communications Corporation.  Portions created by Netscape are
# Copyright (C) 1998 Netscape Communications Corporation.  All Rights
# Reserved.

ifdef MOZ_TREX
NS_DEPTH=../..
else
NS_DEPTH=..
endif

DEPTH = $(NS_DEPTH)

include $(NS_DEPTH)/config/config.mk

DIRS = src

CSRCS = julmain.c

include $(NS_DEPTH)/config/rules.mk
