#define VERSION_MAJOR  0
#define VERSION_MINOR  1
#define VERSION_PATCH  0
#define VERSION_EXTRA  ""
#define VERSION_PACKED ((VERSION_MAJOR<<16)|(VERSION_MINOR<<8)|(VERSION_PATCH))
#define VERSION_STRING_NOSP "v0.1.0"
#define VERSION_STRING      " v0.1.0"
