#!gmake
#
# The contents of this file are subject to the Netscape Public License
# Version 1.0 (the "NPL"); you may not use this file except in
# compliance with the NPL.  You may obtain a copy of the NPL at
# http://www.mozilla.org/NPL/
#
# Software distributed under the NPL is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the NPL
# for the specific language governing rights and limitations under the
# NPL.
#
# The Initial Developer of this code under the NPL is Netscape
# Communications Corporation.  Portions created by Netscape are
# Copyright (C) 1998 Netscape Communications Corporation.  All Rights
# Reserved.

DEPTH		= ../../../../..

PACKAGE		= netscape/softupdate

JSRCS		= FolderSpec.java \
		  InstallExecute.java \
		  InstallFile.java \
		  InstallPatch.java \
		  InstallObject.java \
		  ProgressDetails.java \
		  ProgressMediator.java \
		  ProgressWindow.java \
          RegEntryEnumerator.java \
          Registry.java \
          RegistryErrors.java \
          RegistryException.java \
          RegistryNode.java \
          RegKeyEnumerator.java \
		  SoftUpdateException.java \
		  SoftUpdateResourceBundle.java \
		  SoftwareUpdate.java \
		  Strings.java \
		  SymProgressDetails.java \
		  SymProgressWindow.java \
		  Trigger.java \
		  VersionInfo.java \
          VersionRegistry.java \
		  WinProfile.java \
		  WinProfileItem.java \
		  WinReg.java \
		  WinRegItem.java \
		  WinRegValue.java  \
		  $(NULL)

include $(DEPTH)/config/rules.mk

JAVA_SOURCEPATH	= $(DEPTH)/modules/softupdt/classes
