/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsIDOMElement.idl"
#include "nsIDOMXULElement.idl"

[scriptable, uuid(4088e81d-c1dc-40d5-9016-cef0adc836b6)]
interface nsIDOMXULImageElement : nsIDOMXULElement {
  attribute DOMString src;
};

