/* -*- Mode: IDL; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsIDOMXULLabeledControlEl.idl"

[scriptable, uuid(8eec22e8-91f4-44fc-9142-b4cd0f623076)]
interface nsIDOMXULButtonElement : nsIDOMXULLabeledControlElement {
  const short CHECKSTATE_UNCHECKED = 0;
  const short CHECKSTATE_CHECKED = 1;
  const short CHECKSTATE_MIXED = 2;

  attribute DOMString type;
  attribute DOMString dlgType;

  // For buttons of type="menu" only.
  attribute boolean open;
  
  // For buttons of type="checkbox" only.
  attribute boolean checked;
  attribute long checkState;
  attribute boolean autoCheck;

  // For buttons of type="radio" only.
  attribute DOMString group;
};

