/* -*- Mode: IDL; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsIDOMXULDescriptionElement.idl"

[scriptable, uuid(a5b91902-2412-4724-8dff-789dc2a7bcd7)]
interface nsIDOMXULLabelElement : nsIDOMXULDescriptionElement {
  attribute DOMString accessKey;
  attribute DOMString control;
};

