#
# This is a list of local files which get copied to the mozilla:dist directory
#

nspr.h
pratom.h
prbit.h
prclist.h
prcmon.h
prcvar.h
prdtoa.h
prenv.h
prerror.h
prinet.h
prinit.h
prinrval.h
prio.h
prlink.h
prlock.h
prlog.h
prlong.h
prmem.h
prmon.h
prmwait.h
prnetdb.h
prpdce.h
prprf.h
prproces.h
prsystem.h
prthread.h
prtime.h
prtypes.h
prwin16.h

obsolete:protypes.h
obsolete:prsem.h
md:prosdep.h
md:_macos.h
