/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsIFile.idl"

/**
 * An empty interface to provide backwards compatibility for existing code.
 *
 * @see nsIFile
 */
[scriptable, builtinclass, uuid(ce4ef184-7660-445e-9e59-6731bdc65505)]
interface nsILocalFile : nsIFile
{
};

