/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is cookie manager code.
 *
 * The Initial Developer of the Original Code is
 * Michiel van Leeuwen (mvl@exedo.nl).
 * Portions created by the Initial Developer are Copyright (C) 2003
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */

#include "nsISupports.idl"

/**
 * An interface to test for cookie permissions
 */

interface nsICookie;
interface nsIURI;
interface nsIDOMWindow;

[scriptable, uuid(EF565D0A-AB9A-4A13-9160-0644CDFD859A)]
interface nsICookiePermission : nsISupports
{
  /**
   * Test if a cookie from the given host should be accepted or denied,
   * only by prompting the user (does not perform a permissionlist lookup)
   * @param uri             the website to be tested
   * @param cookie          the cookie that wants to be set
   * @param parent          the parant window
   * @param cookiesFromHost number of cookies this host already has set
   * @param changingCookie  are we changing this cookie?
   * @param showDialog      show a prompt to the user?
   * @param listPermission  previous result from nsIPermissionManager::
                            TestPermission() (use UNKNOWN_ACTION if none)
   * @return                whether the cookie has permission to be loaded
   */
  boolean testPermission(in nsIURI uri,
                         in nsICookie cookie,
                         in nsIDOMWindow parent,
                         in long cookiesFromHost,
                         in boolean changingCookie,
                         in boolean showDialog,
                         in PRUint32 listPermission);
};

%{ C++
#define NS_COOKIEPERMISSION_CONTRACTID "@mozilla.org/cookie/permission;1"
%}
