#include "nsISupports.idl"

[scriptable, uuid(f271bdb9-44e8-4f34-a345-490300f1f141)]
interface iExclusionSupport : nsISupports
{ 
      void exclude(in unsigned long count,[array, size_is(count)] in string exclusionList);

};


