#filter emptyLines

#define MOZ_LANGPACK_EID {f68df430-4534-4473-8ca4-d5de32268a8d}
#define MOZ_LANGPACK_CREATOR mozilla.org

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
# #define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Joe Solon</em:contributor> <em:contributor>Suzy Solon</em:contributor>

#unfilter emptyLines
