/* -*- Mode: IDL; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

%{C++
class nsWrapperCache;
%}

[ptr] native nsWrapperCachePtr(nsWrapperCache);

typedef unsigned long long DOMTimeStamp;
typedef double DOMHighResTimeStamp;
typedef unsigned long long nsViewID;

// Core
interface nsIDOMDocument;
interface nsIDOMElement;
interface nsIDOMNode;
interface nsIDOMNodeList;

// Needed for raises() in our IDL
%{C++
namespace mozilla {
namespace dom {
class DOMException;
}
}
%}

// Base
interface nsIDOMWindow;
interface nsIDOMWindowCollection;

// Events
interface nsIDOMEvent;
interface nsIDOMEventListener;

// HTML
interface nsIDOMHTMLHeadElement;

// Range
interface nsIDOMRange;
