/* -*- Mode: IDL; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "domstubs.idl"

typedef unsigned short nsDOMPerformanceNavigationType;

[scriptable, uuid(a2132ad8-a841-4285-a140-338e8de6c2e0)]
interface nsIDOMPerformanceNavigation : nsISupports
{
  const nsDOMPerformanceNavigationType TYPE_NAVIGATE = 0;
  const nsDOMPerformanceNavigationType TYPE_RELOAD = 1;
  const nsDOMPerformanceNavigationType TYPE_BACK_FORWARD = 2;
  const nsDOMPerformanceNavigationType TYPE_RESERVED = 255;

  readonly attribute nsDOMPerformanceNavigationType type;
  readonly attribute unsigned short redirectCount;
};

