/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
 *
 * The contents of this file are subject to the Netscape Public License
 * Version 1.0 (the "NPL"); you may not use this file except in
 * compliance with the NPL.  You may obtain a copy of the NPL at
 * http://www.mozilla.org/NPL/
 *
 * Software distributed under the NPL is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the NPL
 * for the specific language governing rights and limitations under the
 * NPL.
 *
 * The Initial Developer of this code under the NPL is Netscape
 * Communications Corporation.  Portions created by Netscape are
 * Copyright (C) 1998 Netscape Communications Corporation.  All Rights
 * Reserved.
 */

/*

  A sample of XPComized ProfileManager. This file contains a profile interface.

 */

#include "nsISupports.idl"

[scriptable, uuid(F4C0DA81-3887-11d3-9F5D-006008A6EFE9)]
interface nsIProfileServices : nsISupports
{
	void CreateNewProfile(in string data);
	void RenameProfile(in string oldName, in string newName);
	void DeleteProfile(in string profileName, in string canDeleteFiles);
	string GetProfileList();
	void StartCommunicator(in string profileName);
	string GetCurrentProfile();
	void MigrateProfile(in string profileName);
	void ProcessPREGInfo(in string data);
	void CloneProfile(in string profileName);
};


%{ C++
// {F4C0DA83-3887-11d3-9F5D-006008A6EFE9}
#define NS_ProfileServices_CID \
{ 0xf4c0da83, 0x3887, 0x11d3, { 0x9f, 0x5d, 0x00, 0x60, 0x08, 0xa6, 0xef, 0xe9 } }

extern nsresult
NS_NewProfileServices(nsIProfileServices** aProfile);
%}
