	$(MAKE_INSTALL) chatzilla.css $(DIST)\bin\chrome\$(THEME)\chatzila\skin
	$(MAKE_INSTALL) output-default.css $(DIST)\bin\chrome\$(THEME)\chatzila\skin
	$(MAKE_INSTALL) output-loud.css $(DIST)\bin\chrome\$(THEME)\chatzila\skin
	$(MAKE_INSTALL) output-marble.css $(DIST)\bin\chrome\$(THEME)\chatzila\skin
