/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

//! This module contains getters for static prefs.
//!
//! The contents of this module are generated by
//! `modules/libpref/init/generate_static_pref_list.py`, from
//! `modules/libpref/init/StaticPrefList.yaml`.

include!(mozbuild::objdir_path!("modules/libpref/static_prefs.rs"));
