<stringbundleset id="stringbundleset"/>

<commandset id="globalEditCommandSet"/>
<commandset id="selectEditCommandSet"/>
<commandset id="undoEditCommandSet"/>
<commandset id="pasteCommandSet"/>
<commandset id="mainCommandSet"/>
<commandset id="baseMenuCommandSet"/>

<broadcasterset id="mainBroadcasterSet"/>

<keyset id="mainKeyset"/>
<keyset id="baseMenuKeyset"/>

<menubar id="main-menubar"/>

<template id="bookmarks-template"/>

<tree id="hiddenHistoryTree"/>
