/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*-
 *
 * The contents of this file are subject to the Mozilla Public
 * License Version 1.1 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of
 * the License at http://www.mozilla.org/MPL/
 * 
 * Software distributed under the License is distributed on an "AS
 * IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
 * implied. See the License for the specific language governing
 * rights and limitations under the License.
 * 
 * The Original Code is mozilla.org code.
 * 
 * The Initial Developer of the Original Code is Netscape
 * Communications Corporation. Portions created by Netscape are
 * Copyright (C) 2000 Netscape Communications Corporation. All
 * Rights Reserved.
 * 
 * Contributor(s): 
 *   Mike Pinkerton <pinkerton@netscape.com>
 */

#include "nsISupports.idl"
#include "gfxtypes.idl"

/**
 * nsIScreenManager interface
 *
 * @author Mike Pinkerton <pinkerton@netscape.com>
 * @author Stuart Parmenter <pavlov@netscape.com>
 * @version 1.1
 * @see nsIOutputDevice
 * @see "gfx2"
 **/
[scriptable, uuid(f728830e-1dd1-11b2-9598-fb9f414f2465)]
interface nsIScreen : nsISupports
{
  void getRect(out gfx_coord x, out gfx_coord y, out gfx_dimension width, out gfx_dimension height);
  void getAvailRect(out gfx_coord x, out gfx_coord y, out gfx_dimension width, out gfx_dimension height);
  
  readonly attribute gfx_depth pixelDepth;
  readonly attribute gfx_depth colorDepth;  
};
