/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/* ***** BEGIN LICENSE BLOCK *****
 * Version: NPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Netscape Public License
 * Version 1.1 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 * http://www.mozilla.org/NPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is mozilla.org code.
 *
 * The Initial Developer of the Original Code is 
 * Netscape Communications Corporation.
 * Portions created by the Initial Developer are Copyright (C) 1998
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or 
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the NPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the NPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */

#include "nsISupports.idl"

%{C++

#define NS_PROFILE_STARTUP_LISTENER_CID                \
  { /* {6962ca90-0b8b-11d4-9875-00c04fa0d28b} */       \
    0x6962ca90,                                        \
    0x0b8b,                                            \
    0x11d4,                                            \
    { 0x98, 0x75, 0x00, 0xc0, 0x4f, 0xa0, 0xd2, 0x8b } \
  }

#define NS_PROFILE_STARTUP_LISTENER_CONTRACTID	\
	"@mozilla.org/profile/startuplistener;1"
%}

[scriptable, uuid(6962ca8f-0b8b-11d4-9875-00c04fa0d28b)]
interface nsIProfileStartupListener : nsISupports {

    void onProfileStartup(in wstring profileName);

};

#endif /* nsIProfile_Startup_Listener_h__ */
