/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
 *
 * The contents of this file are subject to the Netscape Public
 * License Version 1.1 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of
 * the License at http://www.mozilla.org/NPL/
 *
 * Software distributed under the License is distributed on an "AS
 * IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
 * implied. See the License for the specific language governing
 * rights and limitations under the License.
 *
 * The Original Code is mozilla.org code.
 *
 * The Initial Developer of the Original Code is Netscape
 * Communications Corporation.  Portions created by Netscape are
 * Copyright (C) 1998 Netscape Communications Corporation. All
 * Rights Reserved.
 *
 * Contributor(s): 
 */

////////////////////////////////////////////////////////////////////////////////
/**
 * <B>INTERFACE TO NETSCAPE COMMUNICATOR PLUGINS (NEW C++ API).</B>
 *
 * <P>This supersedes the old plugin API (npapi.h, npupp.h), and 
 * eliminates the need for glue files: npunix.c, npwin.cpp and npmac.cpp that
 * get linked with the plugin. You will however need to link with the "backward
 * adapter" (badapter.cpp) in order to allow your plugin to run in pre-5.0
 * browsers. 
 *
 * <P>See nsPlugin.idl for an overview of how this interface fits with the 
 * overall plugin architecture.
 */
////////////////////////////////////////////////////////////////////////////////

#include "nsIPluginInstancePeer.idl"

/**
 * The nsIPluginInstancePeer2 interface extends the nsIPluginInstancePeer
 * interface, providing access to functionality provided by newer browsers.
 * All functionality in nsIPluginInstancePeer can be mapped to the 4.X
 * plugin API.
 */
[scriptable, uuid(e7d48c00-e1f1-11d2-8360-fbc8abc4ae7c)]
interface nsIPluginInstancePeer2 : nsIPluginInstancePeer
{
    /**
     * Get the JavaScript window object corresponding to this plugin instance.
     *
     * @result - the resulting JavaScript window object
     */
    [noscript] readonly attribute JSObjectPtr JSWindow;
	
	/**
	 * Get the JavaScript execution thread corresponding to this plugin instance.
	 *
	 * @result - the resulting JavaScript thread
	 */
    readonly attribute unsigned long JSThread;

	/**
	 * Get the JavaScript context to this plugin instance.
	 *
	 * @result - the resulting JavaScript context
	 */
    [noscript] readonly attribute JSContextPtr JSContext;
};
