From Wd@rgsrdds.com Thu Feb 26 03:26:07 2004
Return-Path: <Wd@rgsrdds.com>
Received: from 24-196-112-88.fdl.wi.chrter.com (24-196-112-88.fdl.wi.charter.com [24.196.112.88])
	by leggite.example.com (8.12.8/8.12.8) with SMTP id i1QBRUVf004909
	for <exp@example.com>; Thu, 26 Feb 2004 03:27:39 -0800
Received: from 243.66.85.172 by 24.196.112.88; Thu, 26 Feb 2004 07:22:07 -0400
Message-ID: <UAEXRCYRSQWVZYJINKNBA@rtemedsr.com>
From: "Mil" <Wd@rgsrdds.com>
Reply-To: "Mil" <Wd@rgsrdds.com>
To: exp@example.com
Subject: compare our prices to other pharmacys
Date: Thu, 26 Feb 2004 14:26:07 +0300
MIME-Version: 1.0
Content-Type: multipart/alternative;
  boundary="--2159753839863261329"

----2159753839863261329
Content-Type: text/plain;
Content-Transfer-Encoding: quoted-printable

get your meds online 
  
Your easy-to-use solution is here:

http://rtmdsr.com/gp/deflt.asp?id=3Djim

  
  
  
THX,
Elvin Hurd 
  
Dac below is for u if u dislike e-commerce
http://rtmdsr.com/er/r.asp?Folder=3Dgp


----2159753839863261329--


