From anaspec@rthlnk.net Tue Aug 31 15:36:37 2004
Return-Path: <nspec@rthlnk.net>
Received: from localhost (localhost [127.0.0.1])
	by smtp.example.com (8.12.11/8.12.5) with ESMTP id i811APdX006705
	for <exp@localhost>; Tue, 31 Aug 2004 18:10:26 -0700
Received: from snacker.example.com [207.111.254.120]
	by localhost with IMAP (fetchmail-6.2.5)
	for exp@localhost (single-drop); Tue, 31 Aug 2004 18:10:26 -0700 (PDT)
Received: from leggte.example.com ([207.111.254.118]) by snacker.example.com
          (Netscape Messaging Server 4.15) with ESMTP id I3C17600.438 for
          <exp@example.com>; Tue, 31 Aug 2004 15:30:42 -0700 
Received: from rthlnk.net (218-35-236-63.etheric.net [63.236.35.218] (may be forged))
	by leggte.example.com (8.12.8/8.12.8) with ESMTP id i7VMbcCu000722
	for <exp@example.com>; Tue, 31 Aug 2004 15:37:38 -0700
Message-ID: <20040831153637.D2409658E4524456@rthlnk.net>
From: nspec@rthlnk.net
To: exp@example.com
Subject: Peptide News
Reply-To: nspec@rthlnk.net
Date: 31 Aug 2004 15:36:37 -0700
MIME-Version: 1.0
Content-Type: text/html;
  charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

<html xmlns:v=3D"urn:schemas-microsoft-com:vml"
xmlns:o=3D"urn:schemas-microsoft-com:office:office"
xmlns:w=3D"urn:schemas-microsoft-com:office:word"
xmlns=3D"http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=3DContent-Type content=3D"text/html; charset=3Diso-8859-1">=

<meta name=3DProgId content=3DWord.Document>
<meta name=3DGenerator content=3D"Microsoft Word 9">
<meta name=3DOriginator content=3D"Microsoft Word 9">
<link rel=3DFile-List href=3D"./30%25savings_files/fillst.xml">
<link rel=3DEdit-Time-Data href=3D"./30%25savings_files/edidta.mso">
<!--[if !mso]>
<style>
v\:* {behavior:url(#default#VML);}
o\:* {behavior:url(#default#VML);}
w\:* {behavior:url(#default#VML);}
.shape {behavior:url(#default#VML);}
</style>
<![endif]-->
<title>SynPep Corporation</title>
<!--[if gte mso 9]><xml>
 <o:DocumentProperties>
  <o:Author>davids</o:Author>
  <o:LastAuthor>davids</o:LastAuthor>
  <o:Revision>2</o:Revision>
  <o:TotalTime>32</o:TotalTime>
  <o:Created>2004-08-30T23:39:00Z</o:Created>
  <o:LastSaved>2004-08-30T23:39:00Z</o:LastSaved>
  <o:Pages>1</o:Pages>
  <o:Words>670</o:Words>
  <o:Characters>3821</o:Characters>
  <o:Lines>31</o:Lines>
  <o:Paragraphs>7</o:Paragraphs>
  <o:CharactersWithSpaces>4692</o:CharactersWithSpaces>
  <o:Version>9.6926</o:Version>
 </o:DocumentProperties>
</xml><![endif]-->
<style>
<!--
 /* Font Definitions */
@font-face
	{font-family:Wingdings;
	panose-1:5 0 0 0 0 0 0 0 0 0;
	mso-font-charset:2;
	mso-generic-font-family:auto;
	mso-font-pitch:variable;
	mso-font-signature:0 268435456 0 0 -2147483648 0;}
@font-face
	{font-family:Verdana;
	panose-1:2 11 6 4 3 5 4 4 2 4;
	mso-font-charset:0;
	mso-generic-font-family:swiss;
	mso-font-pitch:variable;
	mso-font-signature:536871559 0 0 0 415 0;}
 /* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{mso-style-parent:"";
	margin:0in;
	margin-bottom:.0001pt;
	mso-pagination:widow-orphan;
	font-size:12.0pt;
	font-family:"Times New Roman";
	mso-fareast-font-family:"Times New Roman";
	color:maroon;}
a:link, span.MsoHyperlink
	{color:blue;}
a:visited, span.MsoHyperlinkFollowed
	{color:blue;}
pre
	{margin:0in;
	margin-bottom:.0001pt;
	font-size:10.0pt;
	font-family:"Courier New";
	mso-fareast-font-family:"Courier New";
	color:maroon;}
@page Section1
	{size:8.5in 11.0in;
	margin:1.0in 1.25in 1.0in 1.25in;
	mso-header-margin:.5in;
	mso-footer-margin:.5in;
	mso-paper-source:0;}
div.Section1
	{page:Section1;}
 /* List Definitions */
@list l0
	{mso-list-id:410741857;
	mso-list-type:hybrid;
	mso-list-template-ids:784620064 286026972 -788265640 993687158 626055678 -1=
811375712 -151983676 -930189644 1334191436 815690794;}
@list l0:level1
	{mso-level-number-format:bullet;
	mso-level-text:\F0B7;
	mso-level-tab-stop:.5in;
	mso-level-number-position:left;
	text-indent:-.25in;
	mso-ansi-font-size:10.0pt;
	font-family:Symbol;}
@list l1
	{mso-list-id:573589179;
	mso-list-type:hybrid;
	mso-list-template-ids:1335506698 -287414814 -166539250 1278239692 20987546 =
-72418112 -735677686 -1233212756 288795288 889766454;}
@list l1:level1
	{mso-level-number-format:bullet;
	mso-level-text:\F0B7;
	mso-level-tab-stop:.5in;
	mso-level-number-position:left;
	text-indent:-.25in;
	mso-ansi-font-size:10.0pt;
	font-family:Symbol;}
@list l2
	{mso-list-id:1811441157;
	mso-list-type:hybrid;
	mso-list-template-ids:868497156 -610104194 1657037930 -1004880116 -13919388=
22 -1255648344 -314401074 -609714884 -811151446 832969692;}
@list l2:level1
	{mso-level-number-format:bullet;
	mso-level-text:\F0B7;
	mso-level-tab-stop:.5in;
	mso-level-number-position:left;
	text-indent:-.25in;
	mso-ansi-font-size:10.0pt;
	font-family:Symbol;}
ol
	{margin-bottom:0in;}
ul
	{margin-bottom:0in;}
-->
</style>
<!--[if gte mso 9]><xml>
 <o:shapedefaults v:ext=3D"edit" spidmax=3D"1028"/>
</xml><![endif]--><!--[if gte mso 9]><xml>
 <o:shapelayout v:ext=3D"edit">
  <o:idmap v:ext=3D"edit" data=3D"1"/>
 </o:shapelayout></xml><![endif]-->
</head>

<body bgcolor=3Dsilver lang=3DEN-US link=3Dblue vlink=3Dblue style=3D'tab-in=
terval:.5in'>

<div class=3DSection1>

<div align=3Dcenter>

<table border=3D0 cellspacing=3D0 cellpadding=3D0 width=3D"80%" bgcolor=3Dma=
roon
 style=3D'width:80.0%;mso-cellspacing:0in;background:maroon;mso-padding-alt:=
.6pt .6pt .6pt .6pt'>
 <tr>
  <td style=3D'padding:.6pt .6pt .6pt .6pt'><!-- Content Starts Here -->
  <div align=3Dcenter>
  <table border=3D0 cellspacing=3D0 cellpadding=3D0 width=3D"100%" bgcolor=
=3Dwhite
   style=3D'width:100.0%;mso-cellspacing:0in;background:white;mso-padding-al=
t:
   0in 0in 0in 0in'>
   <tr>
    <td style=3D'padding:0in 0in 0in 0in'>
    <table border=3D0 cellspacing=3D0 cellpadding=3D0 width=3D"100%" style=
=3D'width:100.0%;
     mso-cellspacing:0in;mso-padding-alt:3.0pt 3.0pt 3.0pt 3.0pt'>
     <tr>
      <td width=3D"100%" valign=3Dbottom style=3D'width:100.0%;padding:3.0pt=
 3.0pt 3.0pt 3.0pt'>
      <p class=3DMsoNormal><![if !supportEmptyParas]>&nbsp;<![endif]><o:p></=
o:p></p>
      </td>
     </tr>
     <tr>
      <td width=3D"100%" style=3D'width:100.0%;padding:3.0pt 3.0pt 3.0pt 3.0=
pt'>
      <p class=3DMsoNormal align=3Dcenter style=3D'text-align:center'><b><sp=
an
      style=3D'font-size:14.5pt;font-family:Verdana'>Are you or your staff i=
n
      need of Quality Peptides?<o:p></o:p></span></b></p>
      </td>
     </tr>
     <tr>
      <td style=3D'background:#FFDD66;padding:3.0pt 3.0pt 3.0pt 3.0pt'>
      <table border=3D0 cellspacing=3D0 cellpadding=3D0 width=3D"100%"
       style=3D'width:100.0%;mso-cellspacing:0in;mso-padding-alt:0in 0in 0in=
 0in'>
       <tr>
        <td width=3D"70%" style=3D'width:70.0%;background:#FFDD66;padding:0i=
n 0in 0in 0in'>
        <p class=3DMsoNormal><span style=3D'font-size:18.0pt;mso-bidi-font-s=
ize:
        7.0pt;font-family:Verdana;color:black'>If the answer is </span><stro=
ng><span
        style=3D'font-size:18.0pt;mso-bidi-font-size:7.0pt;font-family:Verda=
na;
        color:navy'>YES</span></strong><span style=3D'font-size:18.0pt;
        mso-bidi-font-size:7.0pt;font-family:Verdana;color:black'>, </span><=
strong><span
        style=3D'font-size:18.0pt;mso-bidi-font-size:7.0pt;font-family:Verda=
na;
        color:navy'>nSpec</span></strong><span style=3D'font-size:18.0pt;
        mso-bidi-font-size:7.0pt;font-family:Verdana;color:black'> is offeri=
ng
        up to 30% off your first new order.<br>
        </span><span style=3D'font-size:7.0pt;font-family:Verdana;color:blac=
k'><br>
        We are the market leader in the manufacturing of Custom Peptides, an=
d Catalog
        Peptides,. We offer high-throughput manufacturing under GLP conditio=
ns
        to meet the demand for synthetic peptides in pharmaceuticals,
        biotechnology, agrochemical industries and research institutes.<br>
        <br>
        With 11 plus years of experience and synthesizing over 10,000 HPLC
        purified peptides per year, we believe that our innovative productio=
n
        processes, inventory management system, strict quality-assurance and=

        quality-controls insure the highest quality peptides in the industry=
.<br>
        <br>
        In addition to our superior quality, We provide competitive prices,
        fast delivery, and an award-winning technical support team that resu=
lt
        in the best value available on the market. <o:p></o:p></span></p>
        </td>
        <td width=3D"30%" style=3D'width:30.0%;background:#FFDD66;padding:0i=
n 0in 0in 0in'>
        <p class=3DMsoNormal><img id=3D"_x0000_i1026"
        src=3D"http://www.bpfrntln.com/sals/girl.jpg" border=3D0
        align=3Dmiddle></p>
        </td>
       </tr>
      </table>
      <p class=3DMsoNormal><o:p></o:p></p>
      </td>
     </tr>
     <tr>
      <td style=3D'background:#FFDD66;padding:3.0pt 3.0pt 3.0pt 3.0pt'>
      <table border=3D0 cellspacing=3D0 cellpadding=3D0 width=3D"100%"
       style=3D'width:100.0%;mso-cellspacing:0in;mso-padding-alt:1.8pt 1.8pt=
 1.8pt 1.8pt'>
       <tr>
        <td width=3D"30%" valign=3Dtop style=3D'width:30.0%;background:#FFDD=
66;
        padding:1.8pt 1.8pt 1.8pt 1.8pt'>
        <p class=3DMsoNormal><img width=3D249 height=3D249 id=3D"_x0000_i102=
7"
        src=3D"http://www.bpfrntln.com/sals/chem.jpg" border=3D0></p>
        </td>
        <td width=3D"70%" style=3D'width:70.0%;background:#FFDD66;padding:1.=
8pt 1.8pt 1.8pt 1.8pt'>
        <p class=3DMsoNormal style=3D'margin-bottom:12.0pt'><strong><span
        style=3D'font-size:8.5pt;font-family:Verdana;color:navy'>Low Cost</s=
pan></strong><span
        style=3D'font-size:7.0pt;font-family:Verdana;color:black'><br>
        We provide the most competitive rates in the industry. Our
        cost-effective high-throughput production facility allows us to pass=

        the savings onto you! We have built our facility and capabilities
        around state-of-the-art equipment and have meticulously fine-tuned o=
ur
        process methodology to avoid the high cost of unnecessary labor. <a
        href=3D"mailto:nspec@rthlnk.net?subject=3DREF.CODE:SeptemberSpe=
cial"><span style=3D'text-decoration:
        none;text-underline:none'>Click here</span></a> to find out more abo=
ut
        our low cost.<br>
        <br>
        </span><strong><span style=3D'font-size:8.5pt;font-family:Verdana;
        color:navy'>Quality</span></strong><span style=3D'font-size:7.0pt;
        font-family:Verdana;color:black'><br>
        Under GLP conditions, our products are manufactured under protocol a=
nd
        tracked using our Data Management System. All produced peptides are
        shipped with HPLC, Mass Spectra Analysis, and UV Scan Data. Our QC
        Department verification and signature stands with every product
        produced and shipped by <strong>nSpec</strong>. <a
        href=3D"mailto:nspec@rthlnk.net?subject=3DREF.CODE:SeptemberSpe=
cial"><span style=3D'text-decoration:
        none;text-underline:none'>Click here</span></a> to find out more abo=
ut
        our quality.<br>
        <br>
        </span><strong><span style=3D'font-size:8.5pt;font-family:Verdana;
        color:navy'>Service</span></strong><span style=3D'font-size:7.0pt;
        font-family:Verdana;color:black'><br>
        We here at <strong>nSpec</strong>, are continuing to advance our
        excellence to the customer. We provide our customers with 100%
        satisfaction guarantee on our products, services, and delivery. Our
        production turnaround time for delivery is around 3 weeks. <a
        href=3D"mailto:nspec@rthlnk.net?subject=3DREF.CODE:SeptemberSpe=
cial"><span style=3D'text-decoration:
        none;text-underline:none'>Click here</span></a> to find out more abo=
ut
        our service.<o:p></o:p></span></p>
        </td>
       </tr>
      </table>
      <p class=3DMsoNormal><o:p></o:p></p>
      </td>
     </tr>
     <tr>
      <td style=3D'padding:3.0pt 3.0pt 3.0pt 3.0pt'
      background=3D"http://www.bpfrntln.com/sals/bg.jpg">
      <p class=3DMsoNormal><strong><span style=3D'font-size:8.5pt;font-famil=
y:Verdana;
      color:black'>The nSpec Family</span></strong><span style=3D'font-siz=
e:
      7.0pt;font-family:Verdana;color:black'><br>
      In addition to producing the regular peptides, nSpechas the capacity=
 to
      offer almost every commercially available peptide modifications. <o:p>=
</o:p></span></p>
      <div align=3Dcenter>
      <table border=3D0 cellspacing=3D3 cellpadding=3D0 width=3D"80%" style=
=3D'width:
       80.0%;mso-cellspacing:1.5pt'>
       <tr>
        <td valign=3Dtop style=3D'padding:.75pt .75pt .75pt .75pt'>
        <ul type=3Ddisc>
         <li class=3DMsoNormal style=3D'color:black;mso-margin-top-alt:auto;=

             mso-margin-bottom-alt:auto;mso-list:l2 level1 lfo1;tab-stops:li=
st .5in'><span
             style=3D'font-size:7.0pt;font-family:Verdana'>Long Peptide Synt=
hesis
             up to 100-mer <o:p></o:p></span></li>
         <li class=3DMsoNormal style=3D'color:black;mso-margin-top-alt:auto;=

             mso-margin-bottom-alt:auto;mso-list:l2 level1 lfo1;tab-stops:li=
st .5in'><span
             style=3D'font-size:7.0pt;font-family:Verdana'>Fluorescent Label=
ed
             Peptides (such as): FITC/5 FAM, EDANS, TAMRA, Etc. <o:p></o:p><=
/span></li>
         <li class=3DMsoNormal style=3D'color:black;mso-margin-top-alt:auto;=

             mso-margin-bottom-alt:auto;mso-list:l2 level1 lfo1;tab-stops:li=
st .5in'><span
             style=3D'font-size:7.0pt;font-family:Verdana'>Multiple Disulfid=
e
             Bridges containing Peptides <o:p></o:p></span></li>
         <li class=3DMsoNormal style=3D'color:black;mso-margin-top-alt:auto;=

             mso-margin-bottom-alt:auto;mso-list:l2 level1 lfo1;tab-stops:li=
st .5in'><span
             style=3D'font-size:7.0pt;font-family:Verdana'>Multiple Phospho
             Related Peptides <o:p></o:p></span></li>
         <li class=3DMsoNormal style=3D'color:black;mso-margin-top-alt:auto;=

             mso-margin-bottom-alt:auto;mso-list:l2 level1 lfo1;tab-stops:li=
st .5in'><span
             style=3D'font-size:7.0pt;font-family:Verdana'>Symmetrical and
             Unsymmetrical Multiple Antigenic Peptides (MAPS) <o:p></o:p></s=
pan></li>
        </ul>
        </td>
        <td valign=3Dtop style=3D'padding:.75pt .75pt .75pt .75pt'>
        <ul type=3Ddisc>
         <li class=3DMsoNormal style=3D'color:black;mso-margin-top-alt:auto;=

             mso-margin-bottom-alt:auto;mso-list:l1 level1 lfo2;tab-stops:li=
st .5in'><span
             style=3D'font-size:7.0pt;font-family:Verdana'>Fatty Acid and
             Isoprenylated Peptides <o:p></o:p></span></li>
         <li class=3DMsoNormal style=3D'color:black;mso-margin-top-alt:auto;=

             mso-margin-bottom-alt:auto;mso-list:l1 level1 lfo2;tab-stops:li=
st .5in'><span
             style=3D'font-size:7.0pt;font-family:Verdana'>Glycosylated Pept=
ides <o:p></o:p></span></li>
         <li class=3DMsoNormal style=3D'color:black;mso-margin-top-alt:auto;=

             mso-margin-bottom-alt:auto;mso-list:l1 level1 lfo2;tab-stops:li=
st .5in'><span
             style=3D'font-size:7.0pt;font-family:Verdana'>Regio-Selective C=
onjugation
             of Peptides with Antibiotics, Nucleotides, Proteins, Etc. <o:p>=
</o:p></span></li>
         <li class=3DMsoNormal style=3D'color:black;mso-margin-top-alt:auto;=

             mso-margin-bottom-alt:auto;mso-list:l1 level1 lfo2;tab-stops:li=
st .5in'><span
             style=3D'font-size:7.0pt;font-family:Verdana'>Biotinylation <o:=
p></o:p></span></li>
        </ul>
        </td>
       </tr>
      </table>
      </div>
      <p class=3DMsoNormal><span style=3D'font-size:7.0pt;font-family:Verdan=
a;
      color:black'>Our state-of-the-art facility and
      innovative-industrial-processes provide additional services: <o:p></o:=
p></span></p>
      <ul type=3Ddisc>
       <li class=3DMsoNormal style=3D'color:black;mso-margin-top-alt:auto;
           mso-margin-bottom-alt:auto;mso-list:l0 level1 lfo3;tab-stops:list=
 .5in'><b><span
           style=3D'font-size:7.0pt;font-family:Verdana'>Purification</span>=
</b><span
           style=3D'font-size:7.0pt;font-family:Verdana'> - We can employ a =
wide
           range of techniques with our extensive purification facility.<o:p=
></o:p></span></li>
       <li class=3DMsoNormal style=3D'color:black;mso-margin-top-alt:auto;
           mso-margin-bottom-alt:auto;mso-list:l0 level1 lfo3;tab-stops:list=
 .5in'><strong><span
           style=3D'font-size:7.0pt;font-family:Verdana'>Custom Synthesis</s=
pan></strong><span
           style=3D'font-size:7.0pt;font-family:Verdana'> - Custom Synthesis=
 of
           Amino Acids &amp; Resins and General Organic Synthesis <o:p></o:p=
></span></li>
       <li class=3DMsoNormal style=3D'color:black;mso-margin-top-alt:auto;
           mso-margin-bottom-alt:auto;mso-list:l0 level1 lfo3;tab-stops:list=
 .5in'><strong><span
           style=3D'font-size:7.0pt;font-family:Verdana'>Amino Acid Cartridg=
es</span></strong><span
           style=3D'font-size:7.0pt;font-family:Verdana'> - Cost Effective R=
efill
           Service <o:p></o:p></span></li>
       <li class=3DMsoNormal style=3D'color:black;mso-margin-top-alt:auto;
           mso-margin-bottom-alt:auto;mso-list:l0 level1 lfo3;tab-stops:list=
 .5in'><strong><span
           style=3D'font-size:7.0pt;font-family:Verdana'>Mass Spectrometry</=
span></strong><span
           style=3D'font-size:7.0pt;font-family:Verdana'> - Electrospray,
           Electron Impact, APCI, LC, and Well Plate Analysis <o:p></o:p></s=
pan></li>
       <li class=3DMsoNormal style=3D'color:black;mso-margin-top-alt:auto;
           mso-margin-bottom-alt:auto;mso-list:l0 level1 lfo3;tab-stops:list=
 .5in'><strong><span
           style=3D'font-size:7.0pt;font-family:Verdana'>Analytical Services=
</span></strong><span
           style=3D'font-size:7.0pt;font-family:Verdana'> - Liquid
           Chromatography, Capillary Electrophoresis, and Amino Acid Analysi=
s <o:p></o:p></span></li>
       <li class=3DMsoNormal style=3D'color:black;mso-margin-top-alt:auto;
           mso-margin-bottom-alt:auto;mso-list:l0 level1 lfo3;tab-stops:list=
 .5in'><strong><span
           style=3D'font-size:7.0pt;font-family:Verdana'>Antibody Services</=
span></strong><span
           style=3D'font-size:7.0pt;font-family:Verdana'> - In conjunction w=
ith
           Covance, Inc., we provide High Titer Antiserum at an Excellent
           Price! <o:p></o:p></span></li>
      </ul>
      <p class=3DMsoNormal><strong><span style=3D'font-size:7.0pt;font-famil=
y:Verdana;
      color:black'>nSpec</span></strong><span style=3D'font-size:7.0pt;
      font-family:Verdana;color:black'> is a privately held company establis=
hed
      in 1993. nSpecis located in San Jose, California and occupies a 18,0=
00
      sq. ft facility for our laboratories and administrative offices.<br>
      <br>
      For a FREE catalog and more information about <strong>nSpec</strong>=
,
      please visit us on the Internet at <a href=3D"http://www.nspc.com/"=
>http://www.nspc.com/</a>.<br>
      <br>
      Reply via Fax, Phone, or <a
      href=3D"mailto:nspc@rthlnk.net?subject=3DREF.CODE:SeptemberSpeci=
al">email</a>
      with <strong>REF. CODE: September Special</strong> to see how you can
      start your savings today with <strong>nSpec</strong>! <o:p></o:p></s=
pan></p>
      <pre><span style=3D'font-size:7.0pt;font-family:Verdana;color:black'><=
![if !supportEmptyParas]>&nbsp;<![endif]><o:p></o:p></span></pre><pre><span
      style=3D'font-size:7.0pt;font-family:Verdana;color:black'><![if !suppo=
rtEmptyParas]>&nbsp;<![endif]><o:p></o:p></span></pre><pre><b><span
      style=3D'font-size:7.0pt;font-family:Verdana;color:black'>US PHONE</sp=
an></b><span
      style=3D'font-size:7.0pt;font-family:Verdana;color:black'>:<span
      style=3D'mso-tab-count:1'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&n=
bsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>408 =
517 4223<o:p></o:p></span></pre><pre><b><span
      style=3D'font-size:7.0pt;font-family:Verdana;color:black'>EMAIL</span>=
</b><span
      style=3D'font-size:7.0pt;font-family:Verdana;color:black'>:<span
      style=3D'mso-tab-count:2'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&n=
bsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><a
      href=3D"mailto:nspec@rthlnk.net?subject=3DREF.CODE:SeptemberSpeci=
al">nspec@rthlnk.net</a></span></pre>
      <p class=3DMsoNormal><img border=3D0 width=3D1 height=3D1 id=3D"_x0000=
_i1028"
      src=3D"http://www.bpfrntln.com/sals/rddot.gif"></p>
      <p class=3DMsoNormal align=3Dcenter style=3D'text-align:center'><span
      style=3D'font-size:5.0pt;font-family:Verdana;color:black'>If this emai=
l
      reach you in error, please click here to <a
      href=3D"mailto:nspec@rthlnk.net?subject=3DRemove"><span
      style=3D'color:red'>remove</span></a>. If this link is not working, pl=
ease
      reply to this email with &quot;Remove&quot; in the subject line.<o:p><=
/o:p></span></p>
      </td>
     </tr>
    </table>
<!-- Content ends here -->
    <p class=3DMsoNormal><o:p></o:p></p>
    </td>
   </tr>
  </table>
  </div>
  <p class=3DMsoNormal><o:p></o:p></p>
  </td>
 </tr>
</table>

</div>

<p class=3DMsoNormal><span style=3D'color:windowtext'><![if !supportEmptyPar=
as]>&nbsp;<![endif]><o:p></o:p></span></p>

</div>

</body>

</html>


