From wfskr@fstml.us Wed Sep  1 17:37:30 2004
Return-Path: <wfskr@fstml.us>
Received: from 63.194.242.243 (adsl-63-194-242-243.dsl.lsan03.pacbell.net [63.194.242.243])
	by leggite.example.com (8.12.8/8.12.8) with SMTP id i820cVCv002160
	for <exp@example.com>; Wed, 1 Sep 2004 17:38:33 -0700
Message-Id: <200409020038.i820cVCv002160@leggite.example.com>
From: "wf skr" <wfskr@fstml.us>
To: <exp@example.com>
Subject: The wf skr...
Sender: "wf skr" <wfskr@fstml.us>
Mime-Version: 1.0
Content-Type: multipart/related;
  boundary="= Multipart Boundary 0901041737"
Date: Wed, 1 Sep 2004 17:37:30 -0700

This is a multipart MIME message.

--= Multipart Boundary 0901041737
Content-Type: multipart/alternative;
	boundary="= Multipart Boundary _EXTRA_0901041737"

--= Multipart Boundary _EXTRA_0901041737
Content-Type: text/plain;
	charset="ISO-8859-1"
Content-Transfer-Encoding: quoted-printable
X-MIME-Autoconverted: from 8bit to quoted-printable by leggite.example.com id i820cVCv002160

Virtually every student and business professional has a laptop with wirel=
ensive piece of technology will locate the wf connection and the best p=
lace for reception.

Where to buy (eB):  http://cgi.eb.com/ws/eBISAPI.dll?vi&categ=
ory=3D61818&item=3D5718431248&rd=3D1

Please contact me for volume discounts and custom logo/design information=
.  We can do clamshell, bulk or custom packaging.  Colors, school logos, =
etc. are not a problem and at minor additional cost or free if the quanti=
ty is large enough!!

Thank you, and reply with REMOVE to opt-out...

-Brian

reply to wfskr@fstml.us I will not be sending you multiple messag=
es on this.... Thanks again...
Tuesday, April 27, 2004 | by Eamon Hickey
=20
keychain-sized device that scans for active wf (802.11b) networks. It's=
 also handy for measuring signal strength within a given coverage area.
=20
Gizmodo.com: Best Wi-Fi Signal Finder Yet, 04/22/2004 05:19
=20
stargeek: Best Wi-Fi Signal Finder Yet, 04/22/2004 05:19
=20
 wf skr, which they designed to differentiate 80211b/g networks from=
 other devices. Two previous Wi-Fi signal finders fell short in ways the =
active scan--but it can tell Wi-Fi from junk.
 =20
ngdgt.com: The wf skr Apr 23, 2004

ll use ours fairly often). Anyway, Glenn Fleishman checks out a brand new=
 He says it=92s the best of the bunch and that it should be on sale by Ju=
ne.=20
=20
Wi-Fi skr: Hotspot seeking keychain
=20
earth, finding wireless access points with the equivalent of a tiny divin=
g hotspots and junk interference, something this latest version is appare=
ntly much better at.

--= Multipart Boundary _EXTRA_0901041737
Content-Type: text/html;
	charset="ISO-8859-1"
Content-Transfer-Encoding: quoted-printable
X-MIME-Autoconverted: from 8bit to quoted-printable by leggite.example.com id i820cVCv002160

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML><HEAD>
<META http-equiv=3DContent-Type content=3D"text/html; charset=3Dwindows-1=
252">
<META content=3D"MSHTML 6.00.2800.1458" name=3DGENERATOR>
<STYLE>BODY {
	FONT-FAMILY: arial
}
</STYLE>
</HEAD>
<BODY>
<DIV>
<DIV>
<DIV><SPAN class=3d3-4><SPAN class=3d7-0><F=
ONT=20
face=3DArial size=3D2>Virtually every student<SPAN class=3D458063818-1905=
2004>=20
and&nbsp;<SPAN class=3D450083818-19052004>b</SPAN></SPAN><SPAN=20
class=3D101323200-04052004>usiness&nbsp;<SPAN=20
class=3D450083818-19052004>p</SPAN>rofessional</SPAN> has a laptop=20
with&nbsp;wireless LAN&nbsp;capability, and wants to log anywhere and=20
everywhere.&nbsp; This inexpensive piece of technology will locate the Wi=
Fi=20
connection and the best place for reception.</FONT></SPAN></SPAN></DIV>
<DIV><SPAN class=3d3-4><SPAN class=3d7-0><F=
ONT=20
face=3DArial size=3D2></FONT></SPAN></SPAN>&nbsp;</DIV>
<DIV><SPAN class=3d3-4><SPAN=20
class=3d7-0><STRONG><U><FONT face=3DArial size=3D2>What it=
=20
is:</FONT></U></STRONG></SPAN></SPAN></DIV>
<DIV><FONT size=3D2><FONT face=3DArial><SPAN class=3d3-4><=
SPAN=20
class=3d7-0><SPAN class=3d3-4><SPAN=20
class=3d7-0>T</SPAN>he wf skr</SPAN></SPAN>&nbsp;find=
<SPAN=20
class=3d7-0>s</SPAN>&nbsp;wireless hot spot<SPAN=20
class=3d7-0>s</SPAN> (<SPAN class=3d3-4>w</=
SPAN><SPAN=20
class=3d3-4>ithout having to boot-up your computer)=20
and&nbsp;</SPAN>finds the strongest wireless (802.11 b/g)=20
signal.&nbsp;&nbsp;W</SPAN>hether you're in an airport,&nbsp;<SPAN=20
class=3d7-0>coffee shop, classroom</SPAN> or&nbsp;at home,=
 the wf=20
skr will&nbsp;zero-in on the best access point.&nbsp;<SPAN=20
class=3d3-4> </SPAN><BR></FONT></FONT></DIV>
<DIV><FONT size=3D2><FONT face=3DArial><SPAN=20
class=3d7-0></SPAN><STRONG><U></U></STRONG></FONT></FONT>&=
nbsp;</DIV>
<DIV><FONT size=3D2><FONT face=3DArial><STRONG><U>H<SPAN class=3D72630411=
5-06052004>ow=20
it works:</SPAN></U></STRONG><BR>Simply point the wf skr in any=20
direction<SPAN class=3d3-4>, p</SPAN>ush the button and ho=
ld it=20
down.<SPAN class=3d3-4> </SPAN>&nbsp;The red lights sweep =
back and=20
forth<SPAN class=3d3-4>, i</SPAN>f there is a wireless acc=
ess point=20
within 300 feet, the wf skr will find it<SPAN class=3D331482323-0305=
2004>.=20
</SPAN>&nbsp;When the red lights stop sweeping and remain lit, you've loc=
ated an=20
(802.11 b/g) access point<SPAN class=3d3-4>, t</SPAN>he mo=
re red=20
lights that stay lit, the stronger the signal.&nbsp;<BR><BR></FONT></FONT=
><SPAN=20
class=3d3-4><SPAN class=3d3-4><SPAN=20
class=3d7-0><FONT size=3D2><FONT face=3DArial><STRONG><SPA=
N><U>Where to=20
buy<SPAN class=3D717052920-06082004> (eB)</SPAN>:</U><SPAN=20
class=3D717052920-06082004>&nbsp; <U><A=20
href=3D"http://cgi.eb.com/ws/eBISAPI.dll?vi&amp;ctg=3D6181=
8&amp;item=3D5718431248&amp;rd=3D1">http://cgi.eb.com/ws/eBISAPI.dll?=
vi&amp;ctg=3D61818&amp;item=3D5718431248&amp;rd=3D1</A></U></S=
PAN></SPAN></STRONG><BR></FONT></FONT></SPAN></SPAN></SPAN></DIV>
<DIV><SPAN class=3d3-4><FONT size=3D2><FONT face=3DArial><=
SPAN=20
class=3d3-4><SPAN=20
class=3d7-0>Please&nbsp;c</SPAN></SPAN>ontact me for volum=
e=20
discount<SPAN class=3d7-0>s</SPAN>&nbsp;and custom=20
logo/design&nbsp;<SPAN class=3d7-0>information</SPAN>.<SPA=
N=20
class=3d7-0>&nbsp; We can do clamshell, bulk or custom=20
packaging.&nbsp; Colors, school logos, etc. are not&nbsp;a problem and at=
 minor=20
additional cost<SPAN class=3D717052920-06082004> or free if the quantity =
is large=20
enough!!</SPAN></SPAN></FONT></FONT></SPAN></DIV>
<DIV><SPAN class=3d3-4><SPAN class=3d7-0><F=
ONT=20
face=3DArial size=3D2></FONT></SPAN></SPAN>&nbsp;</DIV>
<DIV>
<DIV><SPAN class=3d3-4><FONT face=3DArial=20
size=3D2></FONT></SPAN></DIV><SPAN class=3d3-4></SPAN></DI=
V>
<DIV><SPAN class=3d3-4><FONT face=3DArial size=3D2>Thank y=
ou, and reply=20
with REMOVE to opt-out...</FONT></SPAN></DIV>
<DIV><SPAN style=3D"FONT-SIZE: 10pt; COLOR: blue; FONT-FAMILY: Arial"><A=20
href=3D"http://www.dnncrprtd.com/"><FONT face=3DArial size=3D2></FO=
NT></A><FONT=20
color=3D#000000></FONT></SPAN>&nbsp;</DIV>
<DIV><SPAN style=3D"FONT-SIZE: 10pt; COLOR: blue; FONT-FAMILY: Arial"></S=
PAN><SPAN=20
style=3D"FONT-FAMILY: Arial"><SPAN style=3D"FONT-FAMILY: Arial"><SPAN=20
style=3D"FONT-FAMILY: Arial"><SPAN class=3D717052920-06082004><FONT=20
size=3D2>-Brian</FONT></SPAN></SPAN></SPAN></SPAN></DIV>
<DIV><SPAN style=3D"FONT-FAMILY: Arial"><SPAN style=3D"FONT-FAMILY: Arial=
"><SPAN=20
style=3D"FONT-FAMILY: Arial"><SPAN class=3D717052920-06082004><FONT face=3D=
Arial=20
size=3D2></FONT></SPAN></SPAN></SPAN></SPAN>&nbsp;</DIV>
<DIV><SPAN style=3D"FONT-FAMILY: Arial"><SPAN style=3D"FONT-FAMILY: Arial=
"><SPAN=20
style=3D"FONT-FAMILY: Arial"><SPAN class=3D717052920-06082004><FONT size=3D=
2>reply to=20
</FONT><A href=3D"mailto:wfskr@fstml.us"><FONT=20
size=3D2>wfskr@fstml.us</FONT></A><FONT size=3D2>&nbsp;<SPAN=20
class=3D072343215-26082004>I will not be sending you multiple messages on=
 this....=20
Thanks again...</SPAN></FONT></SPAN></SPAN></SPAN></SPAN></DIV>
<DIV class=3DSection1>
<P align=3Dcenter><FONT size=3D3><SPAN style=3D"FONT-FAMILY: Arial"><FONT=
 size=3D3><SPAN=20
style=3D"FONT-FAMILY: Arial"><FONT size=3D3><SPAN=20
style=3D"FONT-FAMILY: Arial"></SPAN></FONT></SPAN></FONT></SPAN></FONT></=
P>
<P align=3Dcenter><FONT size=3D3><SPAN style=3D"FONT-FAMILY: Arial"><FONT=
 size=3D3><SPAN=20
style=3D"FONT-FAMILY: Arial"><FONT size=3D3><SPAN style=3D"FONT-FAMILY: A=
rial"><SPAN=20
style=3D"FONT-FAMILY: Arial"><SPAN=20
style=3D"FONT-FAMILY: Arial"><STRONG><U></U></STRONG></SPAN></SPAN></SPAN=
></FONT></SPAN></FONT></SPAN></FONT></P>
<P align=3Dleft><FONT size=3D3><SPAN style=3D"FONT-FAMILY: Arial"><FONT s=
ize=3D3><SPAN=20
style=3D"FONT-FAMILY: Arial"><FONT size=3D3><SPAN=20
style=3D"FONT-FAMILY: Arial"><SPAN><FONT size=3D4><IMG alt=3D"" hspace=3D=
0=20
src=3D"cid:2183279"=20
align=3Dbaseline border=3D0>Wi-Fi Networking News: Crsls wf=20
seeker&nbsp;&nbsp;<?xml:namespace prefix =3D o ns =3D=20
"urn:schemas-microsoft-com:office:office" /><o:p></o:p></FONT></SPAN></P>
<H1 class=3dmn style=3D"MARGIN: 0in 0in 0pt"><SPAN class=3Dbodytex=
tbold1><SPAN=20
style=3D"FONT-SIZE: 9pt; COLOR: black; LETTER-SPACING: 0pt">Tuesday,&nbsp=
;April&nbsp;27,&nbsp;2004</SPAN></SPAN><SPAN=20
style=3D"FONT-SIZE: 9pt; COLOR: black">&nbsp;|&nbsp;by Eamon Hickey</SPAN=
></H1>
<H1 class=3dmn style=3D"MARGIN: 0in 0in 0pt"><SPAN style=3D"COLOR:=
 black"><FONT=20
size=3D2>&nbsp;<o:p></o:p></FONT></SPAN></H1></DIV>
<DIV class=3DSection1 style=3D"MARGIN: 0in 0in 0pt"><SPAN=20
style=3D"FONT-SIZE: 9pt; COLOR: black"><FONT size=3D2>Wi-Fi Networking Ne=
ws has=20
this<SPAN class=3d3-4> </SPAN><SPAN class=3D331482323-0305=
2004>brief=20
report on Crsls Wi Fi skr,&nbsp;</SPAN>a keychain-sized device tha=
t scans=20
for active wf (802.11b) networks. It's also handy for measuring signal=20
strength within a given coverage area.<o:p></o:p></FONT></SPAN></DIV>
<H1 class=3DSection1 style=3D"MARGIN: 0in 0in 0pt">
<P class=3dmn style=3D"MARGIN: 0in 0in 0pt"><FONT=20
size=3D2>&nbsp;<o:p></o:p></FONT></P>
<H1 style=3D"MARGIN: 0in 0in 0pt"><FONT size=3D4><SPAN>Gizmd.com<SPAN=20
class=3D130050304-05052004>:</SPAN></SPAN> Best Wi-Fi Signal Finder=20
Yet</FONT><FONT size=3D3>, </FONT><SPAN style=3D"FONT-SIZE: 8.5pt">04/22/=
2004=20
05:19</SPAN><SPAN=20
style=3D"FONT-SIZE: 14pt; COLOR: #666699; FONT-FAMILY: Verdana; mso-bidi-=
font-size: 10.0pt"><o:p></o:p></SPAN></H1>
<P style=3D"MARGIN: 0in 0in 0pt; LINE-HEIGHT: 12pt"><SPAN=20
style=3D"FONT-SIZE: 9pt; COLOR: blue; FONT-FAMILY: Arial"></SPAN></P>
<P class=3dmn style=3D"MARGIN: 0in 0in 0pt"><SPAN=20
style=3D"COLOR: black; FONT-FAMILY: 'Times New Roman'"><FONT=20
size=3D2>&nbsp;<o:p></o:p></FONT></SPAN></P></H1>
<H1 class=3DMsoBodyText style=3D"MARGIN: 0in 0in 0pt"><FONT size=3D2>Glen=
n Fleishman=20
got a hold of the Crsls wf skr, a keychain-sized sniffer to dete=
ct=20
802.11b/g networks and says it's the best yet:</FONT></H1>
<H1 class=3DSection1 style=3D"MARGIN: 0in 0in 0pt">
<P class=3DMsoBodyText style=3D"MARGIN: 0in 0in 0pt"><FONT size=3D2>Push =
the button on=20
signal strength in zero to four LEDs. Keep the button held down and it=92=
s a Wi-Fi=20
dowser, allowing you to move around and see immediate response to differe=
nt=20
signal strengths.</FONT></P>
<P class=3dmn style=3D"MARGIN: 0in 0in 0pt"><SPAN style=3D"COLOR: =
black"><FONT=20
size=3D2><FONT face=3DArial>&nbsp;<o:p></o:p></FONT></FONT></SPAN></P>
<P class=3dmn style=3D"MARGIN: 0in 0in 0pt"><FONT color=3D#000080>=
<SPAN=20
style=3D"FONT-SIZE: 14pt; COLOR: #333399; FONT-FAMILY: Verdana; mso-bidi-=
font-size: 10.0pt"><FONT=20
size=3D4>stargeek<SPAN class=3D130050304-05052004>:</SPAN><SPAN=20
class=3D130050304-05052004>&nbsp;</SPAN></FONT></SPAN><SPAN=20
style=3D"FONT-FAMILY: Georgia"><FONT size=3D2>Best Wi-Fi Signal Finder Ye=
t,=20
</FONT></SPAN><SPAN style=3D"FONT-SIZE: 8.5pt; FONT-FAMILY: Georgia">04/2=
2/2004=20
05:19</SPAN></FONT></P></H1>
<DIV class=3dmn style=3D"MARGIN: 0in 0in 0pt"><FONT color=3D#00008=
0><SPAN=20
style=3D"FONT-SIZE: 8.5pt; FONT-FAMILY: Georgia"></SPAN><SPAN=20
style=3D"FONT-FAMILY: Georgia"><o:p></o:p></SPAN></FONT><FONT=20
size=3D2>&nbsp;</FONT></DIV>
<DIV class=3dmn style=3D"MARGIN: 0in 0in 0pt"><FONT color=3D#00008=
0><FONT=20
size=3D2><SPAN style=3D"FONT-FAMILY: Georgia; LETTER-SPACING: 0.2pt">Chry=
salis=20
previous Wi-Fi signal finders fell short in ways the skr does not. The=
=20
displaying the results instant of a constant active scan--but it can tell=
 Wi-Fi=20
from junk.</SPAN><SPAN=20
style=3D"COLOR: black"><o:p></o:p></SPAN></FONT></FONT></DIV>
<H1 class=3DSection1 style=3D"MARGIN: 0in 0in 0pt">
<P class=3dmn style=3D"MARGIN: 0in 0in 0pt"><SPAN style=3D"COLOR: =
black"><FONT=20
size=3D2>&nbsp;</FONT></SPAN><SPAN style=3D"COLOR: black"><FONT=20
size=3D2>&nbsp;<o:p></o:p></FONT></SPAN></P>
<P class=3dmn style=3D"MARGIN: 0in 0in 0pt"><SPAN><FONT=20
size=3D4>ngdgt.com<SPAN class=3d3-4>: The wf=20
skr</SPAN></FONT>&nbsp;</SPAN><FONT size=3D2>Apr 23, 2004</FONT></P>
<P class=3dmn style=3D"MARGIN: 0in 0in 0pt"><FONT=20
size=3D2></FONT>&nbsp;</P></H1>
<DIV class=3dmn style=3D"MARGIN: 0in 0in 0pt"><FONT size=3D2>There=
 were a=20
couple of&nbsp;credit card-sized&nbsp;wf detectors that came out last y=
ear,=20
signals occupying the 2.4GHz part of the spectrum. He says it=92s the bes=
t of the=20
bunch and that it should be on sale by&nbsp;June.&nbsp;</FONT></DIV>
<H1 class=3DSection1 style=3D"MARGIN: 0in 0in 0pt">
<P class=3dmn style=3D"MARGIN: 0in 0in 0pt"><FONT=20
size=3D2>&nbsp;<o:p></o:p></FONT></P>
<P class=3dmn style=3D"MARGIN: 0in 0in 0pt"><SPAN=20
style=3D"FONT-SIZE: 14pt; COLOR: #333399; FONT-FAMILY: Verdana; mso-bidi-=
font-size: 9.5pt"><A=20
href=3D"http://www.brdbndrprts.com/shnws/42831"></A><A=20
href=3D"http://www.brdbndrprts.com/shnws/42831"><SPAN=20
style=3D"COLOR: #333399; TEXT-DECORATION: none; mso-bidi-font-size: 10.0p=
t; text-underline: none"><FONT=20
color=3D#000000 size=3D4>Wi-Fi skr</FONT></SPAN></A><FONT color=3D#000=
000><FONT=20
size=3D4><SPAN class=3d3-4></SPAN>: </FONT></FONT><A=20
href=3D"http://www.brdbndrprts.com/shnws/42831"><SPAN=20
style=3D"COLOR: #333399; TEXT-DECORATION: none; text-underline: none"><FO=
NT=20
color=3D#000000 size=3D4>Hotspot seeking=20
keychain</FONT></SPAN></A><o:p></o:p></SPAN></P>
<P class=3dmn style=3D"MARGIN: 0in 0in 0pt"><SPAN=20
style=3D"FONT-SIZE: 9.5pt; COLOR: black; FONT-FAMILY: Verdana"><FONT=20
size=3D2>&nbsp;<o:p></o:p></FONT></SPAN></P></H1>
<DIV class=3dmn style=3D"MARGIN: 0in 0in 0pt"><SPAN class=3Dnews1>=
<SPAN=20
style=3D"FONT-SIZE: 9.5pt; COLOR: black; FONT-FAMILY: Verdana"><A=20
href=3D"http://wifntnws.com/archives/003248.html"><SPAN=20
style=3D"COLOR: black"><FONT size=3D2>Wi-Fi Networking News</FONT></SPAN>=
</A><FONT=20
size=3D2> takes a look at the new "</FONT><A=20
href=3D"http://wifntnws.com/archives/003248.html"><SPAN=20
style=3D"COLOR: black"><FONT size=3D2>Wi-Fi skr</FONT></SPAN></A><FONT=
 size=3D2>"=20
and junk interference, something this latest version is apparently much b=
etter=20
at.</FONT></SPAN></SPAN></DIV></SPAN></FONT></SPAN></FONT></SPAN></FONT><=
/DIV></DIV></BODY></HTML>

--= Multipart Boundary _EXTRA_0901041737--

--= Multipart Boundary 0901041737
Content-Type: application/octet-stream;
	name="retail.jpg"
Content-ID: <2183279>
Content-Disposition: attachment;
	filename="retail.jpg"
Content-Transfer-Encoding: base64

/9j/6wJgRVBTAHic7ZjJigIxEIbn/Z/EiwfxoHjQgyfB5aKg4oKouIH7goow
UPAdDJPpZKxMO0N/l5+mO92V6qSWfHwkJCT8d87ns+hmsxGtVqui5XJZNJVK
ic7n8y/HX69X0VarJZrJZJ7G9fv9EGYHYzqdimI/mk6nRYvFomilUhFtNpui
+Xxe1Jw/yv16vf40LpvNiv4VP2Hvcrn0GsfzzJvr2+327Tju4793YzabiRYK
BdHJZBKLHcPhMJbvDgYDUeZvrnvWC/tFi6h1Y0J8Ox6Pqnas12tR1/nzn06n
k6odJp1OR/R+v3uN6/V6Kt/fbreixE3iHvvD9/9pcblcvJ4nv0Gj0VCxI5fL
icblh8ViIcq+0IL4/iqs39CMRiNRbT/YiCs//BWIi6vVKsj749pv2lBva8M+
IK+Hej/5kvxIXW0qcdK3PqaPCYV2PUrfQJ3gWx9QV+CvKLTitA3sob/05fF4
iOJnrXqJ/d9ut799jv7Et37ytaNUKv1oPH7xjWfUM/QttVpNlDxI/WfLU4fD
4el6PB57fd8X376Bde26XogTtrrdjEfcJ451u90vvw9a9bQN7HCNj5zr2NYN
72OezJv97Lre8D/7iPeZ5wb7/d7pfa/iGq/N8wlgv9DPaNdxvucp2rj2pZyP
sU52u50ofvmtOjoufOM1ceS3/ELfHRf0+VHgj9B+0erXtWB/kXdthM4b1Ffk
g3eDvGM7T7fZHeXXKDjPe/d4Rh4mX3FeEhW/8aurn+gD+Q/v7pdXwa9mvWdT
4jv/4b+cL7jCOqB+QUOfbyckJCTExSfQUQHQ/+AAEEpGSUYAAQIBAGAAYAAA
//4AJkNyZWF0ZWQgYnkgSW1hZ2VHZWFyLCBBY2N1U29mdCBDb3JwLv/AABEI
ASwBkAMBIgACEQEDEQH/2wCEAAcFBQYFBAcGBgYICAcJCxMMCwoKCxgREg4T
HBkeHRwZGxsfIy0mHyErIhsbJzYoKy8wMzMzHiY4PDcxOy0yMzEBCAgICwoL
FwwMFzEgGyAgMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEx
MTExMTExMTExMTExMf/EAaIAAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkK
CxAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0Kx
wRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZ
WmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKz
tLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6
AQADAQEBAQEBAQEBAAAAAAAAAQIDBAUGBwgJCgsRAAIBAgQEAwQHBQQEAAEC
dwABAgMRBAUhMQYSQVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEX
GBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5
eoKDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJ
ytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29/j5+v/aAAwDAQACEQMRAD8A+kaK
KKACiiigAooooAKKKKACiiigCK6/485v9w/yrnBXR3X/AB5zf7h/lXOVnMaD
8KWkpagYopeKaKdTELxRSUtABS0lLQAUtJRQAtFJRRYBaPak7UdqLALxRSUd
qACiikpALSUUnSiwBSUZpKACm0uaQ0WASkpaSkMQ11lcma6ytKYmFFFFaCCi
iigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAIrr/jzm/3D/Kub
rpLr/jzm/wBw/wAq5us5jQUtJUsETTzLGvU96SQDBS9q249Pt40+ZA2OpNRy
Q24QlYBgd6pQEZNFaPkRTKoWH7w4ZAf59KQaUrEg+YMd9w5p8gGfS1e/slcZ
xLx23jmmnScchZD7eZ0o5AKdFWzpDdAGPuZTxTDo8xGAij3Mzc/pRyAQUVP/
AGPOR9yMEdB5zHP6Un9jXGMhYgf7vmtj88UcgXIe1HSpv7FuByPJ56gu3FL/
AGHMDjdFj1y2aOQLkGaSrA0OUnBkjA7EbqX+w5T1kjH0Lf40cgXK1HarP9hy
7s+an5t/jTToc4PyyRkZ7swxRyBcr0lT/wBh3X3fMjxjht7Z/Kk/sS7wTmIE
dAJW5/SjkAgpKlOmXMa72VBjjaJXx+eKng06aIhzbhww6CTO388UuQLlKkq9
DFGXnUYDqOQ6/d9OKz53kjbDhAT0wODRyBcWkpiSb1zjFPrNqwxDXW1yVdbV
0wYUUUVoIKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAiuv
+POb/cP8q5uukuv+POb/AHD/ACrm6znuNBV7SB/pZ/3TVA9K0dHH+kufRKI7
gaVxJtAUfkKigTzmLEq0GMAddx75pty7CRioY47YqWdSkEcEGELHaMDoO9ao
kc9zbwkI0irjoKadQtAB+/U5OOOaWKyt4lwIlJ7lhkmphGigAIoA9BRoBAb6
3HHmH/vk0h1G2A++3/fB/wAKsbV/uj8qNq+go0GVTqlqDje2f9w0h1W1UgEv
/wB8GppJQnQYqubog9cUWAf/AGnbkZAkI9kNH9pQAgbZef8ApmazJPEunxKz
NcsVU4LxozLn6gEVXfxtoUfDaiAfQq3+FAGyNWt2TcEuCB/0xb/Cj+1IdpYQ
3OB/0wb/AArnLjxlpclvNNHq8SRRA/u0cebIfQA8gfhXO2njuKK6Lm9vGVj9
xyGVfz5/Wk2kI9FGqwn/AJZXI+sDD+lSLfxuuRFPj3jIrnF8f6EgVLi9MUpA
yhjc4/EDFO/4Tzw6ScarHx14bj9KYHQHUIwB+6n54/1RpRfIWAEM/wD37NVL
LV7W/t1mtLqKaNhkNG4Iq0LjnG6gY77YAceTN/3xS/axj/Uzf981JHIHFPpA
VJNQjRfmt7gj0ERNRLf2pP8AqbiMHuY2UVo0nanoBUktoLy1xFKwydyyK2SD
WDPH5hmjkXDRkjPv/wDXH862Zs2eqwOjBYrjKOv+11BH60moQM9xvUgDaM0C
ObgY5Ix1qyOlReUI55FHQGpV6VjNDQlddXImuup0xsKKKK0EFFFFABRRRQAU
UUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUARXX/AB5zf7h/lXNV0t1/x5zf
7jfyrmqznuNAa09FH7yU+wrL71q6L/y2/D+tEQLMob7TlMDkZ5qWYgXduvqW
/lUMwH2jO4/fXiluJQmpWqkgZz/KtUSSXMhjdMNjrQLtAPmIrH1vUbaJwJJ1
QgEjnk1xeoeJQVPlXQZR2AppaAehza3aQttMgB9Cay7vxbaxcBhn2NeX3evS
OMqzM2P73WsefXGOV38n3/pRZAemX/jmKH7vI9+K56/8bSTpIkcgG8bMHPQ9
a88m1VlYneP+AjFZdxqjY+WRs9aAOk1GW8vr5jcEtsOxRyQoHYe1ReRMo+RG
qhaeN7y0Zf8AR7aRAgXDJ6Drmr0fxQu1BH9l6ecDrsbP86jlAv6bptxdyASo
wWtxvCmI98bPn0rlU+KupbsLY6cgH/TNv/iqX/hbWthfltbAfSNv/iqXKM07
zSrq3ztDHHtWNLNdwtgpIMfWnN8WNcY/8e1gR7wn/wCKprfE7UpIyr6dprZ/
i8o8f+PUcoHXeCvEGyC4tLyNtpZTFKo+dHPHBrdtfHyBzDLIC6naTngkV5PN
451KeNkihtbbd1aCPDD6Ek4/CqdtqcqoPnyPfmrWwrH0Ba+NrX+PKmtyw8S2
d2PlnX8a+fLHWpNoBIx6HofyrZtbyZ+Vl8v2BosB7/HeRSAFSCPWpldWHFeS
aL4gubRsPMGQ8ZY13mk6yt5GoLLux0FFhlnXiqfYZT1S4BWrN+sZkUsVzt7j
ms/xFMv2G24588D6cGruqCMPE7A5wQMH6UCM1442huHRNpGO+e4qqtWZJT++
QgAFRj3FVV61lMaFNddXImuuogNhRRRWggooooAKKKKACiiigAooooAKKKKA
CiiigAooooAKKKKACiiigCK6/wCPOb/cb+VczXTXX/HlN/1zb+Vcx2rOY0Fa
2ifdn+o/rWRWvof3JvqKIiH3UqpOp2jd5i8Z9xWXqN+rapbyKeF64/Grmpys
nRekg5x2rm55AViOex/rWyJZxvjy9m+327CZR8r9T15FcVNqDLnc4zn+E1t/
EmbyruxYKCdrdfwrhpboMuWUhqFsM1JL7cAMkLjjmqktzu6ufzptoqyvFLIR
5WcYIPzeo61o3Ediuwx2ygd8MT/OqUbptB5GFJM23apOPrVUyE+9duttZLaI
psrRmZc7nXnn8azYNNsZZmMlshVQMknaCScDAyO/cnFP2ctPMLo5RpB0IqPc
A3cD1rqrvSCLeWXToINqbmMbqCcDhsFhnI7g4x15FZsIjTTY3+xxS7VJdiCT
1PvWkcPzaJkOdtzIRv3mMblBp24EnHA7c9Knl1GBGZFsIVbpkKeP1pdQN35C
maCKNM8bNmf05qXRSV7jUr9CqXx6cd6A47HFQjJU4IxUeXXkZxWBZdD89TU6
OVHUcVUtAk1xHHNL5aM2C4XO0fSu+b4W6hKJF069guniuGglVh5e0jbyM9R8
4ppAcpFckY2gAita11B2wueB2yRVvSfAeo397cRebAq21wLeUo285PcDpjkc
kitSL4a658rGayIxniQkqME88eimnYQWN6q7QxY+x/8A112OgaqLeRGVlxnH
DVhH4f6tbmLZdWg4VXLORhycEDrke/6VFeaRe6MYDKVdW+86IxCtuYYJOOfl
NMD1fVLpbnRbeQDP79efwNdDqRxFEQoY5wPUcV5VoOqvcW5tHkyA6uF/Tj86
9Uv2P2aHacEkfyqWBz9ywF22DjK5x6UgpL1sXmNv8PJoHSspjQ8111ch2rr6
KY2FFFFaCCiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAIrv
/jym/wCubfyrmK6e7/48pv8Arm38q5es57jQnatfRGCwzE8fMKyDTo7qSAAJ
naWyQO9EBMs6y7iAFXGN+evXrXOSOMIcdj/WtnWpI/ssRJbJfgAdPlNYEr5C
jFaks83+J74ubDB52OP1FcCzgnmu0+KUh+3aeOmEc/qK4oCOOLzJF3ZxW1Cj
Kpe2yBtI2dO1G0FrHbXSKpQOA5ztZWGCDjkeoIzg9QR01mjguYVKqjI2NxyA
Om0nI45HUDPtiuU+02skaq0O0AdagtZZ+Vh3kg8FTirhGMXZy0aKlBtLlV2d
fc29vLfCUbD6EtUEloBbSqH/AHTHJwc8DB59Og/KsCSTVYx5rSz7Qc8SE4/W
q7vd6lmKMSyt3y2cVSrxs5SltsEsPVUlDkd2acl6sNrKyz+ZKzS/dORlxhiT
06dhms1J3itInU5AU8HoeTTn069srFjJbsVySWUg44p8enXM+h/alCCONDnJ
54Jp0sbh4QUnJbNfPohzy/FObjyPv8u5BLrLSxMhhgGRjiJBj6cVHfscD60a
foeo6lE0lrb+ZGvBYsAB+dadt4a1nXkLWtniMHHmO4AP09fwrmeY0Iwn7WaW
nkL6pVbi4xZz6thTzjigOe546Vr6n4R1rR2iW7tCqysER1YFST0GR0/Grkvw
88TW93BbPpjtLPnYEdW6YySQcDqOtcP17DWT9otdtV0LdOa0aMrRVsn1+xj1
Bitk06CdgcYTIzz9K7+ax8KyCS5h8Tyw+Yskgt0mJCsCCoJI3cgeh5AriTp9
34Z8X29vqNks01vNG8ltw+8cHbxkHI/nXWya/pi63YXOm+Ep4JrG6Mk4WPBI
wTtIA49eemOOK6ac4zjzRd0yGrF99O8Gec5i8V3ex5GJzJ0wPlJOM+nOD1x2
qKybw6uuTp/wkN5aWhtk8qZGLbmZcOp+XPUn8AfWpZL7T4WiRfAM8ZAjZmiR
ZNy43FfukdCCT97jBqxqmoQmC4sE8AukjRukUiRh/LLDcCCq8kBvXjA96uwi
vJZeFF06a6tNevJJY4TIULYywICryo5O7tnG01zdrqchi8oOxQncVDHGf8k1
kz2l3ZGMXNvLAZFDp5iFdy+oz1FPt5xG38J+tIZ6L4Mu1k1qOHaOcD6c17JP
qHmyLbnG0Pw3fp/+uvCPAN35niy0jOAWzwB7GvXo5WXUiM5j3kOufrj9aGLq
WL0sbxQoG3bxmlXpUN8f9JQg4G3pnpUq9KymUh/auwrjweK7CiAMKKKK0EFF
FFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAQ3f/HlP/1zb+Vc
vmuou/8Ajxn/AOubfyrlqznuNB2qN2IAx68U/tVebqADRETJtYlP2a3AjUkv
ySP9k1hSEnb06Vs6x532O3AYhA3r1G01hvuCDJzWhLPMPikA17Yf7j/zFcTD
P5ahXUkCu1+KKFr6x29o2/mK4iO5jKgSRZx3FdmEny3alb9RS9C2Ire4iBVc
EcEgYIqWJI4tNZRIY8/eYD3qobtY4tsCYz3NR2941upjlUPG1TiJRltv5HpY
StThL3uxoWFxaWquDdtIrdip4q1bxwx6M7LMYkc5MijJHNZ8NzYIdy2rMfTP
FSWmpfZDLbzxB4jk7TxtryK9GUlePc9jD46jTahUa2aVr6X7vf7i3p99p9gr
q+oNKr/wsh4rQ02OGbw5NHv2QMXG49lz/hVOws4r+XfYaFNLg4Mj/LGp92Jw
K6ODw/PFpM1ndzWdsZA3HmZxn8MfrXHVwtSavBO91vY6qePo07RnKLSjK1r9
baXfco6mksPh62i07aLN2VZHXrtJH862PEsOmQafaW19qM9jbDIUQxkhsAdc
DtTdFt9L0vTnsbvVBPEeNuxeAeo+8a1oH0OawFnqd0t5CvCF4QDjtk7uvuMV
w1MsxUZJqN1GTd01d3669UcNTHUKkW07XitNdLdPQy4vEnhweFTo66pNdyDA
iaWF87t2VGcdjitX4n+JtW8OW2nHSrnyDOzh22Kx4xjqDjrSXFjpCadLb6Ba
6aJJxgs8uHxntgN/MVg/EeXWNehtFbQZoBalmLRyCbg46henTvXNSyeTxdOT
pvku2+ble67LzPLrVk4tX18jhotV1bWfGFrfPItzqTzxhC8YIZgQFyoGCOB2
r0T7N4+0rXL/AFIzafBcXUYabjcrJEqjcBg9mA9eTx1ryoHZeOULhgwKsowR
/hUx1jU2JJv7rAOcmVs5xj+VfXwhGEVGKskcG56sbf4i2k8e7UtPV4FWIjeD
gPtXLYHGNi8nHt1qPTbj4h6tcXkEWoWYfT5/JdJU2gttPYrgjGT839a8rXUL
47Qb2fAxgeaeMdKDqN8lpLbLdTeRK4kkQMcMwyMn35NUFj07VfAfibW4bVr6
/smmt0MS5XYNg27cELkn58YIGK5fxP4Z/wCEXuLaF7xbh5kLErGVA54wT14r
kftU5JJlkz1J3GnCeRsFizY45PSi4Hd/DyVR43sAOnz/APoDV7KCE1ncG+YS
tx69a8K+HU23x5YAjnLjj/cavcXKjWnHIPnNt+uTSewupdvyDOhc/Nt5qaP7
oxVW+G2VASD8vBFWIsbBj0rOZSJhXY1xorsqKYMKKKK0EFFFFABRRRQAUUUU
AFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAQ3f/HjP/wBc2/lXK11V5/x4z/8A
XNv5VylZzGg7VXmIDj6VY7VVuMbqIiYurRoYLbMgzvyBj/ZNZEigADPatbVG
iCW4wxbd36D5TWU+DJWhLPLPikxW/slH/PM/zrhFQkHOK774mqG1az4yoiPf
3rhN4LEKOKa2GQtgLxURYmvSofh5pOoaVpaQaq8OrXtutwIpCGUrhy2FAyMB
eOec4pH+E7JYfvL+OOQO7mc7ivlCJZBlMZDYPr+HenYDzmCXY55A4ru/CGk2
EttPrepBXiQsI4nOQSo689eSAB069cYrN8VeA/8AhFtOgnfUBNO91JbsoTai
7QCDuPqCOP8ACqlitybGNftMJhg6ASeuT/jV0VGVRQb3CakocyR1l1qWoXOF
MpgjI+WOLjavpnrVUQ+pLE9yetdD4Z0i21/TmurrUIraOAhXXGZH/wB0Vu/Z
vDOnKRFYyXjBM77iU8n02rjFfSxVCi+WELteX6s8tupPWUtDhxCiIWIGAM8i
mxbJoydoBHY1vXHiaQ/Jb6Rp8KdAPskbf+h0638UlFbz9D0yQ+v2VAf/AB2u
jmqW+H8TK0e5zUsC5xgCmpdXdowMNzImP4c8flXWSaz4XvP3eoaQbNjwJ7Vy
uPwbg1n6z4bji006npl+l5YhgG3DZImTgZXuMkcis3GjUfLVhZ+a/VFXnFXh
Izp7PT/FWnXRdUg1uBd6yjjzh7nvzjOegORgAg+cFNiASqeCeM13NxaCGO7K
sRJFCpyP9p1Qj8mritWPlahcRMRuSVgT7g187jaUaVVxhsejQm5wTkUecnFG
T70xQSetTKVGBjNchuIqkngCnhSOODSlgVGBj2FCYz1waAOj+HpKeP8ASsDr
KR/46a94nYjWpBj/AJbnn8a8F8Ckp480j3uVH58V7vcE/wBsyHt5p/nUvYXU
v3xBaIqpC4IGanhP7tfpUF6xJjLLg4IxipYWBjXjtUTKROK7OuLFdpRTBhRR
RWggooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigCG8/48Z/+
ubfyrk66y8/48J/+ubfyrk6znuNAelVZz89WTVSc/vDilETDVZQVgURrwTyP
pWVIRn04rV1VpykOQdnP8qx5mwDxWhLPJvitPs1ayUf88j/OuFjuOeOK7T4q
Ef2xZggf6k/zrgx7ULYZqrf3HmROJ5A8QAjbecoB2HpSy6jeuHY3k53Elv3h
5JGDn8KzBJjGalWQMKYxZ726uFZJrmV0LbyrOSC2MZ+tXNNkZdsYJCtyR64q
iVBOas2BxdovoP611YP+NFea/MyrfA/Q7nwreGG8mj5IYAYrqdQMn2UZljQf
3VOD9K47wwXXUJmQDhRnP1rT1G6k87DYUei/419XWpOckoyseRTmox1VzRiX
ThCxkf8AeEcDBqSzNiyMJnAOMAEVzyTCRsHJ/wCBH+lK52Dcpb/vo1yyy2lJ
NOT1ZssVJWslodHZWNtdyFM457c8VJo2nQ2/iy3syQ0E0gUx4wp5A6VzttdO
HBWU5B79fzFdJpEs7+LdIlfBQ3EYz/wICk8POlzPnvHl28xe0jO2lnc5iY7r
bU2PU26E/wDf+OuD8QEjxLqa+l1KP/HjXoMrQxRaoJo2YCAcK2P+W8ftXHeI
5tOPijUsWcxb7XJuYTjBO9skfL9PyPrx4WZSarPS/wDwyO/CK8bXH+FvCU/i
WG/kguUj+xxiQxhGeRwT/CqjJA7+laUPww8WStAF0sjzk3qWlQADj73Pyn5h
wfWrPw0sNXv9auBok1vZSRQ+Y1zPAspQ9PlJB2k5P4Dvit7Q7zxlqmoajbz6
qIZtNgAlDWKSPKhIABG3LcYPNcSd0dLVnY5TxD4F1Dw3plnf3JBinQbwwCmO
QlspjPONvX3Fc6ABxivTdY0LxrrOmrZJdJeaf5UcypIkMOCVZwFA5zjd0wex
GK5bxB4Ju/DnhmDUr+VFuJLnyGtlIYoNgcEkHg4PSmIreDm2+NtH4/5e4/8A
0IV7vcAjVXYHjzOlfPvhKfHjTSCP+fuL/wBCFe/znOosQcHfUvYXU0r4uPL3
nJwe9S25zCnHGBVe8GFiw4brzU1sT5CZ9KzmUi0DxXa1xI6V21OmDCiiitBB
RRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAEN5/x4T/9c2/l
XJV1t7/x4XH/AFzb+VciKzmNC9qpTn96QKuE1QnP75h70oiYupKQYiXU8HgH
6VlTd61NRMe+EKW3YPXp2rLmyWYVbJPIPisf+JxZf9cT/OuCzxgV3vxYGNas
h/0xP864HpQthjgfloDEd677RPAmj6n4O0+9uNVe11K/laG3RiCjOHVQNuM9
GyTnjFOm+EuoQPNE2oW5nSAzpAqnfIAzKQoOM/cz9COKqwzghI2Kuaad10P9
0/zrpPG/gaHw3YW+o2V35lrK0cTRPnejtErnnABHJ/SsDSLYmJrjIwhCY+uT
/SurBfx4+q/Mxr/w36HT6A2Lqc89B061Y1i5eJkEURZmYIqk4yar6A22edgO
cCjVnP2i3LEZMw4/CvsZfGeKvhK//EyDHD2kZ9Pmb+lDPqSj/XWbj0O8f0qX
zeTSq/qCa05BXEs7qYzGKaEIwXcCrbgwrr9KfbrGksCxP2iM4J6fMK5O2wdR
QKmf3RP6iur05wb/AE9+AFmjzxjowrmrr3X6GlMyPEP+j3evR4+6pXH0uI64
jX8f8JJqRIHN1L/6Ea7bxgANV8RY9X/9KY64PxJIB4m1MZ6XUn/oRr5fHu9T
7vyR6uGXulvQ/Feq+G3lfS7oQmXbvBjVwSpyDhgeQehqGTxVqjzalIbn59SB
F0di/vMtu9OOfTFYfmjbt6VGzH0rhOg6yP4heJII4o49UZUiVVQCNOAqlR2/
usR+NVda8X63rthDaajqD3EEbBlRlX7wG0EkDJOOOa5sORTw3HUj2poDc8LO
R4t0gg9LuP8A9CFfQs5H9ptk4O4Zr5z8OyBPE2mNj7tzGf8Ax4V9FXGP7SYn
++KmQupqXYAjiCsSMnqKmtMi3T6VBeMHjjwoUAkcVLaf8e6c1nIpFxTXb1wy
13NOmDCiiitBBRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFA
EF7/AMeFx/1zb+VcjXXXv/IPuP8Arm38q5AVnMEKelUZhulJzyDV09KoyY81
ue9KIMTUXRpYVWMKcNzn6Vmy/eNamptOZIBICEw2OPpWVL95qtiPIviyD/bV
l/1xP86XwZ8O4vFHhm/1CaeWOZCUtFRlAdgMtnPYZXPTgk9sUfFUj+3LMf8A
TA/zNcpaatqGnwNHZ39zbxtyyQysoY+4Boi9BpHZeEvBsHiPS7OefV5rfZqn
2REWX5QCm4mPg/NkD24rZsPh9rT3kb6h4iu5bWeI+ckU7htrI7oNx4bocj3r
y+2vb2GJBb3M0aK/mBUcgBumeO+O9K2q6kqRIL66CR5Ma+a2Fzwcc8VWgM7H
xf4UuPDXhC2ur3UJ7u8a8EbK5JhAMIYYB6kA4yPp2rndMaSfTXlwiosioVRQ
MnDYP6frWZd315cWccNxdTypGRtR5CQvHGB9KfpUsiv5QYhDyV7Ejp/M104K
KeIi/NfmZ15NUmvI6rRJNkkoGByDUmsqJJbd17SjI/CodDIE0h9xzWnqNr9o
t8RvskVtwOM9q+yk7TPEirxMgHnpzU8ZBIBNRLY3m4k3MBwO8R/xqT7HeqoI
ubcg8f6o/wCNbOSISHLIiaqgCn/UnnPvXRWM4Q2zFflEinBPXkVgWFlI12ZZ
5Fd8bRtXAArUysBUHsQcVzVUmrGkdNRfHimLXfEakfxSEf8AgRGa8z8SuT4q
1Qg8fapP/QjXp3xMkUeJNbK8Bx/7UjNeW+ITnxNqRz1uZP8A0I18ljHefyX5
I9ehsZ+c0ozjFIBg0/FchuAA9KCM9KVR6U/bjGRSHYs6S5TWbNv7syH9RX0n
M2b9iB/EK+bbVwlzBgDiRT+tfR5YGZiB3HNJi6mxebjDEXGDnjjHFPs8eQuD
61HdZWGPcwY57HOKdZkeQPqf51MxouCu7rgx0rvKKYMKKKK0EFFFFABRRRQA
UUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAQXv/IPuP+ubfyrjxXYX3/IO
uP8Ark38q44Gs5ghSeKoSEea3+9V09KoO375hj+KkgYaigWeE+ajHa3Cn/dr
Nl6tWhqBiFxDs37tjdcY6rWdIRlqsR5H8Vv+Q3Z/9cP/AGY1wRcgc9K7z4q/
8hqz/wCuJ/nXAP0pIuOxPDcmNBipBdbiQVBqipwo/lSgkGqGWxIHd81Pph/0
v2waz1fBIzV/S/8AX5x2rswC/wBoj6o58T/DfodRpEvltKfcVsedGyt1OR1H
auesWwZB712Oh6RqFnfwS3lg/wBkmwjF8DhuBn05I619diZqnHmZ49CHO+Uw
d7FXI6Y61JHI/wC7jxjnNdf9jtLW1d1sgJNOQwyszqwaRgoUkfUmtTVfsWmv
bRzJH9onneNXFpG5YjaBknGMZ6gVw08w59OQ6auEVPaVzzm1uMXJ3cDnvUrX
I3sgOQDwaseJbT7P4tv4lOESUgHAHb0AArLZgZRtHOMfWvRVpx5u6ON3TsXf
iTceZrd5IMYdQePqleea3h/EF847zuf1rsvHTk3QJ6lFP/oNcTqB36nct6yH
+dfH45WqNen5I9nD6xIZVVXwOmBSdqV23NnPYU30riOglQc4BzUj/dXgcVCh
xTmdcYFAyaEgSxn0Yfzr6PVskntkV82Rtgr9RX0fC52ZxxgH9Kl7Evc3LnYL
ZAhLfNzke1SWZHkDjuainZGt02JtAPPOc8U+0P7r8TUyGi4CMV31efrXoFOm
DCiiitBBRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAEF9/y
Drj/AK5N/KuNHSuyvv8AkHXP/XJv5VxYrOYCk8VnOf37f71aB6Vmyf69uf4q
SAW/eNriERxBSEbJyT3Ws6Q/e4rT1FpzPD5iFV2Nj5cf3azJM5arYjyP4rkD
WbL/AK4n+dcAzfLXoHxWQtrNmR/zxP8AM150+4DFJFrYcn3BS55qJX2qKTzO
aqwXJB1NaWk/8fH/AAGssHitTSR+9J/2P6iu3L/94j6nPif4bOi08gM+SRzX
oqeJ9CM0U1+Bfzq6bZRa+W4Udd/OG7ce1eb2iusbMY2COflbHBxVjkkEA/lX
11ahGra72PFhUcFoeijxPpW9t9xE1x5e2O6EMmVG7OGOd3Pt0qQeKdBbykl8
ssDIxkjhYKuWUkBT/eAPPUV52OnINIwHoa5/qFPuzT28ux6LdeJ9H8i8dJbS
WQxP9mDW7Myk4wp3LjHH0rzue4aa8eZwNzks20ADJPYDpTQh7Bqjm/dLuYHL
cCt6OHhSTUepE5ue5V8Wz+d5L9flA/lXKS/PO7dyxroNecPHCoPRa50/fP1z
XyuYq1eXr+iPXwr9xDcCk9qcVxzSY9BXn2OkTNJnilpCeMUAPQ8gD1r6PtiT
AjZ6qD+lfOETsj5VipPHB7V9G2hJtIiDyY1PH0qXsJ7nQXMjNaIQioA2OBjP
FPssiE59TTbsTi2TzifvcAnpxS2nEZwf4qmQ0XAa9BrzwGvQ6dMGFFFFaCCi
iigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAK9/wD8g25/65N/
KuLB4rtL/wD5Btz/ANcm/lXFdqzmAE8VnSf69v8Aeq+TxWfKR57D3pIBdQRl
uIS0qv8AI3Rs/wB2s9+rc1dvhEs8OyQsdrfw4xytZ7nlvrViPKfis5XWLID/
AJ4n+dcA4V4zxzXd/Fk/8Tmy/wCuJ/nXAbuKSNFsRCImMMKhPBq2pxGB7VFJ
HxlRzVJktDA3y1qaRIPM+dtiDqxBx9KyCPlFWbK5ktZN0YUgjDIwyGHoa2o1
XSmpx6GdSCnHlZ2a6hG1vEjXW+JB+7TJwgPJGO3NPinimbbG+4+grlJ9RkvS
MwxReWMDylxn61WRZ5plhRmy5C4B616LzafY5Vg49zu4Skyjy5N3uOR+lOmZ
II2d2OFGTkEVnWMP2CNrRZg7wnaxHY9cU3UrtrXT3mkRZRkDY/RvY170ZRdD
23TlucDTU+TzLUOp2sqbkmU46ru5FSi9tHT52XHuc1zt7p9jcaMmsaRugZGC
XFvuJ2H1B9DVWzKT27/a5pFAjYgqAfmAO3Oe2a8JZs7/AA/id/1RdyxrlzDN
dH7OQURQOBgVkZ5HrROZEEYLfKVDAVGGIxXn4iu60+ZnTSpqEbImJ5xSZAqN
mO7igNWBqOYg8YpuR3pM80vGaQDkI3CvomwIOnQnpmFT/wCOivnQcMK+iNPY
f2VATwPIU/8AjopMXU6WaMRwKPMRzn+E9KfaY8s4/vVFOIVhUI7Oc85XFPtD
8hx61EhourXolecqa9Gp0wYUUUVoIKKKKACiiigAooooAKKKKACiiigAoooo
AKKKKACiiigAooooAr3/APyDbn/rk38jXEdq7fUP+QZc/wDXJv5GuHrOYAel
UJ8ecfrV09KoTn98aEA2+eNpYQkQQ7Wyck56VnueWrSvzcFoDLnZtOOntWY/
3mqhHlHxZ/5Clif+mTfzrz7PFeg/Fj/kKWH/AFyb+dedk4ojsWth4+6MUmeK
aGwKYW5pgKU6U5AQRQMECgYB4pkksP3HPvitfwreQ2PiuwuJ4leNZMENjGSC
AfwJB/CsZDiL6mu0+GngOXxvrUqOzR2duuZZV4IJB24/EUpbCbsYsF2+n6zd
W92rKzykkkdDmk1u7F3AFjJMYPJxXaeObbw63iGDRZbgx6hYxCKa+jTKyHnh
gO4GOfXI6AAUz4d8O29mfP8AEiTgjiO3t2LH2OcAfrXZHMav1f2HQx+rwc/a
HN6DEq+F9enlbCeWiIp7sW/pj9ay4WBgdParmtX6eXHpllE0NjC24Bj80jf3
mrMhf5setcS7m45mE0cYYY2Jt+vJpjRDbkelLGMZFPb7hpgivINrkdqTbxwK
dLy+fbtTOQKBi0CmjOaeM4wO9IYDqK+htNIOiwE5x9mXP/fIr58TaFIK5J6H
0r6C0vA0G3JXI+zLx/wEUmSzpJ/I8lRFvznndipbXHl/jUM8kbKoSIJz6k1N
a8R/jUyGiyK9IrzcYr0inTBhRRRWggooooAKKKKACiiigAooooAKKKKACiii
gAooooAKKKKACiiigCvqH/IMuv8Ark38jXC9q7nUf+QXdf8AXFv5GuFzUSAD
0qhcH9+1XSaoXP8Arj9BSQmNvFjDQFZdzYPG3HaqTfeb61au5I/9GCxYOSN2
f9mqjnDNVMDyb4tNjVbAf9Mm/nXnh5FegfFw/wDE2sP+uJ/nXnobihbFIMn0
pMUuaWmMUdKUUoXjpRiglirxHj3Ne7fBqXT9K8HXrzXyw3M7+bgngKBgZ/HP
5ivGLawa70yaWHDSQnLJ3x6/59/Smx6pfWoZY7qVMpsbDHlcYx9MUOzJauX3
mk1DVbrUZvv3ErSc+5zU4GAcVVsMi0QH649K0VjBQNkD1oKMzVbR5lSSNMkc
HFZ01nNaeQ0q4E0YkT6ZI/pXSBgxCIQaj1y48/SbKGSGJBa7kSRR8zgnOD7A
k0COcTuak6jFNXhcCtzw5ZSXzXkUVrBO5iwPNONpz1Bxj88fUUxnPONuPpUZ
r0iDTbg2wUeHNNkZcBd8yEtjHPH59f65qWugXdrHJDLodlKMsSJLlMrkjHPX
j69O1Kw0cEOtOrv7TToWmu4l0GwRocKxlnOMYJJHHI9/pWUvgvUL5pLuBLaG
BzuRDMMLk8L+AP6UrDOXA5r6E0fI8O2hwD/oqcH/AHRXhF5YyWNw8EwAkQDO
DkcjNe9aGG/4R6yK/e+zR4x/uihiZ0E0pk2gxov+6uKmtxiP8ahnMx8vzSxG
Plz6VPAP3QqJAiYCvSa83Ar0inTBhRRRWggooooAKKKKACiiigAooooAKKKK
ACiiigAooooAKKKKACiiigCtqP8AyC7r/ri/8jXB54rvNR/5BV3/ANcX/ka4
AGokA4niqN1/rPwq2TxVK5+/+FJALdtOIYA64jPT5cdqosOScVaulASAiVW/
2Rn0psVlc3EMrQoWC4zg9Pw79KqxJ4z8XB/xN7ADOPJP8688A5r33xh4Oi8S
6aF81YruLJibqM+h9q8qm+H3iGGQobEtjujAihO25SOZCjPJI+lKBiuh/wCE
G8QDk6dJ+lA8Ea//ANA6X8qLjuYSnAprEiuhHgvXgOdNm/Km/wDCFa9/0Dpf
youDMS1vJ7O5WeByrD071pWq2mqTnzWELnoBgAmrY8Fa7j/kHSflTv8AhCtc
J40+QU7oRL9jlgXJhcqOhXlfzFEcm7gRMXJxtAzmli8L+J7cjybedSPQ1K+h
+MZUKsk5U9RupAJLdi0T/SFSP/Y/i/8ArVgX1+97NuIwg4Va1D4L8RO257CR
j7kU4eCde/6B7/mKLoDABwMVe0y8s7SSRrywF2rLhVMjJtPrxWj/AMITr3T+
z3/MUh8E6/njT3/MUXKTF/tzRBMrL4eAUZOPtT/z/wA9vxRdf0wXMztoiNDI
EHlmU5XaD0bGeTgn6Un/AAhOv/8AQPf8xTv+EI1/H/IPf8xRzDuhW8QaRuLR
eH4o23qwJmZuAQSMHjnGPxqxH4m0zB3eH4TnkqszBc4wSF5A/pVf/hCdeA50
9/zFC+DNf6DT3p3C6K+rXunXcEIstPNrKM+ZiQsp9Ote2aArf2Bp6N8rfZ4x
zxj5RXnnhr4dXsl7HcasixwociEHJc++Ogr1BIxbpmTCKMDjtSZLfY0Jl2eW
d6tkdj0q1Af3QqpKqAoEfd+GKswnES1EgRYB4r0mvNAeK9Lp0wYUUUVoIKKK
KACiikJxQAtFNLhRkkCq4vDKWEERk2nBI4H60AWqKqfarnfs+xvnGeox+ecV
JFcF3KPGUcDO00AT0UUUAFFFFABRRRQAUUUUAFFFFAFbUv8AkFXf/XF/5GvP
s16DqX/IJu/+uL/yNeeZqJAKTxUW2KSUq23IGfmJFPNRsaSYD3jjaNUaRdi9
BuOB+lS297b2lrLCI1bzBgtlsiqTHioHbjinzAOlW2Lkgj/gRP8AQVWkWD/n
pCPxb/CmyNxVSU1PMIc6Wv8AFcR/QBv8KryR2x+7cQge+7/CoZKgYUcwE/l2
4/5eof8AvljTCLMHm7X8ImP9arstRlaXMBcBsO9y/wCEB/8Aiqd5mnD/AJby
f+A//wBlWfto49KOYZoiXTx/y3f8bb/7KgPp+f8Aj4f/AMBv/sqztwHalDj0
o5gNPdp+eJ2+n2c//FU4tppHDtn/AK5N/wDFVliQelOEg9KOYDSAsT0mI/4A
f/iqeEsu0+Pqp/xrMDinBhRzAaQjtz0uox9Vb/CnrHFji8t/xD//ABNZysKe
CKOYRoiKM9bq3P4sP5rUq28R6TQH/toBWauM1OmOKOZDN/TjZ2brK8cMzD+F
pV20kyR3M7uFQBmyVEi4rJjIzVqMinzBY0DBE2N3BHpIo/pSRY2DHT3OagQi
plOBxSbuOxMDxXp1eXg16hVUwYUUUVoIKKKKACqmpXDWti0qjkVbqG7hE9s0
ZHBFAFZ7W1ji33dwWBx8zvtH4Yps7s9gh0to0Qv8zjACjv1/Cq9u3m6cYpBm
Wzbv3X/9WfyqNI4JC9w8BlPmeXFCvRmxnJ/D+VAD/t8kVg0S3iz3Och0XIA+
vQ1bjlMotLjAzIm1iPX0/nTRGQqpd/YokPSILyB7HI5/CgW/2Oz2MQVSbMXP
UH/9ZoA0aKKKACiiigAooooAKKKKACiiigCtqX/IJu/+uL/yNefY4r0HUv8A
kE3f/XF/5GvPe1TJANYVC2fSrIAIpNoPapsIoPn0qB8+lahiU9qaYUI6UrDM
ZgfSoHQntW4bePH3aabaL+7SsI55oSR0qI27eldIbaL+7QLaLH3aVgOXNo56
Cm/YpMdDXV/Zov7tKLaL+7TsByX2GT0o+wS+ldeLaL+7S/Zov7tKwzj/ALBL
/dpPsMv92uyFtF/dFH2WL+7RYDjfsUv92k+xyf3a7T7LD/cpPskP9yiwWON+
yyf3aBbOP4a7D7HD/cpps4f7tFgOTELgfdNOETD+GunNnD/dpptIc/dpWA5x
VYdqeu4djW8bSHP3aT7LEB92iwGOrsD0q1FKeOKu/ZYs/dpRBGOgp2GMjk4q
wj8UwRKBwKeFAoAkDV6pXlIAFerVcAYUUUVoIKKKKACkNLSGgDKuAbHU47oc
RP8AJJ7D1qe2ihsd9uLtd0rEopIyOOMetXGVWGGAIqA2FqUKiCMA9QFxQBQG
lTNEUkSEMfvysSxPvU1uiTzRrFlra3XahP8AEfX/AD71N/Z1uQAwd1H8LuWH
5E4q0qhVAUAAdhQB/9k=

--= Multipart Boundary 0901041737--


