From ladymrs@hotmail.com Wed Feb  4 15:18:52 2004
Return-Path: <ladymrs@htmal.com>
Received: from psszone01 ([220.85.210.40])
	by seagrss.example.com (8.12.8/8.12.8) with SMTP id i1501w8m026266
	for <exp@example.com>; Wed, 4 Feb 2004 19:01:59 -0500
Message-Id: <200402050001.i1501w8m026266@seagrss.example.com>
From: ladymore <ladymrs@htmal.com>
To: exp@example.com
Subject: =?euc-kr?q?(=B1=A4=B0=ED)=B9=CC=B1=B9=C1=F7=B9=E8=BC=DB...=B0=C7=B0=AD=BD=C4=C7=B0=B0=FA_=B4=D9=C0=CC=BE=EE=C6=AE_=C1=A6=C7=B0=B8=A6_=BC=D2=B0=B3=C7=D5=B4=CF=B4=D9._@?=
Content-Transfer-Encoding: quoted-printable
MIME-Version: 1.0
Content-Type: multipart/related;
  boundary="def67978-b4e7-4853-987a-b20e2bc5050e"
Reply-To: ladymr <ladymrs@htmal.com>
Date: Thu, 05 Feb 2004 08:18:52 +0900

This is a multi-part message in MIME format
--def67978-b4e7-4853-987a-b20e2bc5050e
Content-Type: text/html; charset=euc-kr
Content-Transfer-Encoding: quoted-printable

<HTML>
<HEAD>
<TITLE>spam_mail6</TITLE>
<META HTTP-EQUIV=3D"Content-Type" CONTENT=3D"text/html; charset=3Deuc-kr">
</HEAD>
<BODY BGCOLOR=3D#FFFFFF LEFTMARGIN=3D0 TOPMARGIN=3D0 MARGINWIDTH=3D0 =
MARGINHEIGHT=3D0>
<TABLE WIDTH=3D595 BORDER=3D0 align=3D"center" CELLPADDING=3D0 CELLSPACING=3D=
0>
	<TR>
		<TD COLSPAN=3D2>
			<a href=3D"http://www.ldymr.com" target=3D"_blank"><IMG SRC=3D=
"http://www.ldymr.com/ad_mail07/imgs/mail7_01.jpg" ALT=3D"" WIDTH=3D595 =
HEIGHT=3D24 border=3D"0"></a></TD>
	</TR>
	<TR>
		<TD COLSPAN=3D2>
			<a href=3D"http://www.ldymr.com" target=3D"_blank"><IMG SRC=3D=
"http://www.ldymr.com/ad_mail07/imgs/mail7_02.jpg" ALT=3D"" WIDTH=3D595 =
HEIGHT=3D51 border=3D"0"></a></TD>
	</TR>
	<TR>
		<TD COLSPAN=3D2>
			<a href=3D"http://www.ldymr.com" target=3D"_blank"><IMG SRC=3D=
"http://www.ldymr.com/ad_mail07/imgs/mail7_03.jpg" ALT=3D"" WIDTH=3D595 =
HEIGHT=3D161 border=3D"0"></a></TD>
	</TR>
	<TR>
		<TD>
			<a href=3D"http://www.ldymr.com" target=3D"_blank"><IMG SRC=3D=
"http://www.ldymr.com/ad_mail07/imgs/mail7_04.jpg" ALT=3D"" WIDTH=3D173 =
HEIGHT=3D166 border=3D"0"></a></TD>
		<TD>
			<a href=3D"http://www.ldymr.com" target=3D"_blank"><IMG SRC=3D=
"http://www.ldymr.com/ad_mail07/imgs/mail7_05.jpg" ALT=3D"" WIDTH=3D422 =
HEIGHT=3D166 border=3D"0"></a></TD>
	</TR>
	<TR>
		<TD>
			<a href=3D"http://www.ldymr.com" target=3D"_blank"><IMG SRC=3D=
"http://www.ldymr.com/ad_mail07/imgs/mail7_06.jpg" ALT=3D"" WIDTH=3D173 =
HEIGHT=3D163 border=3D"0"></a></TD>
		<TD>
			<a href=3D"http://www.ldymr.com" target=3D"_blank"><IMG SRC=3D=
"http://www.ldymr.com/ad_mail07/imgs/mail7_07.jpg" ALT=3D"" WIDTH=3D422 =
HEIGHT=3D163 border=3D"0"></a></TD>
	</TR>
	<TR>
		<TD>
			<a href=3D"http://www.ldymr.com" target=3D"_blank"><IMG SRC=3D=
"http://www.ldymr.com/ad_mail07/imgs/mail7_08.jpg" ALT=3D"" WIDTH=3D173 =
HEIGHT=3D163 border=3D"0"></a></TD>
		<TD>
			<a href=3D"http://www.ldymr.com" target=3D"_blank"><IMG SRC=3D=
"http://www.ldymr.com/ad_mail07/imgs/mail7_09.jpg" ALT=3D"" WIDTH=3D422 =
HEIGHT=3D163 border=3D"0"></a></TD>
	</TR>
	<TR>
		<TD>
			<a href=3D"http://www.ldymr.com" target=3D"_blank"><IMG SRC=3D=
"http://www.ldymr.com/ad_mail07/imgs/mail7_10.jpg" ALT=3D"" WIDTH=3D173 =
HEIGHT=3D170 border=3D"0"></a></TD>
		<TD>
			<a href=3D"http://www.ldymr.com" target=3D"_blank"><IMG SRC=3D=
"http://www.ldymr.com/ad_mail07/imgs/mail7_11.jpg" ALT=3D"" WIDTH=3D422 =
HEIGHT=3D170 border=3D"0"></a></TD>
	</TR>
	<TR>
		<TD>
			<a href=3D"http://www.ldymr.com" target=3D"_blank"><IMG SRC=3D=
"http://www.ldymr.com/ad_mail07/imgs/mail7_12.jpg" ALT=3D"" WIDTH=3D173 =
HEIGHT=3D170 border=3D"0"></a></TD>
		<TD>
			<a href=3D"http://www.ldymr.com" target=3D"_blank"><IMG SRC=3D=
"http://www.ldymr.com/ad_mail07/imgs/mail7_13.jpg" ALT=3D"" WIDTH=3D422 =
HEIGHT=3D170 border=3D"0"></a></TD>
	</TR>
	<TR>
		<TD COLSPAN=3D2>
			<IMG SRC=3D"http://www.ldymr.com/ad_mail07/imgs/mail7_14.jpg" WIDTH=3D=
595 HEIGHT=3D114 ALT=3D""></TD>
	</TR>
	<TR>
		<TD COLSPAN=3D2>
			<IMG SRC=3D"http://www.ldymr.com/ad_mail07/imgs/mail7_15.jpg" WIDTH=3D=
595 HEIGHT=3D113 ALT=3D""></TD>
	</TR>
	<TR>
		<TD COLSPAN=3D2>
			<IMG SRC=3D"http://www.ldymr.com/ad_mail07/imgs/mail7_16.jpg" WIDTH=3D=
595 HEIGHT=3D115 ALT=3D""></TD>
	</TR>
</TABLE>
<table border=3D0 cellpadding=3D0 cellspacing=3D0 width=3D595 align=3D=
"center" style=3D"font-size: 9pt; line-height: 150%">
	<tr>
		<td>=B1=CD=C7=CF=C0=C7 =C0=CC=B8=DE=C0=CF=C1=D6=BC=D2=B4=C2 =C0=CE=C5=CD=B3=
=DD=BC=AD=C7=CE=C1=DF=BE=CB=B0=D4=B5=C7=BE=FA=C0=B8=B8=E7, =B8=DE=C0=CF=C1=D6=
=BC=D2=C0=CC=BF=DC=C0=C7 =BE=EE=B6=B0=C7=D1 =C1=A4=BA=B8=B5=B5 =B0=A1=C1=F6=B0=
=ED =C0=D6=C1=F6 =BE=CA=BD=C0=B4=CF=B4=D9.<br> =B8=DE=C0=CF=BC=F6=BD=C5=C0=BB =
=BF=F8=C7=CF=C1=F6 =BE=CA=C0=BB=B0=E6=BF=EC <a href=3D=
"mailto:ldymr@nvr.com">[=BC=F6=BD=C5=B0=C5=BA=CE]</a>=B8=A6 =B4=AD=B7=AF=
=C1=D6=BD=CA=BD=C3=BF=E4.. =B0=A8=BB=E7 =C7=D5=B4=CF=B4=D9. If you feel that =
this information is not what you want, please click [HERE] requesting to be =
removed. Thank you, and we apologize for any inconvenience.</td>
	</tr>
	<tr><td>&nbsp;</td></tr>
</table>
</BODY>
</HTML>
--def67978-b4e7-4853-987a-b20e2bc5050e--


