From tiffany21action@hotmail.com Mon Feb 23 06:25:12 2004
Return-Path: <mmimcha@hotmail.com>
Received: from e.com (ns.lefco.co.jp [210.162.221.66])
	by leggite.e.com (8.12.8/8.12.8) with SMTP id i1NETCVg022171
	for <en1k@example.com>; Mon, 23 Feb 2004 06:29:12 -0800
To: <en1k@example.com>
From: "jesph" <tffn21ctn@htmal.com>
Date: Mon, 23 Feb 2004 14:25:12 GMT
Message-Id: <1077546312-23378@excite.com>
Sender: krn1crrll@htmal.com
Subject: Super Cheap V-!-A-G-R-A!!
Content-Type: text/plain;
Status: RO

Starting at $2.50 a dose!!

http://prescrbdmds.com/gv/indx.php?pid=eph9106

Isn't $2.50 worth it for you and your lady?!








rufus bobcatelliot jared amanda1 nautica sarah1 japan 
metallic metallicgray chance wolfMan
oranges young philip 


