From mri-srvce@fstmal.gr Mon Aug  2 08:53:44 2004
Return-Path: <root@77qq.net>
Received: from 77qq.net (S0106000f662071da.vc.shawcable.net [24.81.14.82])
	by leggite.example.com (8.12.8/8.12.8) with ESMTP id i72Ft8gE010695
	for <exp@example.com>; Mon, 2 Aug 2004 08:55:21 -0700
Received: from 77qq.net (77qq.net [127.0.0.1])
	by 77qq.net (8.12.10/8.12.10) with ESMTP id i72FrjjM013257
	for <exp@example.com>; Mon, 2 Aug 2004 08:53:45 -0700
Received: (from root@localhost)
	by 77qq.net (8.12.10/8.12.10/Submit) id i72Frib7013231;
	Mon, 2 Aug 2004 08:53:44 -0700
Date: Mon, 2 Aug 2004 08:53:44 -0700
Message-Id: <200408021553.i72Frib7013231@77qq.net>
To: dcl@example.com
Subject: =?ISO-2022-JP?B?TVJJGyRCRDQ6OiVsJV0hPCVIGyhCIHZvbC4zOBskQiEhKCFGQ0pMSEco?=
 =?ISO-2022-JP?B?IRsoQg==?=
MIME-Version: 1.0
From: mri-srvce@fstmal.gr
Reply-To: mri-srvce@fstmal.gr
Content-type: text/plain;
  charset=JIS
Content-Transfer-Encoding: 7bit


━━━━━━━━━━━━━━━━━━━━━━━━━ 4,313,786部発行 ━

           MRI調査レポート vol.38　─特別版─

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
□今回のもくじ
■夫、人妻であることを忘れたいオトナ急増中！
　●サイト会員へ電話取材！　完全匿名で語られたオトナのホンネ

■最後にはやっぱり、マメな男がトクをする
　●出会いコミュニティサイト管理人だからわかる、今のホント

・・。・゜★・。・・。・゜★・。・・。・゜★・。・。・゜★・。・・。・゜

┏━━━━ 夫、人妻であることを忘れたいオトナ急増中！ ━━━━┓
　　　　　　　　　　http://7qq.net/mrs/1/
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
  サイト管理者の協力で、匿名を条件に現女性会員への電話取材の許可を得て
  直接取材しました。おとなの女性が主催する出会いサイト裏事情つきです。
　  内容はコチラ-----------http://7qq.net/mrs/1/


┏━━━━━ 最後にはやっぱり、マメな男がトクをする ━━━━━┓
　　　　　　　　　　http://77qq.net/mrs/2/
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
　サイト管理者との、メールでのＱ＆Ａで現在の出会いコミュニティ状況
  攻略法などを調査しました。若者の出会い事情を網羅しています。
　　内容はコチラ-----------http://7qq.net/mrs/2/

■------------------------------------------------------------------■
　　私ども（有）出会い調査システムでは、弊社独自のコネクションや
　　精鋭取材陣による直接の取材によって、皆さまにお勧めできる出会い
　　コミュニティの紹介をしております。
■------------------------------------------------------------------■
　　弊社では本ホームページの成り立ち、弊社の考え方にご賛同いただける
　　広告主様を募集いたしております。お気軽にお問い合わせください。

　　　　　（有）出会い調査システム　



