#//------------------------------------------------------------------------
#//
#// Makefile to build the machine independent java runtime library
#//
#//------------------------------------------------------------------------


#//------------------------------------------------------------------------
#//
#// Specify the depth of the current directory relative to the
#// root of NS
#//
#//------------------------------------------------------------------------
DEPTH= ..\..

#//------------------------------------------------------------------------
#//
#// Define any Public Make Variables here: (ie. PDFFILE, MAPFILE, ...)
#//
#//------------------------------------------------------------------------

DLLNAME		= sm$(MOZ_BITS)$(VERSION_NUMBER)
PDBFILE		= $(DLLNAME).pdb
MAPFILE		= $(DLLNAME).map
DLL		=.\$(OBJDIR)\$(DLLNAME).dll
MAKE_OBJ_TYPE	= DLL

include <$(DEPTH)\config\config.mak>

#//------------------------------------------------------------------------
#// 
#// Define the files necessary to build the target (ie. OBJS)
#//
#//------------------------------------------------------------------------

#//------------------------------------------------------------------------
#//
#// Define any Public Targets here (ie. PROGRAM, LIBRARY, DLL, ...)
#// (these must be defined before the common makefiles are included)
#//
#//------------------------------------------------------------------------

#//------------------------------------------------------------------------
#//
#// Define any local options for the make tools 
#//     (ie. LCFLAGS, LLFLAGS, LLIBS, LINCS)
#//
#//------------------------------------------------------------------------

#LCFLAGS = -DSM_NO_TABLE_DIVISION -DSM_DUMP -DSM_VERIFY=2
LCFLAGS = -DSM_NO_TABLE_DIVISION -DSM_DUMP
!ifndef MOZ_PROF        # assume we use a write barrier when profiling
LCFLAGS = $(LCFLAGS) -DSM_NO_WRITE_BARRIER -DSM_CHECK_PTRS -DSM_DEBUG_HEADER
!endif

LLIBS= $(LLIBS)                                     \
        $(DEPTH)\dist\WIN32_D.OBJ\lib\libnspr21.lib \
        $(DEPTH)\dist\WIN32_D.OBJ\lib\libplds21.lib \

#//------------------------------------------------------------------------
#//
#// Include the common makefile rules
#//
#//------------------------------------------------------------------------

include <$(DEPTH)\config\rules.mak>

install:: $(DLL)
	$(MAKE_INSTALL) .\$(OBJDIR)\$(DLLNAME).dll $(DIST)\bin
	$(MAKE_INSTALL) .\$(OBJDIR)\$(DLLNAME).lib $(DIST)\lib
