/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "domstubs.idl"
interface nsIVariant;

/**
 * Property that extends the navigator object.
 */
[scriptable, uuid(A4B2831D-6065-472F-8A6D-2C9085C74C15)]
interface nsIDOMNavigatorDeviceStorage : nsISupports
{
    // returns an array of nsIDOMDeviceStorage
    nsIVariant getDeviceStorage(in DOMString type);
};

