/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/hwine/cvs_conversion/cvsroot/mozilla/xpcom/tools/xpidl/libidl/libIDL-0.6.5/Attic/lexer.c,v 1.1 1999/05/06 15:03:47 beard%netscape.com Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif

#ifdef XP_MAC
#include <unix.h>
#define YY_NEVER_INTERACTIVE 1
#endif

#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define __IDL_const const
#else
#define __IDL_const
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN __IDL__start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((__IDL__start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE __IDL_restart( __IDL_in )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct __IDL__buffer_state *YY_BUFFER_STATE;

extern int __IDL_leng;
extern FILE *__IDL_in, *__IDL_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		__IDL_less( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the __IDL_less() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define __IDL_less(n) \
	do \
		{ \
		/* Undo effects of setting up __IDL_text. */ \
		*__IDL__cp = __IDL__hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		__IDL__c_buf_p = __IDL__cp = __IDL__bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up __IDL_text again */ \
		} \
	while ( 0 )

#define unput(c) __IDL_unput( c, __IDL_text_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int __IDL__size_t;


struct __IDL__buffer_state
	{
	FILE *__IDL__input_file;

	char *__IDL__ch_buf;		/* input buffer */
	char *__IDL__buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	__IDL__size_t __IDL__buf_size;

	/* Number of characters read into __IDL__ch_buf, not including EOB
	 * characters.
	 */
	int __IDL__n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int __IDL__is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int __IDL__is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int __IDL__at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int __IDL__fill_buffer;

	int __IDL__buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via __IDL_restart()), so that the user can continue scanning by
	 * just pointing __IDL_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE __IDL__current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER __IDL__current_buffer


/* __IDL__hold_char holds the character lost when __IDL_text is formed. */
static char __IDL__hold_char;

static int __IDL__n_chars;		/* number of characters read into __IDL__ch_buf */


int __IDL_leng;

/* Points to current character in buffer. */
static char *__IDL__c_buf_p = (char *) 0;
static int __IDL__init = 1;		/* whether we need to initialize */
static int __IDL__start = 0;	/* start state number */

/* Flag which is used to allow __IDL_wrap()'s to do buffer switches
 * instead of setting up a fresh __IDL_in.  A bit of a hack ...
 */
static int __IDL__did_buffer_switch_on_eof;

void __IDL_restart YY_PROTO(( FILE *input_file ));

void __IDL__switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void __IDL__load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE __IDL__create_buffer YY_PROTO(( FILE *file, int size ));
void __IDL__delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void __IDL__init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void __IDL__flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER __IDL__flush_buffer( __IDL__current_buffer )

YY_BUFFER_STATE __IDL__scan_buffer YY_PROTO(( char *base, __IDL__size_t size ));
YY_BUFFER_STATE __IDL__scan_string YY_PROTO(( __IDL_const char *__IDL__str ));
YY_BUFFER_STATE __IDL__scan_bytes YY_PROTO(( __IDL_const char *bytes, int len ));

static void *__IDL__flex_alloc YY_PROTO(( __IDL__size_t ));
static void *__IDL__flex_realloc YY_PROTO(( void *, __IDL__size_t ));
static void __IDL__flex_free YY_PROTO(( void * ));

#define __IDL__new_buffer __IDL__create_buffer

#define __IDL__set_interactive(is_interactive) \
	{ \
	if ( ! __IDL__current_buffer ) \
		__IDL__current_buffer = __IDL__create_buffer( __IDL_in, YY_BUF_SIZE ); \
	__IDL__current_buffer->__IDL__is_interactive = is_interactive; \
	}

#define __IDL__set_bol(at_bol) \
	{ \
	if ( ! __IDL__current_buffer ) \
		__IDL__current_buffer = __IDL__create_buffer( __IDL_in, YY_BUF_SIZE ); \
	__IDL__current_buffer->__IDL__at_bol = at_bol; \
	}

#define YY_AT_BOL() (__IDL__current_buffer->__IDL__at_bol)

typedef unsigned char YY_CHAR;
FILE *__IDL_in = (FILE *) 0, *__IDL_out = (FILE *) 0;
typedef int __IDL__state_type;
extern char *__IDL_text;
#define __IDL_text_ptr __IDL_text

static __IDL__state_type __IDL__get_previous_state YY_PROTO(( void ));
static __IDL__state_type __IDL__try_NUL_trans YY_PROTO(( __IDL__state_type current_state ));
static int __IDL__get_next_buffer YY_PROTO(( void ));
static void __IDL__fatal_error YY_PROTO(( __IDL_const char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up __IDL_text.
 */
#define YY_DO_BEFORE_ACTION \
	__IDL_text_ptr = __IDL__bp; \
	__IDL_leng = (int) (__IDL__cp - __IDL__bp); \
	__IDL__hold_char = *__IDL__cp; \
	*__IDL__cp = '\0'; \
	__IDL__c_buf_p = __IDL__cp;

#define YY_NUM_RULES 69
#define YY_END_OF_BUFFER 70
static __IDL_const short int __IDL__accept[353] =
    {   0,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        3,    3,   70,   68,    6,   66,   68,   68,   68,   68,
       68,    7,    9,   68,   68,   68,   57,   57,   57,   57,
       68,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,    6,    5,
       68,   68,   57,   68,   61,   60,   68,    6,   66,   68,
        6,    5,    3,    3,    3,    3,    3,    3,    6,    0,
       65,    0,   64,    0,   12,    8,   12,   67,   12,    7,
       11,    0,    0,    9,   53,   55,   54,   57,   59,   57,
       57,   57,   58,   58,   57,   57,   57,   57,   57,   57,

       57,   57,   57,   57,   57,   57,   29,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,    6,    5,    5,    5,    5,    1,
        0,   57,    0,   61,    0,   63,    6,   67,    6,    5,
        5,    5,    5,    5,    3,    3,    3,    3,    3,    3,
        3,    3,    2,   12,    8,    0,   67,   12,    0,   12,
       10,   57,   57,   57,   58,   16,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   38,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,    5,    1,   49,

       57,   62,   67,   63,    5,    3,    3,    2,    0,   12,
       57,   57,   15,   58,   57,   57,   19,   20,   57,   57,
       57,   57,   25,   57,   57,   57,   57,   57,   32,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   50,   57,   57,    5,   57,    5,    3,
       13,   57,   58,   57,   57,   21,   57,   57,   57,   57,
       27,   28,   30,   57,   57,   57,   36,   57,   57,   57,
       57,   42,   57,   57,   57,   57,   47,   57,   51,   57,
        5,   57,    5,    3,   14,   58,   57,   57,   57,   57,
       24,   57,   57,   33,   34,   37,   39,   57,   57,   43,

       44,   45,   57,   57,   57,    5,   57,    5,    3,   58,
       57,   18,   22,   23,   57,   57,   57,   57,   46,   57,
       52,    4,   57,    4,    3,   58,   57,   57,   57,   40,
       41,   48,    4,    4,   35,    4,    4,    4,    3,    3,
       58,   17,   26,   31,   58,    0,    0,    0,   56,    0,
        0,    0
    } ;

static __IDL_const int __IDL__ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    6,    1,    7,    8,
        9,    1,    1,    1,   10,   11,   12,   13,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   15,    1,   16,
        1,   17,    1,    1,   18,   19,   19,   20,   21,   22,
       23,   23,   23,   23,   23,   24,   23,   23,   25,   23,
       23,   26,   27,   28,   29,   23,   23,   30,   23,   23,
        1,    1,   31,    1,   32,    1,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   42,   23,   43,   44,   45,
       46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
       56,   23,   57,    1,   58,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static __IDL_const int __IDL__meta[59] =
    {   0,
        1,    2,    3,    1,    1,    1,    1,    1,    4,    1,
        1,    1,    5,    5,    1,    1,    1,    6,    6,    6,
        6,    6,    7,    7,    7,    7,    7,    7,    7,    7,
        1,    8,    6,    6,    6,    6,    6,    6,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    1,    1
    } ;

static __IDL_const short int __IDL__base[378] =
    {   0,
        0,   57,   49,   59,  104,  162,   64,   66,    0,   75,
       80,   83,  916,  917,  913,  917,   87,   90,   85,   87,
      902,  210,  111,  898,  896,  894,  878,  105,   40,  101,
      877,   94,   96,  111,  109,  150,   97,  151,  152,  153,
       70,  155,  117,  171,  102,  156,  160,  154,   82,  150,
      851,  199,  182,    0,    0,  917,  898,  151,  897,  147,
      224,  232,    0,  903,  892,  234,  207,  845,  900,  177,
      917,  235,  917,  203,  237,  248,  250,    0,  262,  280,
      917,  239,    0,  291,  917,  917,  917,  869,    0,  213,
      224,  248,    0,  864,  211,  246,  186,  240,  256,  263,

      271,  274,  278,  283,  264,  275,  288,  290,  293,  281,
      282,  223,  291,  299,  304,  306,  309,  195,  311,  312,
      315,  316,  313,  317,  356,  322,    0,  344,  850,    0,
      887,  328,  888,    0,  887,  917,  361,  363,  362,  371,
      372,  374,    0,  376,    0,  893,    0,  382,  348,    0,
      349,  845,    0,  379,  390,  384,    0,  392,  375,  394,
        0,  382,  385,  170,  856,  860,  370,  249,  398,  388,
      391,  399,  402,  401,  406,  407,  414,  330,  416,  417,
      408,  418,  420,  419,  859,  422,  426,  423,  429,  433,
      431,  432,  434,  435,  445,  438,  447,  857,    0,  917,

      451,  917,  481,    0,  484,    0,  856,    0,  475,  478,
      473,  463,  856,  852,  465,  467,  854,  853,  468,  470,
      469,  471,  852,  476,  477,  478,  479,  483,  851,  484,
      480,  486,  492,  494,  488,  503,  490,  504,  507,  511,
      512,  506,  513,  850,  515,  518,  842,  521,  551,  841,
      847,  523,  835,  524,  529,  845,  525,  533,  531,  534,
      844,  843,  842,  535,  540,  546,  841,  537,  539,  543,
      547,  840,  552,  549,  554,  550,  839,  563,  838,  564,
      825,  565,  595,  824,  833,  806,  567,  569,  570,  571,
      808,  575,  578,  800,  792,  776,  762,  580,  583,  754,

      746,  719,  588,  592,  593,  709,  581,  624,  657,  642,
      585,  656,  655,  654,  598,  599,  603,  605,  650,  609,
      648,  676,  611,  644,  668,  631,  617,  606,  618,  624,
      616,  608,    0,  603,  496,  649,  658,    0,    0,  466,
      389,  354,   98,   47,  661,  663,  670,  672,  917,  674,
      682,  917,  691,  699,  707,  715,  723,  727,  731,  739,
      747,  751,  759,  767,  775,  783,  791,  795,  797,  805,
      813,  821,  829,  837,  845,  853,  860
    } ;

static __IDL_const short int __IDL__def[378] =
    {   0,
      352,    1,    1,    1,  353,  353,  354,  354,    1,    1,
      355,  355,  352,  352,  352,  352,  356,  357,  352,  352,
      352,  352,  352,  352,  352,  352,  358,  358,  358,  358,
      359,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  352,  360,
      352,  352,  358,  361,  362,  352,  363,  363,  363,  363,
      363,  364,  365,  365,  365,  365,  366,  365,  352,  356,
      352,  357,  352,  352,  352,  352,  352,  367,  352,  352,
      352,  352,  368,  352,  352,  352,  352,  358,  369,  358,
      358,  358,  359,  359,  358,  358,  358,  358,  358,  358,

      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  352,  360,  360,  360,  360,  370,
      352,  358,  361,  362,  363,  352,  363,  371,  363,  364,
      364,  364,  360,  364,  365,  365,  372,  365,  366,  366,
      366,  366,  373,  352,  352,  352,  367,  352,  352,  352,
      368,  358,  358,  358,  359,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  360,  370,  352,

      358,  352,  371,  367,  364,  372,  366,  373,  352,  352,
      358,  358,  358,  359,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  360,  358,  364,  366,
      358,  358,  359,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      360,  358,  364,  366,  358,  359,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,

      358,  358,  358,  358,  358,  360,  358,  364,  366,  359,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  374,  358,  375,  376,  359,  358,  358,  358,  358,
      358,  358,  374,  374,  358,  375,  375,  374,  376,  376,
      359,  358,  358,  358,  359,  352,  377,  377,  352,  377,
      352,    0,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352
    } ;

static __IDL_const short int __IDL__nxt[976] =
    {   0,
       14,   15,   16,   17,   14,   14,   18,   14,   14,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   27,   27,
       27,   28,   27,   27,   29,   27,   27,   30,   27,   27,
       14,   31,   32,   33,   34,   35,   36,   37,   27,   27,
       38,   27,   39,   40,   41,   42,   27,   27,   43,   44,
       45,   46,   47,   48,   27,   27,   14,   14,   49,   52,
       49,   50,   51,   50,   51,   58,   59,   61,   59,   52,
       62,   89,   14,   91,   14,   60,   49,   60,   89,   50,
       51,   64,   16,  125,   66,   16,  126,   67,   68,   71,
       71,   65,   73,   53,   65,   74,   73,   75,   76,   77,

       77,   89,  110,   53,   14,   15,   16,   14,   14,   14,
       14,   54,   14,   14,   14,   21,   14,   14,   14,   14,
       14,   79,   90,   84,   84,   89,   92,   89,   89,   89,
       81,   82,   89,   89,   56,   14,   89,  105,   95,  106,
       89,   97,   89,   98,   96,  101,   81,   82,   89,  114,
       99,  128,  137,  115,  102,  136,  100,  120,  138,  136,
       14,   14,   14,   49,   16,   14,   50,   14,   14,   54,
       14,   14,   14,   21,   14,   14,   14,   14,   14,   71,
       71,   89,   89,   89,   89,   89,   89,   89,  123,  111,
      213,   89,   56,   14,  103,  107,  129,  108,  109,  112,

      121,   89,   89,  124,  104,  122,  113,  116,  151,  131,
      117,   77,   77,   89,  110,   77,   77,   89,   14,   14,
       79,  118,   80,   80,  119,  139,   89,  132,  140,   81,
       82,  168,  136,  142,  135,  148,  162,   73,  149,   83,
      143,   73,   89,  190,   89,   81,   82,   79,  159,  154,
      154,  160,  160,  152,   89,   89,   81,   82,   79,  184,
      155,  155,   77,   77,   83,  163,  166,   81,   82,   81,
      156,   89,   81,   82,  158,  158,  164,   89,  144,   89,
       89,   81,   82,   81,   82,   81,  156,   89,  170,  169,
       79,  216,   80,   80,   89,   89,  167,   81,   82,   81,

       82,   79,   89,   84,   84,   89,   89,  171,  172,   89,
       81,   82,   89,   89,   89,   81,   82,  175,  176,   89,
      177,   89,   89,  128,   89,  173,   81,   82,  181,  174,
       89,  182,  183,  178,  180,   89,  187,   89,  179,  186,
       89,  185,   89,   89,   89,  128,   89,   89,   89,  151,
      151,  191,  196,  188,  189,  193,  195,  125,  192,   89,
      126,   89,  137,  139,  194,  135,  140,  197,  129,  136,
      136,  204,  142,  135,  135,  142,  135,  201,  135,  143,
      143,  227,  143,  148,  143,   89,  149,  160,  160,   79,
      129,  154,  154,  209,  152,  152,  210,  210,   81,   82,

       79,   89,  155,  155,  158,  158,  160,  160,  211,   81,
       82,   81,  156,   89,   81,   82,   89,  144,  215,   89,
      144,  212,   89,  345,  205,   81,   82,   81,  156,   89,
       89,  221,   89,   89,  217,  222,  218,   89,   89,   89,
      219,  220,  224,  225,  223,   89,  226,   89,   89,   89,
       89,   89,  228,   89,   89,  229,  232,   89,  231,  230,
       89,  235,   89,   89,   89,   89,   89,  340,  241,   89,
      245,  234,  233,  238,  236,  243,   89,  237,   89,  242,
      244,  240,   89,  135,  239,  248,  135,  210,  210,  204,
      210,  210,  143,  251,   89,  246,   89,  252,   89,   89,

       89,   89,   89,  255,   89,  254,  257,   89,   89,   89,
       89,   89,  261,  259,   89,   89,  249,   89,  256,   89,
      258,   89,  260,   89,  268,   89,  265,   89,  262,  263,
      269,  264,  266,  270,   89,   89,  267,   89,   89,  271,
      272,  274,   89,   89,   89,  275,   89,  276,  273,   89,
      277,  278,   89,  135,   89,   89,   89,  287,  280,  143,
       89,  288,   89,  279,   89,   89,   89,  291,   89,  282,
       89,   89,  293,  285,   89,  290,  294,   89,   89,  289,
       89,   89,  295,   89,  292,   89,  303,  298,  297,  283,
      300,  299,  296,  302,   89,   89,   89,  135,   89,  301,

       89,   89,   89,  143,  334,  307,   89,  304,  305,   89,
      316,   89,   89,  312,   89,  315,   89,  318,  311,   89,
      313,  314,  317,   89,   89,  319,  135,  323,  320,   89,
       89,  321,  143,  329,   89,  327,   89,   89,  308,   89,
       89,  331,   89,  328,  332,  337,  135,   89,   89,   89,
      343,  135,  338,  342,  344,   89,  324,  338,  330,  337,
      135,  335,  346,  346,  346,  346,  338,  341,  347,  340,
      347,  348,  348,  348,  348,  351,  351,  334,  349,   89,
      349,   89,  349,  351,  351,   89,   89,   89,  326,  325,
      349,   55,   55,   55,   55,   55,   55,   55,   55,   57,

       57,   57,   57,   57,   57,   57,   57,   63,   63,   63,
       63,   63,   63,   63,   63,   70,   70,   70,   70,   70,
       70,   70,   70,   72,   72,   72,   72,   72,   72,   72,
       72,   88,   88,   88,   88,   93,   93,   93,   93,  127,
      127,  322,  127,  127,  127,  127,  127,  133,  133,  133,
       89,  133,  133,  133,  133,  134,  134,  134,  134,  135,
      135,  135,  135,  135,  135,  135,  135,  141,  141,  141,
      141,  141,  141,  141,  141,  145,  145,   89,  145,  145,
      145,  145,  145,  150,  150,   89,  150,  150,  150,  150,
      150,  157,  157,   89,  157,  157,  157,  157,  157,  161,

      161,   89,   89,   89,   89,  199,  199,   89,  199,  199,
      199,  199,  199,  203,  203,  203,  203,  203,  203,  203,
      203,  206,  206,   89,  206,  206,  206,  206,  206,  208,
      208,   89,  208,  208,  208,  208,  208,  333,  333,   89,
      333,  333,  333,  333,  333,  336,  336,  336,  336,  336,
      336,  336,  336,  339,  339,  310,  339,  339,  339,  339,
      339,  350,  350,  350,   89,  350,  350,  309,  306,   89,
       89,   89,   89,   89,   89,   89,   89,  286,   89,  284,
      281,   89,   89,   89,   89,   89,  253,   89,  250,  247,
       89,   89,  214,  207,  146,  136,  202,  200,  198,  165,

       89,   69,  153,  147,  146,  136,  136,  130,   94,   89,
       87,   86,   85,   78,   69,  352,   13,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352
    } ;

static __IDL_const short int __IDL__chk[976] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    2,    2,    4,    4,    7,    7,    8,    8,    4,
        8,   29,    7,   29,    8,    7,   10,    8,  344,   10,
       10,   11,   11,   49,   12,   12,   49,   12,   12,   17,
       17,   11,   18,    3,   12,   19,   18,   19,   19,   20,

       20,   41,   41,    4,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,   23,   28,   23,   23,   32,   30,   33,   37,  343,
       23,   23,   30,   45,    5,    5,   28,   37,   32,   37,
       35,   33,   34,   34,   32,   35,   23,   23,   43,   43,
       34,   50,   58,   43,   35,   60,   34,   45,   60,   58,
        5,    5,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,   70,
       70,   36,   38,   39,   40,   48,   42,   46,   48,   42,
      164,   47,    6,    6,   36,   38,   50,   39,   40,   42,

       46,  164,   44,   48,   36,   47,   42,   44,   67,   52,
       44,   52,   52,   53,   53,   74,   74,   97,    6,    6,
       22,   44,   22,   22,   44,   61,  118,   53,   61,   22,
       22,   97,   61,   62,   62,   66,   90,   72,   66,   22,
       62,   72,   95,  118,   90,   22,   22,   75,   82,   75,
       75,   82,   82,   67,  112,   91,   75,   75,   76,  112,
       76,   76,   77,   77,   22,   91,   95,   76,   76,   77,
       77,   98,   75,   75,   79,   79,   92,   96,   62,   92,
      168,   79,   79,   76,   76,   77,   77,   99,   99,   98,
       80,  168,   80,   80,  100,  105,   96,   79,   79,   80,

       80,   84,  101,   84,   84,  102,  106,  100,  101,  103,
       84,   84,  110,  111,  104,   80,   80,  104,  105,  107,
      106,  108,  113,  126,  109,  102,   84,   84,  109,  103,
      114,  110,  111,  107,  108,  115,  115,  116,  107,  114,
      117,  113,  119,  120,  123,  128,  121,  122,  124,  149,
      151,  119,  123,  116,  117,  121,  122,  125,  120,  132,
      125,  178,  137,  139,  121,  138,  139,  124,  126,  137,
      139,  138,  140,  140,  141,  142,  142,  132,  144,  140,
      141,  178,  142,  148,  144,  342,  148,  159,  159,  154,
      128,  154,  154,  156,  149,  151,  156,  156,  154,  154,

      155,  167,  155,  155,  158,  158,  160,  160,  162,  155,
      155,  158,  158,  162,  154,  154,  163,  140,  167,  170,
      142,  163,  171,  341,  144,  155,  155,  158,  158,  169,
      172,  172,  174,  173,  169,  173,  170,  175,  176,  181,
      171,  171,  175,  176,  174,  177,  177,  179,  180,  182,
      184,  183,  179,  186,  188,  180,  183,  187,  182,  181,
      189,  187,  191,  192,  190,  193,  194,  340,  192,  196,
      196,  186,  184,  190,  188,  194,  195,  189,  197,  193,
      195,  191,  201,  203,  190,  201,  205,  209,  209,  203,
      210,  210,  205,  211,  212,  197,  215,  212,  216,  219,

      221,  220,  222,  216,  211,  215,  220,  224,  225,  226,
      227,  231,  225,  222,  228,  230,  205,  232,  219,  235,
      221,  237,  224,  233,  233,  234,  230,  335,  226,  227,
      234,  228,  231,  235,  236,  238,  232,  242,  239,  236,
      237,  239,  240,  241,  243,  240,  245,  241,  238,  246,
      242,  243,  248,  249,  252,  254,  257,  254,  246,  249,
      255,  255,  259,  245,  258,  260,  264,  259,  268,  248,
      269,  265,  264,  252,  270,  258,  265,  266,  271,  257,
      274,  276,  266,  273,  260,  275,  276,  270,  269,  249,
      273,  271,  268,  275,  278,  280,  282,  283,  287,  274,

      288,  289,  290,  283,  334,  282,  292,  278,  280,  293,
      293,  298,  307,  288,  299,  292,  311,  299,  287,  303,
      289,  290,  298,  304,  305,  303,  308,  307,  304,  315,
      316,  305,  308,  316,  317,  311,  318,  328,  283,  332,
      320,  318,  323,  315,  320,  324,  324,  331,  327,  329,
      328,  336,  324,  327,  329,  330,  308,  336,  317,  337,
      337,  323,  345,  345,  346,  346,  337,  326,  345,  325,
      346,  347,  347,  348,  348,  350,  350,  322,  347,  321,
      348,  319,  350,  351,  351,  314,  313,  312,  310,  309,
      351,  353,  353,  353,  353,  353,  353,  353,  353,  354,

      354,  354,  354,  354,  354,  354,  354,  355,  355,  355,
      355,  355,  355,  355,  355,  356,  356,  356,  356,  356,
      356,  356,  356,  357,  357,  357,  357,  357,  357,  357,
      357,  358,  358,  358,  358,  359,  359,  359,  359,  360,
      360,  306,  360,  360,  360,  360,  360,  361,  361,  361,
      302,  361,  361,  361,  361,  362,  362,  362,  362,  363,
      363,  363,  363,  363,  363,  363,  363,  364,  364,  364,
      364,  364,  364,  364,  364,  365,  365,  301,  365,  365,
      365,  365,  365,  366,  366,  300,  366,  366,  366,  366,
      366,  367,  367,  297,  367,  367,  367,  367,  367,  368,

      368,  369,  369,  369,  369,  370,  370,  296,  370,  370,
      370,  370,  370,  371,  371,  371,  371,  371,  371,  371,
      371,  372,  372,  295,  372,  372,  372,  372,  372,  373,
      373,  294,  373,  373,  373,  373,  373,  374,  374,  291,
      374,  374,  374,  374,  374,  375,  375,  375,  375,  375,
      375,  375,  375,  376,  376,  286,  376,  376,  376,  376,
      376,  377,  377,  377,  285,  377,  377,  284,  281,  279,
      277,  272,  267,  263,  262,  261,  256,  253,  251,  250,
      247,  244,  229,  223,  218,  217,  214,  213,  207,  198,
      185,  166,  165,  152,  146,  135,  133,  131,  129,   94,

       88,   69,   68,   65,   64,   59,   57,   51,   31,   27,
       26,   25,   24,   21,   15,   13,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352
    } ;

static __IDL__state_type __IDL__last_accepting_state;
static char *__IDL__last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define __IDL_more() __IDL_more_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *__IDL_text;
#line 1 "lexer.l"
#define INITIAL 0
/***************************************************************************

    lexer.l (IDL lex scanner)

    Copyright (C) 1998, 1999 Andrew T. Veliath

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public
    License along with this library; if not, write to the Free
    Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

    $Id: lexer.c,v 1.1 1999/05/06 15:03:47 beard%netscape.com Exp $

***************************************************************************/
#line 25 "lexer.l"
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>
#include "rename.h"
#include "util.h"
#include "parser.h"

#define YY_INPUT(buf,result,the_max_size)	do {				\
	if (__IDL_inputcb == NULL) {						\
		if ((result = fread (buf, 1, the_max_size, __IDL_in)) == YY_NULL &&	\
		    ferror (__IDL_in))						\
			YY_FATAL_ERROR ("input in scanner failed");		\
	} else {								\
		union IDL_input_data data;					\
										\
		data.fill.buffer = buf;						\
		data.fill.max_size = the_max_size;				\
		result = (*__IDL_inputcb) (IDL_INPUT_REASON_FILL, &data,	\
					   __IDL_inputcb_user_data);		\
		if (result < 0)							\
			YY_FATAL_ERROR ("input callback returned failure");	\
	}									\
} while (0)

#define tokreturn(token)			do {	\
	__IDL_prev_token_line = __IDL_cur_token_line;	\
	__IDL_cur_token_line = __IDL_cur_line;		\
	return token;					\
} while (0)

#define SELECT_START				\
	/* Parser driven start conditions */	\
	if (__IDL_flagsi & IDLFP_PROPERTIES)	\
		BEGIN (PROP);			\
	else if (__IDL_flagsi & IDLFP_NATIVE)	\
		BEGIN (NATIVE);			\
	/* Global syntax start conditions */	\
	else if (__IDL_flags & IDLF_XPIDL)	\
		BEGIN (XP);			\
	else if (__IDL_flags & IDLF_CODEFRAGS)	\
		BEGIN (CFRG);

#define SELECT_RESTART				\
	SELECT_START				\
	else					\
		BEGIN (INITIAL);

extern void		__IDL_do_pragma			(const char *s);
static int		count_nl			(const char *s);

#ifdef YYDEBUG
extern int				__IDL_debug;
#endif
int					__IDL_prev_token_line;
int					__IDL_cur_token_line;
static int				warn_underscores;
static char *				codefrag_desc;
static GSList *				codefrag_list;
static GSList *				codefrag_list_tail;
#define XP 1

#define PROP 2

#define NATIVE 3

#define CFRG 4

#define CFRGX 5


/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int __IDL_wrap YY_PROTO(( void ));
#else
extern int __IDL_wrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void __IDL_unput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef __IDL_text_ptr
static void __IDL__flex_strncpy YY_PROTO(( char *, __IDL_const char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int __IDL__flex_strlen YY_PROTO(( __IDL_const char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int __IDL_input YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int __IDL__start_stack_ptr = 0;
static int __IDL__start_stack_depth = 0;
static int *__IDL__start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void __IDL__push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void __IDL__pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int __IDL__top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( __IDL_text, __IDL_leng, 1, __IDL_out )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( __IDL__current_buffer->__IDL__is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( __IDL_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( __IDL_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, __IDL_in )) == 0) \
		  && ferror( __IDL_in ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "__IDL_terminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef __IDL_terminate
#define __IDL_terminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) __IDL__fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int __IDL_lex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after __IDL_text and __IDL_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( __IDL_leng > 0 ) \
		__IDL__current_buffer->__IDL__at_bol = \
				(__IDL_text[__IDL_leng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register __IDL__state_type __IDL__current_state;
	register char *__IDL__cp, *__IDL__bp;
	register int __IDL__act;

#line 119 "lexer.l"


	SELECT_START;


	if ( __IDL__init )
		{
		__IDL__init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! __IDL__start )
			__IDL__start = 1;	/* first start state */

		if ( ! __IDL_in )
			__IDL_in = stdin;

		if ( ! __IDL_out )
			__IDL_out = stdout;

		if ( ! __IDL__current_buffer )
			__IDL__current_buffer =
				__IDL__create_buffer( __IDL_in, YY_BUF_SIZE );

		__IDL__load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		__IDL__cp = __IDL__c_buf_p;

		/* Support of __IDL_text. */
		*__IDL__cp = __IDL__hold_char;

		/* __IDL__bp points to the position in __IDL__ch_buf of the start of
		 * the current run.
		 */
		__IDL__bp = __IDL__cp;

		__IDL__current_state = __IDL__start;
		__IDL__current_state += YY_AT_BOL();
__IDL__match:
		do
			{
			register YY_CHAR __IDL__c = __IDL__ec[YY_SC_TO_UI(*__IDL__cp)];
			if ( __IDL__accept[__IDL__current_state] )
				{
				__IDL__last_accepting_state = __IDL__current_state;
				__IDL__last_accepting_cpos = __IDL__cp;
				}
			while ( __IDL__chk[__IDL__base[__IDL__current_state] + __IDL__c] != __IDL__current_state )
				{
				__IDL__current_state = (int) __IDL__def[__IDL__current_state];
				if ( __IDL__current_state >= 353 )
					__IDL__c = __IDL__meta[(unsigned int) __IDL__c];
				}
			__IDL__current_state = __IDL__nxt[__IDL__base[__IDL__current_state] + (unsigned int) __IDL__c];
			++__IDL__cp;
			}
		while ( __IDL__base[__IDL__current_state] != 917 );

__IDL__find_action:
		__IDL__act = __IDL__accept[__IDL__current_state];
		if ( __IDL__act == 0 )
			{ /* have to back up */
			__IDL__cp = __IDL__last_accepting_cpos;
			__IDL__current_state = __IDL__last_accepting_state;
			__IDL__act = __IDL__accept[__IDL__current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( __IDL__act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*__IDL__cp = __IDL__hold_char;
			__IDL__cp = __IDL__last_accepting_cpos;
			__IDL__current_state = __IDL__last_accepting_state;
			goto __IDL__find_action;

case 1:
YY_RULE_SETUP
#line 123 "lexer.l"
{
	char *s = __IDL_text + 2;

	while (isspace (*s)) ++s;
	codefrag_desc = g_strdup (s);
	codefrag_list = codefrag_list_tail = NULL;

	if (!(__IDL_flags & IDLF_XPIDL || __IDL_flags & IDLF_CODEFRAGS))
		__IDL_error ("Code fragment syntax not enabled");
	else
		BEGIN (CFRGX);
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 135 "lexer.l"
{
	__IDL_lval.tree = IDL_codefrag_new (codefrag_desc, codefrag_list);
	tokreturn (TOK_CODEFRAG);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 139 "lexer.l"
{
	char *s;
	GSList *slist;

	s = g_strdup (__IDL_text);
	slist = g_slist_alloc ();
	slist->data = s;

	if (codefrag_list == NULL) {
		codefrag_list = slist;
		codefrag_list_tail = slist;
	} else {
		codefrag_list_tail->next = slist;
		codefrag_list_tail = slist;
	}
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 155 "lexer.l"
{
	int n;
	char *p = __IDL_text;
	char *s;

	while (isspace (*p) || *p == '#') ++p;
	s = p;
	sscanf (p, "%*6s%n", &n); s += n;
	while (isspace (*s)) ++s;

	__IDL_do_pragma (s);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 167 "lexer.l"
{
	char *starttext;
	char *filename;
	char *filename2;
	int line;

	starttext = __IDL_text;
	while (isspace (*starttext)) ++starttext;
	filename = g_malloc (strlen (starttext) + 1);

	sscanf (starttext, "# %d %s", &line, filename);

	if (*filename == '"') {
		filename2 = g_strdup (filename + 1);
		filename2[strlen (filename) - 2] = 0;
		g_free (filename);
	} else
		filename2 = filename;

	IDL_file_set (filename2, line);

	g_free (filename2);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 190 "lexer.l"

	YY_BREAK
case 7:
YY_RULE_SETUP
#line 191 "lexer.l"
{
	sscanf (__IDL_text, "%" IDL_LL "o", &__IDL_lval.integer);
	tokreturn (TOK_INTEGER);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 195 "lexer.l"
{
	sscanf (__IDL_text, "%" IDL_LL "d", &__IDL_lval.integer);
	tokreturn (TOK_INTEGER);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 199 "lexer.l"
{
	sscanf (__IDL_text, "%" IDL_LL "u", &__IDL_lval.integer);
	tokreturn (TOK_INTEGER);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 203 "lexer.l"
{
	sscanf (__IDL_text + 2, "%" IDL_LL "x", &__IDL_lval.integer);
	tokreturn (TOK_INTEGER);
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 207 "lexer.l"
{
	__IDL_lval.str = g_strdup (__IDL_text);
	tokreturn (TOK_FIXEDP);
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 211 "lexer.l"
{
	__IDL_lval.floatp = atof (__IDL_text);
	tokreturn (TOK_FLOATP);
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 215 "lexer.l"
tokreturn (TOK_FALSE);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 216 "lexer.l"
tokreturn (TOK_OBJECT);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 217 "lexer.l"
tokreturn (TOK_TRUE);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 218 "lexer.l"
tokreturn (TOK_ANY);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 219 "lexer.l"
tokreturn (TOK_ATTRIBUTE);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 220 "lexer.l"
tokreturn (TOK_BOOLEAN);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 221 "lexer.l"
tokreturn (TOK_CASE);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 222 "lexer.l"
tokreturn (TOK_CHAR);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 223 "lexer.l"
tokreturn (TOK_CONST);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 224 "lexer.l"
tokreturn (TOK_CONTEXT);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 225 "lexer.l"
tokreturn (TOK_DEFAULT);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 226 "lexer.l"
tokreturn (TOK_DOUBLE);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 227 "lexer.l"
tokreturn (TOK_ENUM);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 228 "lexer.l"
tokreturn (TOK_EXCEPTION);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 229 "lexer.l"
tokreturn (TOK_FIXED);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 230 "lexer.l"
tokreturn (TOK_FLOAT);
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 231 "lexer.l"
tokreturn (TOK_IN);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 232 "lexer.l"
tokreturn (TOK_INOUT);
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 233 "lexer.l"
tokreturn (TOK_INTERFACE);
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 234 "lexer.l"
tokreturn (TOK_LONG);
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 235 "lexer.l"
tokreturn (TOK_MODULE);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 236 "lexer.l"
tokreturn (TOK_NATIVE);
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 237 "lexer.l"
tokreturn (TOK_NOSCRIPT);
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 238 "lexer.l"
tokreturn (TOK_OCTET);
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 239 "lexer.l"
tokreturn (TOK_ONEWAY);
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 240 "lexer.l"
tokreturn (TOK_OUT);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 241 "lexer.l"
tokreturn (TOK_RAISES);
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 242 "lexer.l"
tokreturn (TOK_READONLY);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 243 "lexer.l"
tokreturn (TOK_SEQUENCE);
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 244 "lexer.l"
tokreturn (TOK_SHORT);
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 245 "lexer.l"
tokreturn (TOK_STRING);
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 246 "lexer.l"
tokreturn (TOK_STRUCT);
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 247 "lexer.l"
tokreturn (TOK_SWITCH);
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 248 "lexer.l"
tokreturn (TOK_TYPEDEF);
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 249 "lexer.l"
tokreturn (TOK_UNION);
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 250 "lexer.l"
tokreturn (TOK_UNSIGNED);
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 251 "lexer.l"
tokreturn (TOK_VARARGS);
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 252 "lexer.l"
tokreturn (TOK_VOID);
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 253 "lexer.l"
tokreturn (TOK_WCHAR);
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 254 "lexer.l"
tokreturn (TOK_WSTRING);
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 255 "lexer.l"
tokreturn (TOK_OP_SCOPE);
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 256 "lexer.l"
tokreturn (TOK_OP_SHR);
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 257 "lexer.l"
tokreturn (TOK_OP_SHL);
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 258 "lexer.l"
{
	char *s = g_strdup (__IDL_text);

	/* Get the parenthesized expression (ignoring whitespace) */
	sscanf (__IDL_text, "__declspec %*[(] %[A-Za-z_] %*[)]", s);
	__IDL_lval.str = s;
	__IDL_cur_line += count_nl (__IDL_text);
	tokreturn (TOK_DECLSPEC);
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 267 "lexer.l"
{
	if (__IDL_flags & IDLF_TYPECODES && strcmp (__IDL_text, "TypeCode") == 0)
		tokreturn (TOK_TYPECODE);
	__IDL_lval.str = g_strdup (__IDL_text);
	tokreturn (TOK_IDENT);
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 273 "lexer.l"
{
	__IDL_errorv ("`%s' is not a valid identifier in IDL", __IDL_text);
	__IDL_error ("(Identifiers cannot start with an underscore)");
	__IDL_lval.str = g_strdup (__IDL_text);
	tokreturn (TOK_IDENT);
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 279 "lexer.l"
{
	if (!warn_underscores) {
		__IDL_warningv (IDL_WARNING2,
			   "`%s' underscores within identifiers are discouraged for use "
			   "with C-language IDL mappings", __IDL_text);
		warn_underscores = 1;
	}
	__IDL_lval.str = g_strdup (__IDL_text);
	tokreturn (TOK_IDENT);
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 289 "lexer.l"
{
	__IDL_flagsi &= ~IDLFP_PROPERTIES;
	SELECT_RESTART;
	tokreturn (__IDL_text[0]);
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 294 "lexer.l"
{
	__IDL_lval.str = g_strdup (__IDL_text);
	tokreturn (TOK_PROP_KEY);
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 298 "lexer.l"
{
	__IDL_lval.str = g_strdup (__IDL_text + 1);
	__IDL_lval.str[strlen (__IDL_lval.str) - 1] = 0;
	tokreturn (TOK_PROP_VALUE);
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 303 "lexer.l"
{
	__IDL_flagsi &= ~IDLFP_NATIVE;
	__IDL_lval.str = g_strdup (__IDL_text);
	__IDL_lval.str[strlen (__IDL_lval.str) - 1] = 0;
	tokreturn (TOK_NATIVE_TYPE);
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 309 "lexer.l"
{
	__IDL_lval.str = g_strdup (__IDL_text + 1);
	__IDL_lval.str[strlen (__IDL_text) - 2] = 0;
	tokreturn (TOK_SQSTRING);
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 314 "lexer.l"
{
	__IDL_lval.str = g_strdup (__IDL_text + 1);
	__IDL_lval.str[strlen (__IDL_text) - 2] = 0;
	tokreturn (TOK_DQSTRING);
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 319 "lexer.l"
++__IDL_cur_line;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 320 "lexer.l"

	YY_BREAK
case 68:
YY_RULE_SETUP
#line 321 "lexer.l"
tokreturn (__IDL_text[0]);
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 323 "lexer.l"
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(XP):
case YY_STATE_EOF(PROP):
case YY_STATE_EOF(NATIVE):
case YY_STATE_EOF(CFRG):
case YY_STATE_EOF(CFRGX):
	__IDL_terminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int __IDL__amount_of_matched_text = (int) (__IDL__cp - __IDL_text_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*__IDL__cp = __IDL__hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( __IDL__current_buffer->__IDL__buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed __IDL_in at a new source and called
			 * __IDL_lex().  If so, then we have to assure
			 * consistency between __IDL__current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			__IDL__n_chars = __IDL__current_buffer->__IDL__n_chars;
			__IDL__current_buffer->__IDL__input_file = __IDL_in;
			__IDL__current_buffer->__IDL__buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for __IDL__c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since __IDL__c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( __IDL__c_buf_p <= &__IDL__current_buffer->__IDL__ch_buf[__IDL__n_chars] )
			{ /* This was really a NUL. */
			__IDL__state_type __IDL__next_state;

			__IDL__c_buf_p = __IDL_text_ptr + __IDL__amount_of_matched_text;

			__IDL__current_state = __IDL__get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * __IDL__get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			__IDL__next_state = __IDL__try_NUL_trans( __IDL__current_state );

			__IDL__bp = __IDL_text_ptr + YY_MORE_ADJ;

			if ( __IDL__next_state )
				{
				/* Consume the NUL. */
				__IDL__cp = ++__IDL__c_buf_p;
				__IDL__current_state = __IDL__next_state;
				goto __IDL__match;
				}

			else
				{
				__IDL__cp = __IDL__c_buf_p;
				goto __IDL__find_action;
				}
			}

		else switch ( __IDL__get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				__IDL__did_buffer_switch_on_eof = 0;

				if ( __IDL_wrap() )
					{
					/* Note: because we've taken care in
					 * __IDL__get_next_buffer() to have set up
					 * __IDL_text, we can now set up
					 * __IDL__c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					__IDL__c_buf_p = __IDL_text_ptr + YY_MORE_ADJ;

					__IDL__act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! __IDL__did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				__IDL__c_buf_p =
					__IDL_text_ptr + __IDL__amount_of_matched_text;

				__IDL__current_state = __IDL__get_previous_state();

				__IDL__cp = __IDL__c_buf_p;
				__IDL__bp = __IDL_text_ptr + YY_MORE_ADJ;
				goto __IDL__match;

			case EOB_ACT_LAST_MATCH:
				__IDL__c_buf_p =
				&__IDL__current_buffer->__IDL__ch_buf[__IDL__n_chars];

				__IDL__current_state = __IDL__get_previous_state();

				__IDL__cp = __IDL__c_buf_p;
				__IDL__bp = __IDL_text_ptr + YY_MORE_ADJ;
				goto __IDL__find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of __IDL_lex */


/* __IDL__get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int __IDL__get_next_buffer()
	{
	register char *dest = __IDL__current_buffer->__IDL__ch_buf;
	register char *source = __IDL_text_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( __IDL__c_buf_p > &__IDL__current_buffer->__IDL__ch_buf[__IDL__n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( __IDL__current_buffer->__IDL__fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( __IDL__c_buf_p - __IDL_text_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (__IDL__c_buf_p - __IDL_text_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( __IDL__current_buffer->__IDL__buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		__IDL__current_buffer->__IDL__n_chars = __IDL__n_chars = 0;

	else
		{
		int num_to_read =
			__IDL__current_buffer->__IDL__buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = __IDL__current_buffer;

			int __IDL__c_buf_p_offset =
				(int) (__IDL__c_buf_p - b->__IDL__ch_buf);

			if ( b->__IDL__is_our_buffer )
				{
				int new_size = b->__IDL__buf_size * 2;

				if ( new_size <= 0 )
					b->__IDL__buf_size += b->__IDL__buf_size / 8;
				else
					b->__IDL__buf_size *= 2;

				b->__IDL__ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					__IDL__flex_realloc( (void *) b->__IDL__ch_buf,
							 b->__IDL__buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->__IDL__ch_buf = 0;

			if ( ! b->__IDL__ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			__IDL__c_buf_p = &b->__IDL__ch_buf[__IDL__c_buf_p_offset];

			num_to_read = __IDL__current_buffer->__IDL__buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&__IDL__current_buffer->__IDL__ch_buf[number_to_move]),
			__IDL__n_chars, num_to_read );

		__IDL__current_buffer->__IDL__n_chars = __IDL__n_chars;
		}

	if ( __IDL__n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			__IDL_restart( __IDL_in );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			__IDL__current_buffer->__IDL__buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	__IDL__n_chars += number_to_move;
	__IDL__current_buffer->__IDL__ch_buf[__IDL__n_chars] = YY_END_OF_BUFFER_CHAR;
	__IDL__current_buffer->__IDL__ch_buf[__IDL__n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	__IDL_text_ptr = &__IDL__current_buffer->__IDL__ch_buf[0];

	return ret_val;
	}


/* __IDL__get_previous_state - get the state just before the EOB char was reached */

static __IDL__state_type __IDL__get_previous_state()
	{
	register __IDL__state_type __IDL__current_state;
	register char *__IDL__cp;

	__IDL__current_state = __IDL__start;
	__IDL__current_state += YY_AT_BOL();

	for ( __IDL__cp = __IDL_text_ptr + YY_MORE_ADJ; __IDL__cp < __IDL__c_buf_p; ++__IDL__cp )
		{
		register YY_CHAR __IDL__c = (*__IDL__cp ? __IDL__ec[YY_SC_TO_UI(*__IDL__cp)] : 1);
		if ( __IDL__accept[__IDL__current_state] )
			{
			__IDL__last_accepting_state = __IDL__current_state;
			__IDL__last_accepting_cpos = __IDL__cp;
			}
		while ( __IDL__chk[__IDL__base[__IDL__current_state] + __IDL__c] != __IDL__current_state )
			{
			__IDL__current_state = (int) __IDL__def[__IDL__current_state];
			if ( __IDL__current_state >= 353 )
				__IDL__c = __IDL__meta[(unsigned int) __IDL__c];
			}
		__IDL__current_state = __IDL__nxt[__IDL__base[__IDL__current_state] + (unsigned int) __IDL__c];
		}

	return __IDL__current_state;
	}


/* __IDL__try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = __IDL__try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static __IDL__state_type __IDL__try_NUL_trans( __IDL__state_type __IDL__current_state )
#else
static __IDL__state_type __IDL__try_NUL_trans( __IDL__current_state )
__IDL__state_type __IDL__current_state;
#endif
	{
	register int __IDL__is_jam;
	register char *__IDL__cp = __IDL__c_buf_p;

	register YY_CHAR __IDL__c = 1;
	if ( __IDL__accept[__IDL__current_state] )
		{
		__IDL__last_accepting_state = __IDL__current_state;
		__IDL__last_accepting_cpos = __IDL__cp;
		}
	while ( __IDL__chk[__IDL__base[__IDL__current_state] + __IDL__c] != __IDL__current_state )
		{
		__IDL__current_state = (int) __IDL__def[__IDL__current_state];
		if ( __IDL__current_state >= 353 )
			__IDL__c = __IDL__meta[(unsigned int) __IDL__c];
		}
	__IDL__current_state = __IDL__nxt[__IDL__base[__IDL__current_state] + (unsigned int) __IDL__c];
	__IDL__is_jam = (__IDL__current_state == 352);

	return __IDL__is_jam ? 0 : __IDL__current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void __IDL_unput( int c, register char *__IDL__bp )
#else
static void __IDL_unput( c, __IDL__bp )
int c;
register char *__IDL__bp;
#endif
	{
	register char *__IDL__cp = __IDL__c_buf_p;

	/* undo effects of setting up __IDL_text */
	*__IDL__cp = __IDL__hold_char;

	if ( __IDL__cp < __IDL__current_buffer->__IDL__ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = __IDL__n_chars + 2;
		register char *dest = &__IDL__current_buffer->__IDL__ch_buf[
					__IDL__current_buffer->__IDL__buf_size + 2];
		register char *source =
				&__IDL__current_buffer->__IDL__ch_buf[number_to_move];

		while ( source > __IDL__current_buffer->__IDL__ch_buf )
			*--dest = *--source;

		__IDL__cp += (int) (dest - source);
		__IDL__bp += (int) (dest - source);
		__IDL__current_buffer->__IDL__n_chars =
			__IDL__n_chars = __IDL__current_buffer->__IDL__buf_size;

		if ( __IDL__cp < __IDL__current_buffer->__IDL__ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--__IDL__cp = (char) c;


	__IDL_text_ptr = __IDL__bp;
	__IDL__hold_char = *__IDL__cp;
	__IDL__c_buf_p = __IDL__cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int __IDL_input()
#else
static int input()
#endif
	{
	int c;

	*__IDL__c_buf_p = __IDL__hold_char;

	if ( *__IDL__c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* __IDL__c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( __IDL__c_buf_p < &__IDL__current_buffer->__IDL__ch_buf[__IDL__n_chars] )
			/* This was really a NUL. */
			*__IDL__c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = __IDL__c_buf_p - __IDL_text_ptr;
			++__IDL__c_buf_p;

			switch ( __IDL__get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because __IDL__g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					__IDL_restart( __IDL_in );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( __IDL_wrap() )
						return EOF;

					if ( ! __IDL__did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return __IDL_input();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					__IDL__c_buf_p = __IDL_text_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) __IDL__c_buf_p;	/* cast for 8-bit char's */
	*__IDL__c_buf_p = '\0';	/* preserve __IDL_text */
	__IDL__hold_char = *++__IDL__c_buf_p;

	__IDL__current_buffer->__IDL__at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void __IDL_restart( FILE *input_file )
#else
void __IDL_restart( input_file )
FILE *input_file;
#endif
	{
	if ( ! __IDL__current_buffer )
		__IDL__current_buffer = __IDL__create_buffer( __IDL_in, YY_BUF_SIZE );

	__IDL__init_buffer( __IDL__current_buffer, input_file );
	__IDL__load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void __IDL__switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void __IDL__switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( __IDL__current_buffer == new_buffer )
		return;

	if ( __IDL__current_buffer )
		{
		/* Flush out information for old buffer. */
		*__IDL__c_buf_p = __IDL__hold_char;
		__IDL__current_buffer->__IDL__buf_pos = __IDL__c_buf_p;
		__IDL__current_buffer->__IDL__n_chars = __IDL__n_chars;
		}

	__IDL__current_buffer = new_buffer;
	__IDL__load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (__IDL_wrap()) processing, but the only time this flag
	 * is looked at is after __IDL_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	__IDL__did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void __IDL__load_buffer_state( void )
#else
void __IDL__load_buffer_state()
#endif
	{
	__IDL__n_chars = __IDL__current_buffer->__IDL__n_chars;
	__IDL_text_ptr = __IDL__c_buf_p = __IDL__current_buffer->__IDL__buf_pos;
	__IDL_in = __IDL__current_buffer->__IDL__input_file;
	__IDL__hold_char = *__IDL__c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE __IDL__create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE __IDL__create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) __IDL__flex_alloc( sizeof( struct __IDL__buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in __IDL__create_buffer()" );

	b->__IDL__buf_size = size;

	/* __IDL__ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->__IDL__ch_buf = (char *) __IDL__flex_alloc( b->__IDL__buf_size + 2 );
	if ( ! b->__IDL__ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in __IDL__create_buffer()" );

	b->__IDL__is_our_buffer = 1;

	__IDL__init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void __IDL__delete_buffer( YY_BUFFER_STATE b )
#else
void __IDL__delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == __IDL__current_buffer )
		__IDL__current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->__IDL__is_our_buffer )
		__IDL__flex_free( (void *) b->__IDL__ch_buf );

	__IDL__flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void __IDL__init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void __IDL__init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	__IDL__flush_buffer( b );

	b->__IDL__input_file = file;
	b->__IDL__fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->__IDL__is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->__IDL__is_interactive = 0;
#else
	b->__IDL__is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void __IDL__flush_buffer( YY_BUFFER_STATE b )
#else
void __IDL__flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->__IDL__n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->__IDL__ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->__IDL__ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->__IDL__buf_pos = &b->__IDL__ch_buf[0];

	b->__IDL__at_bol = 1;
	b->__IDL__buffer_status = YY_BUFFER_NEW;

	if ( b == __IDL__current_buffer )
		__IDL__load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE __IDL__scan_buffer( char *base, __IDL__size_t size )
#else
YY_BUFFER_STATE __IDL__scan_buffer( base, size )
char *base;
__IDL__size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) __IDL__flex_alloc( sizeof( struct __IDL__buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in __IDL__scan_buffer()" );

	b->__IDL__buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->__IDL__buf_pos = b->__IDL__ch_buf = base;
	b->__IDL__is_our_buffer = 0;
	b->__IDL__input_file = 0;
	b->__IDL__n_chars = b->__IDL__buf_size;
	b->__IDL__is_interactive = 0;
	b->__IDL__at_bol = 1;
	b->__IDL__fill_buffer = 0;
	b->__IDL__buffer_status = YY_BUFFER_NEW;

	__IDL__switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE __IDL__scan_string( __IDL_const char *__IDL__str )
#else
YY_BUFFER_STATE __IDL__scan_string( __IDL__str )
__IDL_const char *__IDL__str;
#endif
	{
	int len;
	for ( len = 0; __IDL__str[len]; ++len )
		;

	return __IDL__scan_bytes( __IDL__str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE __IDL__scan_bytes( __IDL_const char *bytes, int len )
#else
YY_BUFFER_STATE __IDL__scan_bytes( bytes, len )
__IDL_const char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	__IDL__size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) __IDL__flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in __IDL__scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = __IDL__scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in __IDL__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->__IDL__is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void __IDL__push_state( int new_state )
#else
static void __IDL__push_state( new_state )
int new_state;
#endif
	{
	if ( __IDL__start_stack_ptr >= __IDL__start_stack_depth )
		{
		__IDL__size_t new_size;

		__IDL__start_stack_depth += YY_START_STACK_INCR;
		new_size = __IDL__start_stack_depth * sizeof( int );

		if ( ! __IDL__start_stack )
			__IDL__start_stack = (int *) __IDL__flex_alloc( new_size );

		else
			__IDL__start_stack = (int *) __IDL__flex_realloc(
					(void *) __IDL__start_stack, new_size );

		if ( ! __IDL__start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	__IDL__start_stack[__IDL__start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void __IDL__pop_state()
	{
	if ( --__IDL__start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(__IDL__start_stack[__IDL__start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int __IDL__top_state()
	{
	return __IDL__start_stack[__IDL__start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void __IDL__fatal_error( __IDL_const char msg[] )
#else
static void __IDL__fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine __IDL_less() so it works in section 3 code. */

#undef __IDL_less
#define __IDL_less(n) \
	do \
		{ \
		/* Undo effects of setting up __IDL_text. */ \
		__IDL_text[__IDL_leng] = __IDL__hold_char; \
		__IDL__c_buf_p = __IDL_text + n; \
		__IDL__hold_char = *__IDL__c_buf_p; \
		*__IDL__c_buf_p = '\0'; \
		__IDL_leng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef __IDL_text_ptr
#ifdef YY_USE_PROTOS
static void __IDL__flex_strncpy( char *s1, __IDL_const char *s2, int n )
#else
static void __IDL__flex_strncpy( s1, s2, n )
char *s1;
__IDL_const char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int __IDL__flex_strlen( __IDL_const char *s )
#else
static int __IDL__flex_strlen( s )
__IDL_const char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *__IDL__flex_alloc( __IDL__size_t size )
#else
static void *__IDL__flex_alloc( size )
__IDL__size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *__IDL__flex_realloc( void *ptr, __IDL__size_t size )
#else
static void *__IDL__flex_realloc( ptr, size )
void *ptr;
__IDL__size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void __IDL__flex_free( void *ptr )
#else
static void __IDL__flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	__IDL_lex();
	return 0;
	}
#endif
#line 323 "lexer.l"


void __IDL_lex_init (void)
{
	__IDL_inputcb = NULL;
	__IDL_cur_line = 1;
	__IDL_cur_token_line = 0;
	__IDL_prev_token_line = 0;
	__IDL_cur_filename = NULL;
	__IDL_cur_fileinfo = NULL;
	warn_underscores = 0;
}

void __IDL_lex_cleanup (void)
{
	__IDL_cur_filename = NULL;
}

int __IDL_wrap (void)
{
	return 1;
}

static int count_nl (const char *s)
{
	int i;

	for (i = 0;
	     (s = strchr (s, '\n')) != NULL;
	     ++s, ++i) ;

	return i;
}

/*
 * Local variables:
 * mode: C
 * c-basic-offset: 8
 * tab-width: 8
 * indent-tabs-mode: t
 * End:
 */
