/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

interface mozIDOMWindow;

[scriptable, uuid(c03d38e3-bae6-4b62-ae96-cf8acc1501ec)]
interface nsIMobileIdentityService : nsISupports
{
  nsISupports getMobileIdAssertion(in mozIDOMWindow window,
                                   in jsval options);
};
