#
# Copyright 2002 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#ident	"$Id: Makefile,v 1.2 2003/01/13 19:43:14 glen.beasley%sun.com Exp $"
#

CORE_DEPTH = ../../../..
include ../Makefile.com

all:: $(FILES)
publish:: all pkg

include ../Makefile.targ
