#
# The contents of this file are subject to the Netscape Public License
# Version 1.0 (the "NPL"); you may not use this file except in
# compliance with the NPL.  You may obtain a copy of the NPL at
# http://www.mozilla.org/NPL/
#
# Software distributed under the NPL is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the NPL
# for the specific language governing rights and limitations under the
# NPL.
#
# The Initial Developer of this code under the NPL is Netscape
# Communications Corporation.  Portions created by Netscape are
# Copyright (C) 1998 Netscape Communications Corporation.  All Rights
# Reserved.
 
DEPTH=..\..\..

MAKE_OBJ_TYPE	= EXE
PROGRAM = .\$(OBJDIR)\ImageTest.exe
RESFILE = image.res
MAPFILE = image.map

LINCS=-I$(XPDIST)\public\raptor -I$(XPDIST)\public\xpcom -I..\..\src

LLFLAGS = $(LLFLAGS) /SUBSYSTEM:CONSOLE

OBJS =                                  \
	.\$(OBJDIR)\ImageTest.obj         \
	$(NULL)

LLIBS=				\
 $(DIST)\lib\raptorbase.lib		\
 $(DIST)\lib\raptorgfxwin.lib 	\
 $(DIST)\lib\raptorweb.lib		\
 $(DIST)\lib\xpcom32.lib		\
 $(LIBNSPR)			\
 $(DIST)\lib\plc3.lib		\
 $(DIST)\lib\img32$(VERSION_NUMBER).lib		\
 $(DIST)\lib\util.lib 		 \
 comdlg32.lib                 

include <$(DEPTH)\config\rules.mak>

install:: $(PROGRAM)
	$(MAKE_INSTALL) $(PROGRAM) $(DIST)\bin

clobber::
	rm -f $(DIST)\bin\ImageTest.exe

