#!gmake
#
# The contents of this file are subject to the Netscape Public
# License Version 1.1 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy of
# the License at http://www.mozilla.org/NPL/
#
# Software distributed under the License is distributed on an "AS
# IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
# implied. See the License for the specific language governing
# rights and limitations under the License.
#
# The Original Code is mozilla.org code.
#
# The Initial Developer of the Original Code is Netscape
# Communications Corporation.  Portions created by Netscape are
# Copyright (C) 1998 Netscape Communications Corporation. All
# Rights Reserved.
#
# Contributor(s): 

#



MODULE = libicalvcal
EXPORTS = icalvcal.h

#//------------------------------------------------------------------------
#//
#// Makefile to build SUN-JAVA/JPEG Library (NEW)
#//
#//------------------------------------------------------------------------


#//------------------------------------------------------------------------
#//
#// Specify the depth of the current directory relative to the
#// root of NS
#//
#//------------------------------------------------------------------------
DEPTH= ..\..\..\..

#//------------------------------------------------------------------------
#//
#// Define any Public Make Variables here: (ie. PDFFILE, MAPFILE, ...)
#//
#//------------------------------------------------------------------------
EXPORT_LIBRARY=1
LIBRARY_NAME=libicalvcal$(MOZ_BITS)$(VERSION_NUMBER)
PDBFILE=$(LIBRARY_NAME).pdb
MAPFILE=$(LIBRARY_NAME).map
!if "$(MOZ_BITS)" == "16"
DEFFILE=jpg$(MOZ_BIGS)$(VERSION_NUMBER).def
!endif

#//------------------------------------------------------------------------
#//
#// Define any local options for the make tools 
#//     (ie. LCFLAGS, LLFLAGS, LLIBS, LINCS)
#//  -Zi -GM needed to compile mmx functions in assembly.
LCFLAGS = -Zi -GM
LINCS = -I$(XPDIST)\include -I..\libical

#//------------------------------------------------------------------------
#// 
#// Define the files necessary to build the target (ie. OBJS)
#//
#//------------------------------------------------------------------------
LIBICAL_OBJS=   .\$(OBJDIR)\icalvcal.obj \
		.\$(OBJDIR)\vcaltest.obj \
		.\$(OBJDIR)\vcaltmp.obj \
                .\$(OBJDIR)\vcc.obj \
		.\$(OBJDIR)\vobject.obj \
		  $(NULL)



OBJS= ..\libical\$(OBJDIR)\libical$(MOZ_BITS)$(VERSION_NUMBER).lib \
    $(LIBICAL_OBJS)               \
    $(NULL)


#//------------------------------------------------------------------------
#//
#// Define any Public Targets here (ie. PROGRAM, LIBRARY, DLL, ...)
#// (these must be defined before the common makefiles are included)
#//
#//------------------------------------------------------------------------
LIBRARY	= .\$(OBJDIR)\$(LIBRARY_NAME).lib
MAPFILE= $(DLLNAME).map



#//------------------------------------------------------------------------
#//
#// Include the common makefile rules
#//
#//------------------------------------------------------------------------
include <$(DEPTH)/config/rules.mak>
