interface XULDocument : Document {

/* IID: { 0x17ddd8c0, 0xc5f8, 0x11d2, \
        { 0xa6, 0xae, 0x0, 0x10, 0x4b, 0xde, 0x60, 0x48 } } */

        Element getElementById(in DOMString id);

	NodeList getElementsByAttribute(in DOMString name, in DOMString value);
};
