interface XULElement : Element {

/* IID: { 0x0574ed81, 0xc088, 0x11d2, \
  { 0x96, 0xed, 0x00, 0x10, 0x4b, 0x7b, 0x7d, 0xeb } } */
                 attribute DOMString                       id;
                 attribute DOMString                       className;
        readonly attribute CSSStyleDeclaration             style;
        readonly attribute xpidl nsIRDFCompositeDataSource database;
        readonly attribute xpidl nsIXULTemplateBuilder     builder;
        readonly attribute xpidl nsIRDFResource            resource;
        readonly attribute xpidl nsIControllers            controllers;
        readonly attribute xpidl nsIBoxObject              boxObject;

        void addBroadcastListener(in DOMString attr, in Element element);
        void removeBroadcastListener(in DOMString attr, in Element element);
        void doCommand();

        void focus();
        void blur();
        void click();
		
        NodeList getElementsByAttribute(in DOMString name, in DOMString value);
};
