#!/bin/sh
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

#
# edit-dictionary

set -e

if [ -z "$EDITOR" ]; then
  echo 'Need to set the $EDITOR environment variable to your favorite editor!'
  exit 1
fi

# Strip the first line that contains the count
tail -n +2 ../en-US.dic > en-US.stripped

# Open the patched hunspell editor and let the user edit it
echo "Now the dictionary is going to be opened for you to edit.  When you're done, just quit the editor"
echo -n "Press Enter to begin."
read foo
$EDITOR en-US.stripped

# Add back the line count
wc -l < en-US.stripped | tr -d '[:blank:]' > en-US.dic
LC_ALL=C sort en-US.stripped >> en-US.dic

# Clean up
rm -f en-US.stripped

