/* -*- Mode: IDL; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 2 -*-
 *
 * The contents of this file are subject to the Mozilla Public
 * License Version 1.1 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of
 * the License at http://www.mozilla.org/MPL/
 * 
 * Software distributed under the License is distributed on an "AS
 * IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
 * implied. See the License for the specific language governing
 * rights and limitations under the License.
 * 
 * The Original Code is the Mozilla browser.
 * 
 * The Initial Developer of the Original Code is Netscape
 * Communications, Inc.  Portions created by Netscape are
 * Copyright (C) 1999, Mozilla.  All Rights Reserved.
 * 
 * Contributor(s):
 *   Radha Kulkarni <radha@netscape.com>
 */

#include "nsISupports.idl"
#include "nsIEnumerator.idl"
#include "nsISHEntry.idl"


/**
 * The nsISHEntryContainer. The interface to access child entries
 * of an nsISHEntry.
 * 
 */

[scriptable, uuid(65281BA2-988A-11d3-BDC7-0050040A9B44)]
interface nsISHContainer : nsISupports
{
	/**
     * The current number of nsISHEntries which are immediate children of the 
	 * current SHEntry
     */
	readonly attribute long childCount;

	/**
	 * Add a new child SHEntry.  Adds to the end of the list.
	 */
	void AddChild(in nsISHEntry child);

	/**
	 * Removes a child SHEntry
	 */
	void RemoveChild(in nsISHEntry child);

	/**
	 * Get child at an index
	 */
	nsISHEntry GetChildAt(in long index);

	/**
	 * Enumerator to walk child list.
	 */
	readonly attribute nsIEnumerator childEnumerator;

};

