/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* ***** BEGIN LICENSE BLOCK *****
 * Version: NPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Netscape Public License
 * Version 1.1 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 * http://www.mozilla.org/NPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is mozilla.org code.
 *
 * The Initial Developer of the Original Code is 
 * Netscape Communications Corporation.
 * Portions created by the Initial Developer are Copyright (C) 1998
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or 
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the NPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the NPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */

#include "nsISupports.idl"
#include "nsIAtom.idl"

interface nsIFolder;

typedef unsigned long folderListenerNotifyFlagValue;

[scriptable, uuid(d4ff86da-1dd1-11b2-a6f6-9fcd348bcc34)]
interface nsIFolderListener : nsISupports {
  const folderListenerNotifyFlagValue added = 0x1;
  void OnItemAdded(in nsISupports parentItem,
                   in nsISupports item,
                   in string viewString);
  
  const folderListenerNotifyFlagValue removed = 0x2;
  void OnItemRemoved(in nsISupports parentItem,
                     in nsISupports item,
                     in string viewString);
  
  const folderListenerNotifyFlagValue propertyChanged = 0x4;
  void OnItemPropertyChanged(in nsISupports item,
                             in nsIAtom property,
                             in string oldValue,
                             in string newValue);
  
  const folderListenerNotifyFlagValue intPropertyChanged = 0x8;
  void OnItemIntPropertyChanged(in nsISupports item,
                                in nsIAtom property,
                                in long oldValue,
                                in long newValue);
  
  const folderListenerNotifyFlagValue boolPropertyChanged = 0x10;
  void OnItemBoolPropertyChanged(in nsISupports item,
                                 in nsIAtom property,
                                 in boolean oldValue,
                                 in boolean newValue);
  
  const folderListenerNotifyFlagValue unicharPropertyChanged = 0x20;
  void OnItemUnicharPropertyChanged(in nsISupports item,
                                    in nsIAtom property,
                                    in wstring oldValue,
                                    in wstring newValue);
  
  const folderListenerNotifyFlagValue propertyFlagChanged = 0x40;
  void OnItemPropertyFlagChanged(in nsISupports item,
                                 in nsIAtom property,
                                 in unsigned long oldFlag,
                                 in unsigned long newFlag);

  const folderListenerNotifyFlagValue event = 0x80;
  void OnItemEvent(in nsIFolder item, in nsIAtom event);
  
  const folderListenerNotifyFlagValue all = 0xFFFFFFFF; 

  //	void OnFolderLoaded(in nsIFolder aFolder);
  //	void OnDeleteOrMoveMessagesCompleted(in nsIFolder aFolder);
};
