#include "nsISupports.idl"

interface nsIOutputStream;
interface nsIMsgIncomingServer;
interface nsIMsgDBHdr;

[scriptable, uuid(24ca5ee5-4b0b-4d7b-b53c-13fa2279ccf0)]
interface nsISpamSettings: nsISupports {
  attribute nsIMsgIncomingServer server;
  
  /**
   * 0 for nothing, 100 for highest
   */
  attribute long level; 

  attribute boolean moveOnSpam;
  /**
   * 0 for actionTargetAccount, 1 for actionTargetFolder
   * most consumers will just use spamFolderURI
   */
  attribute long moveTargetMode;
  attribute string actionTargetAccount;
  attribute string actionTargetFolder;
  /**
   * built from moveTargetMode, actionTargetAccount, actionTargetFolder
   */
  readonly attribute string spamFolderURI;

  attribute boolean purge;
  /**
   * interval, in days
   */
  attribute long purgeInterval;

  attribute boolean useWhiteList;
  attribute string whiteListAbURI;
  
  // for logging
  attribute boolean loggingEnabled;
  attribute nsIOutputStream logStream;
  readonly attribute string logURL;
  void clearLog();
  void ensureLogFile();
  void flushLogIfNecessary();
  void logJunkHit(in nsIMsgDBHdr aMsgHdr, in boolean aMoveMessage);

  void clone(in nsISpamSettings aSpamSettings); 
};
