%filter substitution

%define loweredShadow 0 1px rgba(255, 255, 255, .4)
%define focusRingShadow 0 0 1px -moz-mac-focusring inset, 0 0 4px 1px -moz-mac-focusring, 0 0 2px 1px -moz-mac-focusring

%define roundButtonBorder 1px solid rgba(0, 0, 0, .4)
%define roundButtonBackground -moz-linear-gradient(top, bottom, from(#FFF), to(#CACACA)) repeat-x
%define roundButtonShadow 0 1px rgba(255, 255, 255, .4)
%define roundButtonPressedBackground #CCC
%define roundButtonPressedShadow inset 0 1px 4px rgba(0, 0, 0, .2), 0 1px rgba(255, 255, 255, .4)

%define scopeBarBackground -moz-linear-gradient(top, bottom, from(#E8E8E8), to(#D0D0D0)) repeat-x
%define scopeBarSeparatorBorder 1px solid #888
%define scopeBarTitleColor #6D6D6D

%define sidebarItemBorderTop 1px solid #94A1C0
%define sidebarItemBackground -moz-linear-gradient(top, bottom, from(#A0B0CF), to(#7386AB)) repeat-x
%define sidebarItemFocusedBorderTop 1px solid #5382C5
%define sidebarItemFocusedBackground -moz-linear-gradient(top, bottom, from(#6494D4), to(#2559AC)) repeat-x
%define sidebarItemGraphiteBorderTop 1px solid #97A4B1
%define sidebarItemGraphiteBackground -moz-linear-gradient(top, bottom, from(#AAB7C4), to(#8393A4)) repeat-x
%define sidebarItemGraphiteFocusedBorderTop 1px solid #6B798D
%define sidebarItemGraphiteFocusedBackground -moz-linear-gradient(top, bottom, from(#8293A6), to(#425972)) repeat-x
%define sidebarItemInactiveBorderTop 1px solid #979797
%define sidebarItemInactiveBackground -moz-linear-gradient(top, bottom, from(#B4B4B4), to(#8A8A8A)) repeat-x
