#!gmake
#
# The contents of this file are subject to the Netscape Public
# License Version 1.1 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy of
# the License at http:\\www.mozilla.org\NPL\
#
# Software distributed under the License is distributed on an "AS
# IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
# implied. See the License for the specific language governing
# rights and limitations under the License.
#
# The Original Code is mozilla.org code.
#
# The Initial Developer of the Original Code is Netscape
# Communications Corporation.  Portions created by Netscape are
# Copyright (C) 1998 Netscape Communications Corporation. All
# Rights Reserved.
#
# Contributor(s): 

DEPTH=..\..\..\..\..\..
topsrcdir       = $(DEPTH)
srcdir          = .
VPATH           = .

MODULE		= MThreadComponent2
MAKE_OBJ_TYPE 	= DLL
DLLNAME 	= $(MODULE)
DLL		=.\$(OBJDIR)\$(DLLNAME).dll
COMPONENT	= 1

CPP_OBJS	= \
        	.\$(OBJDIR)\MThreadComponent2.obj \
	        .\$(OBJDIR)\MThreadComponent2Factory.obj \
	        $(NULL)

XPIDLSRCS	= \
		.\iMThreadComponent2.idl \
		$(NULL)

JAVAI		= iMThreadComponent2.java

LLIBS		=$(LLIBS) $(LIBNSPR) $(DIST)\lib\xpcom.lib

include <$(topsrcdir)\config\rules.mak>

javai:
	echo $(JDKHOME)\bin\javac -classpath $(DEPTH)\dist\classes:$(CLASSPATH) -d $(DEPTH)\dist\classes $(JAVAI)
	$(JDKHOME)\bin\javac -classpath $(DEPTH)\dist\classes:$(CLASSPATH) -d $(DEPTH)\dist\classes $(JAVAI)

install:: $(DLL) javai
	$(MAKE_INSTALL) $(DLL) $(DIST)\bin\components

clobber::
	del /f $(DIST)\bin\components\$(DLLNAME).dll
	del /f $(DIST)\bin\components\$(DLLNAME).xpt
	del /f $(DIST)\..\classes\org\mozilla\xpcom\iMThreadComponent2.class
