/* Automatically generated.  Do not edit */
/* See the mkopcodeh.awk script for details */
#define OP_MemLoad                     1
#define OP_HexBlob                     123
#define OP_Column                      2
#define OP_SetCookie                   3
#define OP_Real                        122
#define OP_MoveGt                      4
#define OP_Ge                          71
#define OP_AggFocus                    5
#define OP_RowKey                      6
#define OP_IdxRecno                    7
#define OP_AggNext                     8
#define OP_Eq                          67
#define OP_OpenWrite                   9
#define OP_NotNull                     65
#define OP_If                          10
#define OP_PutStrKey                   11
#define OP_String8                     85
#define OP_Pop                         12
#define OP_SortPut                     13
#define OP_CollSeq                     14
#define OP_OpenRead                    15
#define OP_SortReset                   16
#define OP_AutoCommit                  17
#define OP_Gt                          68
#define OP_Sort                        18
#define OP_ListRewind                  19
#define OP_IntegrityCk                 20
#define OP_Function                    21
#define OP_Subtract                    77
#define OP_And                         59
#define OP_Noop                        22
#define OP_Return                      23
#define OP_Remainder                   80
#define OP_Multiply                    78
#define OP_Variable                    24
#define OP_String                      25
#define OP_ParseSchema                 26
#define OP_PutIntKey                   27
#define OP_AggFunc                     28
#define OP_Close                       29
#define OP_ListWrite                   30
#define OP_CreateIndex                 31
#define OP_IsUnique                    32
#define OP_IdxIsNull                   33
#define OP_NotFound                    34
#define OP_MustBeInt                   35
#define OP_Halt                        36
#define OP_IdxLT                       37
#define OP_AddImm                      38
#define OP_Statement                   39
#define OP_RowData                     40
#define OP_Push                        41
#define OP_Or                          58
#define OP_KeyAsData                   42
#define OP_NotExists                   43
#define OP_OpenTemp                    44
#define OP_MemIncr                     45
#define OP_Gosub                       46
#define OP_Divide                      79
#define OP_AggSet                      47
#define OP_Integer                     48
#define OP_SortNext                    49
#define OP_Prev                        50
#define OP_Concat                      81
#define OP_BitAnd                      72
#define OP_CreateTable                 51
#define OP_Last                        52
#define OP_IsNull                      64
#define OP_ShiftRight                  75
#define OP_ResetCount                  53
#define OP_Callback                    54
#define OP_ContextPush                 55
#define OP_DropTrigger                 56
#define OP_DropIndex                   57
#define OP_FullKey                     61
#define OP_IdxGE                       62
#define OP_IdxDelete                   63
#define OP_Vacuum                      83
#define OP_MoveLe                      86
#define OP_IfNot                       87
#define OP_DropTable                   88
#define OP_MakeRecord                  89
#define OP_Delete                      90
#define OP_ListRead                    91
#define OP_ListReset                   92
#define OP_ShiftLeft                   74
#define OP_Dup                         93
#define OP_Goto                        94
#define OP_Clear                       95
#define OP_IdxGT                       96
#define OP_MoveLt                      97
#define OP_Le                          69
#define OP_VerifyCookie                98
#define OP_Pull                        99
#define OP_Not                         60
#define OP_SetNumColumns               100
#define OP_AbsValue                    101
#define OP_Transaction                 102
#define OP_Negative                    82
#define OP_Ne                          66
#define OP_AggGet                      103
#define OP_ContextPop                  104
#define OP_BitOr                       73
#define OP_Next                        105
#define OP_AggInit                     106
#define OP_Distinct                    107
#define OP_NewRecno                    108
#define OP_Lt                          70
#define OP_AggReset                    109
#define OP_Destroy                     110
#define OP_ReadCookie                  111
#define OP_ForceInt                    112
#define OP_IdxColumn                   113
#define OP_Recno                       114
#define OP_OpenPseudo                  115
#define OP_Blob                        116
#define OP_Add                         76
#define OP_MemStore                    117
#define OP_Rewind                      118
#define OP_MoveGe                      119
#define OP_IdxPut                      120
#define OP_BitNot                      84
#define OP_Found                       121
#define OP_NullRow                     124
