/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

interface nsIDOMWindow;

/**
  * Implemented by @mozilla.org/dom/activities/proxy;1
  */
[scriptable, uuid(60adef0f-c1a7-4dc5-bc0d-4b879f1e59ca)]
interface nsIActivityProxy : nsISupports
{
    void startActivity(in nsISupports /* MozActivity */ activity,
                       in jsval options,
                       in nsIDOMWindow window);
    void cleanup();
};
