#!nmake
#
# The contents of this file are subject to the Netscape Public
# License Version 1.1 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy of
# the License at http://www.mozilla.org/NPL/
#
# Software distributed under the License is distributed on an "AS
# IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
# implied. See the License for the specific language governing
# rights and limitations under the License.
#
# The Original Code is mozilla.org code.
#
# The Initial Developer of the Original Code is Netscape
# Communications Corporation.  Portions created by Netscape are
# Copyright (C) 1998 Netscape Communications Corporation. All
# Rights Reserved.
#
# Contributor(s): 
DEPTH = ..\..\..
REQUIRES	= xpcom \
		  chardet \
		  $(NULL)
include <$(DEPTH)\config\config.mak>

MAKE_OBJ_TYPE = EXE
PROGRAMNAME = UniversalChardetTest.exe
PROG1 = .\$(OBJDIR)\$(PROGRAMNAME) 
PROGRAM = $(PROG1)

LCFLAGS=-DUSE_NSREG

LLIBS= \
 $(DIST)\lib\xpcom.lib \
 $(LIBNSPR)


CPP_OBJS= \
        .\$(OBJDIR)\UniversalChardetTest.obj \
        $(NULL)

include <$(DEPTH)\config\rules.mak>

install::  $(OBJDIR) $(PROGRAM)
  $(MAKE_INSTALL) $(PROGRAM) $(DIST)\bin

clobber::
  rm -f $(DIST)\bin\$(PROGRAMNAME)

#$(PROG1): $(OBJDIR) UniversalChardetTest.cpp
