#ifndef AVUTIL_AVCONFIG_H
#define AVUTIL_AVCONFIG_H

#include "config.h"

#define AV_HAVE_BIGENDIAN HAVE_BIGENDIAN
#define AV_HAVE_FAST_UNALIGNED HAVE_FAST_UNALIGNED
#define AV_HAVE_INCOMPATIBLE_LIBAV_ABI HAVE_INCOMPATIBLE_LIBAV_ABI

#endif /* AVUTIL_AVCONFIG_H */
