// flow-typed signature: 92b2c276e7ab4727424c83e6c8c86d54
// flow-typed version: <<STUB>>/devtools-utils_v0.0.13/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'devtools-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'devtools-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'devtools-utils/src/network-request' {
  declare module.exports: any;
}

declare module 'devtools-utils/src/privileged-network-request' {
  declare module.exports: any;
}

declare module 'devtools-utils/src/tests/network-request' {
  declare module.exports: any;
}

declare module 'devtools-utils/src/tests/worker-utils' {
  declare module.exports: any;
}

declare module 'devtools-utils/src/worker-utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'devtools-utils/index' {
  declare module.exports: $Exports<'devtools-utils'>;
}
declare module 'devtools-utils/index.js' {
  declare module.exports: $Exports<'devtools-utils'>;
}
declare module 'devtools-utils/src/network-request.js' {
  declare module.exports: $Exports<'devtools-utils/src/network-request'>;
}
declare module 'devtools-utils/src/privileged-network-request.js' {
  declare module.exports: $Exports<'devtools-utils/src/privileged-network-request'>;
}
declare module 'devtools-utils/src/tests/network-request.js' {
  declare module.exports: $Exports<'devtools-utils/src/tests/network-request'>;
}
declare module 'devtools-utils/src/tests/worker-utils.js' {
  declare module.exports: $Exports<'devtools-utils/src/tests/worker-utils'>;
}
declare module 'devtools-utils/src/worker-utils.js' {
  declare module.exports: $Exports<'devtools-utils/src/worker-utils'>;
}
