on run
	set kTargetFolder to "HD:genJS"
	
	tell application "ASEncoder"
		activate
		
		set bSuccess to encode file kTargetFolder
		if bSuccess then
			display dialog "encode SUCCESS"
		else
			display dialog "encode FAILURE"
		end if
		
		set bSuccess to decode file kTargetFolder
		if bSuccess then
			display dialog "decode SUCCESS"
		else
			display dialog "decode FAILURE"
		end if
		
		quit
	end tell
end run