/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */


#include "nsISupports.idl"

/**
 * An object representing a prompt or doorhanger.
 */
[scriptable, uuid(889842e9-052c-46c9-99f3-f4a426571e38)]
interface nsIPromptInstance : nsISupports {
  /**
   * Dismiss this prompt (e.g. because it's not relevant anymore).
   */
  void dismiss();
};
