/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"
#include "nsIDOMWindow.idl"

[scriptable, uuid(0843f3c1-043e-4c64-9d8c-091370548c05)]
interface nsIBrowserTab : nsISupports {
  readonly attribute nsIDOMWindow window;
  readonly attribute float scale;
};

[scriptable, uuid(d10377b4-1c90-493a-a532-63cb3f16ee2b)]
interface nsIAndroidBrowserApp : nsISupports {
  nsIBrowserTab getBrowserTab(in PRInt32 tabId);
};

[scriptable, uuid(bbb8e0d7-5cca-4ad0-88be-538ce6d04f63)]
interface nsIAndroidBridge : nsISupports
{
  AString handleGeckoMessage(in AString message);
  attribute nsIAndroidBrowserApp browserApp;
};
