#include "nsISupports.idl"
#include "nsIEvent.idl"

/**
 * The nsIPhEvent defines what a message looks like on the Photon Platform.    
 */						  

[scriptable, uuid(2EFB5005-4508-11d3-AEDA-00A024FFC08C)]
interface nsIPhEvent : nsIEvent
{
	//XXX Place the contents of a Photon PhEvent_t struct here.
};