DEPTH= ..\..\..

include <$(DEPTH)\config\config.mak>


CFLAGS = \
	-W3 \
	-GX \
	-DWIN32 \
	-D_WINDOWS \
  -D_AFXDLL \
  -DMBCS \
  -UMOZILLA_CLIENT \
	-FD \
	-c \
	$(CFLAGS)

LINCS= \
  $(NULL)

LLFLAGS = \
	$(NULL)

OBJS=				\
	.\$(OBJDIR)\xmltok.obj      	\
	.\$(OBJDIR)\xmlrole.obj     	\
	$(NULL)


include <$(DEPTH)\config\rules.mak>

include <$(DEPTH)\cck\InitDist.win>

libs:: $(OBJDIR) $(OBJS)
