#!nmake
#
# The contents of this file are subject to the Netscape Public License
# Version 1.0 (the "NPL"); you may not use this file except in
# compliance with the NPL.  You may obtain a copy of the NPL at
# http://www.mozilla.org/NPL/
#
# Software distributed under the NPL is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the NPL
# for the specific language governing rights and limitations under the
# NPL.
#
# The Initial Developer of this code under the NPL is Netscape
# Communications Corporation.  Portions created by Netscape are
# Copyright (C) 1998 Netscape Communications Corporation.  All Rights
# Reserved.

DEPTH=..\..

MAKE_OBJ_TYPE	= EXE
PROG1 = .\$(OBJDIR)\TestFileInput.exe
PROG2 = .\$(OBJDIR)\TestSocketInput.exe
PROG3 = .\$(OBJDIR)\TestSocketIO.exe
PROG4 = .\$(OBJDIR)\TestProtocols.exe
PROG5 = .\$(OBJDIR)\TestSocketTransport.exe
PROG6 = .\$(OBJDIR)\urltest.exe
PROG7 = .\$(OBJDIR)\TestFileInput2.exe
PROGRAMS = $(PROG1) $(PROG2) $(PROG3) $(PROG4) $(PROG5) $(PROG6) $(PROG7)

LCFLAGS=-DUSE_NSREG -GX

REQUIRES=libreg

INCS = $(INCS)                  \
        -I$(DEPTH)\dist\include \
        $(NULL)

LLIBS=					\
 $(DIST)\lib\xpcom.lib		\
 $(DIST)\lib\raptorgfxwin.lib		\
 $(LIBNSPR)				\
!if "$(MOZ_BITS)"=="32" && defined(MOZ_DEBUG) && defined(GLOWCODE)
LLIBS=$(LLIBS) $(GLOWDIR)\glowcode.lib
!endif

include <$(DEPTH)\config\rules.mak>

install:: $(PROGRAMS)
	-for %p in ($(PROGRAMS)) do $(MAKE_INSTALL) %p $(DIST)\bin

clobber::
	-for %p in ($(PROGRAMS)) do $(RM) %p $(DIST)\bin\%p

$(PROG1): $(OBJDIR) TestFileInput.cpp

$(PROG2): $(OBJDIR) TestSocketInput.cpp

$(PROG3): $(OBJDIR) TestSocketIO.cpp

$(PROG4): $(OBJDIR) TestProtocols.cpp

$(PROG5): $(OBJDIR) TestSocketTransport.cpp

$(PROG6): $(OBJDIR) urltest.cpp

$(PROG7): $(OBJDIR) TestFileInput2.cpp
