/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsIDOMEvent.idl"

interface nsIVariant;

[scriptable, builtinclass, uuid(627b2102-9605-40e0-a5bf-6d3ac672b328)]
interface nsIDOMMozWifiConnectionInfoEvent : nsIDOMEvent
{
    /**
     * Network object with an SSID field.
     */
    readonly attribute nsIVariant network;

    /**
     * Strength of the signal to network, in dBm between -55 and -100 dBm.
     */
    readonly attribute short signalStrength;

    /**
     * Relative signal strength between 0 and 100.
     */
    readonly attribute short relSignalStrength;

    /**
     * Link speed in Mb/s.
     */
    readonly attribute long linkSpeed;

    /**
     * IP address in the dotted quad format.
     */
    readonly attribute DOMString ipAddress;

    [noscript] void initMozWifiConnectionInfoEvent(in DOMString aType,
                                                   in boolean aCanBubble,
                                                   in boolean aCancelable,
                                                   in nsIVariant aNetwork,
                                                   in short signalStrength,
                                                   in short relSignalStrength,
                                                   in long linkSpeed,
                                                   in DOMString ipAddress);
};
