#!nmake
#
# The contents of this file are subject to the Netscape Public License
# Version 1.0 (the "NPL"); you may not use this file except in
# compliance with the NPL.  You may obtain a copy of the NPL at
# http://www.mozilla.org/NPL/
#
# Software distributed under the NPL is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the NPL
# for the specific language governing rights and limitations under the
# NPL.
#
# The Initial Developer of this code under the NPL is Netscape
# Communications Corporation.  Portions created by Netscape are
# Copyright (C) 1998 Netscape Communications Corporation.  All Rights
# Reserved.

DEPTH=..\..\..\..
IGNORE_MANIFEST=1


MAKE_OBJ_TYPE   = EXE
PROGRAM = .\$(OBJDIR)\nntpTest.exe

OBJS =                          \
	.\$(OBJDIR)\nntpTest.obj    \
	$(NULL)

LINCS=-I$(PUBLIC)\raptor -I$(PUBLIC)\xpcom -I$(PUBLIC)\netlib -I$(PUBLIC)\mailnews -I$(PUBLIC)\security -I$(PUBLIC)\pref -I$(PUBLIC)\rdf

MYLIBS=							\
 $(DIST)\lib\xpcom32.lib		\
 $(LIBNSPR)						\
 $(DIST)\lib\raptorbase.lib		\
 $(DIST)\lib\raptorgfxwin.lib	\
 $(DIST)\lib\raptorwidget.lib	\
 $(DIST)\lib\netlib.lib			\
 $(DIST)\lib\plc3.lib		\
 $(DIST)\lib\nntp.lib    		\
 $(DIST)\lib\nntpTest.lib		\
 $(DIST)\lib\msgcore.lib		\
 $(DIST)\lib\xplib.lib			\
 $(NULL)

LLIBS= $(MYLIBS)				\
 -SUBSYSTEM:CONSOLE 

include <$(DEPTH)\config\rules.mak>

install:: $(PROGRAM)
	$(MAKE_INSTALL) $(PROGRAM) $(DIST)\bin

clobber::
	rm -f $(DIST)\bin\Mailer.exe

$(PROGRAM):: $(OBJS) $(MYLIBS)
