#!/bin/sh
#
# Clean up any weirdness left around by prettier execution from pre-commit
# hook.  Can happen for some workflows (eg `git commit .`).
#
# Install by executing
#
#   ln -s ../../hooks/post-commit .git/hooks/post-commit
#
# at the top-level of the activity-stream github repo.
git update-index -g
