/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsIDOMEvent.idl"

[scriptable, builtinclass, uuid(4d37e578-9469-4067-8de3-34e6f01f11f3)]
interface nsIDOMDeviceLightEvent : nsIDOMEvent
{
  [noscript] void initDeviceLightEvent(in DOMString eventTypeArg,
                                       in boolean canBubbleArg,
                                       in boolean cancelableArg,
                                       in double value);

  readonly attribute double value;
};

dictionary DeviceLightEventInit : EventInit
{
   double value;
};
