/* -*- Mode: IDL; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "domstubs.idl"

interface nsIDOMPaintRequest;

[scriptable, uuid(1d6a6e10-e9f0-468b-b8e5-da39c945690e)]
interface nsIDOMPaintRequestList : nsISupports
{
  readonly attribute unsigned long length;
  nsIDOMPaintRequest        item(in unsigned long index);
};
