IPDLSRCS =					\
  PTestBlockChild.ipdl				\
  PTestCrashCleanup.ipdl			\
  PTestDataStructures.ipdl			\
  PTestDataStructuresSub.ipdl			\
  PTestDesc.ipdl				\
  PTestDescSub.ipdl				\
  PTestDescSubsub.ipdl				\
  PTestHangs.ipdl				\
  PTestLatency.ipdl				\
  PTestManyChildAllocs.ipdl			\
  PTestManyChildAllocsSub.ipdl			\
  PTestMultiMgrs.ipdl				\
  PTestMultiMgrsLeft.ipdl			\
  PTestMultiMgrsRight.ipdl			\
  PTestMultiMgrsBottom.ipdl			\
  PTestNestedLoops.ipdl				\
  PTestRacyRPCReplies.ipdl			\
  PTestRPCErrorCleanup.ipdl			\
  PTestRPCRaces.ipdl				\
  PTestRPCShutdownRace.ipdl			\
  PTestSanity.ipdl				\
  PTestSelfManage.ipdl				\
  PTestSelfManageRoot.ipdl			\
  PTestShmem.ipdl				\
  PTestShutdown.ipdl				\
  PTestShutdownSub.ipdl				\
  PTestShutdownSubsub.ipdl			\
  PTestStackHooks.ipdl				\
  PTestSyncWakeup.ipdl				\
  PTestSysVShmem.ipdl				\
  $(NULL)
