/* Copyright (c) 2012 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

/* Exposes functions needed by the out-of-process proxy to call into the
 * renderer PPAPI implementation.
 */
interface PPB_Proxy_Private_0_2 {
  /* Called when the given plugin process has crashed. */
  void PluginCrashed(
      [in] PP_Module module);

  /* Returns the instance for the given resource, or 0 on failure. */
  PP_Instance GetInstanceForResource(
      [in] PP_Resource resource);
};
